### ISSUE TITLE
Quality of Bathymetric Data - Visualization of Vertical and Positional Uncertainties 

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#1]
**S-101PT5 Action 03** - Consider the implementation of DQWG recommendations on improved portrayal of Quality of Bathymetric Data information in ECDIS.

[DQWG15_2020_05.1B_EN_Uncertainty of measurements and ECDIS performance.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5289954/DQWG15_2020_05.1B_EN_Uncertainty.of.measurements.and.ECDIS.performance.docx) - **original proposal**

[S-101PT5_13_EN_S-100WG5_2020_3.8_EN_DQWG_Report_Paper.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5338136/S-101PT5_13_EN_S-100WG5_2020_3.8_EN_DQWG_Report_Paper.pdf) -  **refer to item 3**

[HSSC12_2020_05.5C_EN_Conversion of M_QUAL-CATZOC to S-101 (1).pptx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5289931/HSSC12_2020_05.5C_EN_Conversion.of.M_QUAL-CATZOC.to.S-101.1.pptx)

**The subWG is invited to:**
1.	Approve the use of **Horizontal Position Uncertainty** & **Vertical Uncertainty** to affect portrayal and ECDIS performance as described in the paper.
1.	Approve the S-57 to S-101 migration strategy proposed by the DQWG and refer it to the relevant ENCWG focus group for consideration. 
2.	Approve the DQWG proposal of adding a new boolean attribute (_**uncertaintyDisplay**_ _Yes/No_) to control the display of uncertainties indicators in ECDIS to the following feature types: Sounding, Underwater Rock, Wreck and Obstruction.
3.	Consider the merits of applying a similar approach to bridges and pipelines/cables overhead using the uncertainties populated in the complex attributes **Vertical Clearance Fixed** and **Horizontal Clearance Fixed**.
4.	If approved, come up with a way forward to develop appropriate symbology and ECDIS functionalities for testing the principles outlined in the proposal (NIWC/KOHA ??). As a minimum, agree on recommending the S101PT on updating the FC and including an entry to the ‘S-100 ECDIS Performance requirements log’ for post DF implementation.
5.	Consider the merits of accepting the DQWG’s suggestion of removing **categoryOfTemporalVariation** from QoBD. – Note that this request conflicts with the proposal outlined in Issue # 4.

**Comment by alvarosanuy** [comment]
The AHO:

- supports the approval of items 1, 2 and 3
- supports the extension of the concept as mentioned in item 4. We recommend this is included into the scope of work allocated to  item 5
- Supports the way forward refered in item 5
- do not support the removal of **categoryOfTemporalVariation** from QoBD.

Please notice that the following comment made in the DQWG paper, and which is repeated for Wrecks, Sounding and Underwater Rocks, is not accurate.  **'The Obstruction Feature type is missing the attribute ref: horizontalPositionUncertainty, which is needed for the permittedPrimitive = point.'**
**horizontalPositionUncertainty** is not missing from these feature types. It is a complex attribute of the Information type **Spatial Quality**. Each instance of **Spatial Quality** must be associated to the geometry to which the information applies using the association 'Spatial Association' (see DCEG clause 25.13).'

**Comment by Christian-Shom** [comment]
France (Shom):

- approves items 1 to 5, with the following comments:
The use of Horizontal Position Uncertainty & Vertical Uncertainty could be an important in S-101 ECDIS as compared to S-57. Yet, thorough testing will be needed to see how far can we go with such a fonctionality. Attention must be paid on the fact that information on a chart are generalized and that an area covered by a single M_QUAL is often covered by various surveys with different SOUACC and POSACC values. Hence, the automatic population of values is not always possible. This may require an important work load for the HOs.
- does not support the removal of categoryOfTemporalVariation. More detailled explanations in the DCEG is probably needed to ensure all HOs will populate this attribute with a similar approach.

**Comment by Christian-Shom** [comment]
France (Shom):

   - approves items 1 to 5, with the following comments:
    The use of Horizontal Position Uncertainty & Vertical Uncertainty could be an important improvement in S-101 ECDIS as compared to S-57. Yet, thorough testing will be needed to see how far can we go with such a fonctionality. Attention must be paid on the fact that information on a chart are generalized and that an area covered by a single M_QUAL is often covered by various surveys with different SOUACC and POSACC values. Hence, the automatic population of values is not always possible. This may require an important work load for the HOs.
    - does not support the removal of categoryOfTemporalVariation. More detailled explanations in the DCEG is probably needed to ensure all HOs will populate this attribute with a similar approach.

I have one general question: If I understand correctly, we plan to have a S-101 portrayal that "looks like" S-52 during DF period (due to the need for an equivalent regime of presentation), and then improve (significantly ?) the S-101 portrayal when there are no more S-57 ENCs. Do we have documentation on this approach with a list of things we can do now and others we plan for later? Do we have a time table?

**Comment by NLHO-Rogier** [comment]
AT DQWG15 meeting UK rejected the existence of category of temporal variation in S-101. Their argument was that if a highly accurate survey is done, it should receive the highest CATZOC value. If significant shoaling is likely and would affect safe navigation, then the CATZOC value would immediately be downgraded. For that argument, the existing attribute values of category of temporal variation are not sufficient.
However, downgrading of CATZOC over time should be possible where an HO finds this appropriate. DQWG could not come to a common agreement on this at the meeting and the issue is to be further discussed within this subWG.

**Comment by SylviaSpohn-BSH** [comment]
Good question from Christian.

The possibility of the temporal variation should be kept, but not mandatory. This is difficult to handle for us as we get every day a lot of little survey puzzles and for the Wadden Sea a monthly changing value does not fit (agree to Rogier, last comment).

**Comment by alvarosanuy** [comment]
**Summary**:

1 - Approved
2 - Christian M.  (S-57 to S101 conversion focus group) to confirm
3 - Approved and implemented in DCEG 1.0.1
4 - Pending
5 - Added entry in ‘S-100 ECDIS Performance requirements log’ for post DF implementation. Will require creation of focus group as soon as S-101 2.0.0 is published. Mariners' input is critical. Recommend S-101PT Chair to log task with Singapore Laboratory.
6 - It has been decided to retain **categoryOfTemporalVariation**. For temporal variation discussions refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/4

**Comment by DavidGrant-NIWC** [comment]
* [ ] Please update remodeled items spreadsheet accordingly

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144326549-620467d8-1399-4d44-991d-f7716f30be27.png)

**Comment by alvarosanuy** [comment]
The focus of this Github issue is now to **propose** possible ways to visualize **verticalUncertainty** and **horizontalPositionUncertainty** in ECDIS for those features (Sounding, Underwater/Awash Rock, Wreck and Obstruction) having **displayUncertainties** = Yes.

The attribute **displayUncertainties** is a cartographic attribute intended to reduce screen clutter in some ECDIS display settings by limiting the display of the horizontal position **_and vertical_** accuracies to those considered by the encoder to be important to the mariner. This attribute only applies to Point geometry and is mandatory for affected features in depths 30 metres or less. Factors to be considered in populating this attribute include depth in relation to the general nature of the seabed, proximity to other dangers, intention of the ENC, proximity to routes taken by vessels, and the types of vessels intended to utilise the ENC. 

Another element to discuss is the possibility of amending the ECDIS safety functions to enable the use of the 'modified' feature values (position/depth) when calculating safe passage. The attributes **verticalUncertainty** and **horizontalPositionUncertainty** would be used to create a buffer around the charted object and therefore, during route planning or route monitoring, the safety corridor would react to an area object (from a positional point of view), and to a shoaler depth.

**Comment by SylviaSpohn-BSH** [comment]
I suppose that an extra symbol for the basic ENC is not necessary. The value should be evaluated for route planning (safety distance shown from the object) As the values are not available comprehensively, we could develop the portyal later, not at a high priority.

**Comment by alvarosanuy** [comment]
Discussion topics:

- [ ] **Route Planning** - Insert  requirement in S-98 Annex C to ensure ECDIS includes an option to check the planned route using **verticalUncertainty** and **horizontalPositionalUncertainty** values. A different option should also exist to visualize the vertical and positional 'worst case' scenarios by showing the shoalest possible depth and an uncertainty circle around features **(final portrayal still TBD but see last bullet point)**.
- [ ] **Route Monitoring** - Should mariners be allowed to display 'altered' sounding/VALSOU figures and/or positional uncertainty circles while underway?? If Yes, should portrayal be any different than the one selected for Route Planning?? What about setting up the safety framework to use these values when populated?? In these cases an ECDIS performance requirement must be added to S-98 Annex C.
- [ ]  Feasibility of resolving, in real time, the ‘final’ Hor and Ver uncertainties when **uncertaintyVariableFactor** is populated (e.g. calculating, on the fly, **valueOfSounding** – [uncertainty fixed + uncertainty variable factor]) before altering the charted values for display/alarms when requested.
- [ ] Decide if the 'worst case' Hor & Vert uncertainties values from **categoryOfZoneOfConfidenceInData** would be used when **verticalUncertainty** and **horizontalPositionalUncertainty** values are not populated/Unknown and  **displayUncertanties**=Yes.
- [ ] Uncertainty circle portrayal proposal for subWG discussion: CHMGF dashed line (thinner than the one used for **AdministrationArea**).

**Comment by forodd** [comment]
First attempt at some testdata for horisontal and vertical uncertainty. This has been created by populating POSACC and SOUACC on individual objects in S-57 before converting to S-101 using FC 1.0.2.

Please let me know if this data need some adjustments, happy to update the data if needed.

Edit; data updated with dates for the QoBD features.
Edit2: added attributs for dateStart to the QoBD features.

[hor_ver_uncert_testdata_NO_v3.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9102452/hor_ver_uncert_testdata_NO_v3.zip)

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/178742490-719db8cb-f18d-4588-b04b-8a733716caaf.png)

**Comment by kusala9** [comment]
happy to help with this one - apologies we haven't been able to prepare much data in support of the efforts here but we're doing some of the S-101 test data and can prepare test datasets for specific, simple cells. We have a YAML processor which produces S-101 conformant data. Attached cell has a QualityOfBathymetricData feature which works in v1.9.0 of the NIWC viewer. This is generated from the following YAML. If you want this modifying, let me know and I can produce a new version with the required attributes.....

```
  - Name: QualityOfBathymetricData
    Foid: 1810:1411:100
    Prim: Surface
    Attributes:
      - Name: categoryOfTemporalVariation
        Value: Unassessed
      - Name: dataAssessment
        Value: Unassessed
      - Name: featuresDetected
        id: 1
      - Name: significantFeaturesDetected
        parent: 1
        Value: false
      - Name: leastDepthOfDetectedFeaturesMeasured
        parent: 1
        Value: false
      - Name: surveyDateRange
        id: 2
      - Name: dateEnd
        parent: 2
        Value: 2021-01-01
      - Name: zoneOfConfidence
        id: 3
      - Name: categoryOfZoneOfConfidenceInData
        Value: Zone of Confidence U
      - Name: fullSeafloorCoverageAchieved
        Value: false
```
[101USTESTOR001.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9104245/101USTESTOR001.zip)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Use test datasets to progress with testing of portrayal and A&I (see below). Leave the issue open. 
2. NIWC to implement the portrayal of **horizontalPositionalUncertainty** (value to be used should be the result of adding **uncertaintyVariableFactor** to **uncertaintyFixed**. If not possible use fixed value and report limitation **or** recommend new ECDIS display performance requirement to be passed to the S100WG)  when **displayUncertainties**=TRUE. Applies to Sounding, Underwater/Awash Rock, Wreck and Obstruction features. Use the following line style:                   

- [ ] CHMGF dashed line (thinner than the one used for **AdministrationArea**). Allocate new Viewing Group to enable switching display ON/OFF.

3. Request S100WG to develop a new ECDIS performance requirement to allow (at mariner's request) the triggering of A&I using 'worst case' scenarios for the position and depth of Sounding, Underwater/Awash Rock, Wreck and Obstruction features. This will be possible when **verticalUncertainty** and **horizontalPositionalUncertainty** values are populated (in **SpatialQuality** [when linked at the Point feature level] **or** in the **categoryOfZoneInConfidenceInData** of the overlying **QoBD** feature otherwise). The values to use must be the compound Accuracy value (uncertainty fixed + variable factor). **NOTE THAT** A&I must use the amended position/depth values whenever Hor/Vert uncertainties are encoded, irrespective of the value of the **displayUncertainties** attribute. This attribute is to only affect the display component of the horizontal uncertainties, as detailed in bullet point 1 above.

**Comment by DavidGrant-NIWC** [comment]
Jonathan,

Thanks - the data does load, but it has some errors.
 * Dates need to be YYYYMMDD (no dashes unless using an XML encoding).
 * The _categoryOfZoneOfConfidenceInData_ attribute needs to be part of complex attribute _zoneofConfidence_
 * The _name_ attribute of the Hulk needs to be part of complex attribute _featureName_

![image](https://user-images.githubusercontent.com/62906211/179633108-c8ca377a-deea-4c9f-b076-c7106ab75ea3.png)

![image](https://user-images.githubusercontent.com/62906211/179633603-4f97961f-976f-4cf4-ab01-647b5276b5f2.png)

> happy to help with this one - apologies we haven't been able to prepare much data in support of the efforts here but we're doing some of the S-101 test data and can prepare test datasets for specific, simple cells. We have a YAML processor which produces S-101 conformant data. Attached cell has a QualityOfBathymetricData feature which works in v1.9.0 of the NIWC viewer. This is generated from the following YAML. If you want this modifying, let me know and I can produce a new version with the required attributes.....
> 
> ```
>   - Name: QualityOfBathymetricData
>     Foid: 1810:1411:100
>     Prim: Surface
>     Attributes:
>       - Name: categoryOfTemporalVariation
>         Value: Unassessed
>       - Name: dataAssessment
>         Value: Unassessed
>       - Name: featuresDetected
>         id: 1
>       - Name: significantFeaturesDetected
>         parent: 1
>         Value: false
>       - Name: leastDepthOfDetectedFeaturesMeasured
>         parent: 1
>         Value: false
>       - Name: surveyDateRange
>         id: 2
>       - Name: dateEnd
>         parent: 2
>         Value: 2021-01-01
>       - Name: zoneOfConfidence

**Comment by kusala9** [comment]
ah, yes of course. 


remade file here... 

[101USTESTOR001.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9139051/101USTESTOR001.zip)

try this one? I think this is valid to the latest FC (also now includes vertical uncertainty). If you want to change the values just let me know.

yaml should have been 

```
  - Name: QualityOfBathymetricData
    Foid: 1810:1411:100
    Prim: Surface
    Attributes:
      - Name: categoryOfTemporalVariation
        Value: Unassessed
      - Name: dataAssessment
        Value: Unassessed
      - Name: featuresDetected
        id: 1
      - Name: significantFeaturesDetected
        parent: 1
        Value: false
      - Name: leastDepthOfDetectedFeaturesMeasured
        parent: 1
        Value: false
      - Name: surveyDateRange
        id: 2
      - Name: dateEnd
        Value: 20210101
        parent: 2
      - Name: zoneOfConfidence
        id: 3
      - Name: categoryOfZoneOfConfidenceInData
        Value: Zone of Confidence U
        parent: 3
      - Name: fullSeafloorCoverageAchieved
        Value: false
      - Name: verticalUncertainty
        id: 4
      - Name: uncertaintyFixed
        parent: 4
        Value: 0.5
```

**Comment by kusala9** [comment]
this is the feature in JSON (easier to read).
```json
    {
      "type": "Feature",
      "id": "1810:1411:100",
      "properties": {
        "featureType": "QualityOfBathymetricData",
        "surveyDateRange": {
          "dateEnd": "20210101"
        },
        "categoryOfTemporalVariation": "6",
        "featuresDetected": {
          "significantFeaturesDetected": "false",
          "leastDepthOfDetectedFeaturesMeasured": "false"
        },
        "fullSeafloorCoverageAchieved": "false",
        "zoneOfConfidence": {
          "verticalUncertainty": {
            "uncertaintyFixed": "0.5"
          },
          "categoryOfZoneOfConfidenceInData": "6"
        },
        "dataAssessment": "3"
      }
    }
```

**Comment by DavidGrant-NIWC** [comment]
I think that's the first dataset I've ever seen that doesn't have any errors!

Could you create the following two datasets to support prototyping/testing this issue?

## Dataset 1 - model uncertainties using QoBD and SpatialQuality
Add two of each of the following point features, one with and one without _displayUncertainties_=true:
* Sounding
* UnderwaterAwashRock
* Wreck
* Obstruction

For the features which have _displayUncertainties_=true, associate an instance of SpatialQuality to the point.
* The SpatialQuality should participate in a QualityOfBathymetricDataComposition
* The SpatialQuality should contain two instances of _spatialAccuracy_
* Each _spatialAccuracy_ attribute should contain both horizontal and vertical uncertainties
  * Each value should be unique for a given date range (uncertainties should degrade)
  * SpatialQuality._spatialAccuracy_._horizontalPositionUncertainty_
  * SpatialQuality._spatialAccuracy_._verticalUncertainty_
* Each _spatialAccuracy_ attribute should have a non-overlapping _fixedDateRange_ (_dateStart_/_dateEnd_)

## Dataset 2 - model uncertainties using only QoBD
As above, but:
* Don't use SpatialQuality
* Don't use QualityOfBathymetricDataComposition
* Two date ranges should be on instances of _zoneOfConfidence_
  * _zoneOfConfidence_.fixedDateRange_
* Uncertainties should be on instances of _zoneOfConfidence_
  * _zoneOfConfidence_._horizontalPositionUncertainty_
  * _zoneOfConfidence_._verticalUncertainty_

_Note: Adding an aggregation between each QoBD and the features to which it pertains would eliminate the need for spatial evaluation in this encoding method._

**Comment by kusala9** [comment]
yes, can do. I need to confirm some of the details with you but I'll do that via email/offline and we can work a test cell up.

**Comment by DavidGrant-NIWC** [comment]
Some results and questions arising from implementing portrayal and alerting on _horizontalPositionUncertainty_ when associated via SpatialQuality:
![image](https://user-images.githubusercontent.com/62906211/180518231-5081817b-bc4d-46fd-b90f-00ac25e69841.png)

* The thin magenta dashed circle is hard to see in shallow water
* The alert is triggered via an augmented ArcByRadius with a transparent fill
  * We could use NullInstruction, but then it is not clear whether the alert applies to the outline of the circle or to the interior.
* The uncertainty circle is only drawn when all of the following are true. As currently implemented you won't see uncertainty circles on "safe" points.
  * displayUncertainties is true
  * the point has a navigational hazard alert due to
    * DEPTH_VALUE <= safety contour value (OBSTRN/UWTROC/WRECKS)
    * EXPSOU=2 and VE3D subfield <= safety contour value (SOUNDG)
  * The point has an association to SpatialQuality with _spatialAccuracy_ populated
  * At least one of the _spatialAccuracy_ values applies to the selected viewing date
* I'm not doing anything with the vertical uncertainty yet - I'm a little unclear how and when (in the CSPs) this should be applied
  * Does it affect the portrayal?
  * Does this affect the alert processing (should the vertical uncertainty be subtracted from the depth)?
  * Should this affect the portrayal of isolated danger symbols (the adjustment may make a "safe" feature "unsafe")
* In order to apply the variable uncertainty it is necessary to know the depth
  * For UWTROC/OBSTRN/WRECKS I assume I would use DEPTH_VALUE as computed in the CSP?
  * horizontal position uncertainty = _uncertaintyFixed_ + DEPTH_VALUE * _uncertaintyVariableFactor_

I'll start looking at implementing the circles for points with no associated SpatialQuality._spatialAccuracy_, however:
* The DCEG says every point UWTROC/etc. 30 metres or less needs to have SpatialQuality associated
* Therefore the portrayal will never add these circles unless:
  * there is a large vertical uncertainty, or
  * the safety contour is set > 30m

**Comment by DavidGrant-NIWC** [comment]
Some additional results and questions.

I was able to implement for features which don't have an association to **SpatialQuality**, but:
* An extension to S-100 Part 13 is needed to support spatial evaluation of each point of a Multipoint
  * Needed to evaluate which **QoBD** applies to a given sounding
  * Can impact portrayal performance
    * number of evaluations is about 0.5 * # **QoBD** features * # sounding points
      * = about 50 - 5,000 spatial evaluations per dataset each time portrayal is run
* A change to the data model could help alleviate performance issues, some possibilities are listed below. Recommend this issue be brought up in the DCEG SWG.
  1. Always require an association to **SpatialQuality** (not just for features <= 30m)
      * For UWTROC/SOUNDG/etc.
      * eliminates all spatial evaluation
  2.  Require a feature association from **Sounding**/UWTROC/etc. to **QoBD** when association to **SpatialQuality** is not present
      * eliminates all spatial evaluation
      * could always provide the association, even when association to **SpatialQuality** is present
      * concept could be extended to support other meta features (to associate **VerticalDatumOfData**/etc.)
  3. Require all points of a given Sounding feature to lie within the area of a a single **QoBD**
      * Eliminates need for Part 13 extension
      * Reduces number of spatial evaluations to 0.5 * # **QoBD** features * # sounding features
        * = about 1 - 100 evaluations depending on dataset

Additional question:
* What should we do when _horizontalPositionUncertainty_ = unknown?
![image](https://user-images.githubusercontent.com/62906211/180846000-029f6ffb-7265-48b0-bcff-634dd692080f.png)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Can you please confirm the VG allocated to the magenta dashed line used to depict a feature's _horizontalPositionUncertainty_ ? I think we agreed on a new dedicated VG to make it possible to turn the symbology On/Off by mariners as required.

**Comment by DavidGrant-NIWC** [comment]
> @DavidGrant-NIWC - Can you please confirm the VG allocated to the magenta dashed line used to depict a feature's _horizontalPositionUncertainty_ ? I think we agreed on a new dedicated VG to make it possible to turn the symbology On/Off by mariners as required.

* This was only implemented as a prototype - it's not included in the current PC
    * because the capability is targeted for PC 1.1.0 or later
* The VG can be whatever we want, it just needs to be registered (but see next bullet).
* I'm not convinced that the magenta line should be shown at all, so perhaps a viewing group is not needed.
    * At "normal" viewing scales the line tends to overlap / underlap the point symbol, adding clutter.
    * The safety check will detect (and highlight when necessary) the circular area regardless of whether the outline is shown.
* Perhaps a new Portrayal Feature Attribute (DCEG 2.4.5) could be added to indicate that a particularly dangerous / important error circle should be displayed?
    * This would support the need for a new viewing group
    * ![image](https://user-images.githubusercontent.com/62906211/188194214-05d68df7-9e87-4644-afcc-fbce4f6ecc4a.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. NIWC confirmed they haven't implemented vertical uncertainties; neither symbology nor A&I.

2. Discussions continued regarding the need, or not, to display uncertainties (e.g dashed magenta circle). The alternative could be focusing the efforts on the development of A&I ('worst case scenario' option at mariner's request) during Route Planning only. No decision was made.

3. This topic requires comprehensive mariners' input in order to identify user's needs, narrow down requirements and drive areas of development.

@DavidGrant-NIWC  - Would the implementation of 'horizontal uncertainties' (portrayal and A&I) be available in PC 1.1.0 ????

Some discussion topics ... :

- [ ] **Route Planning** - Insert  requirement in S-98 Annex C to ensure ECDIS includes an option to check the planned route using **verticalUncertainty** and **horizontalPositionalUncertainty** values. A different option should also exist to visualize the vertical and positional 'worst case' scenarios by showing the shoalest possible depth and an uncertainty circle around features **(final portrayal still TBD although a preliminary option has been implemented for Horizontal Uncertainties)**.
- [ ] **Route Monitoring** - Should mariners be allowed to display 'altered' sounding/VALSOU figures and/or positional uncertainty circles while underway?? If Yes, should portrayal be any different than the one selected for Route Planning?? What about setting up the safety framework to use these values when populated?? In these cases an ECDIS performance requirement must be added to S-98 Annex C.
- [ ]  Feasibility of resolving, in real time, the ‘final’ Hor and Ver uncertainties when **uncertaintyVariableFactor** is populated (e.g. calculating, on the fly, **valueOfSounding** – [uncertainty fixed + uncertainty variable factor]) before altering the charted values for display/alarms when requested.
- [ ] Decide if the 'worst case' Hor & Vert uncertainties values from **categoryOfZoneOfConfidenceInData** would be used when **verticalUncertainty** and **horizontalPositionalUncertainty** values are not populated/Unknown and  **displayUncertanties**=Yes.

**Comment by DavidGrant-NIWC** [comment]
> @DavidGrant-NIWC - Would the implementation of 'horizontal uncertainties' (portrayal and A&I) be available in PC 1.1.0 ????

No, there are too many issues to be resolved. In particular, if the current modeling is retained then S-100 Part 13 needs to updated; however, the proposal we presented at the S-100 WG to make this change was not accepted.

We can continue to prototype in a PC branch though.

**Comment by DavidGrant-NIWC** [comment]
> No, there are too many issues to be resolved. In particular, if the current modeling is retained then S-100 Part 13 needs to updated; however, the proposal we presented at the S-100 WG to make this change was not accepted.

Proposal was rejected at TSM. Recommendation was to address by modifying the encoding/modeling:
![image](https://user-images.githubusercontent.com/62906211/233126827-ed845b7d-fb4b-436f-b729-ea925b6034e3.png)

One of the following options would address the issue, and there are probably other ways I haven't considered:
* Don't use a meta-feature / spatial relationship between `Sounding` and `QoBD` to encode the uncertainty.
  * Provide a feature association from `Sounding` to `QoBD`
  * Alternatively, provide an information association from `Sounding` to `SpatialQuality`
* Require that every point of a `Sounding` lie within a single `QoBD` feature.
  * Every point of the `Multipoint` geometry associated with a `Sounding` must lie within the `Surface` geometry associated with a single `QoBD` feature.

Any changes to the modeling should probably also include `DepthNoBottomFound`.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

**PC 1.2.0**

1. The first priority is on resolving 'spatial evaluation' issues.

- [x] **NIWC** to submit paper to S101PT10 (June 2023) highlighting the need to provide additional guidance in the DCEG in order to facilitate/enable the required 'spatial evaluation' methodology to manage their association with **SpatialQuality**.

- _**Preferred option**_:
Require that every point of a **Sounding** lie within a single **QoBD** feature.
Every point of the Multipoint geometry associated with a **Sounding** must lie within the Surface geometry associated with a single **QoBD** feature.
Any changes to the modeling should probably also include **DepthNoBottomFound**.

2. The second priority is on implementing A&I during Route Planning and Route Monitoring - Mariner has to be able to check a route taking into consideration the quality aspects (horizontal and vertical accuracies) of relevant hydrographic features (i.e. Sounding, UnderwaterRock, etc) lying within or close to a selected route.
**Reference**: MSC.530.106.-.PERFORMANCE.STANDARDS.FOR.ELECTRONIC.CHART.DISPLAY.AND.INFORMATION.SYSTEMS.ECDIS._Nov2022 - sections 11.4.9 & 11.3.6:
_'It should be possible for the mariner to select that the indications take into account accuracy information of relevant hydrographic information, as defined by IHO standards.'_
**This performance would require a new S-164 test case.**

**PC 2.0.0**
3. Resolve the need for a dedicated symbology that portrays horiz & vert. accuracies of hydrographic features at mariner's request. In short, the need for the attribute 'display uncertainties' (mariner supported Use Case + decision around DF-ECDIS implementation).

**Comment by mikan66** [comment]
Regarding point 1 above: "NIWC to submit paper to S101PT10 (June 2023) ....." noting S-101PT10 paper: "S-101PT10-07.9	29 May	Vertical Datum Information in S-101", which references: https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT9/S-101PT9_2022_INF1-01_EN_Metadata_Issues_V1.pdf

This topic, point 1, falls into this Metadata issues paper as well.  I plan to add talking points to Tom's presentation as needed during discussions at PT10.

**Comment by TomRichardson6** [comment]
@mikan66 thanks Mikan no charge! you have enough actions on your plate! I would be happy for NIWC to provide its presentation from PT9 first when this arises on the agenda and I can then follow with my slides which really just seek to push towards a recommendation.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- Vertical & Horizontal uncertainties' buffer zones' won't have dedicated symbology.
They will only interact wit A&I. For this they will trigger the depiction of INDHLT or DNGHL in the same manner the related charted feature do. 
Refer to Issue #88 for more details on this.
