### ISSUE TITLE
S-98 change proposal - Standardisation of the portrayal of shared edges in ECDIS

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#100]
This issue has been created to facilitate discussions and finalise an S-98 change proposal to establish a new ECDIS performance requirement regarding the portrayal of Surface boundaries when edges are shared by 2 or more features having the same Display Priority.
For background info refer to Github Issues https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/8 and https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/56

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC   -  **S-98 Annex C change proposal**:

![image](https://user-images.githubusercontent.com/70189016/200697962-50f1d0db-0f35-4126-88e6-57faca5615cb.png)

[S-98 Standardization of the portrayal of shared edges in ECDIS.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9941369/S-98.Standardization.of.the.portrayal.of.shared.edges.in.ECDIS.pdf)

**Comment by alvarosanuy** [comment]
Thanks David. It looks great to me.

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/212009789-aedcce05-85e1-49a3-8e1e-dd85cbab4a77.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. Paper was submitted but no decision as yet. The issue has been referred to TSM for further discussions (see previous comment).

2. Leave the issue open until a decision is made by S100-TSWG.

**Comment by DavidGrant-NIWC** [comment]
Change proposal was rejected
![image](https://user-images.githubusercontent.com/62906211/233118441-0b790751-778b-46db-9142-2a90054f7e34.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- [x] **Alvaro** to follow up with S100WG Chair. Particularly around Decision 9/25 from TSM and how NIWC's change proposal could be implemented using S-100 Validation. The S-101 PsWG does not see how this would be possible. The aim of this proposal is to improve ENC readability. We are looking for a portrayal outcome that can be tested in S-164 without dictating how OEMs get to implement it.

**Comment by alvarosanuy** [comment]
> * **Alvaro** to follow up with S100WG Chair. Particularly around Decision 9/25 from TSM and how NIWC's change proposal could be implemented using S-100 Validation. The S-101 PsWG does not see how this would be possible. The aim of this proposal is to improve ENC readability. We are looking for a portrayal outcome that can be tested in S-164 without dictating how OEMs get to implement it.

**Email sent on 22/5/23 - Refer to email trail in the next comment.**

**Comment by alvarosanuy** [comment]
From: Grant, David M (52400) CIV USN NIWC ATLANTIC VA (USA) <david.m.grant22.civ@us.navy.mil>
Sent: Thursday, 1 June 2023 12:57 AM
To: Jonathan Pritchard <jonathan.pritchard@iictechnologies.com>; Sanchez, Alvaro MR <alvaro.sanchez@defence.gov.au>; Powell, Julia L CIV (USA) <julia.powell@noaa.gov>
Cc: yong.baek@iho.int; Thomas Richardson <Thomas.Richardson@ukho.gov.uk>
Subject: RE: Follow up on TSM Decision 9/25 [SEC=OFFICIAL]

 

Hi Jonathan,

 

I agree 😊

 

BTW, in case anyone was suggesting resolving this by masking the coincident line segment:

I’m not 100% sure, but I don’t think you can mask (S100_GF_MaskReference) a shared line segment in a single direction. The mask can only reference the spatial object, and the (single) spatial object is shared by the adjacent features.
Even if possible, masking would be labor intensive for data producers.
In any case, masking doesn’t work for complex line styles, where both directions must be drawn to show the symbols pointing “in”. Since most areas have both a “plain” and a “complex” symbolization (toggled via the “Plain boundaries” context parameter) it would be incorrect to mask any of the line segments; the outline would not be displayed correctly in the complex rendering.
 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/1bb88aff-a5ce-4b34-8c3a-572c3f8fbd61)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/7f0944e5-686c-4ee6-b09e-791146c85e36)



 



 

From: Jonathan Pritchard <[jonathan.pritchard@iictechnologies.com](mailto:jonathan.pritchard@iictechnologies.com)>
Sent: Wednesday, May 31, 2023 9:29 AM
To: Sanchez, Alvaro MR <[alvaro.sanchez@defence.gov.au](mailto:alvaro.sanchez@defence.gov.au)>; Powell, Julia L CIV (USA) <[julia.powell@noaa.gov](mailto:julia.powell@noaa.gov)>
Cc: [yong.baek@iho.int](mailto:yong.baek@iho.int); Thomas Richardson <[Thomas.Richardson@ukho.gov.uk](mailto:Thomas.Richardson@ukho.gov.uk)>; Grant, David M (52400) CIV USN NIWC ATLANTIC VA (USA) <[david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil)>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: Follow up on TSM Decision 9/25 [SEC=OFFICIAL]

 

Hi Alvaro,

 

sorry for the delay, I had to reread Dave's original paper. Yes, we are proposing to implement the S-98 change as written in the paper. I will take the paper forward in the S-164/S-98 dedicated subgroup and we can have an informed discussion there. Although TSM has made a recommendation we can go through it at S100WG8 in November. I'll do an update to the action as part of the S-98 update and include the original paper as an annex.

 

Recalling the conversation at TSM I believe it was Hannu who had asked if the issue raised could be solved by a validation test. I think there's a confusion because the issue occurs when two edges are in a different direction even though they have the same orientation. The confusion arises because it's very unlikely for differently oriented curves to be coincident (i.e. for an interior to be coincident with an exterior) - if you look at the diagram below, the two rectangular polygons are both digitised in the same direction but if they have a single coincident edge (east of the left one, west of the right one) they are digitised in opposite directions. So, the problem Dave outlines is definitely much easier to arise with adjacent polygons, not just those where the orientation is opposite (i.e interior vs exterior). 

 



so, I think our reasoning at TSM9 was probably flawed and we should reconsider this - if the S-98 group agrees we'll add the recommendations into the draft of S-98 and also ensure this situation is tested for in S-164 (I'm not sure where yet, although there are some dedicated  tests for complex rendering of edges). 

 

I hope this clarifies things - I'm sure Dave will correct me if I have the wrong end of the stick 🙂.

 

Jonathan.

 

From: Sanchez, Alvaro MR <[alvaro.sanchez@defence.gov.au](mailto:alvaro.sanchez@defence.gov.au)>
Sent: 30 May 2023 00:58
To: Jonathan Pritchard <[jonathan.pritchard@iictechnologies.com](mailto:jonathan.pritchard@iictechnologies.com)>; Julia Powell - NOAA Federal <[julia.powell@noaa.gov](mailto:julia.powell@noaa.gov)>
Cc: [yong.baek@iho.int](mailto:yong.baek@iho.int) <[yong.baek@iho.int](mailto:yong.baek@iho.int)>; Thomas Richardson <[Thomas.Richardson@ukho.gov.uk](mailto:Thomas.Richardson@ukho.gov.uk)>; [david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil) <[david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil)>
Subject: RE: Follow up on TSM Decision 9/25 [SEC=OFFICIAL]

 

OFFICIAL

Hi all,

 

Thanks Julia and Jonathan for clarifying the situation. It looks like we are in the same page regarding a way forward.

 

We are talking about adding the performance requirement in S-98 and creating a dedicated S-164 test to verify compliance by OEMs.

 

Question is, are we happy to proceed as stated above or do you still want NIWC to re-submit their paper for discussion at the upcoming S100WG8 meeting in November?

 

If we decide to proceed before S100WG8 then the S-98 change proposal in NIWC’s paper could be used by JP to draft a new version of S-98 and as input to develop a new S-164 test.

 

For more details, please refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/100 and/or contact David Grant directly if required.

Looking forward to your views on this.

 

Thanks in advance,

 

Alvaro

 

Alvaro Sanchez | Acting Director National Charting

8 Station Street, Wollongong

T: +61 2 4223 6506 | M: +61 434 349 674

 

Aboriginal AHO logo

Maritime Geospatial Branch

Australian Geospatial-Intelligence Organisation

Defence Intelligence Group | Department of Defence

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.

 

 

From: Jonathan Pritchard <[jonathan.pritchard@iictechnologies.com](mailto:jonathan.pritchard@iictechnologies.com)>
Sent: Tuesday, 30 May 2023 6:45 AM
To: Julia Powell - NOAA Federal <[julia.powell@noaa.gov](mailto:julia.powell@noaa.gov)>; Sanchez, Alvaro MR <[alvaro.sanchez@defence.gov.au](mailto:alvaro.sanchez@defence.gov.au)>
Cc: [yong.baek@iho.int](mailto:yong.baek@iho.int); Thomas Richardson <[Thomas.Richardson@ukho.gov.uk](mailto:Thomas.Richardson@ukho.gov.uk)>; [david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil)
Subject: Re: Follow up on TSM Decision 9/25 [SEC=OFFICIAL]

 

 ⚠  EXTERNAL EMAIL: Do not click any links or open any attachments unless you trust the sender and know the content is safe.  ⚠.

Julia’s interpretation on this is correct - at TSM we didn’t have anyone present who was able to properly present the paper. The paper clearly showed the problem and recommended ways to clarify this to handle it but the question was asked whether the situation could be avoided through data validation tests. I think it definitely stands another discussion as I’m not convinced validation is the best way (or even practical) so if we can handle this through the S98 revision I suggest we go down that route. TSM was a busy week - it’s a shame we didn’t have all the right folks there to do this one properly: there’s no harm in discussing it when we do have the right inputs. We should probably consider including test cases in S164 too if we are to add the clarifications to S98… I’ll add it to the list

 

Cheers

 

JP

 

Jonathan Pritchard

Senior Technical Manager

IIC Technologies Limited

Tel. : +44 7464 371695

[www.iictechnologies.com](http://www.iictechnologies.com/)

From: Julia Powell - NOAA Federal <[julia.powell@noaa.gov](mailto:julia.powell@noaa.gov)>
Sent: Monday, May 29, 2023 3:41:34 PM
To: Sanchez, Alvaro MR <[alvaro.sanchez@defence.gov.au](mailto:alvaro.sanchez@defence.gov.au)>
Cc: [yong.baek@iho.int](mailto:yong.baek@iho.int) <[yong.baek@iho.int](mailto:yong.baek@iho.int)>; Thomas Richardson <[Thomas.Richardson@ukho.gov.uk](mailto:Thomas.Richardson@ukho.gov.uk)>; [david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil) <[david.m.grant22.civ@us.navy.mil](mailto:david.m.grant22.civ@us.navy.mil)>; Jonathan Pritchard <[jonathan.pritchard@iictechnologies.com](mailto:jonathan.pritchard@iictechnologies.com)>
Subject: Re: Follow up on TSM Decision 9/25 [SEC=OFFICIAL]

 

Hi Alvaro -

 

I think part of the problem is that Dave Grant was unable to make the TSM meeting to present the issue in person and the experts may have interpreted it differently.  I know that Jonathan Pritchard realized a bit later that we may have had the wrong interpretation of the proposal, but by that time it was at the end of the meeting.

 

I would suggest that this be resubmitted to the S-100WG in November for reconsideration.  Another option would be for JP to take it up as part of the S-164/S-98 intersessional work that he will be doing to capture everything that is needed for Edition 2.0.0. The work on that will start in earnest after HSSC.

 

Best Regards

 

Julia

 

On Mon, May 22, 2023 at 1:27 AM Sanchez, Alvaro MR <[alvaro.sanchez@defence.gov.au](mailto:alvaro.sanchez@defence.gov.au)> wrote:

OFFICIAL

Hi Julia,

 

At the latest S-101 Portrayal subWG meeting NIWC informed us that S-100 TSM has not approved our proposal to improve ENC readability by including an S-98 Annex C (C-7.2.5) clarification/requirement on the rendering of line symbology on shared edges.

This proposal was original presented at S100WG7 but deferred to the S100TSM meeting to finally being rejected with a recommendation ‘to be considered in S-100 Validation’.

The PsWG could not make sense of the recommendation and how this requirement could be handled by S-100 validation.

 

Accordingly, I was tasked to follow up with you and see if you can provide the S100WG view on how this could be implemented as recommended by TSM.

 

We think a way forward is to update S-98 as recommended in NIWC’s paper (which was born within the PsWG) and ‘Validate’ its implementation by OEMs by adding a new S-164 test.

We are interested in the portrayal outcome and not on how OEMs get to implement it.

Below is a link to the corresponding PsWG GitHub issue.

 

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/100

Thanks in advance for your time,

 

Alvaro

 

Alvaro Sanchez | Acting Director National Charting

8 Station Street, Wollongong

T: +61 2 4223 6506 | M: +61 434 349 674

**Comment by alvarosanuy** [comment]
**Action:**

- [ ] **Jonathan Pritchard**  - Prepare an S-98 draft version including recommendations in NIWC's paper and present for endorsement at S100WG in November 2023.
- [ ] **Jonathan Pritchard** - Include new test in S-164.

**Comment by alvarosanuy** [comment]
@Kusala9 - Can you please provide an update on the Actions above?

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

Understanding is that @kusala9 will:
- [ ] Prepare an S-98 draft version including recommendations in NIWC's paper and present for endorsement at S100WG in November 2023 (S100WG8).
- [ ] Once approved, include a new test in S-164.

**Leave this Issue open until there's confirmation that S-98 change proposal has been endorsed by S100WG8 (November 2023**).

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC & @kusala9 - Where is this issue sitting at the moment? If tracked by @kusala9 for S-98/S-164, can we then close this PC issue?

**Comment by kusala9** [comment]
It was discussed at S100WG8 but I can't find it in the list of actions/decisions unfortunately. My recollection of the conversation was that it was agreed to add a clarification into S-98 Annex C warning of the dangers of drawing lines (particularly symbolised boundaries) in opposite directions but to not include an explicit test for it. I have raised an issue in the S-98 Repository (#37) and I will chase IHO to get the decision recorded in the notes of S100WG8. This one can be closed - if there are any other developments they can be recorded on the S-98 Issue.

**Comment by DavidGrant-NIWC** [comment]
Agree with JP
