### ISSUE TITLE
Value of Local Magnetic Anomaly - Rules to depict values

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#102]
The use of text to display the values of a **LocalMagneticAnomaly** was identified while reviewing Jeff's spreadsheet and tasked to NIWC for implementation within the corresponding PC rule.

Since then, discussions on the logic to display the values based on all possible combinations of **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** continued in the iho-ohi Github space, **after** NIWC's implementation (their issue is currently CLOSED).
Consequently, before NIWC re-opens the issue to make amendments, it make sense to expose the conversation so far to all Portayal subWG members (by opening this new Issue in our Github space) with the aim of getting broader input and agreement.

Please refer to https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/73 to understand the background conversation on this issue. Below, I copied the last entry from Mikus and my comments to his proposal.

I will leave **this issue open until 31AUG2022**. I'll then close it and inform NIWC of the official decision on this topic.

**Please read and provide comments by that date.**

**Comment by alvarosanuy** [comment]
**Last entry by Mikus (11/8/22):**

From Klas comment above and earlier experience I propose to further fine-tune the possible combinations. This might be an "overkill", but at least this would then be unambiguous for encoders and consistent in implementation, and might help in future for ENC printing to paper as backup:

-  When both, magneticAnomalyValueMaximum and magneticAnomalyValueMinimum are populated with the same value and with a value different to Unknown:
depict the value of magneticAnomalyValueMaximum preceded by '±'.
For example ±4°

- When both, magneticAnomalyValueMaximum and magneticAnomalyValueMinimum are populated with different values and with a value different to Unknown:
in brackets, depict 'magneticAnomalyValueMaximum' followed by 'E', followed by '/', followed by 'magneticAnomalyValueMinimum', followed by 'W'.
For example (4°E/6°W)

- When either one, magneticAnomalyValueMaximum or magneticAnomalyValueMinimum is populated with a value and the other respective subattribute is not populated:
in brackets, depict populated subattributes value followed by 'E', if the populated value is 'magneticAnomalyValueMaximum' or 'W', if the populated value is 'magneticAnomalyValueMinimum'.
For example (4°E) or (6°W)

- When magneticAnomalyValueMaximum is populated with Unknown and magneticAnomalyValueMinimum is not populated or Unknown:
portray only the border of the anomaly's geometry;
or,
depict text "Magnetic Anomaly".
For example Magnetic Anomaly

The third option would cover the instances, mentioned by Klas (therefore proposed also changes to first and second), and the fourth would cover the instances, where the data is either very old and might be considered not portray exact values, or where there is no specific value reported or specific values do not exist in the source material.

_Originally posted by @MikusRL in https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/73#issuecomment-1211761346_

**Comment by alvarosanuy** [comment]
> * When both, magneticAnomalyValueMaximum and magneticAnomalyValueMinimum are populated with the same value and with a value different to Unknown:
>   depict the value of magneticAnomalyValueMaximum preceded by '±'.
>   For example ±4°

The problem here is that the DCEG instructs to encode identical magnetic anomaly values using the **magneticAnomalyValueMaximum** attribute only.
I believe Mikus general proposal makes sense and it covers for situations when the magnetic anomaly is only 'positive' (E). 
Consequently, this proposal **will require amending the DCEG to instruct users to 'repeat the value in both magnetic anomaly value attributes when identical'.**

To maintain consistency with the other options, I **recommend displaying the result using brackets**.

**Example: (±4°)**

**Comment by alvarosanuy** [comment]
DO NOT APPLY (DEC ISION MADE IN JANUARY 2022) **NIWC** - Please proceed and amend PC as per the following instructions:

When both, **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** are populated with the same value and with a value different to Unknown:
depict the value of **magneticAnomalyValueMaximum** preceded by '±' and in brackets.
For example **(±4°)**

When both, **magneticAnomalyValueMaximum** and **magneticAnomalyValueMinimum** are populated with different values and with a value different to Unknown:
in brackets, depict **magneticAnomalyValueMaximum** followed by 'E', followed by '/', followed by **magneticAnomalyValueMinimum**, followed by 'W'.
For example **(4°E/6°W)**

When either one, **magneticAnomalyValueMaximum** or **magneticAnomalyValueMinimum** is populated with a value and the other respective subattribute is not populated:
in brackets, depict populated subattributes value followed by 'E', if the populated value is **magneticAnomalyValueMaximum** or 'W', if the populated value is **magneticAnomalyValueMinimum**.
For example **(4°E) or (6°W)**

When **magneticAnomalyValueMaximum** is populated with Unknown and **magneticAnomalyValueMinimum** is not populated or Unknown:
portray only the border of the anomaly's geometry;
or,
depict text "**Magnetic Anomaly**" - Colour (CHMGF to match LOCMAG51), Font, etc as per the numeric values .

**Note**:

1. Legends will require an offset to avoid clashing with SY(LOCMAG51).
2. Implementation has been tagged as 'PC 1.1.0 or later' as DCEG subWG has to discuss/endorse the 'double encoding' of 
 **magneticAnomalyValue** when Maximum and Minimum values are identical (and not just **magneticAnomalyValueMaximum** as currently instructed).

The problem here is that the DCEG instructs to encode identical magnetic anomaly values using the **magneticAnomalyValueMaximum** attribute only.
The labelling proposal above covers for situations when the magnetic anomaly is only 'positive' (E) but it becomes a problem based on the current DCEG guidance that instructs users to only populate **magneticAnomalyValueMaximum** when both magnetic anomaly values (Max & Min) are identical.
Consequently, our labelling proposal will require amending the DCEG to instruct users to 'repeat the value in both magnetic anomaly value attributes when identical'.

**Comment by JeffWootton** [comment]
See possible remodelling to cover all scenario's in S-4 - B-274 as included in new S-101 Documentation and FC issue #21 at https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/21.

**Comment by alvarosanuy** [comment]
Portrayal logic needs revision after feature modelling changes introduced by DCEG 1.1.0 (section 4.2)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

New **text** portrayal instructions based on the final remodelling of **LocalMagneticAnomaly**:

When only one instance of **valueOfLocalMagneticAnomaly** is populated with a value of **magneticAnomalyValue** different to Unknown and **referenceDirection** is empty or Unknown:
depict the value of **magneticAnomalyValue** preceded by '±' and in brackets.
For example (±4°)

When only one instance of **magneticAnomalyValue** is populated with a value of **magneticAnomalyValue** different that Unknown and **referenceDirection** is also populated with a value different to Unknown:
in brackets, depict **magneticAnomalyValue** followed by the hemisphere label linked to the value of **referenceDirection**
For example (4°E) or (6°W)

When all instances (one or more) of **magneticAnomalyValue** are populated with **magneticAnomalyValue=Unknown**:
depict text "Local Magnetic Anomaly" - Colour (CHMGF to match LOCMAG51), Font, etc as per the numeric values. 
This is irrespective of the values encoded for **referenceDirection**

When two instances of **valueOfLocalMagneticAnomaly** are populated with values different to Unknown:
in brackets, depict the first **magneticAnomalyValue** entry followed by the hemisphere label linked to the value of **referenceDirection**, followed by '/', followed by the second **magneticAnomalyValue** entry followed by the hemisphere label linked to the value of **referenceDirection**
For example (4°E/6°W)

**Note**:
- Legends will require an offset to avoid clashing with SY(LOCMAG51).

**Comment by mikan66** [comment]
In reviewing S-101_FC_1.1.0_20230202.xml, I need further clarification on the decision.  This is what I see in the feature catalog:

(A) Up to 2 instances of:  valueOfLocalMagneticAnomaly
(B) For each instance of (A) one value of: magneticAnomalyValue, optional one value of: referenceDirection

The first part of the guidance from @alvarosanuy  "When only one instance of valueOfLocalMagneticAnomaly ..." then in the next paragraph: "When only one instance of magneticAnomalyValue..."  implies to me that there could be multiple instances of 'magneticAnomalyValue' for each 'valueOfLocalMagneticAnomaly' and I just don't see that from the definition in the feature catalog.

**Comment by alvarosanuy** [comment]
**Updated mapping after comment made by @mikan66 above:**

- When only one instance of **valueOfLocalMagneticAnomaly** is populated with a value of **magneticAnomalyValue** different to Unknown and **referenceDirection** is empty or Unknown:

depict the value of **magneticAnomalyValue** preceded by '±' and in brackets.
For example (±4°)

- When only one instance of **valueOfLocalMagneticAnomaly** is populated with a value of **magneticAnomalyValue** different that Unknown and **referenceDirection** is also populated with a value different to Unknown:

in brackets, depict **magneticAnomalyValue** followed by the hemisphere label linked to the value of **referenceDirection**
For example (4°E) or (6°W)

- When all instances (one or more) of **valueOfLocalMagneticAnomaly**  are populated with **magneticAnomalyValue=Unknown**:

depict text "Local Magnetic Anomaly" - Colour (CHMGF to match LOCMAG51), Font, etc as per the numeric values. 
This is irrespective of the values encoded for **referenceDirection**

- When two instances of **valueOfLocalMagneticAnomaly** are populated with values different to Unknown:

in brackets, depict the first **magneticAnomalyValue** entry followed by the hemisphere label linked to the value of **referenceDirection**, followed by '/', followed by the second **magneticAnomalyValue** entry followed by the hemisphere label linked to the value of **referenceDirection**. 
For example (4°E/6°W)

If one or both **referenceDirection** attributes are encoded as Unknow the hemisphere labels are not to be shown - For example (4°/6°). This encoding should be forbidden and reported by a validation check but ......

**Note**:
- Legends will require an offset to avoid clashing with SY(LOCMAG51).

**Comment by mikan66** [comment]
@alvarosanuy I've uploaded an attachment with images and scenarios for your review and further discussion.  I think the logic will work once real test data is available.
[Notes.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10687606/Notes.pdf)

**Comment by alvarosanuy** [comment]
@mikan66  - Font must be in CHMGF colour for all magnetic legends - e.g. (±4°).

Refer to S-4 B-274.1 and INT1 B82.1

**Comment by mikan66** [comment]
All text will now look like: 
![image](https://user-images.githubusercontent.com/4913543/217831697-98072200-88da-4bbb-8a2d-58f833480f26.png)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
