### ISSUE TITLE
Review of Pilotage District Symbology

### ISSUE THREAD

**Issue by TomRichardson6** [S-101-Portrayal-subWG/Working-Documents#105]
At S-101 PT9 paper 8.3 noted the similarity of the new Pilotage District symbology agreed under Github item 57 with the Pilot Boarding place symbology and similarity to S-4 guidance for paper charts. 

https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT9/S-101PT9_2022_08.3_EN_S-101_Pilotage_Feature_Symbology_in_S-101_V1.pdf

The PT agreed that the symbology should be reviewed, and alternative symbology considered that is more distinct from the Pilot Boarding place symbology to reflect that the Pilotage District has a distinct meaning. 

https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/57

**Comment by alvarosanuy** [comment]
Based on the encoding guidance for **Pilotage Districts** currently in the S-57 UOC (13.1.2), where it directs the encoding of an ADMARE, it seems logical to consider using the same symbology and do not use the symbol PILBOP02, in any way, so it does not create confusion with the symbology used for **Pilot Boarding Places** (Point and Surface - Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/106).

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. Amend **PilotageDistrict** features to depict as per **AdministrationAreas**

2. Implement in PC 1.1.0

**Comment by mikan66** [comment]
The only thing different will be the Viewing Group.
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/ef7362cd9b38114fa4d07aac997da665c7b3bddc

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0

**Comment by TomRichardson6** [comment]
All

TDS 22 has been updated to include an area Pilotage District to support testing. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0022/4

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/96d77af1-b8c6-4ecb-8148-6e7c7b780570)

**Comment by mikan66** [comment]
Using https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0022, test data was cleared on older PC issue #94.

Plain Boundaries ON: 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/a880c822-39bd-47eb-a1ba-21b1f792a108)


Plain Boundaries OFF: 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/fee32a65-de89-4020-b11e-cad8766cf483)
