### ISSUE TITLE
New Symbology for Pilot Boarding Place surface

### ISSUE THREAD

**Issue by TomRichardson6** [S-101-Portrayal-subWG/Working-Documents#106]
At S-101 PT 9 paper 8.3 highlighted the issue that the centred symbol for a Pilot Boarding place of type surface is the same as the point symbol. The meeting agreed that new symbology should be considered. 

https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT9/S-101PT9_2022_08.3_EN_S-101_Pilotage_Feature_Symbology_in_S-101_V1.pdf

The Portrayal Sub Group is invited to consider the following options to replace the current centred symbol PILBOP02;

A) The addition of a square polygon to the existing PILBOP02 symbol. See paper. 

B) Creation of a larger PILBOP02 symbol in a lighter magenta shade CHMGF similar to the centred symbols for restrictions. e.g. SY(ACHRES51)

Feel free to propose alternative options or comment on the options above.

**Comment by alvarosanuy** [comment]
@MikusRL  - Can you please prepare a symbol as per option B) above? Please make sure there's an offset so it does not display on the center of the viewing area.

I would like to present this option as the preferred option at our next meeting. Once created I would ask @DavidGrant-NIWC to prepare a screenshot with a PILBOP point feature within the Pilot Boarding Place of type Surface (Pilot boarding area) to discuss readability.

**Comment by MikusRL** [comment]
@alvarosanuy - Ok, can try to do it, latest end of next week.

**Comment by MikusRL** [comment]
Design and outputs.

Sketch:
![Sketch](https://user-images.githubusercontent.com/72803214/204112537-c543c5f1-e37c-4e25-a7fb-8e48a4a0dea1.png)
Anchorage area centre sybmol is lineworks, hence less obscures other information on chart. The Pilotage rhomb is opaque and could potentially obscure more, if created up to 14mm. I chose the general convention for the centre symbol size - 9.94mm.

Created symbols for option B) (see @alvarosanuy comment above):
[PILBAR51.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10097228/PILBAR51.zip)

![image](https://user-images.githubusercontent.com/72803214/204113172-a34c7ce9-dc9f-41ec-a6d8-d2afb89e4d03.png)

![image](https://user-images.githubusercontent.com/72803214/204113204-146c8eaa-7471-43e8-a7bd-08a11a7d8d84.png)

![image](https://user-images.githubusercontent.com/72803214/204113209-0fd635d5-4c12-4c68-87bf-f10548a5f41a.png)

During the work process:
![image](https://user-images.githubusercontent.com/72803214/204113157-d6bf2a03-c16e-4982-ac6f-4a3410e88032.png)

![image](https://user-images.githubusercontent.com/72803214/204113217-90caff63-a455-4772-8a15-10eb68ef5781.png)

I personally at the end like the hallow version. It could potentially even be created with no offset, as could possibly be less obscuring of other chart detail and the point symbol, if captured in the area. And in display priority it could be drawn under the point geometry symbol. 

![image](https://user-images.githubusercontent.com/72803214/204113865-2496f312-d6c3-4423-8631-8d94e348ce95.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. The symbol **PILBARE51_hallow** was approved
2. @MikusRL - Please provide Engineering Drawing, SVG and CSS for **PILBARE51_hallow** (rename as PILBARE51)
3. **NIWC** - Update **PilotBoardingPlace** (Surface) to display PILBARE51_hallow symbol as a central symbol for the area (in lieu of PILBOP02).
4. Implement in PC 1.1.0

**Comment by MikusRL** [comment]
Created the symbol and renamed to PILBARE51as per the point 2. above. 
[PILBARE51.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10460247/PILBARE51.zip)

![image](https://user-images.githubusercontent.com/72803214/213537720-56b482b3-e642-4012-9292-d850c5380bb6.png)

**Comment by mikan66** [comment]
> 3\. PILBOP02

NOTE: PILBOP02 is also referenced by Line Style PILDSTR1.xml.  It also appears that only PilotageDistrict.lua references the line style PILDSTR1. I can't find any other references for PILBOP02, so should this line style also be change to PILBARE51 or left as-is?  For now I will leave "as-is" and we can open another issue for the linestyle if needed.

**Comment by mikan66** [comment]
See PC commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/5f8ef0d5a534c8b193de7d7b19fcc6b522353224

**Comment by alvarosanuy** [comment]
> > 3. PILBOP02
> 
> NOTE: PILBOP02 is also referenced by Line Style PILDSTR1.xml. It also appears that only PilotageDistrict.lua references the line style PILDSTR1. I can't find any other references for PILBOP02, so should this line style also be change to PILBARE51 or left as-is? For now I will leave "as-is" and we can open another issue for the linestyle if needed.

@mikan66 - Line style PILDSTR1 won't be used anymore. It was developed to depict the boundary of **PilotageDistrict** features (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/57) but this decision was reverted (at S101PT9 https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/105) to show a dashed magenta line instead. 
PILBOP02 should still be referenced by **PilotBoardingPlace** features of type Point though .....

**Comment by mikan66** [comment]
I think as "checked in" we are good pending official review.  PC directory cleanup of unused files is something we might want to do at some point before production release of the PC.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
