### ISSUE TITLE
Update symbology and mapping of Sloping Ground & Slope Topline features - NCWG8-06.10A

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#108]
NCWG8 meeting confirmed the validity of the guidance in S4 where **SlopingGround** and **SlopeTopline** related symbols are differentiated only when they are visually conspicuous and not when they are Radar conspicuous (as currently implemented by S-52 PL).

Based on this premise, it is proposed to modify the S-52 logic and always depict these features using the same symbology (generally, irrespective of their 'category'), and only alter this default symbology to indicate conspicuity (visual or radar).
As a consequence, the portrayal rules for these 2 features should be amended as follows:

**SLOPING GROUND**

- Symbolise all **SlopingGround** features of type Point using the symbol HILTOP01 **except when** the attributes **visualProminence** = 1 (visually conspicuous) or the attribute **radarConspicuous** = True are encoded; in these cases they are to be mapped to HILTOP11.

- Symbolise all **SlopingGround** features of type Surface as per S-52 SLOGRD (Plain & Symbolised boundaries) but:
                  -  replacing CHGRD with LANDF and CHBLK with CHGRD when features **are not** Visual or Radar conspicuous.
                              AC(LANDF);LS(SOLD,1,CHGRD)
                  -  Using AC(CHGRD);LS(SOLD,1,CHBLK) when features **are** Visual or Radar conspicuous.

**SLOPE TOPLINE**

- Symbolise all **SlopeTopline** features, **not** Visually or Radar conspicuous, and categoryOfSlope <> 2 & 6 using: LS(SOLD,1,LANDF)

- Symbolise all **SlopeTopline** features, **not** Visually or Radar conspicuous, and categoryOfSlope = 2 or 6 using: LS(SOLD,1,CHGRD)

- Symbolise all **SlopeTopline** features, **that are** Visually or Radar conspicuous, where categoryOfSlope = 2 or 6 using: LS(SOLD,1,CHBLK)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. @DavidGrant-NIWC  - Can you please confirm you can amend the simple lines and area boundaries yourself (within the rules) without the need of new symbology? **If yes,** we aim for PC 1.1.0. **If not**, please identify what is needed and I will coordinate development (this will move the implementation target to PC 1.2.0).
 
2. Test data will be required.

**Comment by DavidGrant-NIWC** [comment]
No new symbols are needed.

* [ ] @alvarosanuy please update the label to PC 1.1.0

**Comment by mikan66** [comment]
@alvarosanuy , sloping ground SURFACE (symbolized boundaries) has compound logic depending on categoryOfSlope and also AND combination of radarConspicuous, visualProminence

cat (1,2,3) and feature.radarConspicuous and feature.visualProminence == 1         then CHBLK
cat(4,5,6,7) and feature.radarConspicuous then CHBLK

Please clarify further the exact boolean conditions to change the color
OPTION 1:  
cat (1,2,3) and NOT (feature.radarConspicuous AND feature.visualProminence == 1 )        then CHGRD 
cat(4,5,6,7) and NOT eature.radarConspicuous then CHGRD 

OPTION 2:
cat (1,2,3) and NOT (feature.radarConspicuous OR feature.visualProminence == 1  )       then CHGRD 
cat(4,5,6,7) and NOT eature.radarConspicuous then CHBLK

OPTION 3: ???
   
********************
Specific example for categoryOfSlope(1,2,3):

![image](https://user-images.githubusercontent.com/4913543/224766292-6a489f20-705a-4c7f-81bf-c758fee0a5f2.png)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC  - The decision made at NCWG8 was not to use category of Sloping Ground to drive portrayal and only check if the feature is conspicuous or not (either visual or radar) to drive a change in portrayal.

Category of Sloping Ground is not to be used to drive portrayal of SURFACES. Only focus on their conspicuity (either visual or radar).



> * Symbolise all **SlopingGround** features of type Surface as per S-52 SLOGRD (Plain & Symbolised boundaries) but:
>   -  replacing CHGRD with LANDF and CHBLK with CHGRD when features **are not** Visual or Radar conspicuous.
>   AC(LANDF);LS(SOLD,1,CHGRD)
>   -  Using AC(CHGRD);LS(SOLD,1,CHBLK) when features **are** Visual or Radar conspicuous.

**Comment by mikan66** [comment]
Thanks for clarification, see PC #161 which is now closed.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
