### ISSUE TITLE
Enable the symbolisation of Reeds - S-101PT9_2022_08.10 & NCWG8_2022_06.10A

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#109]
At NCWG8 and S101PT9 meetings it was agreed to enable the symbolisation of reeds (**categoryOfVegetation**=11), both as an area pattern and a Point feature.

Accordingly it is proposed to:

1. Map **Vegetation**, **categoryOfVegetation**=11 features of type Surface, to the same area pattern currently used for **LandRegion**, **categoryOfLandRegion**=2 (marsh) & 12 (swamp). This is MARSHES1P.

2. Create a new symbol for **Vegetation**, **categoryOfVegetation**=11 features of type Point. This is to be based on MARSHES1P (same size and colours) **but** with the pivot point relocated as shown below.

![image](https://user-images.githubusercontent.com/70189016/203888055-fb40464b-1680-44d0-b8e0-b8261f8dc568.png)

3. Update **Vegetation** rule to map Point features to the symbol created above.

**Comment by alvarosanuy** [comment]
@MikusRL - Can you please develop (or seek help from @HolgerBothien to develop) the symbol requested in bullet point 2 above?

@DavidGrant-NIWC  - Can you please proceed as requested in bullet point 1 above (and  number 3 once the new symbol becomes available)?

**Comment by MikusRL** [comment]
Created symbol.
Updated_20221129 - see comments further.

Note. The line cap for the daySvgStyle.css file is Butt.

![image](https://user-images.githubusercontent.com/72803214/204118404-f8914567-6cbd-400c-832e-35110d9187d9.png)

**Comment by MikusRL** [comment]
@DavidGrant-NIWC @mikan66 Here is the same - I have to update the .svg file and return back the .css file. Will do that now.

**Comment by MikusRL** [comment]
Updated Symbol drawing and files.
[MARSHE01.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10114429/MARSHE01.zip)
Note: daySvgStyle.css is returned to original values - "round". The .svg file remained as initially created.

![image](https://user-images.githubusercontent.com/72803214/204570632-48181ecd-c11e-4566-86be-a1f4b1c8dfd9.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. Symbol MARSHE01 was approved.

2. **NIWC** - Please update rules as per the following instructions:

- Map **Vegetation**, **categoryOfVegetation**=11 features of type Surface, to the same area pattern currently used for **LandRegion**, **categoryOfLandRegion**=2 (marsh) & 12 (swamp). This is AP(MARSHES1).

- Map **Vegetation**, **categoryOfVegetation**=11 features of type Point to the new symbol MARSHE01.

**Comment by alvarosanuy** [comment]
**Feedback from IHO Registry's DCB  - 24/1/23**

The proposed new symbol MARSHE01 is almost identical to the existing symbol MARSHES1P except for the position of their pivot point.  The existing symbol has the pivot point 1.5mm (approx.) below the base of the symbol while the new proposed symbol has it at (0,0).

The difference on an ENC display would be almost unnoticeable for a feature that, by definition, is approximate.
Accordingly, I propose:

1. Withdraw the proposal for a new symbol MARSHE01
2. Map Vegetation, **categoryOfVegetation**=11 features of type Point to the existing symbol MARSHES1P

**Comment by MikkoHovi-FI** [comment]
That would then draw the symbol out of position. Even if only that 1.5mm. That would not comply with the rule that profile symbols have their position in the middle of the baseline.

Not sure if that is desirable. 

Another option would be to change the pivot point location MARSHES1P, but that may cause issues with the area pattern for which that symbol is designed for.

**Comment by MikusRL** [comment]
I also was thinking similarly like Mikko, and would propose if we could rename our newly developed symbol as per the already existing one in the GI Registry, and use it as a test case how does the updating of a GI Registry symbol to a version 2 works. 
I think that we can update it and the test bead will show if it creates any issues to the existing approximate border-less marsh pattern. 

I would like to go with the new symbol because it was reviewed and agreed by the working group, and it is built with the new S-100 tools and is defined with the 0;0 pivot point - compliant with S-100 v.5. 
![image](https://user-images.githubusercontent.com/72803214/214535596-dfa8e894-67fe-4a03-ba88-27d68660d273.png)
There looks like there are also some other differences to how we define the symbol now vs the initially registered symbol regarding the bounding or symbol boxes, etc., so I think it would be a good idea to "update" the existing symbol by registering a version 2 of this symbol in GI Registry. 

What do others think?

**Comment by alvarosanuy** [comment]
Based on the limited responses I would proceed and try to register the new symbol as an updated version to the existing S-52 symbol MARSHESP1.

@DavidGrant-NIWC - This shouldn't require any changes to the existing Rules, right? They will continue referring to symbol MARSHESP1 and the S-101 portrayal catalogue should be created using the latest published versions of the symbols contained in the GI Registry.

Please note that S-52 PL will not be updated to deliver v2 of symbol MARSHESP1 and therefore there will be differences between the 2 standards. Let's see if the registry can manage this discrepancy and keep record that MARSHESP1_v1 is used in S-52 and MARSHESP1_v2 is used in S-101 ..........

**Comment by DavidGrant-NIWC** [comment]
> @DavidGrant-NIWC - This shouldn't require any changes to the existing Rules, right? They will continue referring to symbol MARSHESP1 and the S-101 portrayal catalogue should be created using the latest published versions of the symbols contained in the GI Registry.

Agree, however note that the entire portrayal catalogue should be reviewed at some point to ensure that the contents match the contents of the GI Registry. The existing contents of the PC are not pulled from the registry, they have just been carried forward from the developmental version created by Hugh many years ago.

At least until recently, the registry contents lagged the contents of the PC. For instance, I can see that the following context parameters are still not present in the registry:
* Plain boundaries
* Simplified points
* Full sectors
* Radar overlay
* Ignore SCAMIN (name could be improved to be more meaningful for the user...)
* National language

**Comment by alvarosanuy** [comment]
> At least until recently, the registry contents lagged the contents of the PC. For instance, I can see that the following context parameters are still not present in the registry:
> 
> * Plain boundaries
> * Simplified points
> * Full sectors
> * Radar overlay
> * Ignore SCAMIN (name could be improved to be more meaningful for the user...)
> * National language

@DavidGrant-NIWC @JeffWootton - It looks I can go and register these new context parameters in the GI Registry myself. I just need your help to populate the right values, for each of them, using the template below:
![image](https://user-images.githubusercontent.com/70189016/215889219-4632893e-7da8-4aa9-a911-a13d9ef3642c.png)

**While exploring existing registered context parameters, I noted their 'name' are all in capitals and using underscores instead of spaces. Not sure if this is a requirement or not but something to keep in mind.**

**Comment by TDYCARHugh** [comment]
> @DavidGrant-NIWC  however note that the entire portrayal catalogue should be reviewed at some point to ensure that the contents match the contents of the GI Registry. The existing contents of the PC are not pulled from the registry, they have just been carried forward from the developmental version created by Hugh many years ago.

I agree that a review would be prudent however the initial load of symbols into the registry was done using the symbols I created for the early draft PC so they should be the same.  A tool such as Winmerge can be used to compare two folders of files to find which ones are different. Is there a way to download a selected or filtered set of symbols from the registry?

**Comment by mikan66** [comment]
@alvarosanuy please restate the final decision for this issue and if there is any new symbol file to utilize.

**Comment by alvarosanuy** [comment]
**Final Decision for implementation in PC 1.1.0:**

No change to mapping rules. They need to continue referencing to symbol MARSHESP1.

The key thing to remember here is that the new version (MARSHE01) developed by Mikus has ben submitted to the GI Registry as a new version for MARSHESP1. Therefore, unless your are building the PC directly from the GI Registry, NIWC will have to update their 'off-line' version temporarily mapping **Vegetation**, **categoryOfVegetation**=11 features of type Point to MARSHE01 (which is effectively v2 of MARSHESP1).
This will provide the look and feel we want but would be technically incorrect as MARSHE01 is not an approved symbol per se.

**Comment by mikan66** [comment]
Simulated with palm trees, but I will still check this in as it's a simple change in the Vegetation.lua rule file (Simplified symbols or not).
![image](https://user-images.githubusercontent.com/4913543/219030710-0baf0a5f-db27-4ab4-b065-6394d2e92ae1.png)

**Comment by alvarosanuy** [comment]
@mikan66 - Are we good to close this issue?

**Comment by mikan66** [comment]
Yes, I believe so.  It's closed on the PC side.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0

**Comment by TomRichardson6** [comment]
All 

TDS 05 has been edited to include a point Vegetation, categoryOfVegetation=11 to support testing of this issue. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0005/5

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/e8745e29-cb8e-4a39-8b17-2ed8d213268a)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/2ae24e14-5354-4b0c-89ff-1e2174ef51e0)

**Comment by mikan66** [comment]
> ![image](https://user-images.githubusercontent.com/62906211/253360526-e8745e29-cb8e-4a39-8b17-2ed8d213268a.png) ![image](https://user-images.githubusercontent.com/62906211/253360658-2ae24e14-5354-4b0c-89ff-1e2174ef51e0.png)

Clearing TEST label in PC issues #131
