### ISSUE TITLE
NIWC Testbed Update - Slide # 25 - Guidance for the implementation of 'temporary' overlays

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#11]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94633517-de5e1580-0310-11eb-9b57-8bd65bfab0d8.png)

**Comment by rmalyankar** [comment]
Leave to OEM?

**Comment by alvarosanuy** [comment]
This statement has been transferred to S-98 Annex C - C-14.6.7
Mariners' feedback was the driver for implementing an independent mariners selector (viewing group) in PL 4.0. Mariners should be able to turn the 'i' symbol on/off at will.
Same implementation is required in S100 ECDIS but see below for additional info.
My personal view is that the implementation must be a requirement and should not be left up to OEMs. It has to be possible to separate 'documents' (TXTDSC, PICREP) from additional textual' (INFORM) info. I agree that viewing group 31031 should be used for 'Highlight Document'.

**C-10.9** Note 4 states:
![image](https://user-images.githubusercontent.com/70189016/95695921-cc6f6180-0c84-11eb-93b3-e3066bdf3549.png)

**Comment by DavidGrant-NIWC** [comment]
The question is whether the use of an independent viewing group satisfies the requirement for temporary display. If it does, the wording should be updated when moving the requirement to S-98, or the requirement should be removed from S-98.

**Comment by rmalyankar** [comment]
Should there be guidance added to the DCEG(s) as to what kinds of information should be encoded in attribute information and what kinds of information should be encoded in text support files? Can there be a meaningful difference - something other than "producer's discretion" or length (there is a 300 character limit for information (DCEG 2.4.6)). Otherwise user expectations for what is encoded where may become a problem, if users get in the habit of thinking certain types of information are encoded only in attribute _information_ or only in support files. That was the reason for the draft not distinguishing between "highlight document" and "highlight info".

**Comment by DavidGrant-NIWC** [comment]
> Should there be guidance added to the DCEG(s) as to what kinds of information should be encoded in attribute information and what kinds of information should be encoded in text support files? Can there be a meaningful difference - something other than "producer's discretion" or length (there is a 300 character limit for information (DCEG 2.4.6)). Otherwise user expectations for what is encoded where may become a problem, if users get in the habit of thinking certain types of information are encoded only in attribute information or only in support files. That was the reason for the draft not distinguishing between "highlight document" and "highlight info".

This is a separate issue and is probably out of scope for this group IMO. Issues regarding S-98 should be addressed during its document review.

That being said, the portrayal catalogue rules already use the information encoded in **NauticalInformation** to assign a viewing group - manufacturers don't need to do anything special to support this.

**Comment by alvarosanuy** [comment]
I believe the clause in S-52 aims at 2 things:

1. Advice encoders not to overuse the attributes TXTDSC and INFORM (**Achieved** - Guidance exists in DCEG section 2.4.6)
2. Recommend the implementation of an ECDIS independent mariner's selector to give the user the power to turn the symbology on/off and therefore to unclutter the display window. (**Achieved** - Dedicated Viewing Group implemented in S-52 PL 4.0)

I think no further action is required on this topic.

**Comment by DavidGrant-NIWC** [comment]
> I believe the clause in S-52 aims at 2 things:
> 
> 1. Advice encoders not to overuse the attributes TXTDSC and INFORM (**Achieved** - Guidance exists in DCEG section 2.4.6)
> 2. Recommend the implementation of an ECDIS independent mariner's selector to give the user the power to turn the symbology on/off and therefore to unclutter the display window. (**Achieved** - Dedicated Viewing Group implemented in S-52 PL 4.0)
> 
> I think no further action is required on this topic.

![image](https://user-images.githubusercontent.com/62906211/104241188-46052000-542b-11eb-88dc-a78a446d6e6c.png)

We agree no action is required based on your summary.

**Comment by alvarosanuy** [comment]
Resolved - Close issue as approved by S101PT6
