### ISSUE TITLE
New symbology for Waterfall features of type Point - NCWG8_2022_06.10A

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#110]
At NCWG8 and S101PT9 meetings it was agreed that, in certain circumstances, waterfalls can be a valuable aid to navigation and therefore it was decided to enable the symbolisation of **Waterfall** features of type Point.

Note that, in S-52:

- Point features **are not** symbolised
- Curve features **are** symbolised and conspicuous WATFAL curves are depicted differently than non-conspicuous ones.

Based on this, and to provide consistency, it seems logical to either:

- Create 2 versions of a Point symbol - One for conspicuous features and one for non-conspicuous ones **OR**
- Create one Point symbol only (for conspicuous features) and remove the existing mapping that provides symbology to non-conspicuous **Waterfall** features of type Curve.

Below is an example to trigger your creative side .... For this symbol, I would recommend using colours such as LANDF (for the waterfall boundaries), AZUBL (for the downstream and ripple lines at the bottom of the waterfall) and CHWHT (as the backdrop colour for the area of the waterfall - in between the LANDF and including the area covered by the ripples). If we want to have a 'conspicuous' version we could replace LANDF with CHBLK .....

![image](https://user-images.githubusercontent.com/70189016/204439328-db42b3d2-b78b-40b0-a26c-1243df59c089.png)

**Comment by MikusRL** [comment]
Some versions, need some more input...

![image](https://user-images.githubusercontent.com/72803214/211656147-979f502e-8296-4ee0-9eba-af9f6bc45ecf.png)

![image](https://user-images.githubusercontent.com/72803214/211660238-40bc70b6-7d42-4e43-a64f-c42df17ef101.png)

![image](https://user-images.githubusercontent.com/72803214/211662305-adc3da2d-e84d-492f-8d79-274e5dc77f6e.png)

**Comment by MikusRL** [comment]
Some more ideas...

![image](https://user-images.githubusercontent.com/72803214/211664177-f6817d7e-ab46-4faf-a2e8-dd3f918b6a7f.png)

**Comment by MikusRL** [comment]
The broken lines could work, or the land as patches where in between the non drawn is the waterfall...

![image](https://user-images.githubusercontent.com/72803214/211667472-cec8cc06-e4ca-42b7-a3c4-dbbf3d92b518.png)

![image](https://user-images.githubusercontent.com/72803214/211667505-2db5d219-344e-40c8-ad73-723f86cabea4.png)

![image](https://user-images.githubusercontent.com/72803214/211667547-2df0c7ba-afb4-4fc3-9f80-3aaaa20909c5.png)

**Comment by MikusRL** [comment]
And I could not find AZUBL color in the colorProfile file, or do I miss that color in mine?

**Comment by alvarosanuy** [comment]
@MikusRL 
From IHO GI Registry 'Colout Tokens'
![image](https://user-images.githubusercontent.com/70189016/211670030-bf9651f1-8c67-42c6-a80e-7cafa83cbce0.png)

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy That is an IENC color token, it doesn't exist in the S-101 PC. We could add it if desired, but it looks like the Dusk and Night color are almost the same value, so I wonder if it would be too bright at night.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. The subWG decided to refer proposals to update existing symbology or develop new one to the NCWG. This is to provide an opportunity to harmonise presentation among different charting products and ensure concepts and definitions between S-4 and DCEG stay aligned.

2. **Alvaro** to submit this issue for discussion at the next NCWG meeting in November 2023. Issue will remain open until feedback is received by the NCWG.

**Comment by TomRichardson6** [comment]
All

Re Test Datasets TDS 5 contains a Point Waterfall, so Test Data exists pending NCWG discussions. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0005/4

**Comment by TomRichardson6** [comment]
@alvarosanuy I think this issue can have Test Data Needed removed. As above test data exists.

**Comment by alvarosanuy** [comment]
> @alvarosanuy I think this issue can have Test Data Needed removed. As above test data exists.

Done. Thanks.

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by NickRodwell** [comment]
Waterfall Symbol: 

A summary pending the formal minutes from the outcome of our discussion at NCWG. 

We have done some drafting of the proposed symbol for waterfalls to share with the S-101 portrayal sub-WG. 

NCWG is not stating this is the finalised solution, but requesting the symbol is developed along these lines. 

![Draft Waterfall Symbol](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/153098482/935ad779-7fc1-4de7-a906-af8d811ad18c)

Nick (NCWG VC)

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.

Australia presented what was discussed at NCWG 8, waterfalls were agreed to be a valuable aid to 
navigation, however, point symbols are not visualized and it was agreed they should be. 
If a point is required, then a symbol is required.
Canada asked if this should be in S-126, the physical environment, rather than S101?
USA said in ENCs, US uses a landmark and includes watermark.
SE and DK, if there is a symbol then it should be portrayed. 
Should only the conspicuous features be portrayed and or should we have 2 symbols if the feature is 
conspic and one is not. 
The USA asked can black and brown be used to differentiate between conspic and non-conspic respectively, 
as shown in S-52? This would prevent the requirement for 2 new symbols. 
Colour options include:
Black = CHBLK
Brown = LANDF
Blue = AZUBL
The proposed symbol is large, the top 3 lines would be sufficient. Further simplification would be better. 
Prefer this as an option: 
Q: or is legend waterfall as appropriate? 
A: they prefer not to use legends on ENCs as it can’t be controlled in terms of positioning, it can be 
controlled in S-101 however the text will be wide and take up a lot of room. 
Later in the week UK shared their idea for a waterfall; Norway and Latvia said they liked this.
The Chair said that if everyone is happy with UK example, they can provide to the portrayal sub-group

**_Outcome:_** NCWG recommends a symbol which should be even more simplified, and provides the following 
draft as guide on which further development may be done.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/141601841/75127ca9-56d3-4259-8ce4-3edbcaeac131)

**Comment by TomRichardson6** [comment]
@alvarosanuy @MatthewCraggs @NickRodwell The UK will work to create the required symbol here and associated engineering drawing. Outputs will be posted here when ready. It is expected that a few variants will be posted and comments sought but these will reflect the image from NCWG.

**Comment by alvarosanuy** [comment]
@TomRichardson6 & @RichardCoyles - Are you working on a prototype of this symbol (SVG + ED)?

**Comment by RichardCoyles** [comment]
I'm working on a simplified version of this 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/ad9f4954-f30a-4a6b-bb3e-24f68d4d1907)
if there are other favoured options, another 2 maybe that I could work up, then there would be a choice of 3 for S-101 portrayal and NCWG to consider.
Is there a due date for this?

**Comment by RichardCoyles** [comment]
Hi Alvaro,

please my comments on the GitHub.

regards

Richard



Richard Coyles

Senior Standards Specialist

RLI: ***@***.******@***.***>

MODNET: ***@***.******@***.***>

Tel: +44 (0)1823 484444

DD: +44 (0)1823 483237

gov.uk/ukho<http://www.gov.uk/ukho>

[cid:b780372e-1fca-4555-a15b-2d63788d536b]

Find out more about our market-leading

ADMIRALTY Maritime Data Solutions:



[cid:b4b73265-a544-4537-bd21-66597efc96e8]<https://www.admiralty.co.uk/>[cid:bcd01fe7-8436-40f9-bf72-bda4ba6c2bfd]<https://twitter.com/AdmiraltyOnline>[cid:9d319d1d-3a8e-467d-ad7f-d2d260ca3c8c]<https://www.linkedin.com/company/uk-hydrographic-office/>[cid:aadea939-c9d5-4023-aa04-0c9a47814288]<https://www.youtube.com/user/AdmiraltyTV>[cid:bcbef448-4297-4d63-9466-b08717391f2e]<https://www.facebook.com/ADMIRALTYOnline/>

[cid:88d23d33-4ad9-481f-8dbe-3e2783ffc585]



Please consider the environment before printing this email


________________________________

**Comment by RichardCoyles** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/ae1587bc-a064-4dee-86a5-c3bb3e2327c3)
[WATFAL01](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/14e974f3-c02d-429f-ab5a-e0e6172a203c)



![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/71090ade-0416-47b9-bace-5a384126ef22)
[WATFAL02](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/97c848df-d7de-41f7-af67-da00ca21c186)

TOWERS01 added for size reference.

Comments welcome.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a39c77e8-39a9-4d39-b779-dd162a37d351)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/1758dd9a-8a44-4c5c-9776-21cdd6cc5817)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

- Approve WATFAL02

- [x] **UKHO** to Create 'non conspicuous' version (Brown colour) and upload SVG+ED
- [x] **UKHO** to upload S-101 Dataset containing Waterfall features (Conspicuous & non-conspicuous) in a more realistic real world scenario (i.e. on land, close to the coast, etc)
- [x] **NIWC** to map WATFAL02 to **Waterfall** feature having **visualProminence**=1
- [x] **NIWC** to map Non-Conspicuous symbol (TBC) to **Waterfall** feature having **visualProminence**<>1
- [x] **NIWC** to upload OnShore ECDIS screenshots for PsWG review
- [ ] **PsWG** to provide comments **by COB 19th of April**
- [ ] **Alvaro** to submit new symbols to GI Registry

**Target version for deployment is PC 1.3.0**

**Comment by RichardCoyles** [comment]
[WATFAL01](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/6022c314-5734-4aa8-8307-43fc82093acd)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/ec0bd6a3-e1d7-4799-b733-2efe5ac10f46)




[WATFAL02](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/05390435-56d1-4650-9747-6e648ec8450c)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/20648a88-45b6-4af8-948c-5ba679f971e1)


@DavidGrant-NIWC  I will mail you the TDS 101GB005DEQSA.000 (1.2) that has a Waterfall Line in a natural position. I have added Waterfall point in the same position conspic. and non-conspic.
I will do the ED once we agree these symbols look OK.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/bebdfc56-0bf8-4ccf-93e6-fbfcc1b97139)

**Comment by DavidGrant-NIWC** [comment]
|Name|_visualProminence_|
|:---|:---|
|Big Grant Falls|`1 - Visually Conspicuous`|
|Little Grant Falls|`2 - Not Visually Conspicuous`|
|Prom Grant Falls|`3 - Prominent`|

Text On:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/6a1be688-9c48-4f70-a61e-eec3af876e60)

Text Off:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/ca76e39f-9f01-4e7b-bf55-f01d8a2771bc)

Night:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/0c4cd1e4-2bbc-45c9-9459-69937915e16e)

**Comment by DavidGrant-NIWC** [comment]
Updated symbols:
* Fix stylesheet reference
* Update metadata
  * Update namespace to conform to S-100 5.1 schema
  * Change publisher from "IHB" to "IHO"
  * Update creation date to conform to schema
  * Change source from "S52PresLib4.0" to "S-101 PSWG"
  * Change version from "0.1" to "1.0"
* Update description: Waterfall (conspicuous), Waterfall (non-conspicuous)
* Add depiction of pivotPoint

[WATFAL02](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/8c5f019d-e261-4021-975f-5529e81d8f09)

[WATFAL01](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/69e84f48-34e8-4330-bee7-7b43e4a8de8b)

**Comment by DavidGrant-NIWC** [comment]
Implemented by https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/355

**Comment by alvarosanuy** [comment]
**Implemented in PC 1.3.0**
