### ISSUE TITLE
Update DGPS reference station symbol to cover for all possible system providers - NCWG8-06.13A

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#111]
At NCWG8 and S101PT9 meetings it was agreed to update the symbolisation of **RadioStation** features with attribute category of **radioStation** = 10 (Differential GNSS) to be more inclusive and not service provider specific.

Accordingly it is proposed to:

- Create a new symbol identical to DRFSTA01 but replacing the word DGPS with DGNSS
          * @Mikus **or** @HolgerBothien  - Can you please develop the new symbol?? 
           
- Update the **RadioStation** portrayal rule to point to the new symbol
           * @DavidGrant-NIWC  - can you please take this action?

![image](https://user-images.githubusercontent.com/70189016/204442784-97e1bf6a-4315-4880-8477-8cbed4e057e7.png)

**Comment by HolgerBothien** [comment]
I can do this. :-)

**Comment by TomRichardson6** [comment]
Information on test data for this item;

The S-101 Test Dataset 101AA00DS0021 contains an instance of RadioStation with categoryOfRadioStation =10

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0021/3

Ref 21.4 position in dataset 32-14.9301S, 62-11.2508E

**Comment by HolgerBothien** [comment]
[DGNSS.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10114334/DGNSS.zip)
Here is the new symbol.

**Comment by alvarosanuy** [comment]
> [DGNSS.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10114334/DGNSS.zip) Here is the new symbol.

Thanks Holger, I just noticed a discrepancy in the portrayal of SY(DRFSTA01) between what's shown in both, S-52 PresLib Ed 4.0.3 Part I Addendum and S-4 Ed. 4.9.0 when compared to the IHO GI Registry symbol. The first 2 sources show a black position circle at the center of the magenta circle and the second one not. In fact, this discrepancy is consistent among other similar symbols such a radar station. Beyond the arguments in favor or against each option, the key issue for me is the inconsistency between sources, particularly between S-52 and the GI Registry.

**Jeff** - Do you have some background knowledge on this??

![image](https://user-images.githubusercontent.com/70189016/204702610-4bb0122e-610c-4cb0-84fd-3d5fbeb04701.png)

 **AND in** S-4 Ed. 4.9.0

![image](https://user-images.githubusercontent.com/70189016/204702528-e256c70a-2512-49a9-9738-854d5706b1b9.png)

![image](https://user-images.githubusercontent.com/70189016/204704905-54940780-c557-4610-995c-e6cbdc0c783f.png)

**Comment by HolgerBothien** [comment]
Hi Alvaro,

The black circle in the S-52 Addendum is just the marker of the pivot point.
It is not part of the symbol neither in S-52 nor in the SVG from the IHO registry.
To me there is no inconsistency.
Nevertheless, in INT 1 and B-4 there are such small circles, but these symbols are for paper charts and only a guide to the digital symbols.
Or am I wrong?

Best regards

Holger Bothien
Product Manager

P +49 40 853586940
sevencs.com

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. New symbol DRFSTA02 was approved.

2. **NIWC** - Please update the **RadioStation** portrayal rule to point to DRFSTA02.

**Comment by alvarosanuy** [comment]
**Implemented in PC 1.1.0**
