### ISSUE TITLE
Amend incorrect S-52 color for symbol SOUNDSC2

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#118]
**++ No contrary comments by 10/2/23 means approval to proceed ++**

Refer to:
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/141#issue-1530871541

Symbol SOUNDSC2 should be black in color (SNDG2) to follow the principle used for all symbols linked to 'shallow soundings, less than or equal to safety depth'. These symbols start with the word 'SOUNDS". Note this principle is currently also applied to the symbols used for 'swept soundings' (SOUNDSB1 & SOUNDGB1).

**S-52 related CSP is:** 
 
![image](https://user-images.githubusercontent.com/70189016/215360287-e6837e60-cce0-406e-b4b9-a724896fe5ff.png)

**In S-52 both, SOUNDSC2 and SOUNDGC2 have been created using grey color (SNDG1):**

![image](https://user-images.githubusercontent.com/70189016/215360361-970cb419-d15a-4fec-a24b-1b60fc2b3b55.png)
![image](https://user-images.githubusercontent.com/70189016/215360389-60a4be23-028e-458a-9a02-50fbd2b2b495.png)

**The WG is requested to:**
 **++ No contrary comments by 10/2/23 means approval to proceed ++**

1. Approve the change in color of symbol SOUNDSC2 from SNDG1 (grey) to SNDG2 (black). Note that this decision will create a difference between S-52 and S-101 portrayal. 
2. Approve this change for PC 1.1.0 implementation.

**If approved:**
1. @MikusRL would develop a new version (SOUNDSC3) of the symbol and upload SVG & Engineering Drawing files to this space. 
Note that SOUNDSC2 will have to be retained as it will continue being used in S-52 ECDIS (I do not think the ENCWG will create a new version of the S-52 PL for this issue).
2. Alvaro would submit a new symbol proposal to the IHO registry.
3. NIWC would update https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Rules/SNDFRM04.lua in PC 1.1.0 to use the new symbol (C3).

**Comment by alvarosanuy** [comment]
Only one comment received and it was to endorse the proposal. Consequently:

@MikusRL - please develop a new version (SOUNDSC3) of the symbol and upload SVG & Engineering Drawing files to this space.

**Comment by MikusRL** [comment]
@alvarosanuy , I am on it tomorrow.

**Comment by MikusRL** [comment]
@alvarosanuy 
Created the symbol SOUNDSC3 - based on the SOUNDSC2 by running it through S-100Toolkit's Symbol Builder first + preview screenshot to Word, then adjusting .svg as usual afterwards with Notepad++ text editor, creating drawing with 500% zoom in Chrome browser screenshot (enabling pivot point visibility first in .css) and adding dimensions in iPhotoDraw and in 100% view from there screenshot to table in Word doc. as per usual. Have "played" though this time with the metadata entries. Please let me know if this is not right, but I think this is what I understand we have discussed would be good for symbol development tracking good to have.
[SOUNDSC3.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10759173/SOUNDSC3.zip)

![image](https://user-images.githubusercontent.com/72803214/219447649-0cd20a3d-d631-4d72-b637-e9e9b73102c3.png)

**Comment by alvarosanuy** [comment]
@MikusRL  - Thanks, it looks ok to me. I wil proceed and register it in the GI Registry.

@DavidGrant-NIWC  - Can you please proceed and update https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Rules/SNDFRM04.lua in PC 1.1.0 to use the new symbol (SOUNDSC3).

**Comment by mikan66** [comment]
Two cases of 'C2' suffix logic will be replaces with 'C3' suffix.  Example pic below.
![image](https://user-images.githubusercontent.com/4913543/219708716-0ad3836f-20e4-458f-a06d-1e8768315d65.png)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.10. Symbol SOUNDSC3 has been submitted to the GI Registry.
