### ISSUE TITLE
Register S-101 Portrayal Context Parameters

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#119]
> At least until recently, the registry contents lagged the contents of the PC. For instance, I can see that the following context parameters are still not present in the registry:
> 
> * Plain boundaries
> * Simplified points
> * Full sectors
> * Radar overlay
> * Ignore SCAMIN (name could be improved to be more meaningful for the user...)
> * National language

@DavidGrant-NIWC @JeffWootton - It looks I can go and register these new context parameters in the GI Registry myself. I just need your help to populate the right values, for each of them, using the template below:
![image](https://user-images.githubusercontent.com/70189016/215889219-4632893e-7da8-4aa9-a911-a13d9ef3642c.png)

**While exploring existing registered context parameters, I noted their 'name' are all in capitals and using underscores instead of spaces. Not sure if this is a requirement or not but something to keep in mind.**

_Originally posted by @alvarosanuy in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/109#issuecomment-1411109001_

**Comment by DavidGrant-NIWC** [comment]
> While exploring existing registered context parameters, I noted their 'name' are all in capitals and using underscores instead of spaces. Not sure if this is a requirement or not but something to keep in mind.

This has been an outstanding issue for some time, see #18

The requirement for each S-101 context parameter can (mostly) be traced back to S-52 PL 10.3.4.4 Independent Mariner Selections:
![image](https://user-images.githubusercontent.com/62906211/215901052-64820aa0-083b-45bb-bd4a-609e89ed584b.png)

There are some exceptions, for instance the context parameter requirement for the selected safety depth originates within the IMO performance spec, and for some reason is not duplicated within 10.3.4.4 (also true of safety contour, shallow contour, etc.)

Within the S-52 CSP's, the value of each selector is (typically) accessed via a global variable (such as SAFETY_CONTOUR) as specified in S-52 PL 13.1.5:
![image](https://user-images.githubusercontent.com/62906211/215902219-8aef054e-b7fb-4bf9-b5b6-8f04ee35571f.png)

As you can see, the currently registered "names" are not correct. For some reason, the variable names from 13.1.5 were registered instead of the selector names from 10.3.4.4.
* [ ] @alvarosanuy please remove or retire the existing S-101 context parameter registered values:
![image](https://user-images.githubusercontent.com/62906211/216448468-0f8795e3-2a78-4096-9192-7039e708ad13.png)

To register new context parameters, each must define the following attributes:
|Name|xmlID|Type|Default|Description|
|:---|:---|:---|:---|:---|
|A human readable name for the context parameter (e.g. "Safety Depth")|A unique string used to reference the context parameter within the PC (e.g. "SafetyDepth")|"Double", "Boolean", "String", etc.|A default value for the context parameter (e.g. "30")|Describes the context parameter. Should be meaningful for the mariner.|

In this issue, we should focus on context parameters. The remainder of the independent mariner selections should be addressed via #18.

* [x] @DavidGrant-NIWC will update the PC to use the context parameters/attributes from the table below.
* [x] @alvarosanuy please register the following context parameters, after allowing time for discussion / requested changes.

Default values are from IEC 61174 Table 3. Other attributes are from S-52 10.3.4.4. Any changes from the S-52 requirements are noted.

|Name|xmlID|Type|Default|Description|Notes|
|:---|:---|:---|:---|:---|:---|
|Radar overlay|RadarOverlay|Boolean|false|Should be enabled whenever the RADAR sweep is displayed|Required by S-98 C-17.1. Replaces the S-52 DAI "O" / "S" RADAR functionality.|
|Safety depth|SafetyDepth|Double|30|Selected safety depth|Required by IMO PS 5.9 / PL 13.1.5. Undefined in PL 10.3.4.4|
|Safety contour|SafetyContour|Double|30|Selected safety contour|Required by IMO PS 5.8 / PL 13.1.5. Undefined in PL 10.3.4.4|
|Shallow contour|ShallowContour|Double|2|Selected shallow water contour|Required by PL 13.1.5 (optional)|Undefined in PL 10.3.4.4|
|Deep contour|DeepContour|Double|30|Selected deep water contour|Required by PL 13.1.5 (optional)|Undefined in PL 10.3.4.4|
|Full light lines|FullLightLines|Boolean|false|Show full length light sector lines|S-52 description has been changed.|
|Simplified symbols|SimplifiedSymbols|Boolean|false|Point symbol style|S-52 name ("Paper chart / simplified symbols") has been simplified.|
|Plain boundaries|PlainBoundaries|Boolean|true|Line symbol style|S-52 name ("Plain / Symbolized boundaries") has been simplified.|
|Ignore scale minimum|IgnoreScamin|Boolean|false|Features remain visible regardless of display scale|S-52 name and description have been changed.|
|Shallow water dangers|ShallowWaterDangers|Boolean|true|Show isolated dangers in shallow waters|S-52 description has been changed.|
|Four shades|FourShades|Boolean|false|Show depth areas using four colours|Optional. S-52 description has been changed. Note that name is "Four shades" in 10.3.4.4, but "TWO_SHADES" in 13.1.5.|
|National language|NationalLanguage|String|eng|3-letter language code. Selects preferred language for chart text.|Optional. S-52 description has been changed.|

Other selectors required in S-52 PL 10.3.4.4 do not alter the portrayal output and therefore do not require context parameters. Further discussion of those remaining required selectors should be via #18.

**Comment by DavidGrant-NIWC** [comment]
PC has been updated as noted above, see https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/155

![image](https://user-images.githubusercontent.com/62906211/216708171-b8525fb3-4917-40f6-a173-7dda315807c1.png)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC & @JeffWootton - Is the attribute used to display the name of a context parameter on an ECDIS screen 'Alias' or 'contextParameter Name' ??
I am asking to be sure that I correctly map 'Name' and 'xmlID' fields when registering the new context parameters (as proposed by @DavidGrant-NIWC) above. Are the entries below right or should it be the other way around??
![image](https://user-images.githubusercontent.com/70189016/217664960-571801a9-37a7-45d2-b737-de4dfbeaf367.png)

**Comment by alvarosanuy** [comment]
> * @alvarosanuy please register the following context parameters, after allowing time for discussion / requested changes.

The 12 context parameters are ready (drafted and saved) to be submitted for DCB assessment in the GI Registry. Just need to confirm way forward regarding my question in the previous comment.

**Comment by JeffWootton** [comment]
Hi Alvaro.

My assumption is that it should be the other way around.  This is due 
mainly to the fact that contextParameter Name is mandatory and does not 
need to be in camelCase format; while Alias is optional.

Best Regards,

Jeff.

logo-website

	

*Jeff WOOTTON*
Technical Standards Support Officer
Responsable standards techniques

Tel: +377 93 10 81 00
Email: ***@***.***
*www.iho.int* <https:\\www.iho.int>

follow us <http://www.fb.me/IHOhydro> follow us 
<https://twitter.com/IHOhydro> follow us 
<http://linkedin.com/company/international-hydrographic-organization> 
follow us 
<https://www.youtube.com/channel/UCpMKDQTKKlJSXmQCQzFqZPA/featured>

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy I don't think Alias is used, and xmlID is not exposed by the registry interface. Recommend adding "xmlID=CamelCaseValue" to the "Proposed Change" text.

**Comment by alvarosanuy** [comment]
Submissions to GI Registry completed on 10/2/23.
