### ISSUE TITLE
NIWC Testbed Update - Slide # 26 - S-101 PC and Mariners viewing groups

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#12]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94633639-4b71ab00-0311-11eb-8cf9-1a08a2a118c6.png)

**Comment by DavidGrant-NIWC** [comment]
Given the following requirement, mariners viewing groups and viewing group layers should be removed.

**S-52 PresLib 4.0.2**
![image](https://user-images.githubusercontent.com/62906211/95345722-086f8480-0889-11eb-9254-82b71a857818.png)

**Comment by alvarosanuy** [comment]
Mariners viewing groups/ viewing group layers (including names) are well standardize in S-98. Refer to S-98 Annex C, section C-10.5.5 and C-10.5.6,
For standardization of the ECDIS Human Machine Interface (HMI) and to facilitate generic training of Mariners, ECDIS should implement the viewing group/ viewing group layers listed in Tables 15 to 19 to control the display of charted features.

**Is the question:**      Who should be responsible for the implementation of the tables listed in S-98 Annex C ?? 
The IHO via the S-101 PC or OEMs ? 

If the PC does not include rules for Mariners navigational objects that were previously listed in the S-52 LUTs, then it seems logical that the corresponding viewing groups are not listed either. Navigation related symbols, terms and abbreviations are covered by IMO SN_Circ243-Rev.2. Mariners symbols and viewing groups should be managed and implemented by OEMs.

**Comment by DavidGrant-NIWC** [comment]
> Is the question: Who should be responsible for the implementation of the tables listed in S-98 Annex C ??
The IHO via the S-101 PC or OEMs ?

Yes, that is the question.

S-98 will need to provide guidance for OEMs:
- Application developers are responsible for implementing support for mariners / manufacturers features
  - Using viewing groups as specified in C-10.5.5
  - Using viewing group layers as specified in C-10.5.6
  - Using independent 'Mariners' display modes as specified in C-10.6

**Comment by DavidGrant-NIWC** [comment]
Recommend close:
- Mariners viewing groups / viewing group layers have been removed from the PC
- Recommend advising (Julia / Raphael?) to update S-98 with guidance for OEMs:
> * Application developers are responsible for implementing support for mariners / manufacturers features
>   * Using viewing groups as specified in C-10.5.5
>   * Using viewing group layers as specified in C-10.5.6
>   * Using independent 'Mariners' display modes as specified in C-10.6

**Comment by alvarosanuy** [comment]
Decision made and changes implemented as required.

Alvaro sent Julia (11/8/21) Github issue link to assess the implementation of the proposed changes to S-98.
