### ISSUE TITLE
Portrayal of Runway feature of type Point [attribute categoryOfRunway=1 (Aeroplane Runway)]

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#122]
**No contrary comments by COB Friday 3 March will see this proposal implemented in S-101**

This issue is to seek endorsement of the following portrayal (which will differ to S-52):

**Runway** feature of type Point [attribute **categoryOfRunway**=1 (Aeroplane Runway)] - **Map to AIRARE02.**

Note that, in S-52, this combination does not display and that, in S-101, **Runway** feature of type Point [attribute **categoryOfRunway**=2 (Helicopter Landing Pad)] does map to a new point symbol. More details at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/107

**No contrary comments by COB Friday 3 March will see this proposal implemented in S-101**

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC @mikan66 - Please implement as follows:

**Runway** feature of type Point [attribute **categoryOfRunway**=1 (Aeroplane Runway)] - Map to **AIRARE02**

**Comment by DavidGrant-NIWC** [comment]
Implemented via [PC issue 176]( https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/176)

|Parameter|Value|
|:---|---:|
|Symbol|AIRARE02|
|Display Priority|12|
|Over Radar|O|
|Display Category|Other|
|Viewing Group|32240|

Related: #107

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
