### ISSUE TITLE
S-52 includes unknown objects in viewing group layer dedicated to buoys, beacons, and structures

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#123]
![image](https://user-images.githubusercontent.com/62906211/223826748-adf1952b-f2d5-427e-a3dd-617187fcef96.png)

![image](https://user-images.githubusercontent.com/62906211/223828984-fd765161-d05f-4ee0-a16f-90b1e0b3e54f.png)

The unknown object symbol is assigned to viewing group 21010, which is included as part of viewing group layer 3.1:
![image](https://user-images.githubusercontent.com/62906211/223827001-d4ef77d0-0d04-41b0-8fe7-0faf14cb3cf0.png)

This appears to be an error:
* 21010 is not included in the viewing group layer 3
* Unknown objects should not toggle on/off with buoys, beacons, and structures.

### Recommended Actions
- [x] Notify ENCWG
- [x] Approve removal of 21010 from viewing group layer 3.1, and identify the target PC version (1.1.0 or 1.2.0)

Related: [PC issue 158](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/158)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- Approve removal of 21010 from viewing group layer 3.1.

- [x] **NIWC** implement by PC 1.2.0 and notify of the VG this symbol was allocated to.

**Comment by DavidGrant-NIWC** [comment]
Implemented in 1.1.2 PC.

* Viewing group `21010` was removed from viewing group layer 3.1
* Viewing group `21010` is now independent of any display mode (it is no longer part of the `Standard` display mode)
* The viewing group can only be toggled via it's viewing group selector, or via the `Unknown` IMS.

**Comment by alvarosanuy** [comment]
> * Viewing group `21010` is now independent of any display mode (it is no longer part of the `Standard` display mode)
> * The viewing group can only be toggled via it's viewing group selector, or via the `Unknown` IMS.

@DavidGrant-NIWC - I looked a bit closer to this and I think that, once removed from layer 3.1, VG 21010 will be automatically allocated to layer 10 (Miscellaneous) and continue being part of the Standard Display Mode. I think that's the way to go (see orange highlight for my reasoning) and therefore your statements above would be incorrect (?).
In short, **the only decision by the PsWG would be to remove VG 21010 from layer 3.1**. I believe the VG should continue being part of Standard Display (as it contains real world objects that mariners should be aware of [visualize] and avoid running onto them).

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/8e947546-caa1-43ca-90f7-0ec88842e22c)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/7890a1f4-02c3-4753-bd7a-9be0fa80ae48)

**Comment by DavidGrant-NIWC** [comment]
This issue is OBE; it is subsumed as part of #18.  `21010` will no longer be used for unknown objects - a viewing group in the `90000`'s will be used for the IMS. `21010` will be removed from the S-101 PC altogether.

Further details will be provided in #18.

**Comment by alvarosanuy** [comment]
I have my reservations around treating the 'Unknown feature' symbology as an IMS and not linking it to the 'Standard' Display Mode.

I believe this symbology is not 'additional information' on an already displayed feature; it represents a feature in itself, for which a descriptive symbol couldn't be mapped to.

In short, it may represent a physical object and therefore not having this symbol visible in 'Standard' DM would go against is definition in the IMO's PS:
Standard Display is the display mode intended to be used as a minimum during route planning and route monitoring. It's considered the 'minimum display for safe navigation'.

**Can we leave 'Unknown feature' in VG 21010 but remove it from VGL 3.1 (so it is not unnecessary linked to Navaids)?
This will move the VG to the 'Miscellaneous' VGL within the Standard DM**

I understand this symbology would be triggered when a feature type (included in the S101 FC) is 'missed' in the S101 PC and no rule exists to specify how to display it in ECDIS.
Would it be possible for S100 ECDIS to load an S101 ENC with an 'unofficial' (non conformant) schema? Would this be another 'use case' for the 'Unknown feature' symbol??

**Comment by KlasOstergren-SMA** [comment]
> I understand this symbology would be triggered when a feature type (included in the S101 FC) is 'missed' in the S101 PC and no rule exists to specify how to display it in ECDIS. Would it be possible for S100 ECDIS to load an S101 ENC with an 'unofficial' (non conformant) schema? Would this be another 'use case' for the 'Unknown feature' symbol??

I tend to agree to Alvaros concern.
If the catalogues are not distributed together with the data (see [S-100WG8-6.11](http://iho-portal.bluemap.kr/share/files/381)), this could be a case every time a new FC is published and the data producers start to produce data conforming to the new FC before an updated PC is distributed to the vessel.

**Comment by DavidGrant-NIWC** [comment]
While we share your concerns, it's clearly marked as an IMS in S-52, which means its implementation likely varies within OEM ECDIS systems. We should ensure that the behavior of the S-101 presentation matches that of the S-52 presentation; I don't think we want `?` symbols on one chart and not on the other.

Recommend that someone liaison with the ENCWG to adopt a common implementation, either by removing `Unknown` from the IMS, or by retaining it as an IMS and modifying its viewing group to something in the 90k range.

|S-52 requirement|Matching S-98 Annex C requirement|
|:---|:---|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/235eeefd-cf30-4b87-8ffc-de5b866454c2)|Not present|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/984d3851-b759-46e3-88cd-c741f1923ac6)|Not present|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/728a7007-2a1c-495f-ace9-fe0826b3dc90)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/4230763b-d550-485b-a352-1b776ec999be)Missing `OverRadar` and display priority.|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/d0f552d7-3b4b-453d-b2d9-ed99b57d8084)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/e79d0fe8-bd4f-4b07-bbbd-748534652bc1)|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/17e735a5-beac-4eae-bf8f-1cbf4718d42d)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/64d4160c-09fc-4634-ad4a-d9791bc44ef0)|

**Comment by DavidGrant-NIWC** [comment]
> If the catalogues are not distributed together with the data (see [S-100WG8-6.11](http://iho-portal.bluemap.kr/share/files/381)), this could be a case every time a new FC is published and the data producers start to produce data conforming to the new FC before an updated PC is distributed to the vessel.

A new FC should not be made available until the corresponding PC is also available; they should be provided as a set in an exchange catalog.

Regarding the referenced paper:
> Catalogues containing machine readable code could potentially harm the end user system.
* Mitigated by requiring signatures on the catalogs.
* If the ECDIS system is implemented correctly the Lua/XSLT implementations will be sandboxed and "walled-off" from the rest of the system.
> OEMs should probably be invited to test new/new versions of catalogues before being officially released.
* I assume they will have this opportunity but there is nothing compelling them to participate in the process.
>  Catalogue versioning and a multiplicity of catalogues being valid at the same time gives added 
complexity to catalogue distribution.
* Adding complexity doesn't mean that it is complicated.
> IHO must have functionality to digitally sign PC/FC/IC catalogues for their catalogue provision service.
* S-100 is designed to deliver catalogs via exchange sets, and that is how the ECDIS will expect to receive them.

**Comment by alvarosanuy** [comment]
> We should ensure that the behavior of the S-101 presentation matches that of the S-52 presentation; I don't think we want `?` symbols on one chart and not on the other.

Understand, but ... we already agreed on bending that rule by deciding not to link IMS to Display Categories (#18). In S-57 ECDIS, when a mariner selects a DM there's  ahigh chance they will see all those IMS allocated to that display mode. In S100 ECDIS they wouldn't, they will have to manually turn ON the IMS of interest.
My point is that, for 'Unknow features' **only**, this approach is not desirable. The safest approach would be to stop calling 'Unknown features' an IMS, and removing VG 21010 from VGL 3.1.
This way, if mariners select 'Standard Display', any 'Unknown features' will be visible straight away.
If we do things this way, I believe the impact on S-52 is minimum as the other IMS provide additional info only. From my point of view, there's no need to coordinate implementation with the ENCWG Chair or amend S-52.

**We may want to close this issue and add this proposal in**to GitHub #18 ??
Having said this, so far, I haven't seen a specific S-98 change proposal on IMS submitted to S100WG8 or a new draft version of S-98 out for review so ... not sure how @Kusala9 plans to implement these changes before 2.0.0 ......
