### ISSUE TITLE
Features with undefined portrayal

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#125]
A search of the 1.1.0 PC shows that the following elements portray with the testPCB symbol which indicates that the portrayal is yet to be defined:

|Feature|Spatial Type|Issue|
|:---|:---:|:---|
|FloatingDock|point|
|LandRegion|curve|[PC Issue 235](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/235) (closed)
|Pontoon|point|
|RescueStation|surface|[PC Issue 235](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/235) (closed)
|UpdateInformation|all|#78

**Comment by TDYCARHugh** [comment]
LandRegion curve could be portrayed similar to surface with the featureName shown at the center.

**Comment by alvarosanuy** [comment]
**FloatingDock** and **Pontoon** do not have geometric primitive Point in S-57. What's the use case now? The use of point symbols would significantly exaggerate their footprint. If the product is the largest scale available to navigate in, then I would say the product is not good enough. Larger compilation scale is required. If larger scale product exists then the feature should be generalised out and not kept as a Point.
Having said this, I recognise S-57 always had a Point symbol for **Hulk**.......... not sure how much it has been used though (ask RENCs to do search??)

![image](https://user-images.githubusercontent.com/70189016/236117833-152edc4b-2286-4d10-922b-726f39455421.png)
![image](https://user-images.githubusercontent.com/70189016/236119979-ea0a039a-f3f2-4cee-899d-dc664898443b.png)


- **FloatingDock**  
![image](https://user-images.githubusercontent.com/70189016/236116691-2bfe1365-f476-44df-a28b-758f23f6ca71.png)

- **Pontoon**  
![image](https://user-images.githubusercontent.com/70189016/236116836-3b2f969c-8299-4431-ac04-711ec5b54d6c.png)

**Comment by alvarosanuy** [comment]
> LandRegion curve could be portrayed similar to surface with the featureName shown at the center.

**Agree** - Can the name follow the curvature at the middle point???

**Comment by alvarosanuy** [comment]
**RescueStation** Surface can be portrayed as we did with **CoastGuardStation**. I believe we did not use a boundary, we just positioned the Point symbol (in this case it would be RSCSTA02) in the middle of the polygon.

**Comment by MikusRL** [comment]
> Having said this, I recognize S-57 always had a Point symbol for **Hulk**.......... not sure how much it has been used though (ask RENCs to do search??)

Currently there are 631 objects encoded as HULKES. 66 of them are using Point geometry. Around 3/4 of point objects are encoded intending to portray Pontoons of various kinds (reading INFORM attribute) - either pontoons for gas/fuel stations/barges, or as floating docks for mooring, with numbers, or used for other port facility functions like club houses or museums, or just saying "Pontoon". 
This information most likely is intended to be used for planning purposes as stretches from band 3 to band 5. Most used in band 4 and 5, one encoding in band 2 (no other info) and one in band 6 (museum).

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

1. **NIWC** - Implement **LandRegion** Curve symbolisation similar to Surface with the **featureName** shown at the center.
2. **NIWC** - Implement **RescueStation** as per  **CoastGuardStation** but using RSCSTA02 in the middle of the polygon.
3. **Alvaro** - to create new GitHub issues for **FloatingDock** and **Pontoon** and refer them to the NCWG for discussion.
4. Close this issue once 1. and 2. are implemented.

**Comment by TomRichardson6** [comment]
All

A Land Region of type curve has been added to TDS05 to support testing of this issue. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0005/5

**Comment by DavidGrant-NIWC** [comment]
We need a `featureName` attribute on the new feature to support portrayal.

Just to clarify, we will never see the `LandRegion` curve, we will only see a label (if present).
* A `LandRegion` of type surface has no outline, and only uses a fill when `categoryOfLandRegion` is 2 or 12.
* Should the curve do anything special when `categoryOfLandRegion` is 2 or 12?

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9b0bcb07-3ee8-4fc2-9469-5a7f1926413a)

**Comment by TomRichardson6** [comment]
Test Dataset 0005 Edition 6 has been updated so that a feature name is present on the Curve Land Region. Please confirm and close the issue if appropriate. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0005/6

**Comment by DavidGrant-NIWC** [comment]
This issue shouldn't be closed until all undefined symbols are resolved, or this issue is replaced with individual issues. Even though this is labeled for PC 1.2.0, the following two changes didn't require an updated FC so we implemented support in PC 1.1.2 via [PC Issue 235](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/235#issuecomment-1718205427):

### `LandRegion` with curve geometry:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/66a9d447-a2fa-418c-8f49-15c9aeebab84)

### `RescueStation` with surface geometry:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/83ad3576-25b6-4cfa-8917-f3beeea9e4eb)

with Pick Report:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/354353b1-b515-424a-ac29-cde49f58ac44)

**Comment by alvarosanuy** [comment]
Recommend closing this issue as all components are either, already implemented or managed via other PsWG GitHub issues as follows:

|Feature|Spatial Type|Issue|
|:---|:---:|:---|
|FloatingDock|point|[PC Issue 141](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/141) (Open)
|LandRegion|curve|Implemented in PC 1.1.2
|Pontoon|point|[PC Issue 142](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/142) (Open)
|RescueStation|surface|Implemented in PC 1.1.2
|UpdateInformation|all|[PC Issue 78](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/78) (Closed)
|"|all|[PC Issue 151](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/151) (Open)
|"|all|[PC Issue 152](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/152) (Open)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 17/10/23**

All features reported in this issue are either, already implemented in the PC or being actively managed via other GitHub issues.
