### ISSUE TITLE
Invalid display modes in registry

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#126]
![image](https://user-images.githubusercontent.com/62906211/225020786-f4d35991-67bb-46ca-9d6b-69a97277f4fd.png)

* Duplicate entries should be removed
* `Mariners` should be removed.
  *  However, note that S-52 has conflicting requirements with regard to mariners' objects.
      * S-52 PresLib 4.0.3 Part 1 clause 10.3.4.5 _"... the display of Mariners objects is independent of the ECDIS display category ..."_
![image](https://user-images.githubusercontent.com/62906211/225021450-61c8ef76-fe6c-4285-8810-f98ad864c7e5.png)
      * S-52 PresLib 4.0.3 Part 1 clause 14.2 shows Mariners' objects assigned to ECDIS display categories (italics)    
![image](https://user-images.githubusercontent.com/62906211/225023874-2ea7d1bd-f09d-4d4a-b200-62e1ac711897.png)
  * IEC 61174 doesn't specify Mariners' objects in Annex M
  * S-64 doesn't test Mariners' objects viewing group implementation
![image](https://user-images.githubusercontent.com/62906211/225024525-4bc6e956-ed03-4650-a731-d0be29a60d13.png)

**Comment by alvarosanuy** [comment]
I will proceed and submit requests to remove duplicate entries from the GI Registry **but** will retain 'Mariners' display until this topic is further discussed at the next PsWG meeting.
Accordingly, I have labelled this issue as 'PC 1.2.0 or later'.

Is S-52 clause 14.2 replicated in S-98 ? I have added a label to review content based on future decisions.

**Comment by alvarosanuy** [comment]
**20230316** - I have completed the GI Registry requests to **retire** all duplicate versions of the 4 display modes.

**Still pending for PC 1.2.0 or later:**

- [ ] Discussion on the implementation of the **Mariners** display mode

- practical implementation (independency from other display modes)
- review of guidance in S-98
- new test in S-164

**Comment by alvarosanuy** [comment]
**Mariners' objects extracted from S-52 LUT:**
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/0c9531b1-292c-4c37-b818-887ccb4664cd)

VGs 53nnn are not listed in the the S-52 section 14.2 VGL table (_refer to 1st comment in this issue_). This table includes VGs allocated to 'Mariners Information' objects (i.e own ship, north arrow, etc) which are a different thing. My understanding is that their symbology have been standardised and is currently managed by IEC. Not sure if they should be included in the IHO GI Registry.

My understanding is that the S-101PC won't include any of the symbols known as 'Mariners' Objects' (_refer to the image above_) and that they will need to be managed by the OEMs in ECDIS. I think these symbols are currently defined and registered in the GI Registry.
Based on this, the S-101 PC shouldn't be making any reference to the 'Mariners' display mode.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [ ] 1. **NIWC** to remove 'Mariners Objects' from the S-101 PC (CHINFO08, CHINFO09)
- [ ] 2. **NIWC** to assess if INDHLT01, INDHLT01 and DNGHILIT can be also removed from the S-101 PC due to their potential relationship with A&I
- [x] 3. Leave displayMode 'Mariners' in the IHO GI Registry in case it is required by OEMs or other stakeholders
- [x] 4. **NIWC** to review S-98 and recommend changes as required.
- [x] 5. **Alvaro** to provide an update on this topic to S101PT10 when delivering PsWG report.

**Comment by alvarosanuy** [comment]
> * [ ]  1. **NIWC** to remove 'Mariners Objects' from the S-101 PC (CHINFO08, CHINFO09)
> * [ ]  2. **NIWC** to assess if INDHLT01, INDHLT01 and DNGHILIT can be also removed from the S-101 PC due to their potential relationship with A&I

@DavidGrant-NIWC  - Can you please provide an update on these 2 actions? Action 1 is for PC 1.2.0.

Also, is the action below linked to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/135. If so, please tick off and follow up on the S-98 change proposal as recommended in that issue.


> [ ] 4. **NIWC** to review S-98 and recommend changes as required.

**Comment by DavidGrant-NIWC** [comment]
> @DavidGrant-NIWC - Can you please provide an update on these 2 actions? Action 1 is for PC 1.2.0.

No work has been done on anything labeled as PC 1.2.0 - we will start once we get a draft 1.2.0 FC.

Regarding items 1 & 2, there are a bunch of items in the PC that are unreferenced, including the items you listed but also BLKADJ01, CURSR*, SCALEB*, etc. We've pointed this out previously in testbed reports, but as far as I know there has been no direction on how these objects should be handled:
* Let OEM's implement them themselves.
* Register the items but don't distribute them, let OEM's retrieve from registry.
* Distribute via S-101 PC so that they can be updated without OEM software changes. Direct OEM's to use the objects provided.
* Distribute via some other PC and direct OEM's to use them.

I'd recommend leaving them in for now until someone tells us they are no longer needed.

> Also, is the action below linked to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/135. If so, please tick off and follow up on the S-98 change proposal as recommended in that issue.

Yes, but I can't update your checkboxes.

**Comment by alvarosanuy** [comment]
> Yes, but I can't update your checkboxes.

Done on your behalf.


> We've pointed this out previously in testbed reports, but as far as I know there has been no direction on how these objects should be handled:

My view is that all these symbols must be in the registry but probably under an IEC Domain. It shouldn't be the S101PT (IHO) responsibility to develop and register the portrayal for mariner's objects (some of which are linked to IMO requirements).
My view is that an IEC representative should coordinate this activity and generate a dedicated (standardised) catalogue for Mariner's symbols. The concept may extend beyond Portrayal but I won't to get there.
This approach aligns with the IHO GI Registry foundational view and is up to HSSC to provide high level direction (in my opinion).

I have a slide on this in my PsWG status report to S101PT11. Final direction should come from that.

We may get directed to proceed as per your bullet point 3 above **but** I hope the message gets through and is seen as a short term solution. I would like this topic to be escalated to S100WG/HSSC and have a different approach for the medium and long term.

**Comment by DavidGrant-NIWC** [comment]
Sounds reasonable to me.

**Comment by TomRichardson6** [comment]
Support Alvaro's view that this should sit with IEC and escalation at S-100WG8 is appropriate. Please include in PT11 brief so I can include it at WG8 @alvarosanuy I have previously suggested inclusion in S-421 as an option but noting some of the items here there is probably a need for something separate but maintained by IEC.

**Comment by alvarosanuy** [comment]
**S101PT11 decision was to retain the Mariners Objects in S101 PC 1.2.0** awaiting outcome of discussions with IEC.

On this note, the S101PT Chair sent a letter to IEC's rep to S101PT requesting this topic is escalated to the right IEC forum for discussion and resolution.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

CLOSE this Issue and create  anew one to track the progress of the S101PT proposal to IEC.
