### ISSUE TITLE
QoBD should evaluate depth range

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#127]
QoBD should evaluate DRVAL1 and DRVAL2 when present to exclude portrayal of QoBD features which do not apply to the mariners currently selected safety contour.

- [x] Implemented via [PC Issue 178](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/178)
    * PC 1.1.0 assigns NullInstruction to inactive QoBD features (see item one below)

### Need guidance regarding the following

1. What should happen to the inactive QoBD features (the ones which don't intersect the safety contour value) regarding portrayal and pick report? We need to choose one of the following:
    *  Assigning NullInstruction in portrayal will make them invisible but they will show in the pick report.
    * Not emitting any drawing instruction will make them invisible and exclude them from the pick report.

1. The current guidance in the DCEG has the potential to create a discontinuity at the minimum value of the topmost QoBD feature. Most of the QoBD features must satisfy DRVAL1 < safety contour <= DRVAL2, but the topmost QoBD feature must satisfy DRVAL1 <= safety contour <= DRVAL2. To eliminate this discontinuity, suggest liaison with the DCEG group:
    - [x] Clarify that DRVAL1 is disallowed (must be null) on the topmost QoBD feature for a given date range.
    - [x] Clarify that DRVAL2 is disallowed (must be null) on the bottommost QoBD feature for a given date range.
    - [x] Highlight the inclusive / exclusive properties of DRVAL1 and DRVAL2 so that it’s clear for all encoders:
        * Applicable when the date range is active and [(DRVAL1 is null) or (DRVAL1 < safety contour)] and [(DRVAL2 is null) or (safety contour <= DRVAL2)]

1. Suggest liaison with test group to get supporting test data developed:
    * Adjoining and overlapping QoBD with adjoining and overlapping date ranges on the individual features
    * To include the necessary swept area(s)

1. Should this issue be brought to the attention of the doc and FC group so that the PS can be updated to include guidance for OEM’s regarding display of QoBD in the legend?

**Comment by alvarosanuy** [comment]
![image](https://user-images.githubusercontent.com/70189016/236356346-9dbb04b5-a642-45b1-946c-360a0f8f2d64.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [ ] **NIWC** create issue in DCEG space recommending action to avoid the potential to create a discontinuity at the minimum value of the topmost QoBD feature. 
- [ ] The preference is for pick report, symbolisations and ECDIS legend to be consistent and convey the same information.
 **NIWC** to prepare and submit update proposals to relevant documents (S-98, S101 PS) on the implementation of pick report and ECDIS legend for these scenarios.
- [x] Request creation of new S-164 test to evaluate the above mentioned behavior. **Alvaro** to notify Tom R. of the introduction of a new label in the S101 PsWG GitHub called 'New S-164 test'.

**Comment by TomRichardson6** [comment]
@alvarosanuy understood re the creation of a New S-164 Test label and I will raise this with the S-164 sub group.

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Have you progressed this topic with the DCEGsWG? Refer to actions above

**Comment by DavidGrant-NIWC** [comment]
Sorry, dropped the ball on this. It looks like I asked you via email to ask Jeff to update it, and you asked me to create a DCEG issue &#x1f600;

Added now as https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/91

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - All good, thanks!

@JeffWootton - Would you be able to squeeze this one into your report to S101PT11?

**Comment by DavidGrant-NIWC** [comment]
Believe this can be closed - implemented as [PC 285](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/285)

**Comment by alvarosanuy** [comment]
Implemented in Pc 1.2.0
