### ISSUE TITLE
Assign dedicated viewing group to Virtual AIS Aids to Navigation?

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#128]
See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59#issuecomment-1177866686

The 1.1.0 PC assigns this feature to viewing group 21020, which is NEWOBJ in S-52. We can either keep these in 21020 for the dual fuel transition period, or dedicate a new viewing group to this feature - maybe something in the 27000 range?

![image](https://user-images.githubusercontent.com/62906211/225147153-45e120aa-aec7-4861-acca-b54ebd395a4f.png)
![image](https://user-images.githubusercontent.com/62906211/225147370-11cfe774-90b5-4809-8c4f-4eed8d567c4f.png)

I believe they would remain in viewing group layer 3 / 3.1:
![image](https://user-images.githubusercontent.com/62906211/225147944-6b5a918d-07c7-4037-9a43-e35358f0a837.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- Retain **Virtual AIS Aids to Navigation** in VG 21020 under VGL 3.1
- If the ENCWG decides to use **NEWOBJ** to portray something different than V-AIS in the future this decision will need to be reviewed accordingly.
