### ISSUE TITLE
Unregistered symbol - FLGSTF02 - LNDMRK, CATLMK=5

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#129]
**The purpose of this Issue is to generate SVG file and Engineering Drawing to enable the registration of conspicuous flagstaff in the GI registry in support of a decision made at the ENCWG (see below):** The **Landmark** rule has been updated and is available in PC 1.1.0 using a symbols that is not yet in the GI Register.

**From @DavidGrant-NIWC** 

 
![image](https://user-images.githubusercontent.com/70189016/226223674-de776a3e-eab7-4a0a-ac4a-53257508ff17.png)

FLGSTF02 
![image](https://user-images.githubusercontent.com/70189016/226223788-dc8a412f-b9b3-45ba-be20-104af3e3d7ae.png)
 is the same as FLGSTF01 ![image](https://user-images.githubusercontent.com/70189016/226223859-dd4d6aa9-8b86-4b70-8b0b-a58852ec0b66.png) but uses CHBLK instead of LANDF. The SVG file is available in the PC repo.

 
FLGSTF02.svg was added to portray conspicuous flagstaffs (**symbol is not in the registry**)
[Apply S-52 PresLib 4.0.3 corrections · Issue #24 · iho-ohi/S-101_Portrayal-Catalogue (github.com)](https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.com%2Fiho-ohi%2FS-101_Portrayal-Catalogue%2Fissues%2F24&data=05%7C01%7Cdavid.m.grant22.civ%40us.navy.mil%7Ce5559d42aefa460fab7f08db25b209e2%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C638145220570615035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F5HXSbmILAnI9lIpx8M0T2elDy2k22n9%2BCO4orCxqIE%3D&reserved=0)

It's important to note that the symbol (FLGSTF02) in the S-101 PC Github space uses a feature which is not included in SVG Tiny 1.2 (the basis for the S-100 SVG schema). This means that this (and all other registered symbols) will require updating at a later stage (refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/124)

@MikusRL - Can you please use the existing symbol (FLGSTF02) in the S-101 PC 1.1.0 in the IHO Github space and create the corresponding Engineer Drawing file to assist me with the registration?

**Comment by MikusRL** [comment]
@alvarosanuy I will most likely have time to do it little after COB today. I hope it is ok.

**Comment by MikusRL** [comment]
Please find below zipped word doc Engineering Drawing of FLGSTF02.svg.
[FLGSTF02doc.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11022356/FLGSTF02doc.zip)

![image](https://user-images.githubusercontent.com/72803214/226446831-49f6c5ac-fb24-43cc-970d-46ac3e105550.png)

**Comment by alvarosanuy** [comment]
**Submitted to GI Registry on 28/03/2023**
