### ISSUE TITLE
Review registration of all viewing group layers

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#132]
No S-101 viewing group layers are registered.

![image](https://user-images.githubusercontent.com/62906211/227254128-3900fafc-1f7c-4bcc-a170-fb776354d3b6.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- It was noted that this situation is the result of an incomplete migration performed when the GI Registry was established and populated for the first time using S-52 as source. It was mentioned that his activity was originally coordinated by the S100WG and executed by KHOA.
Accordingly the PsWG recommends this shortfall is communicated to the S100WG Chair for follow up and remediation.

- [x] **Alvaro** to include this issue in the PsWG report to S101PT10 and request S101PT Chair liaison with S100WG Chair and IHO Sec. for follow up and remediation.

**Comment by alvarosanuy** [comment]
**Decision made at S101PT10:**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/c55e850a-954d-4359-824a-6bb0de91047b)

**Need volunteer/s to conduct this task on behalf of the PsWG.**

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

Nobody volunteer to lead this work.

- [x] **Alvaro** - Report lack of progress to S101PT12.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

Activity is still under resourced. No progress made. May require IHO special funds to get it resolved in Q12025. Links to other necessary GI Registry 'house keeping' activities 
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/131

 - [x] **Alvaro** to talk to S101PT Chair and recommend including this issue in his HSSC16 report.

**Comment by alvarosanuy** [comment]
Refer to https://github.com/iho-ohi/S100Infrastructure/issues/20

CLOSE this issue.
