### ISSUE TITLE
Viewing groups for FOGSIG and BUISGL when they are in structure/equipment relationship

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#134]
Should Building (non conspicuous and most likely point feature) (currently only in vg 32220) be considered also in Standard display with Built up Area (currently in vg 22240) if it has structure/equipment relationship with AtoNs like Fog signal (currently in vgs 27000 and 27080). (Looking in S-98 Ed. 1.0.0 May 2022.) I noticed the difference that in S-57 this is true, that although there is a master/slave relationship, non conspicuous Building single is not shown in ECDIS in Standard display, but Fog signal is. Can or should this be improved for S-101 portray?
S-57 Standard:
![image](https://user-images.githubusercontent.com/72803214/228072511-2978d998-be50-4e87-a67c-4e90eb82ba00.png)
S-57 Full:
![image](https://user-images.githubusercontent.com/72803214/228072342-38abd991-2ae0-46de-a91b-45d2b37b272e.png)

**Comment by alvarosanuy** [comment]
S-101 implementation should replicate S-52. Is this not the case? Is there a particular reason for the deviation or just an oversight?

**Comment by MikusRL** [comment]
Yes, at the moment it looks like it is replicating S-52. It looks like it might have been an "oversight" back then creating the S-52. It is now "replicated" in S-98 for S-101 portray too. 
The question is, if we can "upgrade" this for S-101 at this stage - add Building in the Standard viewing groups too (perhaps under condition when it's equipment object is supposed to be portrayed in the Standard?), or "leave as in the S-52" for the consistency sake with not really good S-57 portray.

**Comment by DavidGrant-NIWC** [comment]
@MikusRL , I believe non-conspicuous building can't be included in the `Standard` display due to requirements in MSC.232(82), which classify the `Standard` display as the minimum information content suitable for navigation.

![image](https://user-images.githubusercontent.com/62906211/236833878-0c00e88e-8cef-4d22-af34-c9866c7e7a78.png)

![image](https://user-images.githubusercontent.com/62906211/236833714-5f01a7e3-fb15-4514-b9d6-d1bdd3d81f31.png)

**Comment by MikusRL** [comment]
@DavidGrant-NIWC Thanks for your input. I personally would "translate" or "interpret" in this case the building as the fixed structure of the aid to navigation - e.g. the structure of the AtoN, which makes it under the point No. 3. - , but this is just my understanding I assume. I still think that this is not full AtoN, if only the signal is shown. Similarly if only light is shown without the structure. But thanks. 

@alvarosanuy , would you consider this to be closed without the action based on Davids explanation and that it is the same also in S-57 portrayal? Thanks.

**Comment by DavidGrant-NIWC** [comment]
> Similarly if only light is shown without the structure.

Please see this issue / comment:
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/17#issuecomment-818039080

**Comment by MikusRL** [comment]
OK, thanks @DavidGrant-NIWC . I see your point now. I am happy this is discussed and can be closed as the case mentioned by David.
