### ISSUE TITLE
Submit S-98 change proposal regarding removal of mariners viewing groups from S-101 PC

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#135]
See #12

* Add a note: Application developers are responsible for implementing support for mariners / manufacturers features
  * Using viewing groups as specified in C-9.5.5
  * Using viewing group layers as specified in C-9.5.6

Mariners viewing group for alert highlights will be included in the S-101 PC since they are referenced from `AlertCatalog-S101.xml`. See #136.

![image](https://user-images.githubusercontent.com/62906211/228935139-fc02cbf5-75ab-443d-88ec-9a0dbd9e641b.png)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/126

**Comment by DavidGrant-NIWC** [comment]
Change proposal submitted (S-100WG8-05.2) for upcoming S-100WG:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/39c97976-49d4-40f8-8a86-c6b03ee95df5)

**Comment by alvarosanuy** [comment]
> Change proposal submitted (S-100WG8-05.2) for upcoming S-100WG: ![image](https://user-images.githubusercontent.com/62906211/274358806-39c97976-49d4-40f8-8a86-c6b03ee95df5.png)

@DavidGrant-NIWC - Your proposal above is for Issue #136 . This has been updated accordingly.

In regards to this issue (#135), it seems that you have not requested to add the clarifying notes proposed in you opening comment https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/135#issue-1648148667

**At this point in time we have:**

- Removed Mariners Display Mode from S101PC (left it in the GI Registry).
- Retained Mariners/Manufacturers Objects (at least for PC 1.2.0. Highly likely we'll remove them for PC 2.0.0)
- Retained Mariners VGs (as listed in Table C-14) and not added an accompanying foot note to clarify they are up to OEMs to implement.

Am I missing something here?

**I'd appreciate your views on the last bullet point so I know what to do with this issue** (_i.e close or leave open awaiting something?_)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC -  Can you please go through my comment above and advice what is pending to be done under this Issue #?

Can we close this issue?

**Comment by DavidGrant-NIWC** [comment]
The issue is being tracked here: https://github.com/iho-ohi/98-interoperability/issues/28

I updated that issue to clarify that we would like the foot note added (https://github.com/iho-ohi/98-interoperability/issues/28#issuecomment-1936722259).

I believe this can be closed.
