### ISSUE TITLE
Registered BOYMOR02 symbol

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#137]
@alvarosanuy The point symbol BOYMOR02 is registered in the GI Registry with the name BOYM**A**R02. Should the Registry entry be updated for name and alias fields? 

Also the description field from the .svg and Symbol Explanation row from the engineering drawing ("Mooring buoy area, point symbol") does not match the Definition entry in the GI Registry ("Small Craft Moorings"). Is this intentional or as described in the Portrayal Catalogue? Is there a necessity to update the .svg file's "desc" field and the engineering drawing's Symbol Explanation's row?

**Comment by alvarosanuy** [comment]
Registration updated. Retired symbol BOYMAR02 and registered new symbol BOYMOR02.
