### ISSUE TITLE
Display plane for `DockArea` and `LockBasin`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#138]
### Recommendation
`DockArea` and `LockBasin` should always be drawn in the `UnderRADAR` display plane.

### Reasoning
Issue #121 established new display parameters for these features; the parameters are implemented in PC v1.1.0:

|Parameter|Value|
|:---|:---:|
|Display Category|`Standard`|
|Display Plane|`OverRADAR`|
|Drawing Priority|9|
|Viewing Group| `22010`|

An example (with RADAR on):
![image](https://user-images.githubusercontent.com/62906211/232322873-f3de3a8a-a15a-4886-b69a-f5e5ee6a6d32.png)

In general, I think it's not a good idea to have surface features in the above RADAR display plane:
* They obscure the sweep over the area covered by the feature
* They obscure all overlapping features in the below RADAR display plane
  * including features with a higher drawing priority

**Comment by alvarosanuy** [comment]
Agree. It seems more appropriate to allocate display plane **Under Radar** to these 2 features.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [x] **NIWC** to update **DockArea** & **LockBasin** display planes to **UNDER RADAR** in PC 1.1.n or 1.2.0.

**Comment by mikan66** [comment]
This one is completed.
