### ISSUE TITLE
NIWC Testbed Update - Slide # 32 - Guidance on Date dependent and Safety check

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#14]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94640235-69dfa280-0321-11eb-9292-bb42874bcdfa.png)

**Comment by DavidGrant-NIWC** [comment]
Clearly distinguish between display requirements and route check / look-ahead requirements:

"ECDIS must always display date dependent chart data using the Mariner selected date or date range. When performing a safety check during route planning the ECDIS must use the Mariner selected date(s). The look-ahead function during route monitoring must use the current date."

**Comment by alvarosanuy** [comment]
Agree for S-101 but I'm not sure ENCWG will open S-52 to specify the same requirement. 
In saying this, there may be other S-101 / S-52 harmonization issues that would benefit from corrections/clarifications to S-52. All these issues should be documented and consolidated into one S-52 'limited amendment' proposal to be presented to the ENCWG.

**Comment by alvarosanuy** [comment]
We support the intent and the amended wording but this requirement should be proposed at the S-98 Annex C level as it should be standardized for all S-100 Products using date dependency.
In the short term (DF-ECDIS), and in this case, S-57 and S-101 data should be set up and behave in the same way. At present, date dependent objects are displayed/used based on mariners' input and not on the task in hand (planning or monitoring). This is based on the current IHO position (manifested at the ENCWG level) against making any changes to S-52 (beyond clarifications).

**Comment by alvarosanuy** [comment]
Can NIWC discuss the interpretation of the S-52 wording with OEMs (i.e. Furuno, SevenCs)?

It looks to me this case could be similar to GitHub Issue #15 where OEMs implementation (in general) follows the most pragmatic logic but the pure words in S-52 may be open for a different interpretation and therefore implementation. If the current ECDIS implementation by OEMs such as Furuno and SevenCs, is as per NIWCs proposed new wording then it would be a matter of seeking the S101PT's approval to submit a change proposal to the S100WG (recommending the amending/clarification of the corresponding section in S-98 part C).

**Comment by DavidGrant-NIWC** [comment]
* No response from SevenCs
* Furuno always uses the mariner selected date(s)

**Comment by kusala9** [comment]
just saw this one yesterday. I've been looking at date-dependent as part of looking into realtime in the broader sense. 

I would add to the current text in S-98 Annex C there's a need to expand the date-dependent display out to other S-100 product specifications as well, not just S-101. 

The behaviour as documented in NIWC's report seems sensible to me, mariner selected date for route checking and current date during monitoring. The primary use case (which I believe is in S-52/S-98) is TSS changes but expands to all features with PERSTA (+S-100 equivalents). 

I will grab the current text from S-52/S-98 and paste it here. there's a couple of options for adding in other product specs which I would be grateful for feedback on.....

**Comment by alvarosanuy** [comment]
**November 2021 subWG Meeting** - Agreed current S-52 guidance does not guarantee standardized implementation by OEMs. Also, an indication similar to the one required in S-52 Part I (10.4.1) for Route Monitoring should be expanded to Roue Planning and alert mariners when performing 'route check' using today's date. It was decided to **close this issue at the Portrayal subWG level and pass S-98 Part C amendment proposals to S100WG.** Refer to Portrayal subWg Action # 56.
