### ISSUE TITLE
Registered display plane names should not use camelCase

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#140]
![image](https://user-images.githubusercontent.com/62906211/232324156-5877a49a-6503-4343-b22f-c90b580ce61c.png)

The display plane names as currently registered look more like `xmlId` values. The display plane names should be human readable text.

The values currently used in the 1.1 PC are:
|xmlId|Name|Description|
|:---|:---|:---|
|`UnderRADAR`|Under radar|Content displayed underneath Radar image|
|`OverRADAR`|Over radar|Content displayed on top of Radar image|

**Comment by alvarosanuy** [comment]
Change proposal submitted on 18/4/22
