### ISSUE TITLE
Missing symbolisation instruction for Floating Dock Point feature

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#141]
**FloatingDock** does not have geometric primitive Point in S-57. What's the use case now? The use of point symbols would significantly exaggerate their footprint. If the product is the largest scale available to navigate in, then I would say the product is not good enough. Larger compilation scale is required. If larger scale product exists then the feature should be generalised out and not kept as a Point.
Having said this, I recognise S-57 always had a Point symbol for **Hulk**........... (refer to Mikus/PRIMAR report on the use of **Hulk** in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/125)

![image](https://user-images.githubusercontent.com/70189016/236117833-152edc4b-2286-4d10-922b-726f39455421.png)
![image](https://user-images.githubusercontent.com/70189016/236119979-ea0a039a-f3f2-4cee-899d-dc664898443b.png)

- **FloatingDock**  
![image](https://user-images.githubusercontent.com/70189016/236116691-2bfe1365-f476-44df-a28b-758f23f6ca71.png)

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by TomRichardson6** [comment]
I note that in the 1.2.0 PC this rule results in the smiley face symbol. Propose that while NCWG discussions continue that the point Hulk symbol be adopted here so that a symbol displays. It seems unlikely that NCWG are going to progress this for edition 2.0.0.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.
**_Australia presented S-57 does not allow point features of Floating Dock, S-101 does, is there a user need for 
a point feature in S-101?_** 
Is there a greater safety concern from a POV of a floating dock being larger / more 
resilient structure?
**_Outcome:_** NCWG recommends retaining the S-57 approach not allowing a point feature.

**Comment by alvarosanuy** [comment]
NCWG decided there's No Portrayal impact. I created a new issue in the 'Documentation' GitHub space to discuss NCWG9 recommendation of removing geometric primitive Point from **FloatingDock**.
