### ISSUE TITLE
PC rules - References to 'Converter' and 'FC' versions

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#143]
It has been noted that comments in the header of the rules' files include the following text that could be misleading to 'new users':
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/09a85b2b-ecf1-4b11-8dba-cddf4b710c27)
 Some may read the Feature Catalogue version as the version the content of the rule is compliant with.

@mikan66 provided the following comment to this issue:
_the rule file header comment was from the initial automation conversion from S-52 DAI to S-101 Lua.  The conversion tool inserted the catalogue used for the conversion process.  Most rules will have this same comment if they were converted over.  Users can disregard this header comment on each converted rule.  There is some usefulness for us to know what edition was used for the conversion during development.  I suppose the WG will need to decide if we need to clean up all rules for the production release and standardize the header comment across all files.  We should keep comments for specific issues resolved in each rule file like: "-- PSWG #109, PC #131"._

 **Should we look at removing these entries from PC 2.0.0 onwards or maybe replace them with something else?**

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 19/10/23**

- [ ] **NIWC** to consider removing these 'internal' comments from all S101 PC rules from the official PC 2.0.0 version.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

- [ ] NIWC to remove all references to Converter and FC versions for S-101 PC 1.3.0

**Comment by alvarosanuy** [comment]
I noticed you closed your Issue # 340. I'm closing this issue as well

**Comment by alvarosanuy** [comment]
Implemented in PC 1.3.0

**Comment by DavidGrant-NIWC** [comment]
Implemented in PC 1.3 by https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/340
