### ISSUE TITLE
Register symbols with dots

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#146]
Symbols with dots were portraying incorrectly due to an issue with the original conversion from S-52. See [PC issue 232](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/232) for details.

The updated symbols will need to be registered, but we may wish to hold off since they follow the current S-100 SVG schema. The S-100 SVG schema will likely be updated after the next S-100 WG meeting which will necessitate updating all of the symbols.

## Affected symbols
DANGER01.svg
DANGER02.svg
DANGER03.svg
DRGARE01P.svg
FSHHAV01.svg
OBSTRN01.svg
OBSTRN02.svg
OBSTRN03.svg
SPRING02.svg
UWTROC03.svg
WRECKS05.svg

**Comment by alvarosanuy** [comment]
Below is the link to the new symbol files using the current S-100 (Ed. 5.0.0) SVG schema (Duplicated from https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/232.

https://github.com/iho-ohi/S-101_Portrayal-Catalogue/files/11367642/Symbols_with_Dots.zip

**Comment by alvarosanuy** [comment]
I will register them because, at S101PT10 meeting, it was decided to explore the possibility for KHOA et al. to do a back end bulk SVG update to all the symbols registered in the GI Registry.

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy
The symbols should be taken from the PC rather than from the link Hugh provided. As noted in https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/232#issuecomment-1587984276, the metadata was updated to conform to latest direction (publisher and version attributes).

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- [x] **Alvaro** to register symbols in the GI Registry (download symbols from NIWC PC GitHub space).

**Comment by alvarosanuy** [comment]
Clarifications to existing Symbols submitted to GI Registry on 10NOV2023
