### ISSUE TITLE
Issues with viewing group 28010 (PILBOP)

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#147]
Given changes introduced by #105, consider changing the name of viewing group 28010.

* Registry has duplicate entries and is missing fields:
  * ![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/ee7d4c5a-edbc-48f5-b9fc-00c170313a5e)
* Implemented in S-101 PC as `pilot boarding point (PILBOP)`, taken from S-52.
  * Recommend remove S-52 mnemonic.
  * Recommend update name to be inclusive of `PilotageDistrict` of type surface.

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - I understand that VG 28010 now refers to both, Pilot Boarding Place and Pilotage District.

- [ ] Alvaro to update the GI Registry entry (VG 28010) accordingly.

**Comment by DavidGrant-NIWC** [comment]
Will change to `Pilot boarding place, Pilotage district` in the current (1.1.2) PC.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**
S-98 Annex C already included Pilotage District to the Pilot Boarding Place VG (28010):
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/f8eb127c-5f33-4bd2-8f77-f1c43a76b9a5)

- [x] **Alvaro** to delete duplicate VG entry in the GI Registry.
- [x] **Alvaro** to update GI Registry entry (VG 28010) to reflect it covers `Pilot boarding place, Pilotage district`

**Comment by alvarosanuy** [comment]
Changes to GI Registry submitted on 11NOV2023.
