### ISSUE TITLE
Determine portrayal impact of allowing `topmark`'s with multiple colours

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#149]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9fd74c15-6741-4977-819b-70ddee812b0b)

https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/48

**Comment by alvarosanuy** [comment]
I do not see the need for any changes to the Portrayal Catalogue. S-52 CSP only uses TOPSHP and not colour.
