### ISSUE TITLE
List of S-98 annex C revisions arising from S-101 portrayal discussions

### ISSUE THREAD

**Issue by rmalyankar** [S-101-Portrayal-subWG/Working-Documents#150]
During the discussions of the S-101 portrayal subgroup, the decisions on some topics involved proposing particular revisions to S-98 Annex C.

- There are only 5 issues so far tagged "S-98 change proposal" in this repository, are those all the changes?
- Have the actual changes themselves been finalized into proposals for revisions to S-98 Annex C?

**Comment by alvarosanuy** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/f821efbe-fbd5-4302-a6cd-6ba2308e7d9c)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

CLOSE as issues impacting S-98 and requiring proposals are (should be) actively tracked by @rmalyankar and @kusala9 using the `S-98 Change Proposal` label.
