### ISSUE TITLE
Update Information - Better ways of presenting features that were 'Moved' by an ENC update.

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#151]
Current methodology to represent features that were Moved by an ENC update are not ideal and may not be effective in conveying the right message to mariners.
At the moment, 2 **UpdateInformation** features are generated, one with **updateType**=Delete and the other one with **updateType**=Add. As per S-52, there's no visual connection between the 2 actions and therefore the real world occurrence (i.e. a buoy was moved from A to B) may be misinterpreted by the mariner.

A comment from @TDYCARHugh in DCEGsWG issue https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/41#top have some ideas on how modelling/encoding guidance could be improved to support this task:

_The discussion in sub group VTC meeting today identified that the S-100 portrayal is only working with current features in the dataset and does not have access to the 8211 records used to apply the update. For a deletion it seems there would need to be an Update Information with the geometry of the deletion (since the deleted feature/geom is gone) and to define a move or compound situation it might be useful to be able to make a compound **UpdateInformation** ( associations to other **UpdateInformation** features) or an Information type that is shared by the **UpdateInformation** features where the Information type carries the higher level contextual meaning for a set of **UpdateInformation** features.
If we use a compound feature we would want to extend **updateType** to include 'complex' or make it optional._

- [ ] Can this modelling be leveraged and used to improve portrayal of 'Moved' features? How?

- [ ] What other modelling and portrayal options could we consider?

Another thing that comes to my mind is that the 'ENC Update review' function in ECDIS generally brings up a dedicated window (can't confirm this is a requirement without further reading) where all different changes, a particular ENC update introduced (i.e. ED11 UD6), are listed. This is done using statements like 'BOYSPP moved' with the added benefit that mariners can select a particular entry and the ECDIS display will focus (zoom/center) on the location where the change occurred. 
If we get to bundle together both update types (Delete and Add) then the change description (BOYSPP moved) and the simultaneous highlighting of both **UpdateInformation** features could help resolving this issue ....

**Note that this issue has dependencies with the symbolisation of deleted features as discussed in issue** https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/152

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

As per S-52, the expectation is that the 'Move' action will end up showing the existing S-52 symbology for both, the old (CHRVDELn) and the new (CHRVID0n ) location of the feature. 

It was decided to experiment with the use an **UpdateInformation** Curve feature joining the old and the new locations and then symbolise it using an arrow shape pointing in the direction of the movement (CHCOR colour and thin linework).
This approach will heavily rely on production software being able to automatically encode the **UpdateInformation** **updateType**=4 (move) feature and the corresponding 'Updated Information' Association.
**On the portrayal side**, it's expected that the portrayal rule will not only show the **UpdateInformation** Curve feature as an arrow but, **for Point geometries**, also add the corresponding CHRVDELn symbol at the start of the arrow (From) and the corresponding CHRVID0n symbol at the end of it (To).
For **Curve** and **Surface** features, data producers (assisted by production tools) will have to capture an **UpdateInformation** feature (Delete) using the geometry at origin and another **UpdateInformation** (Add) feature using the geometry at the new location of the feature.
These 3 **UpdateInformation** meta features (Delete/Move/Add) will have to be linked together by using an '**Updated Association**'.

**Problem**: The current 1.2.0 modelling for '**Updated Association**' does not allow linking **UpdatedInformation** Meta features together, only Geographic features ...


![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/5f8a5ceb-4ca1-495d-89bc-059159144f80)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/e165a373-1333-46a3-bdbe-7aa893511b2b)


![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/004c6ac4-d74b-4adc-8b7b-af5074962eaf)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/1d0f3fbd-89d5-4d75-a478-52b0d8fba659)

- [x] **Alvaro** - Create Test datasets (once production tools are updated to handle FC 1.2.0) and supply to NIWC for testing of portrayal rules.
- [x] **NIWC** - Implement the above portrayal requirements for **UpdateInformation**, **updateType**=4 features of type Curve.
- [ ] @kusala9 - If S101PT approves to proceed with **UpdateInformation** as the replacement to the current 'ENC Update' review functionality in ECDIS, the use of the 'Arrow' will have to be detailed in **S-98 Annex C** (C-12.11.2). Also, refer to GitHub #152 for other proposed changes to S-98 on this topic.

**Comment by alvarosanuy** [comment]
Australia submitted an update paper to S101PT12 https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT12/S-101PT12_2024_06.6_EN_Use_and_Modelling_of_the_Update_Information_Feature_V1.pdf
As a result, some minor changes to modelling were approved for inclusion in FC 1.2.0

It was agreed to delay the decision on discontinuing the current (S-57) binary ENC Update Review function until S101PT13. 
In the meantime, CARIS is to demonstrate their progress with automating the creation of **UpdateInformation** features and all members are to continue testing using FC 1.2.0 and PC 1.2.3.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/04/24**

- The PsWG agreed that **UpdateInformation** modelling in FC 1.3.0 is enough as to support **UpdateInformation** 'Move' action.
- It was decided to symbolise **UpdateInformation** **updateType**=4 (move) using an orange **dashed** thin line (0.32mm) when the feature is of geometry type Curve. It was highlighted that 'Move' can be also done using No Geometry (data producers have therefore control of the display (or not) of a 'connector' between 'Delete' and 'Insert' **UpdateInformation** features.
**Please note that** I have changed the line from solid to dashed to better work with the decision made at https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/152 (solid thin line to enhance 'Deleted' features).

- [x] NIWC to update **UpdateInformation** rule to display an orange thin line for when **updateType**=4 and geometric primitive is **Curve** to support Testing - **Target is PC 1.3.0**
- [ ] @JeffWootton - Update DCEG guidance to 'alert' data producers of the differences in ECDIS display when encoding **updateType**=4 using Curves or No Geometry.
- [ ] **Alvaro** to provide ECDIS screenshots to @JeffWootton to support DCEG update.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/91ddd8be-86e3-4756-8685-8491b26e47ab)

**Comment by alvarosanuy** [comment]
**Closing this Issue. Initial implementation has been included in PC 1.3.0.**

Further changes to the portrayal of **UpdateInformation** are to be raised in a new Issue.
