### ISSUE TITLE
Update Information - Portrayal of Deleted features

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#152]
For the portrayal of Deleted features during an ENC Update review process, S-52 and S-98 Annex C require:

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/875d1f3c-5864-421c-8872-59f0ce875071)

This means that **UpdateInformation** should be able to 'retain and expose' the symbology of the deleted feature when Mariners perform the 'ENC Update review' process in ECDIS.
The feature must not be part of the dataset in the sense that it can't be visible during route monitoring or planning or tigger alarms, etc. In practical terms a deleted feature does not longer exist but, somehow its symbology should be retained so it can be used when reviewing ENC updates.

- [ ] Is this currently possible to achieve using the **UpdateInformation** modelling and encoding guidance currently proposed for S101 Ed 1.2.0? Refer to https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/41#top

**Comment by alvarosanuy** [comment]
<img width="465" alt="image" src="https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/9333d265-e02b-4e51-b5f6-4a760d305db7">
<img width="564" alt="image" src="https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/ef8eecce-a54c-4590-b6bb-a67318d98926">

**Comment by DavidGrant-NIWC** [comment]
> This means that **UpdateInformation** should be able to 'retain and expose' the symbology of the deleted feature when Mariners perform the 'ENC Update review' process in ECDIS. The feature must not be part of the dataset in the sense that it can't be visible during route monitoring or planning or trigger alarms, etc. In practical terms a deleted feature does not longer exist but, somehow its symbology should be retained so it can be used when reviewing ENC updates.
> 
> * [ ]  Is this currently possible to achieve using the **UpdateInformation** modelling and encoding guidance currently proposed for S101 Ed 1.2.0? Refer to [Update Information - Detailed Description iho-ohi/S-101-Documentation-and-FC#41 (comment)](https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/41#top)

### Option A
* Let the OEM's handle it by running the deleted feature(s) through portrayal and merging the drawing instructions with the current dataset.
  * Would require some way of determining which features/spatials are deleted.
  * Seems like a kludge.

### Option B
* Continue to provide the feature/spatial in the updated dataset, but mark it as deleted.
  * Perhaps by associating `fixedDateRange` with it through a new information type.
  * Or, add a new feature type (`UpdateDeletion`) which can carry the characteristics of the deleted feature/spatial

### Option C
* Just show the update symbol without the portrayal of the feature which has been deleted.
  * The text associated with the update information feature will describe the deleted feature.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

The group decided to proceed with Option C above:

**Portrayal wise**, only the Update (delete) pattern will be shown
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/3cbe153a-924a-45ca-868a-db6817377fd7)
the symboogy of the feature which has been deleted will not be shown.

**Encoding wise:**

- An **UpdateInformation** feature will be created using the geometry of the Deleted feature (P/C/S).
- As a minimum, the feature type of the deleted object will be described using the attribute **Information/text**. 
- Not sure what to do with the '**Updated Association**' as the only possibility would be to link it to the **UpdateInformation** meta feature (not currently allowed in 1.2.0). - Maybe in this case the Association is irrelevant and not required (?).
If this is agreed, **DCEG** will have to be updated accordingly.

Also, if **UpdateINformation** end up replacing the current 'ENC Update Review' functionality in ECDIS, **S-98 Annex C (C-12.11.2.2)** will have to be updated to remove the requirement to 'overwrite' or 'superimpose' CHRVDEL01 or CHRVDEL02 on the original symbology as this one won't be retained in S-101.

**Proposal - Symbology Update:** 
If the 'original ' feature won't be depicted anymore it may be worth considering the following changes to the 'Delete' symbology:

- **Point**: Enclose the CHRVDEL01 symbol using a thin line (same than the 'moved' arrow).
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/6ff42cda-1bdf-4116-8d26-5795ebe1e944)

- **Curve and Surface**: Add a thin line (same than the 'moved' arrow) underneath the CHRVDEL0n symbols
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/65fa0880-7281-427a-980a-888527ac3ddb)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/ae5ac4b2-fbfc-44e1-8024-4baf32e13c4f)


- [ ] **Alvaro** - Create Test datasets (once production tools are updated to handle FC 1.2.0) and supply to NIWC for testing of portrayal rules.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/04/24**

- **Do not approve** the use of an orange circle to support the current symbology for **UpdateInformation** **Point** features having **updateType**=2 (delete).
- **Approve** the use of an orange thin (0.32mm) solid line for **UpdateInformation** **Curve** & **Surface** features having **updateType**=2 (delete) (as per screenshots in previous comment).
- The line symbology above is to be added to the existing 'Delete' symbology (CHRVDEL1). It does not replace it.


- [x] NIWC to update **UpdateInformation** rule for Curves and Surfaces having **updateType**=4** to support Testing - Target is **PC 1.3.0**.
Upload screenshots when available.

**Comment by DavidGrant-NIWC** [comment]
Portrayal of delete (ignore the adds with no associated feature - there's some issues with this old data):
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/2f40b124-7627-4f94-b119-3da307298cd9)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.3.0
