### ISSUE TITLE
Mapping of 'Preferred Channel' symbols

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#154]
The symbol a Preferred Channel mark uses depends on the navigational system of marks the navaid sits on.
This issue is to confirm portrayal rules can perform the necessary spatial evaluation against the underlying navigational system of marks feature and display the correct preferred channel mark symbol.

Required Test Data seems to be available in Issue #79 . NIWC to confirm.

**Comment by mikan66** [comment]
Current test data situation is:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/90bfa419-650e-46af-add5-fe20e0d90146)

The current portrayal rule examines feature.virtualAISAidToNavigationType == 7 and assigns the symbol accordingly.  There is no spatial evaluation taking place at the moment.  Although #79 is closed, the way forward was not completely clear for PC 1.2.0.  None of that prototype work in #79 has been incorporated as yet.

**Comment by alvarosanuy** [comment]
**Some clarifications:**

1. 'Preferred Channel' options have been removed from **VirtualAISAidToNavigation** in S101 1.2.0. Having said this, my direct question in https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/67#issuecomment-1707528128 has not been formally addressed as yet ....
    Therefore, there's no spatial evaluation required for this feature type.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/32d58dbf-2084-464a-9404-79df4c75e623)

2. We thought that, for features **LateralBuoy** and **LateralBeacon**, having **categoryOfLateralMark** = 3 or 4, the Portrayal Rule would require to check the value of the attribute **marksNavigationalSystemOf** of the underlying **NavigationalSystemOfMarks** Surface in order to pick the correct symbol to display.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/6e7b2f59-8f73-4497-9252-1c9ad1076659)

For the same attribute value there are 2 different possible symbols; one for IALA A and one for IALA B.

### Having said that:

I have looked at the  current mapping of '**Simplified**' BOYLAT and BCNLAT symbols in S-52 and I realized that the CSP is using COLOUR to drive symbology (more restrictive approach).
If everybody agree, we can just follow the same logic and rely on the S-101 **colour** attribute to drive the correct '**Paper Chart**' symbology for preferred channel Buoys and Beacons as well. In this case, no spatial evaluation would be required and we could close this issue (unless I am missing something else).

**Comment by mikan66** [comment]
@alvarosanuy, yesterday I mixed up some of these ideas in this issue with symbol changes in PSWG #117.  I will try to clarify the state of rules specific to your points above without regard to #117.  However, moving forward independently of #117 may not be possible.

EXISTING RULES TODAY (with original symbols from PC 1.1.2):

1.  For VirtualAISAidToNavigation, attribute virtualAISAidToNavigationType values assign the symbol, i.e. 1 thru 12 drives symbol assignment.  I don't think there is any new issue here.

2. It would be good to try and resolve all beacon and buoys changes at one time but this might not be possible.  Having said that, the current rules for Lateral Buoy and Lateral beacon are:

For BuoyLateral SimplifiedSymbols, categoryOfLateralMark = 3 or 4 is used along with feature colour.  
For BuoyLateral paper chart symbols, only bouyShape and CSP TOPMAR02 are used.

For BeaconLateral SimplifiedSymbols, only colour is used for symbols logic
For BeaconLateral paper chart symbols, categoryOfLateralMark = 1 or 2 and beaconShape = 2 are used along with CSP TOPMAR02.  There are some other logic conditions as well.

I don't think spatial evaluation is needed and colour can drive the mappings.  Regarding test data, it's possible that 
\S-101-Test-Datasets\dev\cells\101AA00DS0020 currently has the attributes required to support this.

**Comment by alvarosanuy** [comment]
> 1. For VirtualAISAidToNavigation, attribute virtualAISAidToNavigationType values assign the symbol, i.e. 1 thru 12 drives symbol assignment.  I don't think there is any new issue her

**Agree**

@mikan66  - For Physical Aids to navigation (non Virtual), the mapping rules to handle '**Paper Chart**' symbols for Buoys and Beacons have been provided by Holger in #117.  They now also refer to the attribute **colour** when required.

Mappings when 'Simplified=ON' must remain as per S-52 CSPs. Only mappings of Buoys and Beacons when 'Simplified=OFF' (PaperChart symbols=ON) have to be altered to accommodate color filled symbols.


> I don't think spatial evaluation is needed and colour can drive the mappings. Regarding test data, it's possible that
> \S-101-Test-Datasets\dev\cells\101AA00DS0020 currently has the attributes required to support this.

**Agree** - This issue will be closed.
