### ISSUE TITLE
Update portrayal registry due to merge of `RestrictedArea` features

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#157]
`RestrictedAreaRegulatory` and `RestrictedAreaNavigational` are now merged as `RestrictedArea`.

The portrayal registry entries related to the old features should be updated:
### Viewing Group `26010`
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9efe8e92-a3bd-4fe8-b8fd-7a9e74d01801)
* [ ] Remove duplicate entry
* [ ] Recommended xmlID: "26010"
* [x] Recommended name: "Restricted area"
* [x] Recommended description: "Standard: N - Special areas"

### Viewing Group `26020`
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/3cc5f101-efc9-41df-ba2c-b672a6a0f6fa)
* [x] Retire
* [ ] Ideally update xmlID / name / description to match above. Updating xmlID prior to retiring would help eliminate the possiblity of collision with future use of viewing group `1447`

**Comment by alvarosanuy** [comment]
> * [ ]  Remove duplicate entry
> * [ ]  Recommended xmlID: "26010"

**First task** - Not possible due to problem with GI Registry interface - Raised https://github.com/iho-ohi/S100Infrastructure/issues/10 .
**Second task** - not discussed (I think the request was already raised at S101PT12).

> * [ ]  Ideally update xmlID / name / description to match above. Updating xmlID prior to retiring would help eliminate the possibility of collision with future use of viewing group `1447`

**xmlID** - See my previous comment on this topic.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

Problems with the retirement of a duplicate entry for VG 26010 has been resolved and the request successfully processed.
Changes to xmlID are not possible at this stage.

**Close this Issue.**
