### ISSUE TITLE
New 'Paper Chart' symbols for EWM & Safe Water Buoys

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#158]
Pending actions taken form https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/117:
- [ ] Create a new version of the Safe Water 'Paper Chart' symbol BOYSHP50 (to show slanted color bands)

- [ ] Create a new version of the EWMB 'Paper Chart' symbol BOYSHP60 (to show slanted color bands)

- [ ]  Create new EWMB 'Paper Chart' symbol for 'Pilar' & 'Spar' buoy shapes
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4b10ef6b-90f3-4ec7-9e7b-9d16cbfd5467)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/53570862-08aa-466d-97f2-7cabca64338b)

- [ ] Update Rule mappings to new symbols when available.

**Comment by TomRichardson6** [comment]
@alvarosanuy The UK will work to create the required symbols here and associated engineering drawings. Outputs will be posted here when ready.

**Comment by RichardCoyles** [comment]
[new EWMB.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14757087/new.EWMB.zip)
[new SW.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14757120/new.SW.zip)

@alvarosanuy please find attached new symbiology for review.

**Comment by alvarosanuy** [comment]
> @alvarosanuy please find attached new symbiology for review.

@RichardCoyles - Thanks Richard. Would you be able to submit Engineering Drawings? I need them to finalise registration in the GI Registry. I have attached an example for your reference.
@MikusRL may be able to assist as he had to create some in the past while using KHOA's Symbol Editor (my understanding is that this tool does not generate the ED file automatically as yet ...)

[dKart_Discoloured Water_3.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14765138/dKart_Discoloured.Water_3.docx)

**Comment by RichardCoyles** [comment]
@HolgerBothien I found the drawings you produced for EWM https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/117#issuecomment-1559313859

I will compare these dimensions with the EWM symbols I produced above, also based on BOYPIL01, BOYSPH01 and BOYSPR01. 

Did you produce drawings for Safe Water Buoys also? I feel I may be stepping on your toes here?!

**Comment by RichardCoyles** [comment]
I see that EWM buoys Spherical, Pillar and Spar already exist in the registry with .svg and engineering drawings. 
The spherical buoy name should be amended from BOYSHP60 to BOYSPH60 to agree with the name of the .svg

**Comment by RichardCoyles** [comment]
SW buoys Pillar and Spar already exist in the registry with .svg and engineering drawings.

Buoy, spherical – safe water mark – paper chart does not exist in the registry.
PSB engineering drawing and .svg for this
[BOYSPH50 engineering drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14775217/BOYSPH50.engineering.drawing.docx)
[BOYSPH50](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/5a384fca-389a-4835-a36e-d743f1da3688)

**Comment by alvarosanuy** [comment]
Thanks Richard for following up.
Please refer to the document below (table at the end) with my comments. Apart from new versions for BOYSPH50 and BOYSPH60, we need 2 other new symbols (EWMB Spar & Pillar) as per the images in my first comment in this GitHub issue.

[Alvaro - graphical comments.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14782308/Alvaro.-.graphical.comments.docx)

The key requirement for all these 4 new symbols is to have the line between colours at an angle (015 degrees approx). This is to address Guttorm's concerns as this seems to be the rule for all floating navaids having vertical stripes.

**Comment by RichardCoyles** [comment]
I will make the changes in the .docx above.

**Comment by RichardCoyles** [comment]
symbols with slanting colours:
[BOYSPH50](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/d5475d84-4f70-49ee-8621-c0d1d3c4899d)
[BOYSPH60](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/4e3c348b-4749-4aff-a4b3-4396246b59cd)
[BOYSPR60](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/bfd8f2f3-6bc7-4d24-879d-6cc4b84de5a5)
[BOYPIL60](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/108347351/716c766d-d747-434b-8fc1-2cf92b3bf868)

and associated engineering drawing with comments:
[BOYSPH50 engineering drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14791967/BOYSPH50.engineering.drawing.docx)
[BOYSPH60 engineering drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14791966/BOYSPH60.engineering.drawing.docx)
[BOYSPR60 engineering drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14791968/BOYSPR60.engineering.drawing.docx)
[BOYPIL60 engineering drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14791969/BOYPIL60.engineering.drawing.docx)
[UKHO.-.graphical.comments.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14791970/UKHO.-.graphical.comments.docx)

**Comment by alvarosanuy** [comment]
@RichardCoyles - Thank you very much Richard. I noted a few comments against KHOA's symbol editor performance and some questions for @HolgerBothien. I propose we document known shortfalls in KHOA's tool at the upcoming meeting and use that to create an Issue in the 'Infrastructure' GitHub space to get them resolved in a new version of the symbol editor.

@HolgerBothien - Would you mind addressing Richard's comments included in the uploaded Engineering Drawing documents?

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

- Approve new versions of the symbols BOYSHP50, BOYSHP60
- Approve new symbols BOYSPR60 & BOYPIL60

- [ ] NIWC to update mapping Rules **for 'Paper Chart' symbology** as follows:

- **SafeWaterBuoy** - buoyShape=3 colour=1,3 BOYSHP50 - Current mapping is correct in PC 1.2.3. **Update symbol version only.**
- **SafeWaterBuoy** - buoyShape=3 colour=3,1 BOYSHP50 - Current mapping is correct in PC 1.2.3. **Update symbol version only**.

- **EmergencyWreckMarkingBuouy** - buoyShape=3 BOYSPH60 - Current mapping is correct in PC 1.2.3. **Update symbol version only**.
- **EmergencyWreckMarkingBuouy** - buoyShape=5 BOYSPR60 - **New Mapping** 
- **EmergencyWreckMarkingBuouy** - buoyShape=4 BOYPIL60 - **New Mapping**

- [ ] **Alvaro** to update the GI Registry
- [ ] **NIWC** to upload screenshots if Test Data is available

**Comment by mikan66** [comment]
EWMB mappings look correct but new files need at least iho:S100SVG namespaces to be updated.  I will take care of this and post updates here.

Dataset: GITHUB\S-101-Test-Datasets\S-101_1.2\000\101AA00DS0020.000

BOYSPH50: 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/c7f518dc-ca1d-4ce0-add2-aaff6a7d4249)

BOYSPR60:  This doesn't look good
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/97611e6f-f7f5-471a-b784-ab58d7ba95b3)

BOYPIL60:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/a4586922-a8e7-41a1-965f-e8e686513f00)

BOYSHP60:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/403705cb-2271-4d71-a4d5-4dc045416391)


Corrected metadata in SVG files

[PSWG#158.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15013318/PSWG.158.zip)

**Comment by alvarosanuy** [comment]
Tend to agree with @mikan66 - Below are the original images provided bu Guttorm and the SVG's we plan to register.
@RichardCoyles  - Is there anything you can do to improve the Spar symbol? Maybe make it a bit wider or make the line thinner (although I imagine line thickness matches other symbols in the GI Registry).

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/64f37010-e304-4136-b8c3-0ab57721fc0b) 
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/73ce5d9d-5a31-4aee-b42c-e199a9b4bf71)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4fd144e7-ba0c-44ba-af71-acdbc0726c16)  
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/647f25ed-8c6d-469c-aa9f-aa7d9df85698)

**Comment by mikan66** [comment]
@alvarosanuy, @RichardCoyles   I also notice that the descriptions have changed on these and some don't make sense.  For example:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/8978cf53-ce5f-484d-825e-440e67ae1089)

I can clean these up to match PC 1.2.3 if you like.  Please advise.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.3.0
