### ISSUE TITLE
MSC.530(106) requires user-selectable categories to be created for the navigational hazards alerts

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#159]
Also related to https://github.com/iho-ohi/98-interoperability/issues/33

User-selectable object categories need to be created for the navigational hazards alerts. Each category requires a separate viewing group which will be associated with the corresponding alert highlight. Alerts associated with prohibited areas/areas with special conditions already provide user-selectable categories corresponding to viewing groups 53012-53024.

Note that there are only five unused viewing groups available in the 53010-53029 block currently being used for alert highlights. We may need to also use values from 53001-53009 if more than five user-selectable categories are added.

|Viewing Group|Contents|Notes|
|:---:|:---|:---|
|53000|Mariners' Features|Describes the group - not actually assigned to anything|
|53010|Danger highlight (dnghlt)|Alerts associated with the safety contour|
|53011|Nav hazards highlight|Currently all the alerts associated with nav hazards/nav aids. Requires user-selectable categories to be defined and viewing groups assigned to each|
|53012|Proh Are highlight|Traffic separation zones
|53013|Proh Are highlight|Inshore traffic zones
|53014|Proh Are highlight|Restricted areas
|53015|Proh Are highlight|Areas to be avoided
|53016|Proh Are highlight|Particularly Sensitive Sea Areas
|53017|Proh Are highlight|Caution areas
|53018|Proh Are highlight|Offshore production areas
|53019|Proh Are highlight|User defined areas to be avoided
|53020|Proh Are highlight|Military practice areas
|53021|Proh Are highlight|Seaplane landing areas
|53022|Proh Are highlight|Submarine transit lanes
|53023|Proh Are highlight|Anchorage areas
|53024|Proh Are highlight|Marine farm/aquaculture
|53030|Mariners' information note|marnot catnot 1
|53040|Mariners' cautionary note|marnot catnot 2
|53050|Mariners' feature|marfea

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/4852acff-a908-4949-9889-0dcc67256ff7)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/73ed72b2-eceb-44a7-86d0-831e3e0e98bc)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

Leave issue open until MSC.530(106) implementation details are finalised (currently in discussions with the ENCWG).

Below is the latest A&I mapping table for references to existing Alert Highlight'' VGs

https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14780023/S-101.Alerts.Mapping.Table.v8.20240327.xlsx

**Comment by DavidGrant-NIWC** [comment]
Any update? If not, I will retarget the PC implementation to v1.4.

**Comment by DavidGrant-NIWC** [comment]
Added `StructureOverNavigableWater` to NavHazards - please confirm.

[S-101 Alerts Mapping Table v9 20240503.xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15205513/S-101.Alerts.Mapping.Table.v9.20240503.xlsx)

**Comment by DavidGrant-NIWC** [comment]
@alvarosanuy @jeffwootton

* Added many features to NavHazards when "inTheWater = true"
* Added `BuiltUpArea` to Safety Contour alert when "inTheWater = true"

[S-101 Alerts Mapping Table v10 20240507.xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15241188/S-101.Alerts.Mapping.Table.v10.20240507.xlsx)

**Comment by alvarosanuy** [comment]
**My Proposal:**

_**Note:**_ My understanding is that the ENCWG change proposal is not looking at changes to VGs for managing of A&I. This would be an S101 specific implementation (an enhancement to get us closer to MSC.530 requirements).

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4aaa9c7c-3524-4038-b89d-cc2dabf663d3)

**Functionality:** By switching the 'Alerts Highlights' VG layers OFF, mariners won't get an A&I when their 'safety framework' in Route Planning or Monitoring clashes with the corresponding feature/attribute combinations as listed in https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15241188/S-101.Alerts.Mapping.Table.v10.20240507.xlsx. This means no yellow/red highlight, sound or entry in the Alerts Panel.
This is under the premise that the mariner wants to reduce 'Alerts fatigue' and wants to prioritize his attention to certain elements only (depending on his area of operation, time of the day, etc).
A permanent indication that some A&I have been disabled should be presented on the ECDIS screen and the actions of the mariner (switching Alerts VG layers ON/OFF) appropriately recorded in the ECDIS log (who/what/when).

**Comment by alvarosanuy** [comment]
**Decision at PsWG meeting on 10/7/2024**

IHO interpretation of requirements is that there is only one user-selectable category for NavHazards, which is supported by the current implementation.

Some changes were done to remove the Alert highlights from VGL and treat them as Independent Mariners' selctors not linked to ECDIS Display Modes, etc @DavidGrant-NIWC -**Need confirmation of any PC changes done during the meeting**

Refer to https://github.com/iho-ohi/S-164-Sub-Group/issues/88 regarding the impact the deselection of Alerts highlights would have on the entries reported in an ECDIS Alerts panel.

**Comment by DavidGrant-NIWC** [comment]
Implemented by [PC 414](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/414)

NOTE:
The toggles for the graphical highlights are not implemented as Independent Mariner Selectors. All of the current IMS are implemented as viewing group layers. The layers aren't tied to a display mode. Each layer toggles one or more viewing groups. I expect that the ECDIS will expose the IMS selectors to the user. For instance, the IMS for `Accuracy` toggles viewing groups 90010 (accuracy) and 90011 (the low accuracy symbol).

Since Hannu indicated the alert highlights should not be exposed to the user these are now only provided using viewing groups. The viewing groups are not included in any viewing group layer or display mode. I expect that the ECDIS will not directly expose these viewing group selectors to the user but will instead tie their operation to existing GUI components of the ECDIS.

### IMS's
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/8200325e-dc7f-47f3-bf82-ea912064184c)

### Independent viewing groups / alert graphical highlights
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/2f2c4b6f-07dc-44f9-9edb-a5433709ac82)

**Comment by alvarosanuy** [comment]
**Implemented in PC 1.4.0**
