### ISSUE TITLE
NIWC Testbed Update - Slide # 34 - OEM guidance on application of changes to viewing groups

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#16]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94640489-436e3700-0322-11eb-97c1-4d5a883b1ef9.png)

**Comment by DavidGrant-NIWC** [comment]
Current guidance:
> 8.5 Feature and Portrayal Catalogue Management
> For each new version of the S-101 Product Specification a new Feature and Portrayal Catalogue will be released. The end user system must be able to manage datasets and their corresponding catalogues that are created using different versions of the S-101 Product Specification.

- It is not clear if the portrayal catalogue will be updated independently of the feature catalogue
    - e.g. for portrayal changes not tied to FC changes
- How to synchronize viewing group layers / display modes across different catalogue versions when a layer is moved or deleted? Recommendations:
    - Ensure deleted layers are "retired" and never re-used - document in PS
        - May be "un-retired", but not for new purpose
    - Ensure layers will not be moved - document in PS. Rather than moving an existing layer:
        - Retire the existing layer
        - Add a new layer

**Comment by rmalyankar** [comment]
There is some provisional guidance about this in the draft "S-98 Annex C" clause 23.1. 

Principles for the specification/production aspects (synchronization of viewing groups for different versions, etc.) may be better suited for a different document, being relevant to other product specifications as well as S-101.

**Comment by alvarosanuy** [comment]
The introduction of a new symbol for an existing feature/ feature attribute combination already described in the FC is plausible. This may require a new version of the PC but not of the FC ....... It should be possible to release a new FC version without a matching FC one.

The rules for a practical implementation of different catalogue versions in ECDIS seems to require specific attention, therefore it may be beneficial creating a dedicated focus group in order to develop a proposal paper to be presented at the next S100WG (??) meeting.

**Comment by DavidGrant-NIWC** [comment]
Recommend closing. The issue applies to ECDIS across multiple products; will petition to address in S-98.

**Comment by alvarosanuy** [comment]
NIWC to liaise with S100WG for necessary changes to S-98.
