### ISSUE TITLE
Hierarchy of metadata

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#164]
Work item Identified when processing changes introduced by DCEG 1.20 (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153).
As the task to fully implement 'Hierarchy of Metadata' is still unresolved and all other tasks in that Issue have been completed, it was decided to close (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/153) and open this new Issue to track that particular task only.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/52fa7182-3a2c-42bc-9d78-f35d937f976a)

**Refer to:** https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/314 ; https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/153 ; https://github.com/iho-ohi/S-164-Sub-Group/issues/71

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Can I close this one?

**Comment by DavidGrant-NIWC** [comment]
It's tracked for implementation via [PC, issue 314](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/314). I don't believe it's needed for symbolization (see below) - you can close this issue if you don't think there are any related decisions required of this group.

### Low Accuracy Curves and Soundings / Swept Soundings
The latest guidance I got from @jeffwootton indicated that we should not implement inheritance from `QualityOfSurvey` and that those entries would be removed from the table in the DCEG. This means there is no symbolization dependent on evaluating the meta-feature relationships.

### Horizontal/Vertical Uncertainty
The only remaining case where the portrayal might evaluate the hierarchy of metadata is if it needs to evaluate horizontal/vertical uncertainty for alerts.

The issues which were/are preventing implementation:
* Lack of test data (on latest FC)
  * Soundings have to be grouped appropriately. See https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/135
* Need guidance on application of uncertainties
  * Need to agree on an algorithm with ENCWG
    * If we use CATZOC and apply to the route plan / look ahead then OEM's will implement and portrayal doesn't need to be modified.
* Might need a context parameter to turn the evaluation on/off.
* Portrayal can only modify alert geometries for point features (point -> circle)
  * Even if you could modify curves and areas, they would need to be split on the boundaries of `QoBD` features to unambiguously inherit an uncertainty.

**Comment by alvarosanuy** [comment]
> ### Horizontal/Vertical Uncertainty
> The only remaining case where the portrayal might evaluate the hierarchy of metadata is if it needs to evaluate horizontal/vertical uncertainty for alerts.

Can we track all this in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/160 ??

**Comment by alvarosanuy** [comment]
**Decision at PsWG meeting on 10/7/2024**

Refer to decision made in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/160 that there's no need to evaluate horizontal/vertical uncertainty for Alerts.

No further work required in the PC. Close this issue.
