### ISSUE TITLE
Improve EWMB 'Spar' symbol

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#165]
**Colour bands are very hard to distinguish.**

Is there anything we can do to improve the EWMB Spar symbol? Maybe make it a bit wider or make the line thinner (although I imagine line thickness matches other symbols in the GI Registry).

**Image Below are the original images provided by Guttorm** - ![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/64f37010-e304-4136-b8c3-0ab57721fc0b) 
**The SVG we will use in PC 1.3.0** - ![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/73ce5d9d-5a31-4aee-b42c-e199a9b4bf71)

Any volunteer to assist with prototyping a new version of the symbol?

The original symbol was created by @RichardCoyles

**Comment by DavidGrant-NIWC** [comment]
There are inconsistencies in the line weights of the various symbols. Here I (temporarily) changed the line weight of the subject symbol, but the symbol probably needs to be made wider.

The line weight on the other EWMB (and maybe BOYSPH50 and some others could also be reduced:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/83f08d36-3291-40cb-8754-cc952ed2bc10)

**Comment by alvarosanuy** [comment]
It seems the policy is thinner lines for colored navaids. Agree to reduce line thickness to the 2 highlighted symbols. Also agree we need a new Spar EWMB that is a bit wider and use thinner line.

- [x] NIWC to update line thickness for the symbols marked in red below (upload SVG and xml).
- [x] Alvaro to register new versions
- [x] **Assistance required** to develop a new version of Spar EWMB as per the guidance above.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/b4fc6400-0426-4b8c-b831-749e32d6868b)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/fb3c1dc9-5dfe-4e63-8e1b-eace19ea82a5)

[BOYSPH50](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/BOYSPH50.svg?short_path=dcfd2a1)
[BOYPIL60](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/BOYPIL60.svg?short_path=4fa7713)
[BOYSPH60](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/BOYSPH60.svg?short_path=63d8e3e)
[BOYSPR60](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/BOYSPR60.svg?short_path=6038509)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Can you pleaes review the Engineering Drawings below and let me know if there's anything I should change? I am planning to add the line weight (0.32mm) in The 'Commnets' for all of them.
I would probably need your input regarding the new size of the 'Spar' buoy (I believe you made it a bit wider).
[BOYSPR60.engineering.drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15227422/BOYSPR60.engineering.drawing.docx)
[BOYPIL60.engineering.drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15227425/BOYPIL60.engineering.drawing.docx)
[BOYSPH50.engineering.drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15227427/BOYSPH50.engineering.drawing.docx)
[BOYSPH60.engineering.drawing.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15227428/BOYSPH60.engineering.drawing.docx)

Need this to proceed with their registration in the GI Registry.

**Comment by DavidGrant-NIWC** [comment]
|Symbol name|BOYSPR60|
|:---|:---|
|Symbol Details:|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/0fe33e7f-23e8-492e-9c6a-fd7aea86a82b)|
|Width, Height of Bounding Box:|3.52 mm, 5.42mm|
|Width of color fill:|1.5mm|
|Height of color fill:|4.5mm|
|Width of baseline:|3.0mm|
|Radius of circle:|0.52mm|
|Colors:|DEPDW (center circle), OUTLW (outlines), CHYLW (yellow), RESBL (blue)|

|Symbol name|BOYSPH50|
|:---|:---|
|Symbol Details:|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/54e67dff-cdc8-4d13-a90d-56fca55678aa)|
|Width, Height of Bounding Box:|7.65 mm, 6.91mm|
|Radius of small circle:|0.52mm|
|Width of baseline:|5.65mm|
|Baseline to top:|4.39mm|
|Colors:|DEPDW (center circle), OUTLW (outlines), CHRED (red), CHWHT (white)|

|Symbol name|BOYPIL60|
|:---|:---|
|Symbol Details:|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/05718d65-e503-453a-8f99-ad3966987316)
|Width, Height of Bounding Box:|7.97 mm, 6.9mm|
|Radius of small circle:|0.58mm|
|Width of baseline:|5.97mm|
|Width of colored portion:|at bottom: 4.74mm, at top: 1.83mm|
|Baseline to top:|4.3mm|
|Colors:|DEPDW (center circle), OUTLW (outlines), CHYLW (yellow), RESBL (blue)|
|Notes:|There were a tiny blue and a tiny yellow circle hidden under the center circle, I removed them.|

|Symbol name|BOYSPH60|
|:---|:---|
|Symbol Details:|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/073c190c-f757-488d-831c-81da05fe55ff)|
|Width, Height of Bounding Box:|7.65 mm, 6.91mm|
|Radius of small circle:|0.52mm|
|Width of baseline:|5.65mm|
|Baseline to top:|4.39mm|
|Colors:|DEPDW (center circle), OUTLW (outlines), CHYLW (yellow), RESBL (blue)|

**Comment by DavidGrant-NIWC** [comment]
I'm sure we all agree that it's a lot of work to create and maintain these engineering drawings. Recommend petitioning Jeff / the powers that be to see if these can be made optional.

Maybe these are useful if someone can't submit an SVG, in which case they can submit an engineering drawing and someone else can create an SVG. But if an SVG is provided then what is the utility of the engineering drawings?

**Comment by alvarosanuy** [comment]
Can we close as implemented in PC 1.3.0? I have updated the GI Registry.

**Comment by DavidGrant-NIWC** [comment]
> Can we close as implemented in PC 1.3.0? I have updated the GI Registry.

Yes, it's in PC 1.3.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.3.0
