### ISSUE TITLE
Landmark portrayal featureName placement different for simplified/traditional

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#166]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/edc5af50-bed1-44fe-8cb8-5188f63e57ee)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/6ce8af28-bc4d-40dd-9cb8-c88c9b2cb02d)

**Extract from S-52 LUT below:**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/643ef515-cacd-40b8-b079-55632d94d55f)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/e114cbbc-7a4e-4808-9ca6-7b58b5e50ab0)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/3b043361-ee65-4148-b9ba-6d38e7f88734)

It seems to be a typo on the 'Y' offset for **featureName** (not a conscious decision to manage a particular use case). The 'minus' is missing.
**Recommend we amend this in PC 1.4.0**. The impact on S-52 is negligible and I do not see the need to seek endorsement from ENCWG.

When you look at the only other example where **featureName** is used in Portrayal for Landmark (for FUNCTN=33) all text offsets are identical irrespective of the symbolisation type (Simplified or Paper Chart).

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/18075e1c-6445-4f47-9a0f-29bfd66710df)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/38864b49-4ef8-4f87-a596-d5afff1b9e68)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4324e143-5d01-46e3-a61e-a4346bda67ba)

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC  - Due to lack of comments I recommend you proceed and amend TOWERS05 & TOWERS15 to have the same text offset than TOWERS03 & TOWERS01 **(1,-1)**.

**Comment by DavidGrant-NIWC** [comment]
Fixed via [PC 382](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/382), recommend close.
