### ISSUE TITLE
Add UpdateInformation to Alerts & Indications

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#171]
Now that **UpdateInformation** has been retained for S-101 Ed. 2.0.0 (although it won't replace the binary ENC Update review functionality in the short term) the AHO recommend this feature triggers an Indication in ECDIS.

We want mariners to be notified of Updates that intersect their planned route and safety framework once underway. Many times, the **UpdateIndofrmation** feature will come 'linked' to a Geographic feature/s in an ENC Update/NE and this feature/s could trigger an indication by itself (if currently required), but producers may just add a box with some textual information for mariners to read (no Geo features attached to it).

Not sure if the best thing is to add **UpdateInformation** as an 'Area for which special conditions exist' as this feature does not appear listed in Appendix 4 of MSC.530 (106). Another option is to add this requirement to S-98 Annex C for ECDIS implementation. A new S-164 test would be required either way.

**Comment by alvarosanuy** [comment]
**PsWG meeting on 11/7/2024**

**It was noted that:**

Existing IMO ECDIS performance requirements require ECDIS to direct mariners to re-check their Active route when 'new features' (via ENC Update or manually entered by the user) intersect that route **after it was checked** (@HannuPeiponen - Can you please refer us to the relevant document?).
Having said that, ECDIS will only notify the mariner of objects linked to the A&I.
**UpdateInformation** is not one of those Objects linked to A&I therefore it existence wouldn't be reported to mariners through that mechanism.

Only when (and If) the mariner decides to use the 'ENC Update review' functionality in ECDIS (e.g after receiving a new 'ENC package' from their service provider), the **UpdateInformation** feature would be presented to them via the 'binary comparison' methodology currently in place.

The release/encoding of an **UpdateInformation** feature alone (e.g A Surface feature that carries an important message to mariners without being linked to Geo features able to trigger A&I) via ENC update won't trigger any real time notification to mariners, even if that feature sits along their planned route.

**Decision:** No changes to PC at this point in time. Review performance when DF ECDIS prototypes become available (with full ENC update implementation available for testing). Gather mariners' opinions and present change proposals at a later stage as required.

**Comment by HannuPeiponen** [comment]
Dear Alvaro,

I was requested to provide information about the relevant document requiring the check of a route plan.

The draft Ed 5 of IEC 61174 ECDIS intended to be the type-approval testing standard against compliance with IMO MSC-530(106).Rev1 include following requirement in clause 4.10.3 Route monitoring

The ECDIS shall either:

a)   allow the user to select a route for monitoring only if the route has been checked for safety contour, prohibited areas, geographic areas for which special conditions exist and navigational hazards as specified in 4.10.2.1. or;

NOTE 1 The requirement is that the check has been performed, but there are no requirements related to the results from this check that prevent use of the route for monitoring.

b)   have a permanent indication that the monitored route has not been checked for safety contour, prohibited areas, geographic areas for which special conditions exist and navigational hazards as specified in 4.10.2.1.

NOTE 2 A route originating from an ECDIS or from an ECDIS backup arrangement from the same manufacturer can have facilities to inform if these checks are already done.

As the Ed 5 of IEC 61174 ECDIS is still under progress the above could be improved to specify that these rules shall also be met also for the case that the underlaying system database for nautical charts and nautical publications (i.e. ENDS) has been updates.

Best regards
Hannu

**Comment by alvarosanuy** [comment]
> As the Ed 5 of IEC 61174 ECDIS is still under progress the above could be improved to specify that these rules shall also be met also for the case that the underlaying system database for nautical charts and nautical publications (i.e. ENDS) has been updates.

@HannuPeiponen - I will certainly lobby for this to be included in Ed5 of IEC 61174. The mariner may have checked the route 3 weeks ago and the underlying data, at the time of effectively commencing the voyage, could have been altered by changes in the underlying ENDS content (by NE or product Update). If not prompted to recheck the route, mariners may be exposed to unsafe data that was not present at the time the route was previously checked.
**Can you raise a change proposal?**
