### ISSUE TITLE
Remove viewing group layer 6 - Chart scale boundaries and viewing group 21030 - Chart scale boundary, overscale data [AP(OVERSC01)]?

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#174]
**Seeking input from OEMs and implementers to the following question:**

Should the following be removed from S-101 PC?

- Viewing Group Layer 6 - Chart scale boundaries and
- Viewing Group 21030 - Chart scale boundary, overscale data [AP(OVERSC01)] 

They are 'added' by the OEM/ECDIS. The subject viewing group is never output by any rule in the portrayal catalog.

OTOH, leaving them in the PC provides a machine-readable mechanism to control the visibility of this manufacturer added information.

![image](https://github.com/user-attachments/assets/b28fcacf-9eec-4ece-a89e-8d8c2887ada1)

https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/430

**Comment by alvarosanuy** [comment]
@DavidGrant-NIWC - Have you addressed this in PC 2.0.0?

**Comment by DavidGrant-NIWC** [comment]
They are retained in PC 2.0.0

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting on 03/12/24**

Implemented in PC 2.0.0 - CLOSE this issue but confirm with @kusala9 that S-98 Annex C provides clear direction to OEMs regarding implementation.
