### ISSUE TITLE
Viewing group descriptions should be reviewed and updated

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#176]
The viewing group descriptions currently contain S-57 feature / attribute codes. For instance, `13030` - "depth area (DEPARE), dredged area (DRGARE)".

The S-57 terminology should be either removed, replaced with S-101 terminology, or augmented with S-101 terminology.

**Comment by alvarosanuy** [comment]
**PsWG meeting on 03/12/24**

It was agreed that VG Descriptions should not include feature acronyms (S-57 or S-101).

The lack of guidance for the registration of elements within the GI Registry was identified as a shortfall that requires prompt attention by the IHO. The sWG decided to escalate this issue to the S101PT for endorsement and escalation to the S100WG at the earliest opportunity.

A decision and a way forward for the updating (or not) of all registered items will also be required.

Close this issue.
