### ISSUE TITLE
ENCWG 'ENC Display subWG'

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#19]
**Proposal:** Recommend the S101PT Chair to engage with the ENCWG Chair and decide on a way forward. Any proposals for consideration of the S101PT subWG are to be submitted using the newly proposed "portrayal amendments request workflow and form'.

**Priority**: Low

![image](https://user-images.githubusercontent.com/70189016/94645156-79b1b380-032e-11eb-99cc-f74c4e1c52cb.png)

**Comment by alvarosanuy** [comment]
Agreed.

**Comment by Christian-Shom** [comment]
The ENC Display SubWG has been inactive for some while.
The details of the issues identify are available in paper ENCWG3-5.1. A few other issues were found later and are available in the SubWG BaseCamp. Most of the issues implies changes in the S-101 portrayal.
My view (as we now have this S-101 Portrayal SubWG and as S-52 is frozen) is , as suggested by Alvaro, to formalize the findings with the new form.
I also suggest, if the ENCWG agrees, to put an end to the ENC Display SubWG.

**Comment by alvarosanuy** [comment]
Christian, can you please confirm you will liaise with the ENCWG (submit paper/proposal to the next meeting)?
The idea would be:

- recommend the ENCWG to 'migrate' the ENC portrayal requirements (new or amendments to existing) to the S-101PT using the online S-101 Portrayal change request form and
- disband the ENC Display subWG.

Please keep in mind that the proposals have to be as specific as possible (including sketches or draft SVG files) and therefore you will probably need the support of the ENC Display subWG one more time.

**Comment by Christian-Shom** [comment]
Alvaro,
I'll prepare a paper for next ENCWG catch-up meeting (19th February).

**Comment by Christian-Shom** [comment]
[ENCWG3_2018_5.1_EN_Improvement_of_ENCs_display_on_ECDIS_v1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7468705/ENCWG3_2018_5.1_EN_Improvement_of_ENCs_display_on_ECDIS_v1.pdf)

Paper submitted at the ENCWG3 that lists the display issues identified by the ENC Display Sub-Group.

**Comment by Christian-Shom** [comment]
[ENCWGVTC3_2021_08_EN_ENC Display SG_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7473003/ENCWGVTC3_2021_08_EN_ENC.Display.SG_V1.pdf)

Paper submitted at the ENCWG VTC catch-up meeting (17th February 2021).

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144342412-d6f14ceb-6be8-4141-8feb-7c1175b1d3da.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. Leave issue open until new dedicated Github issues are open by Christian Mouden.
**NOTE**: CM migrated 'ENC display' subWG recommendations to Github Issues (94  - 99) on 27/7/22. - Close this issue.
