### ISSUE TITLE
Fairway Portrayal

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#2]
**S-101PT5 Action 17** - Discuss paper S-101PT5-14.

[S-101PT5_14_EN_Fairway Portrayal_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5289976/S-101PT5_14_EN_Fairway.Portrayal_V1.pdf)

**Comment by alvarosanuy** [comment]
S-4 B-432.1 (c) states that:

- **Fairways** which are designated by a regulatory authority are treated as Routeing Measures.
- ........ routeing measures must be represented by symbols, in magenta,....

Therefore, the AHO think there are merits to amend the colour of the existing Fairway feature from CHGRD to TRFCF (traffic control features). As stated in the paper, a faint magenta colour is preferred over a dominant one.

**Comment by Christian-Shom** [comment]
Agree with the proposal to use faint magenta. 
Do we have the refer to the NCWG (in charge of portrayal?).

**Comment by SylviaSpohn-BSH** [comment]
As a NCWG member I ask if grey tint is not possible to use for the fairway area as it was recommended in S-4? The magenta tint 30% is not possible to use as it is used for prohibited areas and separation zones. If magenta is the only technical solution it must be lighter (max. 15%).

**Comment by forodd** [comment]
We have now provided some testdata for this issue. The Norwegian S-57 ENCs NO4L1109 and NO4R1109 have been converted to S-101 using version 1.0.37 of the ESRI converter.

These ENCs contains the Fairway shown in the paper.

Both the converted S-101 data sets and the original S-57 files are attached to this post. 


[Fairway_portrayal_testdata.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5444303/Fairway_portrayal_testdata.zip)

**Comment by forodd** [comment]
And a response to a previous comment, I guess we have only been discussing changing the color of the area outline from grey to magenta, not adding area fill at this stage, as it will be a more substantial change?

**Comment by alvarosanuy** [comment]
Thanks for the test data. The only approved change to Fairways was the colour of its linework, from grey to faint magenta (no area fill).
According to the Action item agreed for Issue#2, NIWC (Dave) should propose 2/3 faint magenta options and prepare some screenshots to support Norway's 'formal' proposal using the new 'S101 Portrayal request form'.

**Comment by DavidGrant-NIWC** [comment]
> We have now provided some testdata for this issue. The Norwegian S-57 ENCs NO4L1109 and NO4R1109 have been converted to S-101 using version 1.0.37 of the ESRI converter.

The S-101 files did not load in the testbed - I was able to load after converting the S-57 ENCs using v1.0.0.20 of the converter, which I believe is the latest version. The 1.0.0.20 converter can be downloaded from: http://registry.iho.int/beta/repository/list.do or from Basecamp.

I should be able to post some screenshots early next week. Here are the magenta colors currently provided in the portrayal catalog:


|Color|Tokens|CIE<br>(x, y, L)|sRGB<br>(R, G, B)|Sample
|:---:|:---:|:---:|:---:|:---:|
|Magenta<br>(dominant)|CHMGD<br>ISDNG<br>TRFCD<br>UINFM|0.3, 0.17, 20|192, 69, 209|![image](https://user-images.githubusercontent.com/62906211/97608505-d1ecdb80-19e8-11eb-8fb0-f1bfe8e501c0.png)|
|Magenta<br>(faint)|CHMGF<br>TRFCF|0.28, 0.24, 48|203, 169, 249|![image](https://user-images.githubusercontent.com/62906211/97608569-e4ffab80-19e8-11eb-9241-bc60e2c2997b.png)|
|Magenta<br>(mariners)|MARMG|0.36, 0.22, 20|198, 77, 166|![image](https://user-images.githubusercontent.com/62906211/97608615-f47ef480-19e8-11eb-99b4-84c1f15a1c7f.png)|

I will post images of the current portrayal (grey) alongside a portrayal using CHMGF. Let me know if there are other colors which should be evaluated.

I'll also use an area where there is already a lot of magenta (101US005VA15M):
![image](https://user-images.githubusercontent.com/62906211/97610969-f1393800-19eb-11eb-83dc-a3fe77f3880f.png)

**Comment by DavidGrant-NIWC** [comment]
Available for evaluation from: [Portrayal Catalog with CHMGF fairways](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/tree/magenta-fairway-proposal). To download, select the "Code" button and then "Download ZIP".

![image](https://user-images.githubusercontent.com/62906211/124310616-6ee4b300-db3a-11eb-9ac5-95b9f1c8b9c7.png)

_NOTE: The linestyle and symbol for fairways was shared in some cases with other features. I assumed that these other features should not also be changed to CHMGF. For instance, line style NAVARE51 was used to outline fairways, and is described as:_

> boundary of a navigation feature such as a fairway, magnetic anomaly, etc.

_Rather than modifying this linestyle, a new style was created for use by fairways. Similarly, rather than modify symbol EMAREGR1, a new symbol was added: EMAREMG2._

**Comment by TDYCARHugh** [comment]
I agree with Sylvia.  When we worked on the original S-52 a vision/perception scientist was consulted and informed us that the human eye has difficulty distinguishing between shades of red, magenta and orange but can do quiet well with shades of blue and green.  I think if these different shades are side by side with enough surface area then it is easier to distinguish.  Also when the colours are faded as per night colour palettes etc everything becomes shades of grey. If the intention is to provide significantly different meaning to the user it is better to use different patterns.

**Comment by EdwardHands** [comment]
It is clear that the proposed change does not achieve the desired result with regards improvements to the visibility of fairways and that there is little point pushing for its implantation as is. However it is maintained that the issue is worthy of attention and work will continue to try develop a more suitable solution and will submit details for discussion/testing.

**Comment by DavidGrant-NIWC** [comment]
Prototype with transparent fill (token=LITYW, transparency=0.85). If a transparent fill is used then might want to add a new color token so the transparency can be different in each color palette.

#### Click pictures to enlarge
|Sample|Day|Dusk|Night|
|:---:|:---:|:---:|:---:|
|1|![ShoreECDIS 2021-11-07T224848Z](https://user-images.githubusercontent.com/62906211/140664955-45424f6b-a85e-4e81-b4c7-85dfdfdf59b6.png)|![ShoreECDIS 2021-11-07T224900Z](https://user-images.githubusercontent.com/62906211/140664976-1426ed17-79d3-42bb-b09f-d76ca99968ba.png)|![ShoreECDIS 2021-11-07T224907Z](https://user-images.githubusercontent.com/62906211/140664977-9556e99c-7c27-49d6-ab4f-d4d4cb3dead7.png)|
|2|![ShoreECDIS 2021-11-07T224402Z](https://user-images.githubusercontent.com/62906211/140665068-f2730e7e-37cb-4de1-b84f-b279f80a0704.png)|![ShoreECDIS 2021-11-07T224407Z](https://user-images.githubusercontent.com/62906211/140665074-d6bb794a-7333-42a8-8fe2-08c63b166bb4.png)|![ShoreECDIS 2021-11-07T224412Z](https://user-images.githubusercontent.com/62906211/140665079-08ea63a9-444a-4e1a-9674-2705ffc42534.png)|
|3|![ShoreECDIS 2021-11-07T224325Z](https://user-images.githubusercontent.com/62906211/140665098-8a5f25ce-1df4-44ab-af15-b00fa81b2444.png)|![ShoreECDIS 2021-11-07T224331Z](https://user-images.githubusercontent.com/62906211/140665124-3c080fb3-55da-44b1-a2a6-9c668b864ed4.png)|![ShoreECDIS 2021-11-07T230851Z](https://user-images.githubusercontent.com/62906211/140665361-cc5b2cbf-54cf-4ea0-adc4-90d94f441431.png)|

**Comment by EdwardHands** [comment]
Thanks David, I will continue to look into this and come back with some suggestions a soon as possible.

**Comment by EdwardHands** [comment]
Thanks for preparing the prototypes Dave. The solutions appears to work well in Day and Dusk modes. The ability to adjust the transparency in night mode would be beneficial and I would be keen to investigate the options to add new colour tokens to enable this

**Comment by DavidGrant-NIWC** [comment]
### To modify
* Edit PC/ColorProfiles/colorProfile.xml
  * Add a color to the \<colors> section
![image](https://user-images.githubusercontent.com/62906211/142451265-7f869e5a-ecb8-4450-a7eb-c3b7fddafb25.png)

  * Add the color to each palette. Transparency can be added with a transparency attribute on the item: 
![image](https://user-images.githubusercontent.com/62906211/142450459-f5cb0c13-5560-4cec-8a92-823ae93e2290.png)


* Edit PC/Rules/Fairway.lua
  * Add a ColorFill instruction prior to each LineInstruction: 
![image](https://user-images.githubusercontent.com/62906211/142450940-6a44b34e-9c04-4502-8338-a8311994411a.png)

* Import the new PC using the SENCEditor
* Assign the new PC to the test dataset(s)
* Run ShoreECDIS to see results

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144326756-87437c69-1cad-46f3-a1c0-19345f4bfd7b.png)

**Comment by GuttormTomren** [comment]
IALA supports the efforts to visualize for the mariners more easily defined fairways. As described this have some challenges, and still requires work/testing. For IALA it is important that a change do not degrades visibility of AtoN or AtoN information in the area.

**Comment by GuttormTomren** [comment]
IALA supports the efforts to visualize for the mariners more easily defined fairways. As described this have some challenges, and still requires work/testing. For IALA it is important that a change do not degrades visibility of AtoN or AtoN information in the area.

**Comment by LeoKuzmin** [comment]
One question, Why do we need add a new colour, if its RGB is identical to CHYLW colour? And transparency value can be assigned by ColourFill command: 
featurePortrayal:AddInstructions('ColorFill:CHYLW,0.85')
The result of this command gets the same portrayal as it is offered above. But this change doesn't require many modifications of PC.
![image](https://user-images.githubusercontent.com/106175259/178463706-719598c7-31f4-49c0-bfd5-b23823f028f6.png)

**Comment by DavidGrant-NIWC** [comment]
> One question, Why do we need add a new colour, if its RGB is identical to CHYLW colour? And transparency value can be assigned by ColourFill command:
> featurePortrayal:AddInstructions('ColorFill:CHYLW,0.85')

Specifying a transparency in the ColorFill instruction applies the same transparency in every palette. To get a different transparency in one of the palettes it is necessary to specify the transparency in the realization of the color within the palette - see 2b-4.2.19 in S-100 v5:

![image](https://user-images.githubusercontent.com/62906211/178525721-02b29b1a-ef6a-4be5-a966-8ad7f20ce2d0.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Leave issue open as Norway has not yet submitted a new proposal for discussion.
2. Release PC 1.1.0 using S-52 symbology for **FAIRWY**.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [ ] **Norway** to submit paper to S101PT10 highlighting their preferred option for a new Portrayal of **Fairway** (by using transparent fill or a new set of grey colours to better manage readability in Day/Dusk/Night settings). The paper would seek endorsement to introduce this portrayal change during DF-ECDIS period. If endorsed by the PT, Norway will continue working with NIWC to implement the changes for PC 2.0.0 using this issue.

If the answer is negative, we would close this issue and Norway would need to open up a new one later in time ....

**Comment by alvarosanuy** [comment]
No update or proposal to S101PT11.
