### ISSUE TITLE
ECDIS Chart 1

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#20]
**Proposal:**

- Discuss the need for an S-101 ECDIS Chart 1.
- Needs review and decisions regarding new features to be added, etc (Who, How?)-  

![image](https://user-images.githubusercontent.com/70189016/94645703-d2358080-032f-11eb-8ab4-e33f7b95bdc9.png)

**Comment by rmalyankar** [comment]
About the second question, if there is a "Chart 1" in the future, each PS used on ECDIS would need an equivalent, because they may have features that are not used in S-101 and therefore use different symbols; or "Chart 1" may need to be made extensible by product specifications other than S-101.

**Comment by kusala9** [comment]
Chart 1 is included in multiple references in IEC61174. I think it would be hard to drop it as a requirement (there's also interrogation features required by 61174 too and the black adjust boxes are used for calibration tests). I think it would be hard to drop it as an essential part of the IHO's contribution to the standards for ECDIS but I think it would be possible to restrict the scope to S-101ENC only. We had a conversation at S100WG about DF-ECDIS and we discussed whether an ENC forms the "foundation" of a SOLAS-compatible display. I think this is the case (although I accept there were other views). If we accept that ENC is always a foundation (whether S-57 or S-101) then ECDIS Chart 1 could be restricted to only those features within their scope. If other S-100 layers are also enabled then they could be optionally indexed with a product specific chart 1 or it could be mandated locally if need be.... I think there would be a lot of complexity in creating an extensible chart 1 function/content - we could look at it but I'm not convinced it's necessarily required.... thoughts?

**Comment by AntonioDiLieto** [comment]
From a mariner point of view, ECDIS Chart 1 is still valid today, and our officers do use it.
I would still like to have it for an S-101 ENC, along with separate S100 product specific chart1s.

**Comment by AntonioDiLieto** [comment]
It would be also beneficial to create and maintain a consolidated IHO S100 chart1 in pdf format, divided in product specific sections. This could be made available through IHO website, to assist mariners in becoming familiar with completely new breeds of symbols.

**Comment by alvarosanuy** [comment]
Recommend:

- Approve the creation of and maintenance of an S-101 ECDIS Chart 1 draft version
- Seek volunteer to develop the first version
- Ask S100WG to provide guidance on the need and management of ECDIS Chartt 1 equivalents for other S100 products

**Comment by alvarosanuy** [comment]
Refer to S101PT Actions **PortSG-30** and **PortSG-31**

**Comment by alvarosanuy** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/8571f3e5-a5ce-4dab-9f46-ea5e3b51d569)
