### ISSUE TITLE
S101 ECDIS Performance requirements log

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#21]
**Proposal:**

- Discuss gaps between S-57 ECDIS performance requirements listed in S-52 and existing S101 instruments (PS, catalogues, ect). 
- Understand current S100WG initiatives in this respect and identify best practice to coordinate efforts.
- Approve the creation of an **S-101 ECDIS Performance requirements log** to be managed by this subWG and used to manage implementation priorities based on different S100 ECDIS development phases (i.e. DF vs 'pure' S100).

![image](https://user-images.githubusercontent.com/70189016/94646835-7ddfd000-0332-11eb-8b78-cd7179b7dc2f.png)

![image](https://user-images.githubusercontent.com/70189016/94647906-d0ba8700-0334-11eb-9831-6810f4625f38.png)

**Comment by DavidGrant-NIWC** [comment]
S-52 requirements are currently included in the draft S-98 Annex C Harmonised Portrayal for ECDIS and INS - the cross-reference would be useful for ensuring completeness, as well as tracking intentional changes or removal of existing requirements.

**Comment by rmalyankar** [comment]
What David says. Comparing S-52 to the new draft "S-98 Annex C" instead of S-101 would save time. An S-101 ECDIS would ultimately encompass more S-100 products than S-101 ENCs.

**Comment by kusala9** [comment]
[Jonathan] - we made a list of some of the gaps when we did the initial dual-fuel ECDIS report with NOAA last year. I'll dig out the list and post it here. I think there's a whole bunch of elements from S-64, S-52 and 61774 which need to be accounted for somewhere. Happy to look at the revised S-98 Annex C against those too.  There's also some S-63 elements, particularly the ECDIS status report which we probably can't ignore too. Basically all the "IHO defined" content of the user experience (which aren't just portrayal based...) 👍

**Comment by alvarosanuy** [comment]
Agree on performing cross check between S-52 & S-98 Annex C. This has just been released and we all need time to have a good look at it.

Still not convinced that S-98 is the right place for ECDIS **product specific** requirements. S-98 should contain guidance on elements that affect multiple products and require coordination and standardization. What about product specific requirements?
For example (if approved), details on how the downgrading of S-101 QoBD should be implemented by OEMs.

**Comment by alvarosanuy** [comment]
I think this Issue has evolved into 2 different topics:

1. Should S-98 Annex C include ECDIS/INS performance requirements that are S100 Product Specific (e.g. S-101) **or** should they be included somewhere else (e.g. S-101 Product Specification Section nn)? 
                    - I suggest we await the output of the S-98 Annex C review process.

2. The need to keep record of new S-101 specific ECDIS functionalities that, although approved in principle by the S101PT, they can't be implemented in a DF-ECDIS scenario and therefore their development and testing will be delayed or managed at a slower pace. The key objective of maintaining an 'S-101 ECDIS Performance requirements' log is to ensure:
      * these requirements are not lost or forgotten,
      * the requirement for development and testing is recorded
      * their progress is managed in one place.     
   
See Draft '_S-101 ECDIS Performance requirements_' log    https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/20201218_Draft_S-101%20ECDIS%20Performance%20log.xlsx 
   
It's important to remember that, although the preference is to manage new functionalities using machine readable catalogs, some elements will need to be implemented at the ECDIS level (by OEMs). These requirements will have to be properly documented and included in the corresponding ECDIS type approval document.

**Comment by rmalyankar** [comment]
On item (1), I think Product Specifications should be limited to describing the data products.  The performance requirements should be described separately from the Product Specification.  Any particular data product could be used in different types of systems, which may have constraints and requirements different from ECDIS.

It will be easier to keep the user experience for different products on ECDIS/INS harmonized if the ECDIS/INS performance requirements for all relevant S-100 data products are specified in only one document.

I agree with awaiting the outcome of the S-98 Annex C review process for this.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343052-5d750e50-ceda-440d-9417-70c3aa031c93.png)

**Comment by alvarosanuy** [comment]
S101PT action PortSG-37 discontinued the use of the "S101 ECDIS Performance and Portrayal requirements log' and tasked Alvaro to migrate all entries to Github as new issues.
