### ISSUE TITLE
Portrayal proposals - Workflow and Form

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#22]
**Proposal:**

- Review and approve the use of the proposed 'Portrayal amendments request workflow and form'.
- Decide on an implementation date (i.e. New proposals submitted from 01NOV2020).

[Portrayal request form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__sOmn1BUQUwwMFk0NUI5UFZGQUdaVEdVUTZHNVVXRC4u)

[S101 Portrayal update workflow.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5303377/S101.Portrayal.update.workflow.docx)

**Comment by DavidGrant-NIWC** [comment]
Add to request form item 9:
- Pixmap
- Color Token (need values for each palette)
- Viewing Group (part of display base? included in which viewing group layers?)
- Other (allow user input rather than listing sub-bullets)
  - Context Parameter
  - Viewing Group Layer
  - Foundation mode
  - Display Mode
  - Stylesheet (needs to be updated as color tokens are changed/added/removed)
  - Display Plane
  - Alerts
    - Message
    - Highlight
    - Alert

**Comment by alvarosanuy** [comment]
Thanks David. Changes applied.

New version looks like this:
[20201014_Updated portrayal request form.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5374688/20201014_Updated.portrayal.request.form.pdf)

**Comment by DavidGrant-NIWC** [comment]
Item 6 - change to "Add", "Amend", "Remove" (changes do not always affect symbology)
Item 8 - in addition to name, also need:
  - description
Item 9 - change "Portrayal Type" to "Affected Catalogue Item(s)"
Item 10 - change to "Details"

**Comment by alvarosanuy** [comment]
Done but:
item 9 - used the term 'Definition' instead of 'Description' as per the IHO registry fields.
item 10 - amended to 'Other Details' and include one possible example.

**Comment by SylviaSpohn-BSH** [comment]
Is this form only for member states or other contributers. Where it will be found in future and how distributed?
The real size for the symbol and its components should be shown somewhere. Can this be mentioned in the form?

**Comment by alvarosanuy** [comment]
Thinking back, a better and more standardised approach would be aligning the 'Physical' AIS display with paper charts (only because mariners are familiar with it). What I mean is using a magenta circle with the text AIS (no P -AIS). 

- AIS and V-AIS are recognised international abbreviations (S-4 B-122.1).
- Section B-480 of S-4 states: The location of a charted radio station must be emphasised by a **magenta circle** 3mm radius, centred on the position. This symbol is generally referred to as a radio circle; it is also used for coast radar stations providing range and bearing on request (see B-485.1), various radar beacons (see B-486) and AIS-equipped aids to navigation (see B-489). **The international abbreviation indicating the type of transmission must be shown in magenta adjacent to the circle**.

![image](https://user-images.githubusercontent.com/70189016/96056005-43009f00-0ed1-11eb-9e17-684060e6e7ab.png)
![image](https://user-images.githubusercontent.com/70189016/96055967-2fedcf00-0ed1-11eb-970f-8567ded75b35.png)

**Comment by izzykim7** [comment]
- KHOA will need pivot point, size of symbol, coulour plan and a design(scatch).
if the propsed colour is not on the 101 colorprofile,  color registration is required first.

- Producing SVG file could be in between  primary and final approval if the initial proposal is not SVGfile.

**Comment by alvarosanuy** [comment]
I have updated the 'Portrayal update request form' to align it with the official IHO's Registry version.

**Comment by alvarosanuy** [comment]
Portrayal proposal online form and workflow approved by S101PT6
