### ISSUE TITLE
Review the need for new symbology

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#23]
**Proposal:**

- Use the attached spreadsheet to comment on each new Feature/attribute combination introduced in S-101 and the need or not for new symbology.
Latest spreadsheet: [S-57 Removed_Remodelled Items_Ed3_28AUG2020_.xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5303468/S-57.Removed_Remodelled.Items_Ed3_28AUG2020_.xlsx)
Previous version with proposed new columns to standardise and track responses: [S-57 Removed_Remodelled Items_Ed2_OCT2019.xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5303474/S-57.Removed_Remodelled.Items_Ed2_OCT2019.xlsx)

- S101PT VC to collate inputs and present consolidated responses and decisions at S101PT6 (Dec 2020)

![image](https://user-images.githubusercontent.com/70189016/94649789-bbdff280-0338-11eb-8058-56c19fa83d8b.png)

**Comment by AntonioDiLieto** [comment]
Hi Alvaro,
as a user, I would like to be able to distinguish between the different types of AIS AtoNs (Real, Synthetic, Virtual), not only knowing the "name" of the AIS AtoN (lateral buoy, cardinal etc). My experience with our officers is that they believe all AIS AtoNs are Virtual (i.e. not physically present).
The attached ITU document makes this distinction
[AIS AtoN ITU.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5364037/AIS.AtoN.ITU.pdf)

Will the presentation library be able to reflect the three categories of AIS AtoNs with a magenta circle and text (R-AIS, S-AIS, V-AIS) close the AIS AtoN simplified symbol? (see attached picture of V-AIS AtoN)
![V-AIS](https://user-images.githubusercontent.com/72732124/95729946-e22d5880-0c7d-11eb-91c3-0a20a2a2fd29.PNG)

**Comment by alvarosanuy** [comment]
Thanks Antonio.
S-101 has modeled AIS as follows (refer to DCEG 21.1):

AIS signals used as an aid to navigation may:

- actually be transmitted from a physical aid to navigation, or appear to be transmitted from a physical aid to navigation but is actually transmitted from an AIS base station (Physical AIS aid to navigation);
- be transmitted from an AIS base station to represent an aid to navigation where a physical aid to navigation does not exist (Virtual AIS aid to navigation).

I would like to hear from an IALA representative, but my understanding is that from an operational point of view AIS AtoN stations are identified as follows:

- **Physical** AIS AtoN. The AIS station is physically located on the AtoN; 
- **Synthetic** AIS AtoN. AtoN messages  for a  specific AtoN are  transmitted  from a  remote location  (i.e.  from 
another AtoN or a Base station). 
- **Virtual** AIS AtoN. A remote AIS Station (another AtoN or a Base Station) transmit a message to identify an 
AtoN in a location where it does not physically exist. 

'**Real**' does not seem to be an IALA classification ....... and I personally think that what mariners want to know is if the AIS refers (or not) to a physical object in the same location (would I see or hit something?). From this point of view Physical and Synthetic AIS would be encoded as a 'Physical AIS aid to navigation' feature in S-101 and it would be associated to a 'physical' aid to navigation feature as well.  I think the magenta circle with the text **P - AIS** could be  a valid option. At the moment there's no portrayal for this in S-57; usually INFORM is used to indicate an AIS is installed or displayed from a charted navaid. We must keep in mind that S-57 ENCs would look different (no symbology)

Virtual AIS should continue to display as they currently do in S-57 (using SYSMINS drawing instructions).

**Comment by SylviaSpohn-BSH** [comment]
keep it as it is - only differentiate between V-AIS and the other without new preposition.

**Comment by rmalyankar** [comment]
Reference https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/22#issuecomment-708714417

IMO Circ. 243/Rev.2 Table 5.1 describes different shapes for AIS AtoNs. For example:
![image](https://user-images.githubusercontent.com/51188078/96077654-41998d00-0e65-11eb-9175-9962c9676434.png)

**Comment by MikusRL** [comment]
Just for additional consideration. From capture and use afterwards perspective. My understanding is that if we capture and encode features for navigation, we should capture the object and its characteristics - not the characteristics of its master. In case of Synthetic AIS I would assume it is an Virtual AIS, because it is transmitted onto something, the same as fully Virtual. From users perspective I understand it would be beneficial to know the reason, why my buoy feature might not fit the AIS symbol, also on radar. If it is portrayed as V-AIS, I understand and look out the window for the actual location of the buoy. If AIS symbol would be Physical in this example, then there would be much more questions what has happened with this AtoN, if they do not match for position in large scales. If Synthetic AIS would be treated as Virtual, then there is no necessity to introduce new symbol or text legend for it. Just AIS for physical and V-AIS for Synthetic and Virtual feature capture.  
Other consideration is that actually the AIS feature should be captured in ENC product as for panning purpose or while navigating only as hoover over portray function, as AIS for ECDIS would have the diamond symbol from the AIS transmission itself. So from perspective of capturing it is only for Paper charts, Route planning or Recreational users.

**Comment by alvarosanuy** [comment]
23/2/21 - Initial review underway by Alvaro and Jeff - 322 of 345 entries reviewed. Initial recommendations require cross check and final approval to proceed by S101PT.

We propose KHOA to help develop draft SVG symbology and NIWC to create new or update existing rules when recommendations are approved by the S101PT.

New draft symbology will have to follow portrayal workflow before its final approval and inclusion into the PC.

**Comment by alvarosanuy** [comment]
**12/04/21** - Jeff and I have completed our initial assessment of the approx. 350 new or S-57 remodeled S101 features/attributes.

You should have received a link to an excel spreadsheet (S-57 Removed_Remodelled Items_Final for comments_12APR2021) in your email. The last tab (subWG comments) contains a list of 126 features/attributes that we think impact or should impact S101 portrayal (symbology and/or rules).
What we need now is your input, **by COB 16 May 2021**, to help us narrow down the instructions we'll give KHOA and NIWC regarding new symbology or updated rules respectively.
The spreadsheet can be accessed and edited by multiple users online. If you want to make a comment, please make sure you include your name at the top of one of the columns added for this purpose.
Also, if you want, feel free to look at the other 240 items (S-101 and Additional Entries tabs) Jeff and I think shouldn't impact portrayal and send us an email if you think differently.
Any new symbology prototyped by KHOA (_following some general instructions in the spreadsheet_) will be circulated for comments to other stakeholders as per the new portrayal request workflow. Importantly to note is that the S-101 executive has agreed on excluding mariners' input at this point in time in order to speed up the process and give us the chance of having an official and complete S101 PC version by the end of this year. We will still have time to fine tune things before we get to the operational version.
Thanks in advance for your support.

**Comment by alvarosanuy** [comment]
Hi all,

The review period ended without any additional comments beyond Jeff's and I.
I have attached the latest version of the spreadsheet with the recommended way forward for each item in a new column at the end. There are still some entries that require input from this subWG (highlighted in magenta).
Can you please provide your views against these issues by writing your comments in the next available column in the file and emailing your updated version of the spreadsheet to me (alvaro.sanchez@defence.gov.au) by **COB 02JUL2021**?
With your comments in view I will conclude a decision and I'll allocate tasks to KHOA and NIWC in order to present our final recommendations to the S101PT at S101PT8 (Nov/Dec 2021??).
**I'll certainly appreciate if every subWG member takes the time to review and comment on the content of the spreadsheet. The larger the number of comments, the more accurate the decisions.**
[20210607_S-57 Removed_Remodelled Items_Final after review period ending 20210516.xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/6605791/20210607_S-57.Removed_Remodelled.Items_Final.after.review.period.ending.20210516.xlsx)

**A complete S-101 Feature Catalogue version 1.0.0 wont be possible until we sort out all these issues.**

**Comment by alvarosanuy** [comment]
This is the latest version of the remodeled spreadsheet after the review period ending **02JUL2021**.
It includes decisions and allocation of tasks/next steps. Items that are still contentious have been now added as dedicated Github issues.
[FINAL Actions_28JUL2021 (1).xlsx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7239719/FINAL.Actions_28JUL2021.1.xlsx)

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343196-7a10901c-528b-407f-a775-6a361f0d9148.png)

**Comment by GuttormTomren** [comment]
IALA; This was initially a request for more clear indication on types of AIS AtoN, this is now handled in Gitub #37 and 70.

**Comment by alvarosanuy** [comment]
Recommended actions have been endorsed by S-101PT8 and either migrated to Github as new issues or included in '_S-101 Portrayal_Consolidation of pending actions.xls_'.

**If the 'Allocated' person/organisation requires further information to proceed with the implementation as described in the spreadsheet above they are requested to create a new issue in this Github space**
