### ISSUE TITLE
Small Craft moorings - Update symbology

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#28]
[S101PT6_New portrayal for Small Craft Mooring Areas.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/6059230/S101PT6_New.portrayal.for.Small.Craft.Mooring.Areas.docx)

The intention is to discuss ideas to replace the current portrayal for 'Small Craft moorings' before the AHO officially submits a 'Portrayal change request form' and the proposal is shared with the stakeholders we decided when we approved the 'Portrayal request workflow' (refer to Github Issue # 22).
We will also have to recommend the S101PT an implementation date (DF or pure S100 ECDIS).

Other options:

- Linework as proposed in the paper but use mooring buoy symbols along the line instead of area pattern (all in the same faint grey colour).
- Linework as proposed in the paper but use text 'Small Craft Moorings' instead of area pattern made of mooring buoy symbols (all in the same faint grey colour).

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343458-18ed4500-6dba-4cc9-b7d8-f2ad6d43b206.png)

**Comment by alvarosanuy** [comment]
Recommendation:

- **Symbolised** - use complex line structured as LC(ACHARE51) but in CHGRF colour and replacing the small anchor with a new point symbol - smaller BOYMOR01 in CHGRF colour (**Needs development**).
- **Plain** - LS(DASH,2,CHGRF)

Both symbolizations will also display a 'central area symbol' as follows - BOYMOR01 in a circle (both in CHGRF) with a final size similar to ACHARE51 (**Needs development**).

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Portray Surface **AnchorageArea** features with **categoryOfAnchorageArea**=8(small craft mooring area) using:

- **Plain boundaries** - LS(DASH,2,CHGRF) + center symbol (as per bullet point 3 below)
- **Symbolised boundaries** - LC(NAVARE51) but in CHGRF colour+ center symbol (as per bullet point 2 below)

2. Portray Point **AnchorageArea** features with **categoryOfAnchorageArea**=8(small craft mooring area) using:

- BOYMOR01 but in CHGRF colour.

Any other display parameters are to be copied from **AnchorageArea**.

4. Mikus to develop and upload to this Github issue SVG, CSS and Engineering Drawing files for:

- new center symbol: Based on BOYMOR01 but within a circle (both in CHGRF). Final diameter and line thickness as per SY(ENTRES51).
- new Point symbol (as per bullet point 2 above).

**Comment by MikusRL** [comment]
@alvarosanuy In addition to the above description for I assume that removing of the location circle from the bottom line from the BOYMOR01 for the center symbol is by default, as it does not normally representing a precise location any more, correct? Thanks.

**Comment by alvarosanuy** [comment]
> @alvarosanuy In addition to the above description for I assume that removing of the location circle from the bottom line from the BOYMOR01 for the center symbol is by default, as it does not normally representing a precise location any more, correct? Thanks.

That's right.

**Comment by MikusRL** [comment]
I have created three symbols based on that symbol ENTRES itself is in three versions - 51, 61 and 71. 
[BOYMOR_Centred.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9440209/BOYMOR_Centred.zip)

I have not updated any of the .svg "metadata" entries, as I could not find any S-100WG papers or decisions, which would define the S100SVG metadata attributes in more detail, than it is stated in the example in S-100 Part 9, Appendix 9-B, section 9-B-2-4. As I understand, if any changes are introduced, like applying S-100 Part 4, 4a-5.1 the minimum set of metadata elements for any resource to comply with S-100 profile, and not sure if any is applicable from S-100 Part 17, then all of the SVGs already existing would need an update to it too. I think it is better to do it for all in one go, if metadata for svg is created by S-100WG. The link from current metadata does not lead to anywhere at the moment.

I also tried to analyze, if this symbol would need to be shifted by default, and came to a conclusion, that this symbol is as the "main" and not as additional. Not sure though in the ECDIS chart screen, where own ship is in center location, if this "shift" then should be on OEMs implementation side, or should it be standardized, and agreed shift added to the SVG itself. Happy to shift and re-save the symbol, if group agrees on exactly in which direction it should be shifted:
![image](https://user-images.githubusercontent.com/72803214/187090085-cbfb2dbb-ca6b-4853-a5cb-370726bde5f3.png)



![image](https://user-images.githubusercontent.com/72803214/187088633-2c3f851b-0f1f-4bb4-9c7b-70d5f7b2455c.png)

![image](https://user-images.githubusercontent.com/72803214/187088642-5fb31510-1bfd-4e2c-a3d3-b446375ce8fb.png)

![image](https://user-images.githubusercontent.com/72803214/187088654-1040b261-db38-446a-9fd8-3c9bfe8da807.png)

**Comment by rmalyankar** [comment]
Re SVG metadata:

S-100 Part 17 does not apply to this "SVG metadata", nor do 4 or 4a.  There isn't any documentation of SVG metadata apart from 9-B-2-4.  The SVG metadata schema is online at https://schemas.s100dev.net (scroll down to the _Part 9_ section and look for _S-100 SVG metadata_, it has only _publisher_, _creationDate_, _source_, _format_, _version_.

**Comment by alvarosanuy** [comment]
@MikusRL 

- BOYMOR51 is fine. It will be added to the **AnchorageArea** rule and will include (as per S-52) a call to CSP RESTRN01 (and from that to RESCSP02).

- I believe BOYMOR61 and BOYMOR71 are not required. CSP RESTRN01 + RESCSP02 will 'add' new symbols (to be off set by the OEM) to an angle and distance from BOYMOR51 based on the values of the attribute **restriction** (if populated).

                     Does anyone have a different view on this???

- **There's still one new symbol to be created**: Identical to existing S-52 symbol BOYMOR01 but in CHGRF colour (refer to my comment on 14/7 detailing the decisions made at the last PsWG meeting). This symbol is to be used when the geometric primitive of the **AnchorageArea** with **categoryOfAnchorageArea**=8(small craft mooring area) is Point.

**Comment by MikusRL** [comment]
@alvarosanuy Hi, you are correct. I guess little bit "overthought then this was. Sorry. BOUMOR02 in CHGRF coming right up.

**Comment by MikusRL** [comment]
@alvarosanuy I have created the point symbol in CHGRF as BOYMOR02. I also created in CHGRD (BOYMOR04) for discussion, because I think that if the centre symbol is expected to be faint, then being a faint also for point symbol could be too light, seen less significant, or one could look for border line of the area assuming it is a centred symbol. In smaller scales this point symbol shows almost actual position of mooring buoys, definitely covering them. Of course with that consideration in mind we could actually re-use also the existing black symbol (BOYMOR01) for areas as a point. For discussion and option in future. 
[BOYMOR_area_point.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9450948/BOYMOR_area_point.zip)

![image](https://user-images.githubusercontent.com/72803214/187383177-0efa9d84-befb-4ed6-a02b-a69b49e935de.png)

**Comment by alvarosanuy** [comment]
@MikusRL  - Thanks.
Let's proceed with BOYMOR02. Mariner's shouldn't look for an area boundary as the center symbol for Surfaces is surrounded by a circle ......... If you, or anybody else, wants to propose a change to this symbology I propose this is submitted using a new Github issue that would be discussed after PC 1.0.2 implementation.

@mikkan - I Reopen this issue until the rules and symbols are updated by NIWC in PC 1.0.2.

**Comment by mikan66** [comment]
What about feature 'Anchor Berth' as well?

**Comment by mikan66** [comment]
@alvarosanuy  your direction on July 14
> BOYMOR01 but in CHGRF colour.

 BOYMOR01 is a shared symbol with MooringWarpingFacility, color change requires a new symbol for use here. 
 
Is this now replaced with new symbol BOYMOR02 which now has CHGRF as the color?

**Comment by alvarosanuy** [comment]
> Is this now replaced with new symbol BOYMOR02 which now has CHGRF as the color?

@mikan66 - Final portrayal instructions as follows:

1. Surface **AnchorageArea** features with **categoryOfAnchorageArea**=8 (small craft mooring area) using:

- Plain boundaries - LS(DASH,2,CHGRF) + center symbol (BOYMOR51.svg)
- Symbolised boundaries - LC(NAVARE51) but in CHGRF colour + center symbol (BOYMOR51.svg)


2. Point **AnchorageArea** features with **categoryOfAnchorageArea**=8 (small craft mooring area) using:

- BOYMOR02.svg

**Comment by alvarosanuy** [comment]
> What about feature 'Anchor Berth' as well?

@mikan66  - **AnchorBerth** is not affected by any decision made in this issue. As far as I remember, we haven't proposed changes to the S-52 symbology. Am I missing something here?

**Comment by mikan66** [comment]
> > What about feature 'Anchor Berth' as well?
> 
> @mikan66 - **AnchorBerth** is not affected by any decision made in this issue. As far as I remember, we haven't proposed changes to the S-52 symbology. Am I missing something here?

No, I only point out AnchorBerth because it has the same attribution defined with  categoryOfAnchorageArea=8 as a possibility.  Currently, AnchorBerth does not examine any attributes in the portrayal rule and only uses symbol ACHBRT07.  I will leave it "as-is".

**Comment by mikan66** [comment]
> * Symbolised boundaries - LC(NAVARE51) but in CHGRF colour + center symbol (BOYMOR51.svg)

NAVARE51 is a shared line style with other rules, I can't change the color here only.  I can create NAVARE52 manually or someone can supply an official new line style for use here.  I can go with the below if you want.


<?xml version="1.0" encoding="ISO-8859-1"?>

<?S100lineage source="S52Preslib4.0" format="S100Ed2" version="0.1" creationDate="2022-09-16"?>
<?S100Meta name="NAVARE52" exposition="boundary of anchor area with small craft moorings"?>
<lineStyle>
   <intervalLength>8.6</intervalLength>
   <pen width="0.32">
      <color>CHGRF</color>
   </pen>
   <dash>
      <start>1</start>
      <length>6</length>
   </dash>
   <symbol reference="EMAREGR1">
      <position>4</position>
   </symbol>
</lineStyle>

**Comment by mikan66** [comment]
Examples of categoryOfAnchorageArea=8:
Point: 
![image](https://user-images.githubusercontent.com/4913543/190647402-77e12360-921b-4480-82a0-366020085320.png)

Surface + plain boundaries = true:
![image](https://user-images.githubusercontent.com/4913543/190650581-0b755c9d-db7e-4456-ae70-6772d7886005.png)

Surface + plain boundaries = false    [ locally created line style NAVARE52 from NAVARE51 but with color = CHGRF  :
![image](https://user-images.githubusercontent.com/4913543/190651609-a6f8279c-0b7f-4379-ac3d-f4b0c4290bb1.png)

See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/124#issuecomment-1249579967

**Comment by alvarosanuy** [comment]
@mikan66 - Thanks for creating LC(NAVARE52). I will add it to the list of items we need to submit to the IHO Registry. When the time comes I will ask you to supply the associated files.
