### ISSUE TITLE
flipBearing attribute for TextPlacement

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#29]
[Email trail up to 01MAR2021.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/6059277/Email.trail.up.to.01MAR2021.docx)

Please continue the conversation in this space.

**Comment by TDYCARHugh** [comment]
I guess I better make some diagrams.
I was thinking that is would be like putting the text at the end of a Ray.  If the text is centred at that point then the text would cover a circle when you consider rotated maps.  So the placement would essentially be to keep these circles from colliding with other text circles and to keep the text out of the channels.

So I was see the bearing and distance as an alternate to the current vector x,y offset.

The two images below show text placed at the end of the red arrow defined by bearing/distance.  As the chart is turned the Text covers a circle around the point at the end of the arrow.  But it also maintains a relative distance from the feature during zoom in/out.   I just rotated the image so the symbol is upside down.  Do you keep symbols upright on a rotated display?

[cid:image002.png@01D70E88.90A36F10]


[cid:image005.png@01D70E88.90A36F10]

Hugh

**Comment by DavidGrant-NIWC** [comment]
I'm not seeing your images - you should be able to paste them directly into the message.

> This proposal is to add a second offset type to the portrayal of Symbol and TextPoint in Part 9 such that there is a choice of no offset, Vector offset or bearing offset.  The new bearing offset would place the reference point of the Symbol or TextPoint at the location indicated by the bearing and distance.

Adding this second offset type is equivalent to using the current offset but changing the CRS from PortrayalCRS to GeographicCRS. i.e. add offsetCRS to TextPoint and other instructions as needed.

> For example if there is an East-West Channel then text for a buoy on the north side of the channel could be placed in a Northern bearing a given distance from the buoy. As the chart is rotated the text would stay on the northern side of the channel in a consistent way.

The text will only stay on the northern side if it rotates along with the chart, which requires changing the CRS of the rotation parameter from PortrayalCRS to GeographicCRS. i.e. add rotationCRS to TextPoint and other instructions as needed (it's already present in 9-12.3.1.1 Symbol).

**Comment by TDYCARHugh** [comment]
I replaced the images in the previous comment. It was posted by reply from email so they got messed up.

geographicCRS can give the desired bearing but distance is on the ground.
portrayalCRS gives the desired units for the distance angles are from display y axis.

I am proposing that the bearing be in degrees from North (geographicCRS) so that the placement is consistent with a compass bearing. If a point feature has space for the text on the western side then a western bearing gives the hint of where to put the text.  If the distance is in mm on the display (portrayalCRS) than the text stays a specified distance from the point feature when zooming instead of moving.

**Comment by DavidGrant-NIWC** [comment]
Got it.

For consistency / future flexibility I'd recommend:

**GraphicsBase::Offset**
|Role Name|Name|Description|Mult|Type|
|:---|:---|:---|:---:|:---|
|Class|Offset|Used to specify an offset from an anchor coordinate|-|-|
|Attribute|distance|distance from the anchor point. Default = 0|1|CRSLength|
|Attribute|angle|angle from the anchor point. Default = 0|1|CRSAngle|

**GraphicsBase::CRSLength**
|Role Name|Name|Description|Mult|Type|
|:---|:---|:---|:---:|:---|
|Class|Offset|A length in a CRS|-|-|
|Attribute|length|Specifies the length. Default = 0|1|double|
|Attribute|crs|Specifies the CRS. Default = PortrayalCRS|1|CRSType|

**GraphicsBase::CRSAngle**
|Role Name|Name|Description|Mult|Type|
|:---|:---|:---|:---:|:---|
|Class|Rotate|An angle in a CRS|-|-|
|Attribute|angle|Specifies the angle. Default = 0|1|double|
|Attribute|crs|Specifies the CRS. Default = PortrayalCRS|1|CRSType|

**Text::TextPoint**
|Role Name|Name|Description|Mult|Type|
|:---|:---|:---|:---:|:---|
|Class|TextPoint|A graphic element for depicting text relative to a point|-|-|
|Attribute|offset|Specifies the offset from the anchor point|0..1|GraphicsBase::Offset|
|Attribute|rotation|Specifies the rotation angle relative to the CRS.|1|GraphicsBase::CRSAngle|
|Attribute|areaPlacement|Describes the placement of the text when the geometry is a surface.|0..1|Symbol::AreaSymbolPlacement|

**Comment by TDYCARHugh** [comment]
I am now proposing a simpler change to part 9.
 
We can achieve the ability to place text at a bearing and distance by allowing the TextPoint to be portrayed at the end of an AugmentedRay.

The only change to part 9 would be to update Figure 9-18
Add a line to the associated TextPoint table.

Role | linePlacement | Information where on a line the symbol should be placed | 0..1 | LineSymbolPlacement

And add a 'linePlacement' to the TextPoint  class S100SymbolDefinition.xsd

	
	<xs:complexType name="TextPoint">
		<xs:complexContent>
			<xs:extension base="Text">
				<xs:sequence>
					<xs:element name="offset" type="Vector" minOccurs="0" maxOccurs="1"/>
					<xs:element name="areaPlacement" type="AreaSymbolPlacement" minOccurs="0" maxOccurs="1"/>
					<xs:element name="linePlacement" type="LineSymbolPlacement" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<xs:attribute name="rotation" type="xs:double" default="0.0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

An example of a portrayal instruction on xml would be something like this:
<augmentedRay>
    <featureReference>f29</featureReference>
    <viewingGroup>26</viewingGroup>
    <displayPlane>UNDERRADAR</displayPlane>
    <drawingPriority>8</drawingPriority>
    <crs>PortrayalCRS</crs>
    <textPoint horizontalAlignment="Center" verticalAlignment="Center">
      <element>
        <text>Text</text>
        <bodySize>10</bodySize>
        <foreground>CHBLK</foreground>
        <fontCharacteristics>
          <weight>Medium</weight>
          <slant>Upright</slant>
          <serifs>0</serifs>
          <proportion>MonoSpaced</proportion>
        </fontCharacteristics>
      </element>
      <linePlacement placementMode="Relative">
        <offset>1</offset>
      </linePlacement>
    </textPoint>
    <rotationCRS>GeographicCRS</rotationCRS>
    <direction>80</direction>
    <length>10</length>
  </augmentedRay>

Then another proposal to add 'bearing' and 'distancemm' attributes to TextPlacement.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343606-bf7f59c1-60aa-4f52-b290-5a2bd1b314c0.png)

**Comment by GuttormTomren** [comment]
IALA;
This impacts text around lights etc, names on objects etc. 
Rather complicated, IHO will need to develop tools for the persons doing the placement (dragging and dropping) in cases where there are important info close to the objects.
No further comment from IALA.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. No further work from the Portrayal subWG is required. Final discussions and implementation with the DCEG subWG at the moment.
2. Will require Test Data to check performance once functionality is implemented in DDCEG and FC (1.1.0 ??).
