### ISSUE TITLE
Restricted Area Navigational vs Restricted Area Regulatory

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#31]
### Background Info:

- **DCEG 1.0.1** - The determination of whether a particular restricted area is navigational or regulatory in nature is characterised by the type(s) of restrictions that are in place within the area, as listed as allowable values for the attribute restriction for the Restricted Area Navigational or Restricted Area Regulatory. Restricted Area Navigational must only be encoded if one of the allowable values for restriction apply for the area. 
 
- **Jeff Wootton** - Should there be some visible difference between **Navigational** and **Regulatory** restricted areas (such as a slightly different colour (e.g. "lighter" magenta) for regulatory)? At the moment, in S-57, portrayal is managed by CSP RESARE04 which looks at both RESTRN and CATREA attribute values. Based on this, after S-57 to s-101 conversion, there will be some Regulatory Areas that will display the same symbology than Navigational ones.
 
- **Alvaro** - Currently, **RestrictedAreaRegulatory** rule does not link to **RESARE04** rule !?
There are now combinations of  RESTRN/CATREA and RESTRN/RESTRN S-57 attribute values that are not longer possible in S-101. Consequently S-57 ENC may depict a RESARE in a different way than the 'corresponding' S-101 feature ( Navigational or Restricted Area Regulatory).  **RESARE04** needs full review (?). 
 
- **Sylvia Spohn** - Jeff's proposal (if magenta then a light one) sounds good as no restriction to navigation, only additional information.  But to reduce magenta lines for regulated and not navigational restricted areas I would propose green limits as used for nature reserves, PSSA etc. in paper charts. Green means no restriction for navigation.

### The subWG is invited to discuss:

1. Should Rule **RESARE04** be used in **RestrictedAreaRegulatory**. If not, should ALL **RestrictedAreaRegulatory** display the same independent of the attribute values populated in **categoryOfRestrictedArea** and/or **restriction**?
2. Should it be a visual difference between the two types of restricted areas?   If yes, how would you manage their portrayal.
3. If clear visual differences between the two restricted area types is endorsed, would you consider this acceptable for implementation during the DF-ECDIS transition period?
4.  Do you agree that it is not always possible to get the same portrayal result when using RESARE04 in S-57 RESAREs and  S-101 Restricted Areas (both) due to differences in the possible RESTRN-CATREA attribute value combinations available in both standards?
                            -  Would you consider these differences acceptable during the DF ECDIS transition period?

**Comment by JeffWootton** [comment]
Regarding any visible difference between the symbology:  If there is to be any difference, I recommend that this be interms of a (slightly) lighter magenta colour only.

The principle reason that the S-57 RESARE has been "split" in S-101 to navigational and regulatory restricted areas is so as to define in the modelling/encoding a clearer distinction between those areas that require more prominent ECDIS alarms and indications (the navigational ones) and those that do not.  I therefore do not think that a clear distinction in the symbology is required.  In fact, I would not have a problem if the symbology between the two types of restricted areas remains consistent in S-100 ECDIS.

**Comment by kusala9** [comment]
If the only reason for doing the split is to minimise alarms/indications then why don't we just specify the alarm/indication with the individual category attributes, leave the feature as RestrictedArea and have a single portrayal for it? It strikes me splitting them gives us a whole bunch of migration/management headaches, expands the feature catalogue and portrayal entries all because of trying to encourage producers to minimise alarms. I don't mind if that's the actual reason but interesting reading Jeff's comments - maybe we should establish why the split is made first, then work out if the portrayal needs to change.

I don't mind if it does change BUT we need to remember any signifciant portrayal changes need communication to the user and potentially cause confusion in their minds when using S-101 data with revised portrayal catalogues - that said, if we do change the portrayal then suggest the existing portrayal is used for safety critical alerts and a new "non-critical" portrayal is adopted for RestrictedAreaRegulatory ?

**Comment by rmalyankar** [comment]
It would be quite difficult to ensure that slight differences in shade remain perceptibly different in the night and dusk color palettes as well as the day palette. If there is to be a visual difference (other than symbol fill patterns), using different boundary line styles would be the better approach.

Also, DCEG clause 17 says: _If an area is subject to both navigational and regulatory restrictions, an instance of both features Restricted Area Navigational and Restricted Area Regulatory should be encoded._  That makes the idea of slightly different portrayals problematic, particularly for area fill colors. On the other hand, if there is not a coincident Navigational RESARE it would be useful to have a distinguished portrayal for a Regulatory RESARE, especially for marine protected areas. So:

Q2: (a) Yes. (b) Boundary line styles and symbol fill patterns (I believe the latter are already done).

**Comment by TDYCARHugh** [comment]
If memory serves one of the drivers for trying to separate based on the primary purpose of Navigational or Regulatory was to simplify portrayal and alarms.  In S-52 there is a complex conditional procedure that uses a fairly complicated set of tests to determine what the main purpose of the object is based on the set of restriction vaalues and then proceed with the symbology.  Areas not to be entered are meant to have a stronger presentation than the areas which are just informational or where restrictions on specific activities (other than navigation) are in place.

**Comment by TomRichardson6** [comment]
I think its important to note that there are a number of point centered symbols that already exist and either indicate the specific restriction or a the general nature of it. For me it is these symbols which are more pertinent to users than the linestyles so noting the point from Alvaro we should review the CSP and identify where additional specific symbols can be added or improvements made to the existing ones. I think this needs end user validation but I feel whether they are regulatory or navigational is of secondary importance and that may impact the resulting alerts and indications. I guess the regulatory ones could fit within the areas for which special conditions exist so that they can be turned off. That would need more thought including how those concepts carry forward into S-100 ECDIS.

**Comment by HannuPeiponen** [comment]
I am flexible on this issue. Same symbol as for S-57 or amended version if the restriction is only "regulatory" - both are ok. My key point is that whatever is finally agreed the machine readable portrayal and alerts/indications catalogues shall correctly communicate the agreed result to the ECDIS equipment.
The S-52 already specify that RESARE object creates alerts/inidcations when value of attribute RESTRN is other than 14 and when value of attribute CATREA is other than 28. So the concept that some RESARE cause alerts/indications and some not already exist.

**Comment by DavidGrant-NIWC** [comment]
> I am flexible on this issue. Same symbol as for S-57 or amended version if the restriction is only "regulatory" - both are ok. My key point is that whatever is finally agreed the machine readable portrayal and alerts/indications catalogues shall correctly communicate the agreed result to the ECDIS equipment.

Agree.

>3. If clear visual differences between the two restricted area types is endorsed, would you consider this acceptable for implementation during the DF-ECDIS transition period?
>4. Do you agree that it is not always possible to get the same portrayal result when using RESARE04 in S-57 RESAREs and S-101 Restricted Areas (both) due to differences in the possible RESTRN-CATREA attribute value combinations available in both standards?
>    - Would you consider these differences acceptable during the DF ECDIS transition period?

I think during the transition period the goal should be a harmonized portrayal, unless there has been overwhelming user support for a change. At the least portrayal changes should be deferred until the DF concept is more fully defined.

**Comment by alvarosanuy** [comment]
To help understand the impact of the split in S-101 portrayal, I propose creating an S-57 file with all possible **RESARE** attribute combinations used by CSP RESARE04 and then converting the file to S-101.
Once done, we would be able to compare current (S-52) against new (S-101) portrayal and therefore better understand both, the impact on DF-ECDIS and the need to formulate alternative display options. 
For me, one of the main reasons to split RESARE in **RestrictedAreaNavigational** and **RestrictedAreaRegulatory** was to help with the management of Alarms/Indications. **RestrictedAreaRegulatory** features wouldn't trigger Indications (they would behave as ADMARE). They wouldn't be considered as 'areas for which special conditions exist'.
An issue with this at the moment is that, for example, RESARE/RESTRN=28 (PSSA) currently triggers an alarm/indication (S-52 Part I 10.5.10) but, in S-101, this same object can be encoded as both, **RestrictedAreaNavigational** and **RestrictedAreaRegulatory** (DCEG 17.7). In this case, the object in S-57 ENC will trigger an Alarm/Indication but the converted S-101 feature may not.

**Comment by KlasOstergren-SMA** [comment]
Agree to Christians comment about the need of agreement of principles for differences between S-52 and S-101. This is important for many of the portrayal issues. Since the transition period probably will be long, there must be some room for improvement in S-101 compared to S-52. In my opinion, if a change leads to more understandable portrayal or more relevant alarms/indications, this should be accepted if the benefit in terms of safety of navigation exeeds the disadvatige of differences in presentations during the dual fuel period.

**Comment by TomRichardson6** [comment]
Further to the comments from Christian and Klas the S-101PT 8 meeting will include an agenda item on this and a paper is expected to be submitted to S-100WG6 on this. We hope to have some parameters following the meeting to apply to these cases.

**Comment by alvarosanuy** [comment]
I attended one of IIC (Jonathan Pritchard lead) workshops in regards to a **DF-ECDIS Governance document** HSSC tasked them to prepare. I asked Jonathan to document the need to identify the authority with the power to approve S-52/S-101 differences in portrayal and alarms/indications. Particularly important when considering that we'll only be given **guidance** and therefore any recommendation will be subjective and not fully objective (black or white). It has to be written somewhere, **who** (S-101PT, S-100WG, HSSC) **has the authority to make the final call.**

**Comment by TomRichardson6** [comment]
Alvaro that is an important point and I'd argue that IEC TC80 also needs to be included. I plan to attend the next workshop. I hope that PT8 can form the PT view to raise at S-100WG6 and potentially submit that to HSSC to achieve more clarity here. Someone has to bell the cat. I envisage that we (S-101PT) will translate that guidance into some practical examples that reflect our interpretation. I met with Jonathan earlier this week and we discussed this point and am working on an alerts and indications paper that raises this issue.

**Comment by kusala9** [comment]
..."identify the authority with the power to approve S-52/S-101 differences in portrayal and alarms/indications" - ultimately the authority is IHO as the delegation to define standards comes from IMO to IHO. That said, at the workshops IEC (rightly, I think) said that power probably needs to be at HSSC level, not S-101PT nor S-100WG level. If we accept that it is HSSC itself which makes the decision then it would have to do so in consultation with all relevant bodies (IMO, IEC etc...) and be properly informed via papers which highlight the differences (which is what the WGs do). Ultimately this is no different (in terms of authority, approval etc...) than when S-52 PL is updated (which has a BIG impact on users, industry etc etc...). I think the authority question is fairly simple to answer - what's more difficult is the extent to which S-101 can deviate (even in the early days/iterations of the PC) from what the end user is accustomed (now) to seeing on the ECDIS. i'm not sure a firm guideline can be put in place though.... this is all helpful for the governance doc and I will summarise the thread in the document - also happy to chat on it offline if anyone wants...

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144343808-00d32f86-f4b3-4828-a000-51f769af0f55.png)

**Comment by kusala9** [comment]
fits with what is in the current draft of the governance document. It's ok to have "different" alerts/indications between S-57 and S-101 as long as those diferences are "improvements" - i.e things which have been remodelled and no longer meet the IMO criteria for such actions. This seems to be one of those cases...

**Comment by SylviaSpohn-BSH** [comment]
Could it be helpful to to summarize different restrictions and categories and assign different colours and linestyles to them? But we need more time to deal with this...

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Remove **RestrictedAreaRegulatory** from A&I Catalogue. Only **RestrictedAreaNavigational** to trigger Indications in ECDIS.
2. Assign **RestrictedAreaNavigational** a dedicated Viewing Group (use 26020).
3. Symbology for both type of restricted areas is to be retained as per S-52 (based on the use of CSP RESARE04).
4. Test datasets are required to compare symbology between S-52 and 'equivalent' restricted area in S-101. An S-57 dataset containing all possible **RESARE** combinations listed in CS(RESARE04) + corresponding S-101 dataset with 'equivalent' **RestrictedAreaNavigational** & **RestricetdAreaRegulatory** features.
5. Close this issue. A new issue may need to be created in the future as a result of testing outcomes.

**Comment by mikan66** [comment]
Regarding point 2 from Alvaro, "2. Assign RestrictedAreaNavigational a dedicated Viewing Group (use 26020)".  Is this the intent or rather RestrictedAreaRegulatory = 26020 and leave "as-is" RestrictedAreaNavigational = 26010?

**Comment by alvarosanuy** [comment]
> Regarding point 2 from Alvaro, "2. Assign RestrictedAreaNavigational a dedicated Viewing Group (use 26020)". Is this the intent or rather RestrictedAreaRegulatory = 26020 and leave "as-is" RestrictedAreaNavigational = 26010?

Hi Mikan - You are right, I made a mistake. The idea is to leave **RestrictedAreaNavigational** in the existing S-52 VG 26010 (Restricted Areas) and allocate **RstrictedAreaRegulatory** a new VG 26020  (within the same VG layer - 5).

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/549c08488e112b588a230787430aec4966021a97.

**Comment by mikan66** [comment]
Rev 4 test data 101AA00DS0017.000.  Clearing PC #105 TEST label.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/9042dee6-98d1-4696-b84b-2cbac38c418f)
