### ISSUE TITLE
New symbology - Rapids (Point)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#33]
The DCEG subWG has requested the Portrayal subWG to discuss new symbology for **Rapids** (DCEG 5.8) of geometric primitive type = Point.

S-52 symbology instructions for Line and Area **RAPIDS** are as follows:

Area (Plain & Symbolised) - _"RAPIDS","","AC(CHGRD)","3","S","OTHER","32050"_

Line - _"RAPIDS","","LS(SOLD,3,CHGRD)","3","O","OTHER","32050"_

**Comment by TDYCARHugh** [comment]
I remember that when S-52 was being developed the people involved questioned the significance to navigation of point features such as BRIDGE, GRIDRN, PIPSOL, PRDARE, RAPIDS, ROADWY, RUNWAY, TUNNEL, VEGATN, WATFAL.  The decision for the first cut of S-52 was to not bother making symbols and cluttering the display with these objects.  At that time it was expected that there would be feedback from real users if these features needed to be shown.  That was 30 years ago.  

I am not intending to be controversial, I am just curious.  Is the request to make symbology for point RAPIDS coming from mariner feedback?

**Comment by alvarosanuy** [comment]
@TDYCARHugh I don't think so. but I imagine that the existing workaround in the UOC is the consequence of some sort of request (!?)
One would imagine that this was discussed and approved (??) at the WG level. Why would we have some of the features you listed above with workarounds to make them visible and others not? 
Maybe **Jeff** can provide some light on the existence of a user case that was put forward in the past and justified the workaround in the UOC. 
I certainly agree that, before we create new symbols, we have to be sure that there's a need (a requirement) for them. The workaround in the UOC seems to suggest that ......

**Comment by JeffWootton** [comment]
None of the work-around's in S-57 and the requests for symbology to portray valid encoding that does not display in ECDIS has come from mariner feedback that I am aware of.  Quite a few years ago there was a paper submitted to the former C&SMWG (Colours and Symbols Maintenance Working Group - thereafter DIPWG) questioning why there was valid encoding for S-57 ENCs that does not display in ECDIS.  As I recall this was from a Member State with no reference to mariner feedback and was simply asking the question.  The WG conducted a review and suggested to the (then) TSMADWG what encoding combinations it considered warranted some form of display, from which the work-around's were developed.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344023-2a4f8f21-b724-43a4-8534-1466c55a76ff.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. No proposal has been presented by MS. Portrayal will behave as per S-52. Close this issue and create new one when/if a proposal is submitted in the future.
