### ISSUE TITLE
Display of the seaward edge of a mangrove in the intertidal area (DCEG  5.12.1)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#34]
The DCEG subWG has requested the Portrayal subWG to discuss changes to portrayal rules in order to symbolise the seaward edge of mangrove areas encoded in intertidal regions so they display using similar portrayal than **Coastline** with **categoryOfCoatsline**=7 (mangrove).
It's important to note than in S-57, the UOC instructs producers to encode COALNE (CATCOA=7; QUAPOS=4) on the seaward edge of these objects as a workaround to solve display. This encoding guidance has now been removed from the DCEG with the expectation that display will be now managed by portrayal rules.
In both, S-57 and S-101, the landward edge of the vegetation feature shares spatial with the coastline.

**Comment by DavidGrant-NIWC** [comment]
I don't understand the purpose of this requested change. The seaward edge will always be suppressed by the coastline assuming the curve geometry is shared (the coastline is always in the same or higher display plane, and always has a higher drawing priority). See S-100 9-11.1.8 Line Instruction paragraph 2:
>![image](https://user-images.githubusercontent.com/62906211/129767662-b12e4da8-ba9a-4e20-bb70-6433aff6b97a.png)

![image](https://user-images.githubusercontent.com/62906211/129764512-385d11e7-ffc3-475a-8514-a91b34d29057.png)

|Feature|Attribute|Geometry|Viewing Group|Drawing Priority|Display Plane|Line Style|Line Width|Line Color|Area Fill|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Coastline|categoryOfCoastline:7|Curve|12410|21|via RadarOverlay context parameter|dash|0.32 mm|CSTLN|-|
|Vegetation|categoryOfVegetation:7|Curve|32030|9|via RadarOverlay context parameter|dash|0.32 mm|LANDF|-|
|Vegetation|categoryOfVegetation:7|Surface|32030|9|Under RADAR|dash|0.32 mm|LANDF|VEGATN04|

**Comment by alvarosanuy** [comment]
The intent is to make the seaward edge of the **Vegetation/ categoryOfVegetation=7** to display as **Coastline / categoryOfCoastline=7**. This means dashed grey (CSTLN) line. The proper **Coastline** (boundary between Land and Intertidal) will be a continuous grey (CSTLN) line. The interior of the **Vegetation** surface will be made of a pattern (VEGATN04) of buff (LANDF) mangrove symbols.

What about adding the Boolean attribute '**inTheWater**' to **Vegetation**? This would help with portrayal and also make this **Vegetation** surface be part of ECDIS Base display (which makes sense because it is a dangerous area to be avoided). Having **inTheWater**=True could be the trigger to change the portrayal of the seaward boundary of the **Vegetation** from buff dashes to grey dashes. The overlap with the **Coastline** wouldn't be a problem because **Vegetation** would be masked out (due to **Coastline** higher display priority).

This approach would require changes to the FC and DCEG and may also require a new Validation check (Critical?) to avoid encoders from using **inTheWater**=True when **Vegetation** does not overlap **DepthArea**.

**Comment by DavidGrant-NIWC** [comment]
From S-101 DCEG v1.1.0_Working 5.12 Vegetation:
> [...] _**Where the source indicates that a mangrove area is in the intertidal area, a Vegetation feature, with attribute category of vegetation = 7 (mangroves) should be encoded on top of the intertidal area (Depth Area with attributes depth range minimum value = -H and depth range maximum value = 0 – see clause 11.7.3)). The seaward spatial type(s) of the mangrove area should have the attribute quality of horizontal measurement = 4 (approximate). The landward edge of the mangrove area should be encoded as Coastline (see clause 5.3), having no value populated for the attribute category of coastline, and no value for quality of horizontal measurement on the related spatial type(s).**_. [...]

I believe there are no technical issues with implementing the desired portrayal given the latest DCEG guidance; the portrayal can look for SpatialQuality on each curve associated with the Vegetation feature and output the appropriate drawing instruction(s).

* [ ] Need data to support testing
* [ ] Recommend adding this to the spreadsheet of remodeled items.
*  The portrayal can output drawing instructions for this feature that "splits" it into two components:
  * Vegetation in display category OTHER using viewing group 32030 (trees, vegetation, mangrove, marsh)
  * A "virtual" coastline in display category BASE using viewing group 12410 (coastline)
    * The virtual coastline will suppress portrayal of the seaward edge of the Vegetation.
    * A pick report on this coastline will show as "Vegetation", which may be confusing, especially when viewing group 32030 is off
      * This is analogous to portrayal of the safety contour, which is a virtual feature created from depth areas. A pick report on the safety contour shows the contributing depth areas. 
![image](https://user-images.githubusercontent.com/62906211/134718739-1e69772d-376d-4dc6-a6df-787ecb13317f.png)

**Comment by DavidGrant-NIWC** [comment]
### Summary of agreement at mtg:
* Change outline of **Vegetation** feature when _categoryOfVegetation_=7 (Mangroves)
  * from dashed brown (color=LANDF) to dashed grey (color=CSTLN)
  * No other changes
* No changes if _categoryOfVegetation_<>7:
![image](https://user-images.githubusercontent.com/62906211/140176876-e7f33728-d9d1-4dd1-901e-266b7605c45e.png)

### From the test data set
Top left: Vegetation.categoryOfVegetation=7
Bottom middle: Vegetation.categoryOfVegetation=21
![image](https://user-images.githubusercontent.com/62906211/140177586-265da75b-534c-4afe-b1f4-c5fc441b9202.png)

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344135-25d2930b-7951-4d23-94c3-d4b922701bb3.png)

**Comment by SylviaSpohn-BSH** [comment]
As mangroves are usually combined with the land area and if the navigation through this vegetation is not allowed or dangerous. It could be charted as land with an unsurveyed (dashed) coastline. We have the same situation with reed beds in the Baltic Sea. Or the attribute "in the water" is taken to differentiate such vegetation. For navigation issues it seems not so important and to extend the land area seems a better solution. It is also a matter of scale. Obstructions are usually artificial and man-made. Also underwater volcanos should not be charted as a category of obstruction, see #71.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Implement portrayal so **Obstructions** with **categoryOfObstruction**=23 (mangrove) are depicted as follows:
![image](https://user-images.githubusercontent.com/70189016/178646688-1bbee322-6ef4-4cdd-a5b7-ffa6fc5b6df1.png)

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by mikan66** [comment]
> **Decision made at Portrayal subWG meeting on 12/7/22**
> 
> 1. Implement portrayal so **Obstructions** with **categoryOfObstruction**=23 (mangrove) are depicted as follows:
>    ![image](https://user-images.githubusercontent.com/70189016/178646688-1bbee322-6ef4-4cdd-a5b7-ffa6fc5b6df1.png)

Implemented as:
![image](https://user-images.githubusercontent.com/4913543/197008922-8acf7106-73e0-451a-9341-c687db212a3e.png)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2

**Comment by alvarosanuy** [comment]
Can NIWC produce screenshots of an Obstruction with categoryOfObstruction=23 sitting on an intertidal area (sharing full geometry and partial overlapping)? We need to see portrayal in all ECDIS display modes. Safety Contour setting must be deeper than 0m so we can see the impact of CSP OBSTRN07 as well. According to DCEG, this category of obstruction MUST be encoded in intertidal areas only.

If test datasets are required, please submit request to Tom Richardson.

**Comment by DavidGrant-NIWC** [comment]
Using fake data (changed SeabedArea to Obstruction with categoryOfObstruction = 23)

Note:
* Safety contour suppresses boundary of mangroves when co-incident
* CSP OBSTRN07 does not apply / is not called for mangroves
  * Alerts are triggered by the underlying depth area and / or safety contour

|Safety Contour|Base|Std|Other|Notes|
|:---:|:---:|:---:|:---:|:---:|
|5|![ShoreECDIS 2022-11-02T193438Z](https://user-images.githubusercontent.com/62906211/199586207-47b965bb-7743-4ab3-bb47-01cb8db46df8.png)|![ShoreECDIS 2022-11-02T193430Z](https://user-images.githubusercontent.com/62906211/199586184-04e51f78-413a-4608-a6e9-015fe0843b23.png)|![ShoreECDIS 2022-11-02T193420Z](https://user-images.githubusercontent.com/62906211/199586163-cc72a7c2-ba47-4412-84e4-75596ef76799.png)|Safety alert highlights disabled in Base|
|0|![ShoreECDIS 2022-11-02T193244Z](https://user-images.githubusercontent.com/62906211/199586039-d72ae772-9162-43ee-aebf-8aaa855e404b.png)|![ShoreECDIS 2022-11-02T193254Z](https://user-images.githubusercontent.com/62906211/199586006-0088e637-77c9-48ad-bcaa-b17ef3f3abb7.png)|![ShoreECDIS 2022-11-02T193301Z](https://user-images.githubusercontent.com/62906211/199585958-6ae77491-15c8-4c8c-97b9-6b47402fa250.png)|Safety alert highlights disabled in Base|

**Comment by alvarosanuy** [comment]
> Using fake data (changed SeabedArea to Obstruction with categoryOfObstruction = 23)
> 
> Note:
> 
> * Safety contour suppresses boundary of mangroves when co-incident
> * CSP OBSTRN07 does not apply / is not called for mangroves
>   
>   * Alerts are triggered by the underlying depth area and / or safety contour

Looks good to me. I understand that you have Safety Alert/Highlights disabled for all features when in Base display (or is there something not working for the 'Mangrove' encoding only. Alerts/Highlight should be triggered by DEPARE/SC anyway)???

**Comment by DavidGrant-NIWC** [comment]
> I understand that you have Safety Alert/Highlights disabled for all features when in Base display (or is there something not working for the 'Mangrove' encoding only.

The alert highlights are (currently) in viewing groups 101-115, which are part of viewing group layer 10b ("Alert Highlights (Standard)"). These are part of the standard display:
![image](https://user-images.githubusercontent.com/62906211/199717408-2efae282-c7b9-4b86-8116-3e1b84f30303.png)
![image](https://user-images.githubusercontent.com/62906211/199716674-04aa401b-c9b2-47c1-b183-03d4b5303458.png)

The indication at the bottom of the screen reflects the fact that the highlights are disabled:
![image](https://user-images.githubusercontent.com/62906211/199716135-792dfc9b-a558-4a8d-b0df-39a29e3ed4e9.png)

To match S-52 we should probably move all of the alert highlights to viewing group 53010 (mariners standard). The current VG's were created to support testing of the following 61174 requirement (which is not supported by the single S-52 VG). The current viewing group numbers do not follow the convention that standard display VGs are in the range [20000, 30000) for chart elements, and [50000-60000) for mariners' elements.
![image](https://user-images.githubusercontent.com/62906211/199720436-09c1514a-e3da-4496-9506-6e9ca944f2d5.png)

> Alerts/Highlight should be triggered by DEPARE/SC anyway)???

Correct. The mangroves do not trigger an alert. Alerts will be triggered by the underlying depth area.
