### ISSUE TITLE
Limitations in the display of Sloping Ground (DCEG 5.14.1)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#35]
The DCEG subWG has requested the Portrayal subWG to discuss the symbolisation of **SlopingGround** features that are not radar conspicuous or have a **categoryOfSloppingGround** different than 6 (Cliff).
The discussion point at the DCEG subWG (and this apply to many other examples) is around having feature/attribute combinations that do not display in ECDIS but the DCEG provides guidance on how to overcome this issue by recommending the encoding of a different feature.
There are also arguments about the logic behind encoding features that are neither going to be visualized by mariners nor generate Alarms/Indications in ECDIS. If these features are considered important enough by ENC producers as to encode them in a a product, shouldn't them be visible or be able to trigger Alarms/Indications?
Maybe these 'invisible 'encoding options should be removed from the S101 Product data Modelling? Why would we encode something that nobody will notice it exists?

**Comment by DavidGrant-NIWC** [comment]
> Why would we encode something that nobody will notice it exists?

Not a comment on the specifics of the DCEG subWG proposal for Sloping Ground, but in general wrt to "invisible" features:
* So that it is available in the pick report / legend (mainly for metadata)
  * Navigational system of marks
    * ![image](https://user-images.githubusercontent.com/62906211/129752873-c0ff0c65-f116-436e-8a4c-e3b77b3ca569.png)
    *  portrays as a symbolized line, but the lines are usually on the edges of the cell and are masked so the feature becomes "invisible"
  * Data coverage
    * ![image](https://user-images.githubusercontent.com/62906211/129752737-2eb881bd-7b3c-4b91-a9ab-785254de92c6.png)
* To support autonomy
* To support GIS analysis?

**Comment by TomRichardson6** [comment]
My view on SLOGRD is that some sort of portrayal for these items should be developed for those (values 1,2,3) which are covered in S-4. Obviously symbolisation (as on paper charts) is difficult to replicate digitally I think thats' the historic reason for this situation.  In terms of this sub group we should take S-4 as our driving policy. Although if we disagree we should raise that with the NCWG. The other values could potentially be considered for removal in S-101. Its also relevant that in future paper charts may be generated from S-101 ENC so some values could potentially be present to support items symbolised on paper charts.

**Comment by hazelwestlake** [comment]
I agree that that features with values 1, 2 and 3 should have some sort of portrayal and other values removed. Currently we have lots of validation errors for S-58 test 1797 and I see that test has been replicated into new S-101 test S-101_A_166. While validation errors would be significantly reduced by S-101 allowing all cliff features, it still seems strange in a new standard, to allow an encoding that is both warned against in the DCEG, and fails a validation test.

**Comment by alvarosanuy** [comment]
S-52 Look-Up tables for SLOGRD
![image](https://user-images.githubusercontent.com/70189016/133721682-732cb83a-19fd-4a98-91e3-2571c0624200.png)

**Comment by alvarosanuy** [comment]
Some options to discuss (others welcomed):

Option 1
- [ ] Symbolise all non radar conspicuous **categoryOfSlopingGround** values as per 6 (Cliff). This is using AC(CHGRD).

Option 2 
- [ ] Symbolise non radar conspicuous **categoryOfSlopingGround** values 1 (cutting), 2 (embankment) and 3 (dune) as per 6 (Cliff). This is using AC(CHGRD).
- [ ] Discontinue the use of **categoryOfSlopingGround**= 4, 5 & 7

Option 3
- [ ] Symbolise non radar conspicuous **categoryOfSlopingGround** values 1 (cutting), 2 (embankment), 3 (dune) and 4 (Hill) as per 6 (Cliff). This is using AC(CHGRD). Note: I included Hill because it is a very common topographic feature and encoders may use it to refer to Hillocks (see INT1 C4).
- [ ] Discontinue the use of **categoryOfSlopingGround**= 5 & 7

**Comment by hazelwestlake** [comment]
Having checked some of our data, we have more features with the value 4 (hill) than expected. I would be happy with either Option 1 or 3

**Comment by Christian-Shom** [comment]
If the S-101PT considers that some feature types or attribute values are of interest for the mariner, they shoud have a portrayal. If not, these feature types or attribute values should be removed from the S-11 data model.
Tend to agree with option 3.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344216-e539cafa-6d21-4f32-8093-1f7b1648b6f2.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Implement portrayal to match S-52 look-up tables.

**Comment by MikusRL** [comment]
As per the discussions at the meeting on 12/7/22 regarding the discontinuation of the values of "5" & "7" impact on current ENC encodings and for DCEG SubWG further discussions and consideratin. As per the situation in July 2022 in PRIMAR RENC DB available ENC data: 
From bit more than 100 000 features with CATSLO encoded in bit more than 5 000 ENCs there are CATSLO "5" - 41 features in 7 ENCs (CA, CN), and CATSLO "7" - 16 features in 12 ENCs (AR, EC, GB, PT, RU). In some cases these objects have also OBJNAM encoded, including word "pingo" or "scree". 

In total affected would be 57 features in 19 ENCs. 

Disclaimer - this data is only indicative of the encoding practices, as does not include data from some HOs - either not members of the RENCs or distribution arrangements exclude the distribution through PRIMAR RENC.

Till info: @JeffWootton

**Comment by alvarosanuy** [comment]
Thanks PRIMAR for the info, we'll close this issue as per the Portrayal subWG decision (12/7/22) documented above.

Anyone pushing for the removal of categories 5 and/or 7 will have to start a new dedicated Github issue.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/76#issuecomment-1208247353
