### ISSUE TITLE
Signal generation - call and radio activated

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#38]
Some lights and fog signals can be activated by the user (mariner) by calling a number or using a radio frequency.

There are no correlating enumerates in S-57, therefore these are new attribute values in S-101.
**signalGeneration** 
5 - Radio activated
6 - Call activated

It has been proposed to use a new (to S-52) abbreviation. The abbreviation 'man' is listed as an international abbreviation in S-4 but not included in S-52.

**For S-101 ENC**
- Add text "(man)" at the end of the light description.  For fog signals, suggest adding "(man)" next to the FOGSIG01 symbol.
- Recommend including new abbreviation to S-98 Annex C (Table 36). 
- Update LightFlareAndDescription rule accordingly. 

Please provide comments.

**Comment by DavidGrant-NIWC** [comment]
Can someone take an action to:
* [ ] Add the spreadsheet of remodeled items to this repo.
* [ ] Add this item to the spreadsheet.

**Comment by alvarosanuy** [comment]
> Can someone take an action to:
> 
> * [ ]  Add the spreadsheet of remodeled items to this repo.
> * [ ]  Add this item to the spreadsheet.

See https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/23

**Comment by DavidGrant-NIWC** [comment]
Rather than adding as an attachment to an issue, recommend adding the file to the repository itself so that changes to the spreadsheet can be tracked over time.

Also, it is difficult to determine which changes have been approved for the final portrayal and which are requested as a prototype portrayal. The two implementations need to be tracked separately within the portrayal catalog so that prototypes are not added to the master branch prior to final approval.

For instance, line 17 says to update "Island Group" to display featureName.name and has an action "Allocate task to NIWC". Is this an update to the main PC, or is it a prototype which will be used by the S-101WG to determine final approval?

**Comment by TomRichardson6** [comment]
Support the proposal made here for the addition of "man" I note that the S-4 ref is B-122.1 (P56, R2) although it would be desirable to use symbols to convey this I can't come up with an appropriate and intuitive symbol, maybe others have ideas for this? clearly the use of symbols reduces cognitive load to some extent and reduces language issues.

**Comment by Christian-Shom** [comment]
Attribute "signal generation" (multiplicity (0,1) admits the following 5 values for feature Fog Signals:
1 : automatically
2 : by wave action
3 : by hand
4 : by wind
5 : radio activated
6 : call activated
The modelling seems strange to me as "by wave action" and "by wind" are "automatic" generation, whereas other values are "manual". 
I'm aware my remark is more on DCEG than portrayal, but should not this be reviewed?
Back to the initial question, I support the idea of "(man)".

**Comment by MikusRL** [comment]
Support the proposal of addition of "(man)".

**Comment by DavidGrant-NIWC** [comment]
Sub-wg agreed to add (man) when _signalGeneration_=3, 5, or 6 (by hand, radio activated, or call activated)

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344503-a8f6d685-25e3-4d04-952c-141f27e62228.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Add text (man) when **signalGeneration**=3, 5, or 6 (by hand, radio activated, or call activated)
