### ISSUE TITLE
Measured distance value (Distance mark)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#39]
Rule **DistanceMark** exists but does not use  **distanceUnitOfMeasurement**  as input to drive symbology. This rule uses SY(DISMAR03) and SY(DISMAR04) based on **categoryOfDistanceMark**.
DISMAR03 and 04 use the text '_Km_' in magenta for all instances and therefore can be confusing or misinterpreted.
In S-57 (UOC 4.4), the attribute INFORM is used to encode '_the value of distance with its unit of measurement_'. S-52 portrayal rules include INFORM, as a text string, after the point symbols (DISMAR03 or 04). 

**To discuss:**

- [ ] Should we create additional legends (symbols) to depict  the abbreviations for the other possible values of unit of measurement  (e.g 1(metres), 2(yards), 4(statute miles) and 5(nautical miles)? DISMAR03 and 04 would be retained but only used for **distanceUnitOfMeasurement**=1 (kilometres).
   **Note that**, statute miles and Yards would require their abbreviations created and included in S-98 Annex C (Table 36).
   
- [ ] Should we precede **distanceUnitOfMeasurement** with the value populated in the attribute **waterwayDistance** ? For example: _15 Km_.

**Comment by Christian-Shom** [comment]
I am of the opinion that the legend alongside the Distance mark must be consistent with what is effectively written on the mark. Consequently, the portrayal rules should be able to reproduce 1250 m, 3.45km, etc.
"Yes" to both questions.

**Comment by DavidGrant-NIWC** [comment]
### Current Portrayal
|_categoryOfDistanceMark_|Symbol|Appearance|
|:---:|:---:|:---:|
|Distance Mark Not Physically Installed|DISMAR04|![image](https://user-images.githubusercontent.com/62906211/139915251-0d66a0a9-7d7c-46f3-a276-786426f0fe93.png)|
|Visible Mark, Pole|DISMAR03|![image](https://user-images.githubusercontent.com/62906211/139915132-21e012ed-3022-43ed-8e45-0b6c8e8b7b95.png)|
|Visible Mark, Board|DISMAR03|![image](https://user-images.githubusercontent.com/62906211/139915132-21e012ed-3022-43ed-8e45-0b6c8e8b7b95.png)|
|Visible Mark, Unknown Shape|DISMAR03|![image](https://user-images.githubusercontent.com/62906211/139915132-21e012ed-3022-43ed-8e45-0b6c8e8b7b95.png)|

_measuredDistanceValue.distanceUnitOfMeasurement_ and _measuredDistanceValue.waterwayDistance_ are not used

### Proposed Portrayal
If the _waterwayDistance_ is shown then recommend:
* Update the portrayal rules to annotate using text (text color=CHMGD)
  * text could use viewing group 27030, or could use a new text group / text group layer
* DISMAR04.svg is no longer used
* Remove the "km" label from DISMAR03.svg (or discontinue use and add a new symbol)

**Comment by HolgerBothien** [comment]
The INLAND portrayal is
"dismar","","SY(DISMAR05);TX(wtwdis,3,1,2,'14106',1,-1,CHBLK,21)","7","O","OTHER","32430"
"dismar","CATDIS3|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
"dismar","CATDIS3|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
"dismar","CATDIS1|hunits3|","SY(DISMAR05);TX(wtwdis,3,1,2,'14106',1,-1,CHBLK,21)","7","O","OTHER","32420"
"dismar","CATDIS1|hunits4|","SY(DISMAR05)","7","O","OTHER","32420"
"dismar","CATDIS1|hunits5|","SY(DISMAR05);TE('%.f sm','wtwdis',3,2,2,'14109',1,0,CHBLK,21)","7","O","STANDARD","27030"
"dismar","CATDIS1|hunits6|","SY(DISMAR05);TE('%.f nm','wtwdis',3,2,2,'14109',1,0,CHBLK,21)","7","O","STANDARD","27030"
"dismar","CATDIS2|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
"dismar","CATDIS2|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
"dismar","CATDIS4|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
"dismar","CATDIS4|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"

The symbol of interest is DISMAR05

**Comment by HolgerBothien** [comment]
I cannot upload the file, so I post the content:
SYMB   10SY00001NIL
SYMD   39DISMAR05V007500075000160001600067000670
SXPO    0
SCRF    6ACHBLK
SVCT   53SPA;SW1.5;ST0;PU749,750;PD751,750;SW1;PU750,750;CI80;

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344758-0a41246f-4617-41e7-9594-3ae70bc37704.png)

**Comment by HolgerBothien** [comment]
The symbol DISMAR06 has been developed according to the action above:
[DistanceMark.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8398056/DistanceMark.zip)

**Comment by DavidGrant-NIWC** [comment]
See the two distance marks below (display on a 24" 1920x1200 monitor with no display scaling for accurate size):
![image](https://user-images.githubusercontent.com/62906211/178167681-f15db004-4e88-4308-8efb-9ae7ee218af7.png)

The distance mark symbol will not be displayed when a StructureEquipment association is present.

Some questions:
* Are these abbreviations correct: m, yd, km, sm, nm
* Should we implement the various text sizes/placements as per IENC (based on CATDIS/hunits), or just use one set of values?
  * Horizontal Justification: Left
  * Vertical Justification: Bottom or Center (Bottom used in sample)
  * X Offset: 1 * FontSize * 0.351mm
  * Y Offset: (-1 or 0) * FontSize * 0.351mm (0 used in sample)
  * FontWeight: Light
  * FontSize: 6 or 9 (6 used in sample)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Approve symbol DISMAR06 as uploaded by Holger.
2. **NIWC** to change the m to M and sm to StM in the implementation (to adhere to S-98 change proposal submitted to S100WG by Alvaro. Now passed to NCWG for discussion.)
3. **NIWC** – when the distance mark shares spatial with a physical structure, DISMAR06 symbol is not to be shown, only the text is to display. If the mark does not share spatial with a physical mark, both DISMAR06 and the text must be shown. Generated text must not clash with the existing structures other text legends, as lights, name, color, etc.
4. **NIWC** to centre align the text with the symbol when no other text is displayed. If other text (i.e. **featureName**) is present then **DistanceMark** related text should be positioned somewhere else (i.e. to the left of the symbol).
5. **NIWC** -  if the mark is associated with any kind of physical structure, then the texts are in black, but if it is not associated with the physical mark, then the texts generated are in magenta. 
6. Close this issue but a reminder that the abrreviations for Status Mile and Yards are still to be endorsed by the NCWG and added to S-98. Any changes to the proposed acronyms will have an impact on this implementation.

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by DavidGrant-NIWC** [comment]
> 2. **NIWC** to change the m to M and sm to StM in the implementation (to adhere to S-98 change proposal submitted to S100WG by Alvaro. Now passed to NCWG for discussion.)

Done.

> 3a. **NIWC** – when the distance mark shares spatial with a physical structure, DISMAR06 symbol is not to be shown, only the text is to display. If the mark does not share spatial with a physical mark, both DISMAR06 and the text must be shown.

Done. (I don't have test data with a co-located structure so the 2nd image uses a temporarily modified PC to show where the text would be placed if a co-located structure was present. The DISMAR06 symbol will not be shown in this case).
![image](https://user-images.githubusercontent.com/62906211/196804226-0cc2deaf-ddb7-4f57-9d70-880b69dcb2dd.png)
![image](https://user-images.githubusercontent.com/62906211/196809243-7602ea48-f8f1-43a1-a6c4-ea3a413e8f9f.png)

> 3b. Generated text must not clash with the existing structures other text legends, as lights, name, color, etc.

I don't see how this can be done within the portrayal. Note that there are 36 possible StructureEquipment relationships and some of these have complex label generation which may additionally be affected by their own TextPlacement associations.

For now, the label is placed on the left (with a larger offset) if there is a StructureEquipment assocation, otherwise it's placed on the right (with a smaller offset).

If more control is needed, the modelling could be updated to allow TextPlacement to specify the location of the waterway distance label.

> 4. **NIWC** to centre align the text with the symbol when no other text is displayed. If other text (i.e. **featureName**) is present then **DistanceMark** related text should be positioned somewhere else (i.e. to the left of the symbol).

The text is only placed on the left if a StructureEquipment relationship is present. Currently, featureName is never displayed for DistanceMark (although one or more co-located associated features may display featureName). See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/61#issuecomment-1284593680


> 5. **NIWC** -  if the mark is associated with any kind of physical structure, then the texts are in black, but if it is not associated with the physical mark, then the texts generated are in magenta.

Done.

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2.

**Comment by DavidGrant-NIWC** [comment]
Direction to update to abbreviations:
![image](https://user-images.githubusercontent.com/62906211/198305111-5c66274e-686f-46ae-a001-05ed395d271b.png)

**Comment by DavidGrant-NIWC** [comment]
Updated abbreviations implemented in PC 1.0.2

**Comment by mikan66** [comment]
@alvarosanuy I can only find examples with Nautical Miles in test data 101AA00DS0008, which is the final logic check in the rule DistanceMark.lua.  
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/dfff26c2-4bde-4889-a729-33316101a852)

Do we need all the other cases for testing?  I vote no as the final test for 5 should cover the logic block in the rule.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/50a20bc2-268e-48e8-b0ed-e71d25b9ee42)

**Comment by alvarosanuy** [comment]
@mikan66  - When did we say the units of measure precede the distance value? Is that how INLAND has implemented it? My first comment in this issue asked this question and the only response provided in the chat was from SHOM (Christian) agreeing on the opposite sequence (i.e. 5M not M5)?
In regards to test cases I think we need some where a physical mark shares geometry with Distance Mark.

**Comment by DavidGrant-NIWC** [comment]
> @mikan66 - When did we say the units of measure precede the distance value?

(replying for Mikan)
This was directed by:
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/e622c184-73dc-4139-abc9-5f80cdf6b883)
Source: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39#issuecomment-984228194

Should we change it?

**Comment by alvarosanuy** [comment]
> Should we change it?

Do not think so. I believe the instructions try to replicate INLAND's implementation.
Does Holger's coding included in his comment from 3 November 2021 (below) confirm my thoughts (unit before distance)??

> The INLAND portrayal is "dismar","","SY(DISMAR05);TX(wtwdis,3,1,2,'14106',1,-1,CHBLK,21)","7","O","OTHER","32430" "dismar","CATDIS3|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030" "dismar","CATDIS3|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030" "dismar","CATDIS1|hunits3|","SY(DISMAR05);TX(wtwdis,3,1,2,'14106',1,-1,CHBLK,21)","7","O","OTHER","32420" "dismar","CATDIS1|hunits4|","SY(DISMAR05)","7","O","OTHER","32420" "dismar","CATDIS1|hunits5|","SY(DISMAR05);TE('%.f sm','wtwdis',3,2,2,'14109',1,0,CHBLK,21)","7","O","STANDARD","27030" "dismar","CATDIS1|hunits6|","SY(DISMAR05);TE('%.f nm','wtwdis',3,2,2,'14109',1,0,CHBLK,21)","7","O","STANDARD","27030" "dismar","CATDIS2|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030" "dismar","CATDIS2|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030" "dismar","CATDIS4|hunits3|","SY(HECMTR02);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030" "dismar","CATDIS4|hunits4|","SY(HECMTR01);TX(wtwdis,3,1,2,'14106',1,0,CHMGD,21)","7","O","STANDARD","27030"
> 
> The symbol of interest is DISMAR05

**Comment by HolgerBothien** [comment]
No, in the comment is just an excerpt from the IENC lookup-table. 
It is not a try to replicate something it is the original implementation, just as an example.
They use distance befor unit but only if the unit is nautical or statue mile (which is a rare case in an inland environment (May be not in the US :-)) )
If the the decision has been to use unit before distance it must be adapted. I believe that this is alread made in the implementation by NWIG.

**Comment by TDYCARHugh** [comment]
I think in the IENC world these are typically called mile markers.  Mile 2, Mile 3 etc.  The question is what are the mariners used to?   If it differs in different regions then we might need a way to define a local convention or user preference.

**Comment by MikkoHovi-FI** [comment]
For paper charts the guidance is to use unit before distance.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/75314424/74ca3f04-0c8b-4c79-bf7b-8f62bc9e8faf)

**Comment by alvarosanuy** [comment]
All good, we leave implementation as is (unit followed by distance).

**Comment by mikan66** [comment]
> @alvarosanuy I can only find examples with Nautical Miles in test data 101AA00DS0008, which is the final logic check in the rule DistanceMark.lua. ![image](https://user-images.githubusercontent.com/4913543/257303301-dfff26c2-4bde-4889-a729-33316101a852.png)
> 
> Do we need all the other cases for testing? I vote no as the final test for 5 should cover the logic block in the rule. ![image](https://user-images.githubusercontent.com/4913543/257302713-50a20bc2-268e-48e8-b0ed-e71d25b9ee42.png)

@alvarosanuy, please provide thoughts on test cases or can we remove TEST label in PC issues #65?

**Comment by alvarosanuy** [comment]
@mikan66 - Leave TEST label for now and lets ask @TomRichardson6 for an updated test cell (with all possible units of measure).

**Comment by TomRichardson6** [comment]
Test Dataset 0008 Edition 7 has been enhanced to include all Units of Measure across 5 Distance Mark features. @mikan66 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0008/7

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/de8a039e-5a17-40db-ad3f-dbc0f32e6840)

Would be good to have at least one with a co-located structure to test that portrayal.

**Comment by alvarosanuy** [comment]
> Test Dataset 0008 Edition 7 has been enhanced to include all Units of Measure across 5 Distance Mark features

@TomRichardson6  - Can you please update this TDS as requested by NIWC?

- [ ] to have at least one co-located structure to test that portrayal

**Comment by TomRichardson6** [comment]
@alvarosanuy TDS0008 has now been updated to include a co-located beacon feature.

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/S-101_Test_DataSets/cells/101AA00DS0008/8

**Comment by DavidGrant-NIWC** [comment]
Looks a little odd to have the black text, but appears to be per the highlighted guidance

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a7814e99-20c4-483d-8499-a07c1a0fbb3d)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/fb98e4a6-9c99-405d-8a7e-6c5b82976acd)
