### ISSUE TITLE
New rules for ECDIS to alert and provide indications within S-101 ENCs for vertical clearances based on an air draft context parameter

### ISSUE THREAD

**Issue by richardsonaz** [S-101-Portrayal-subWG/Working-Documents#40]
[S-101PT Vertical Clearance_FINAL.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7344749/S-101PT.Vertical.Clearance_FINAL.docx)

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144344866-2f47514a-4e30-4afd-aba0-89fb8b6c3196.png)

**Comment by kusala9** [comment]
worth mentioning that S-98 Annex C contains mechanisms for adjusting water level based on S-104 which would allow ECDIS to display adjusted clearance heights but only if those clearance heights are on the same vertical datum as the S-104 (essentially the same as the sounding datum). Likely that in the future it shoudl be proposed that vertical datums/clearance should have multiplicity > 1 to enable such adjustments. This would then allow display of HW biased clearance (for many this is sufficient to establish clearance) and also an adjusted value if water level constraints exist....

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. **UKHO** to update their paper to cover the points raised by NIWC in a previous comment (15OCT2021).
2. Leave the issue open.
3. Not for PC 1.0.2 or 1.1.0.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

@TomRichardson6 - Can you please check with your UKHO colleagues and provide an update on how they want to proceed with this topic?
Please refer to my previous comment from 29/7/22 regarding the expectation that the UKHO would update their draft paper (based on NIWC's and maybe also JP's comments) and would present it for discussion at an S101PT meeting. The key question here is if the proposed changes would be suitable for the DF-ECDIS period.
**If there's no intent to pursue some changes to S101 PC and S-98, before Edition 2.0, this issue would be closed.**

**Comment by alvarosanuy** [comment]
@TomRichardson6 - Any news on this topic? Please refer to the last sentence in my previous comment.
Thanks

**Comment by TomRichardson6** [comment]
@alvarosanuy Sorry I must have overlooked this one. Yes there is no intent to include this before or in S-101 2.0.0. We consider it would only be possible after the dual fuel transition. Happy that this issue is closed and/or tagged accordingly.

**Comment by alvarosanuy** [comment]
See input from @TomRichardson6
