### ISSUE TITLE
Collision Regulations Limit

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#41]
While new in S-101, this feature may be encoded using CTNARE or ADMARE in S-57. Geometric Primitive in S-101 is Curve not Surface.

**CollisionRegulationsLimit** geo feature is defined as the demarcation line between inland navigation rules and international navigation rules. Therefore it makes sense to coordinate the symbology with the InlandENC PS (S-401). 

No guidance in S-4.

Some countries developed national symbology for paper charts as follows:

- **US** - Magenta dashed line accompanied by  'COLREGS DEMARCATION LINE' magenta text.
- **Germany** - Solid magenta line and no text.

Alvaro discussed the topic with S-401PT Chair (Gert Morlion) and he confirmed they plan to use this geo feature in their products as well. They rely on us to to develop a portrayal proposal. His initial input also supports the use of a magenta line (dashed or solid still TBD).

In order to accelerate the conversation, I propose considering:
LS(SOLD,1,CHMGD) with the text COLREG in Italics, evenly spaced every (30mm ?) and interrupting the line work. See below:
![image](https://user-images.githubusercontent.com/70189016/142296713-d7c008d9-7b49-46f9-b775-33926a478ec2.png)

Thoughts??

**Comment by DavidGrant-NIWC** [comment]
* Recommend not using S-52 notation because it makes it easy to confuse the line width.
  * Line style: solid, 0.32mm wide, using token CHMGD.
* Recommend adding the "COLREG" label as a symbol because the portrayal can't draw repeated text along the length of a line.
  * Alternative is to propose an extension to Part 9/9a to support drawing repeated text along a line.
* Due to the previous, the text will not curve with the line.
  * Recommend using a smaller symbol or shorter string.

**Comment by LeoKuzmin** [comment]
During our development of S-101 Editor we are using the following option of the CollisionRegulationsLimits depiction.
![image](https://user-images.githubusercontent.com/106175259/170281905-6912b107-b809-413e-b287-7d14dc83bb17.png)
The description of a new embedded symbol EM_COLREG and a new line pattern in attached file.
Probably it could suitable for common using
[COLREG.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8771969/COLREG.zip)
.

**Comment by SylviaSpohn-BSH** [comment]
First - in our paper charts we have a solid magenta line with a text - a long one: Seaward Delimination of the Navigable Waterways
![grafik](https://user-images.githubusercontent.com/72885087/171022129-01bb6aad-c1d0-450e-a9a0-57437d5d029c.png)

The now existing ADMARE will be changed to restricted area regulatory and should get a solid magenta line.  The information in the ENC you get only via pick report of the area so far. The text COLREG as label seems good to mark the change in regulations. But it is not clear to which side the text should be placed. Perhaps the labels could contain flexible texts? Is it planned that the label text turns if you change the reading direction?

**Comment by LeoKuzmin** [comment]
Collision Regulation Limit feature type has linear geometry type therefore text direction should be defined by the direction of the line encoding. 
As regards the encoding of Collision Regulation, in according with S-57 UOC the clause 11.13.5: "_it should be done using a narrow CTNARE object of type area (see clause 6.6) covering the demarcation line, with attribute INFORM and/or TXTDSC containing a short explanation about the regulation, (for example cautionary note from the paper chart)._" And then it could be converted to a new Collision Regulation Limit feature type of S-101.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Approve complex line style as submitted by Leo Kuzmin to this Github space on 26/5 (COLREG.zip).
2. **NIWC** - Update **CollisionRegulationsLimit** rule to use the approved symbology.

**Comment by mikan66** [comment]
Why was token "LITGN" modified to "red" from "green" in the COLREG.zip package?

**Comment by mikan66** [comment]
Fake data example:
![image](https://user-images.githubusercontent.com/4913543/182221028-74ad7941-0556-42b5-a63d-7cb95c60f396.png)

Needs proper viewing group etc but commited as this for now.
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/68793e323cb77ad27da203e9badf870725cd5c33

**Comment by mikan66** [comment]
roads feature represented with COLREG (another example): 
![image](https://user-images.githubusercontent.com/4913543/182400941-7f1b88ea-0ce6-4eaa-8b52-a795678d42fd.png)

**Comment by alvarosanuy** [comment]
> Needs proper viewing group etc but commited as this for now

New VG=25001 (Collision Regulations Limit)
DP= 4
IMO Display= Standard
Radar= S

**Comment by mikan66** [comment]
Updated Collision Regulations Limit viewing group etc, based on above. https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e86c477ed8409f7f56e7efd19ce4c6220d6e9c0a

**Comment by mikan66** [comment]
Rev 7 test data 101AA00DS0016.000.  Clearing TEST flag on PC #109.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/ed8dbc8b-188b-41ca-b75b-bb40657d7f5e)
