### ISSUE TITLE
Navigational System Of Marks - The impact of marksNavigationalSystemOf = 11 (CEVNI) in portrayal

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#42]
In S-52, the A-B pattern LC(MARSYS51) is called by the LUT when ORIENT is not populated, irrespective of MARSYS value. Problem is that LC(MARSYS51) 'Symbol explanation' in S-52 (Part I Addendum) is: _boundary between IALA-A and IALA-B systems of lateral buoys and beacons_, therefore this line pattern should be depicted as the boundary between IALA-A and IALA-B systems of marks (not just when ORIENT is missing). This reasoning is particularly important now that CEVNI has been added to S101. If the intention is to show what MARSYS applies at each side of the line, then more complex line styles should be developed and linked to the rule. 
**For example:**
If an 'IALA A' feature shares boundary with a  'No System'  feature, the boundary should only display the letter 'A' pointing inwards and not A and B. In short we need additional complex lines that cover all possible **marksNavigationalSystemOf** combinations. 
LC(MARSYS51) would be only used to depict the boundary between IALA A and B and any other boundary combination will use MARSYS51 line style BUT with a different pattern of letters: 

- IALA-A & B -  LC(MARSYS51)
- IALA-A & No System - Letter 'A'only.
- IALA-B & No System - Letter 'B'only.
- CEVNI & No System - Letter 'C' (or text CEVNI) only.
- IALA-A & CEVNI - A-C pattern.

I imagine that there's no chance for CEVNI to limit with IALA-B as the whole Europe is IALA-A

In order to support the visual identification of 'what MARSYS applies to each side of the line', LC(MARSYS51) could be re-done to have the letters A and B pointing in opposite directions. Similarly, all other complex line styles  (except when associated with 'No system') could be designed the same way.

Please note that for **LocalDirectionOfBuoyage**, it was decided to develop a new symbol for **marksNavigationalSystemOf** = 11 (CEVNI). This will be identical to DIRBOY01 but with the text CEVNI in magenta and centered below the arrow.

**Comment by DavidGrant-NIWC** [comment]
A few other points which may be relevant:
* The line is usually masked on the chart boundary, but we see that this is not always done, even when the buoyage system doesn't change (causes clutter). In this example the local direction of buoyage changes, but the buoyage system doesn't: 
![image](https://user-images.githubusercontent.com/62906211/142453722-565c3da9-c391-42bd-a0b1-ea7b5bf7521c.png)
* The legend shows the buoyage system for the cursor location, but this is only useful if someone is actively operating the ECDIS (as opposed to viewing the chart from a distance): 
![image](https://user-images.githubusercontent.com/62906211/142453878-b57dd0e5-5557-4c74-92b0-486052768a22.png)

**Comment by alvarosanuy** [comment]
Looking further into this topic I realized CEVNI uses the terminology 'right hand side of the waterway' and 'left hand side of the waterway' [https://unece.org/fileadmin/DAM/trans/doc/2010/sc3wp3/ECE-TRANS-SC3-115r4e.pdf](url). What's right or left depends if you are navigating a narrow or wide waterway or if you are entering a port within the waterway. This means that **marks navigational – system of** value 11 (CEVNI) **may** need to be remodeled and expanded to CEVNI_R and CEVNI_L (or similar). This would allow mapping the correct CEVNI DIRBOYnn point symbol version. The new CEVNI point symbol (development currently tasked to KHOA) would then require 2 variations: one with a green circle to the right of the arrow and one with a red circle to the left of the arrow. 
Not sure my interpretation  or practical applicability is right so **Please do your own digging and let us know what you think.**

**Comment by S-100ExpertTeam** [comment]
[7. CEVNI.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7826699/7.CEVNI.zip)
![image](https://user-images.githubusercontent.com/77085220/148497381-b5d995f4-e8cc-47c2-b12b-073d811f0c86.png)

**Comment by yurigangkor** [comment]
Please let us know if you have any comment.

**Comment by gert-MORLION** [comment]
> Looking further into this topic I realized CEVNI uses the terminology 'right hand side of the waterway' and 'left hand side of the waterway' [https://unece.org/fileadmin/DAM/trans/doc/2010/sc3wp3/ECE-TRANS-SC3-115r4e.pdf](url). What's right or left depends if you are navigating a narrow or wide waterway or if you are entering a port within the waterway. This means that **marks navigational – system of** value 11 (CEVNI) **may** need to be remodeled and expanded to CEVNI_R and CEVNI_L (or similar). This would allow mapping the correct CEVNI DIRBOYnn point symbol version. The new CEVNI point symbol (development currently tasked to KHOA) would then require 2 variations: one with a green circle to the right of the arrow and one with a red circle to the left of the arrow. Not sure my interpretation or practical applicability is right so **Please do your own digging and let us know what you think.**

Dear Alvaro,

There is only one 'left hande side' and 'right hand side' defined in CEVNI:

“14 bis. The designations “right-hand side” and “left-hand side” of the waterway or fairway are understood to be for
an observer facing downstream. On canals, lakes and broad waterways, the terms “right-hand side” and “left-hand
side” are defined by the competent authorities;
15. The term “upstream” means the direction towards the source of the river, including sections where the current
changes with the tide. On canals, the direction shall be determined by the competent authorities and the term “in the
direction from point A to point B” shall be used. “Downstream” means the other way around;”

Therefore there is no need for different CEVNI marking systems (L or R). It is offcourse very important to know what downstream and upstream is on a river or canal or in case of a lake it is up to the competent authority to define them. That's the reason why we (inland) decided to use the ORIENT attribute for m_nsys and to display a symbol that is triggered by the enumeration value 11 of MARSYS with an arrow in the direction of ORIENT.

**Comment by alvarosanuy** [comment]
Thanks for your comments Gert,

Would you then say that the following symbol is enough as to adequately represent MARSYS=11 (as far as ORIENT is properly populated by encoders)? Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/64.

![image](https://user-images.githubusercontent.com/70189016/164605252-d94b86d0-5c1d-4077-8981-515b3be02148.png)

**Comment by gert-MORLION** [comment]
Dear Alvaro,

In the Inland ENCs we are using almost the same symbol but without the indication 'CEVNI'. The reason for this is that CEVNI itself is not the regulation in force on most waterways in Europe, but national regulations that are based on CEVNI or use the same buoyage system as CEVNI. There is the possibility that some countries would not like to see a symbol with “CEVNI” on their IENCs.

Another difference with the inland symbol are the colors. In inland we use a red circle on the left side of the arrow and a green circle on the right side. In this way the skipper can interprete the symbol unambiguously. 

![image](https://user-images.githubusercontent.com/85863216/164727938-25fd012a-9213-4732-b5bf-7ff61417de42.png)

**Comment by SylviaSpohn-BSH** [comment]
It is difficult to depict the limit between A and B, perhaps it is not necessary to show it in the chart. More important is the direction of traffic flow.

**Comment by IngaFjellanger** [comment]
Normally the limit between IALA A and IALA B has no practical use since this border is far from shore. I have tried to take a quick look. I found one Taiwanese island close to mainland China. In 1U ENC the border is depicted, and in the harbour there are two breakwaters, one marked with a green light and one with a red light according to IALA B. In an C1 ENCs covering this island, the entire area is depicted as IALA A with a red and a white light accordingly... 

What about line between IALA A and CEVNI (or the local inland navigational system), will that be useful?

**Comment by GuttormTomren** [comment]
IALA comment, IALA have decided to move away from having a defined line in the world-map of IALA Maritime Buoyage System (MBS), but leave this to the Competent Authorities in various countries to draw the line (countries are color-coded A or B). System of marks are then coded in every ENC data cell. This github is related to inland ENC, and the MBS is related to offshore. No further comment from IALA.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Remove symbolisation from ALL **NavigationalSystemOfMarks** Surface boundaries.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9df779db6fcfe88025d1b943d404f8ada6a7316e

**Comment by LeoKuzmin** [comment]
> See [iho-ohi/S-101_Portrayal-Catalogue@9df779d](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9df779db6fcfe88025d1b943d404f8ada6a7316e)

I'm sorry, I write in the closed issue but I haven't found another place.
It looks strange that we don't depict any pattern border (MARSYS51) BUT we draw a dash line for Plane Boundary mode. 
I suppose, if we have removed symbolization from ALL **NavigationalSystemOfMarks** Surface boundaries, it would have to refer to both portrayal modes.

**Comment by alvarosanuy** [comment]
> > See [iho-ohi/S-101_Portrayal-Catalogue@9df779d](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/9df779db6fcfe88025d1b943d404f8ada6a7316e)
> 
> I'm sorry, I write in the closed issue but I haven't found another place. It looks strange that we don't depict any pattern border (MARSYS51) BUT we draw a dash line for Plane Boundary mode. I suppose, if we have removed symbolization from ALL **NavigationalSystemOfMarks** Surface boundaries, it would have to refer to both portrayal modes.

@mikan66 - Implementation must remove surface boundary symbology from both, Plain and Symbolised M_NSYS options.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/47#issuecomment-1245797229
