### ISSUE TITLE
Seagrass

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#47]
[2. Seagrass.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8203639/2.Seagrass.zip)
![Seagrass](https://user-images.githubusercontent.com/92765146/157187399-01e283c1-8e8a-46df-9e50-04eaf74377bd.JPG)

**Comment by HolgerBothien** [comment]
The symbol has issues.
There is a black path in the top left corner. Why?
No pivot point available?
The colour could be easily mistaken as AIS target. Why it is not the same colour than WEDKLP03 - CHGRD.
And finally: Sorry but this looks not very nice. I am sure, that this can be done better.
I don't know all of the discussion, but why it is necessary at all? Isn't the weed/kelb symbol not doing the job?

**Comment by TomRichardson6** [comment]
I agree with Holger's final point and question why the existing symbol cannot be used for Seagrass. I understand that Seagrass areas may have some specific restrictions for conservation but these would be shown on another feature. In other product specifications a dedicated symbol may be needed but from a navigational perspective it is not clear to me that Seagrass has special considerations that would require it to be distinguished from things like Kelp. Noting that regulatory and environmental restrictions would be carried on other features.

**Comment by yurigangkor** [comment]
![Seagrass](https://user-images.githubusercontent.com/92765146/167806794-8b1f3c6d-5d3b-4b17-aa0a-3c202dc36c87.JPG)
[#47_Seagrass.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668170/47_Seagrass.zip)

**Comment by SylviaSpohn-BSH** [comment]
The second symbol looks better but still remembers the marshy symbol C33 (an improvement of it). Should it be not closer to the weed/kelp symbol at J13.2 (proposal could be an upright symbol for seagras instead of the horizontal one for kelp)?

**Comment by IngaFjellanger** [comment]
We agree with Sylvia that the latest symbol looks better , but it still reminds us about symbol for reed or marsh.
Sea grass lives underwater. Maybe we could put a wave symbol on top of it, similar to symbol for submerged pile (K43).
![image](https://user-images.githubusercontent.com/70318960/171179600-2914d4bb-c308-485c-a6b7-abf8264a87ac.png)

**Comment by LeoKuzmin** [comment]
svg file for SEAGRASS symbol
[SEAGRASS.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9094156/SEAGRASS.zip)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Link **Seagrass** feature to the following symbol:
![image](https://user-images.githubusercontent.com/70189016/178652446-d7170475-388b-4af6-b90b-e0424048f9e7.png)

2. @IngaFjellanger to add SVG, CSS and Engineering Drawing files to this Github issue for inclusion in PC 1.1.0.

**Comment by LeoKuzmin** [comment]
![image](https://user-images.githubusercontent.com/106175259/178782035-236bd1dc-8432-4142-8ae3-2466523d5842.png)
[SEAGRASS.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9104208/SEAGRASS.zip)

**Comment by mikan66** [comment]
Is there any guidance for: ViewingGroup, DrawingPriority and DisplayPlane? Should I copy from WeedKelp?

Also, included in provided SEAGRASS.zip is a new daySvgStyle.css which includes BuoyNewDangerMarking tokens.  Do we want to include these and propagate this forward?

![image](https://user-images.githubusercontent.com/4913543/182156161-182a6044-47b8-4092-bc57-e0a35f595888.png)

**Comment by alvarosanuy** [comment]
> Is there any guidance for: ViewingGroup, DrawingPriority and DisplayPlane? Should I copy from WeedKelp?
> 

Please use same values than Weedkelp



> Also, included in provided SEAGRASS.zip is a new daySvgStyle.css which includes BuoyNewDangerMarking tokens. Do we want to include these and propagate this forward?

I imagine that was an overlook by dKart and those lines should be removed from the CSS.

**Comment by mikan66** [comment]
see commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/a4d4520f6b93832df2226a894ae38dfe94c2d278
