### ISSUE TITLE
Signal Station traffic

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#48]
[3. Signal station traffic.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204278/3.Signal.station.traffic.zip)
![Signal Station Traffic](https://user-images.githubusercontent.com/92765146/157201349-b60c62fb-8c99-40dc-9fe6-29e8789dfcc4.JPG)

**Comment by yurigangkor** [comment]
![SignalStationTraffic](https://user-images.githubusercontent.com/92765146/167806940-f592140f-43f2-40b4-b284-8f89ef13fb53.JPG)
[#48_SignalStationTraffic.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668182/48_SignalStationTraffic.zip)

**Comment by SylviaSpohn-BSH** [comment]
The traffic light symbol might be a good addition. We have the same included in our paper charts. See comment on #49

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Implement portrayal using symbol 'Symbol Signal Station Traffic' developed by KHOA (first one from the top) in PC 1.0.2. Copy any other required display values from S-52 SISTAT.
2. NIWC to use the 'traffic light' option to create screenshots in Day, Dusk & Night modes and upload to this Github alongside the same views but with the "SST' symbology. The aim is to asses display clarity and readability before making any final decisions for PC 1.1.0.

**Comment by yurigangkor** [comment]
![SST](https://user-images.githubusercontent.com/92765146/180144262-65993859-be71-42c2-852d-b820c338f06f.PNG)
[Signal.station.traffic.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9156712/Signal.station.traffic.zip)

**Comment by mikan66** [comment]
S-52 SISTAT only defines same symbol for points: SY(SISTAT02).  There is no SURFACE portrayal in S-52. S-101 will need portrayal definition for primitive type SURFACE.

Day:  1:4K scale
![image](https://user-images.githubusercontent.com/4913543/182395971-bb109b2e-bb48-40bc-b625-adc5005b408f.png)

Dusk:
![image](https://user-images.githubusercontent.com/4913543/182395774-8f972d61-1290-44ae-ad29-2adb473afdc9.png)

Night:
![image](https://user-images.githubusercontent.com/4913543/182395813-b61854d0-cc6b-4025-becb-1bf1a44a088c.png)

**Comment by alvarosanuy** [comment]
> S-52 SISTAT only defines same symbol for points: SY(SISTAT02). There is no SURFACE portrayal in S-52. S-101 will need portrayal definition for primitive type SURFACE.

By definition, this feature identifies '...  _a place onshore from which signals are made_ ...'.
Consequently, the geometric primitive Surface option would be to cater for buildings that, a very large scale, may have been captured as areas. Keeping this in mind I recommend we depict Surfaces with their boundaries unsymbolized and the Point symbol as centered in the middle of the area.

**Comment by mikan66** [comment]
For this entry 48, what is the point symbol to move forward with?  "SST" or "Stop Light" graphic?

**Comment by alvarosanuy** [comment]
> mikan66

Recommend we move forward and implement the SST symbol for PC 1.1.0

**Comment by mikan66** [comment]
Faked with "building" as SST. 
![image](https://user-images.githubusercontent.com/4913543/187279128-72953f42-38a3-4429-bc05-285270df06f4.png)

Feature highlight OFF, only "SST" displayed in surface feature
![image](https://user-images.githubusercontent.com/4913543/187279403-fe03d3b1-5a5a-4f1f-a66b-861b06129ae1.png)

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e13d70e8961a0204c231e3f021b2165ca7073c4d

**Comment by alvarosanuy** [comment]
@mikan66 - Please implement in PC 1.02 using 2022_SISTAT03.svg (to be renamed SISTAT03.svg in the PC). This new symbol added by KHOA after my post meeting comments, has addressed some concerns around the line width used in their first version. Sorry for the confusion.
I will close this issue when implemented by NIWC.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/111#issuecomment-1243777781

**Comment by alvarosanuy** [comment]
Completed in PC 1.0.2
