### ISSUE TITLE
Signal Station Warning

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#49]
[4. Signal station warning.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204296/4.Signal.station.warning.zip)
![Signal Station Warning](https://user-images.githubusercontent.com/92765146/157201532-cebda46e-429d-4924-8340-b4f28545a9e9.JPG)

**Comment by TomRichardson6** [comment]
As for my comment on Signal Station Traffic I would like to propose that we consider an actual traffic light symbol with two circles within a vertically oriented rectangle. For the warning feature circles could be filled red and orange. This symbol may be more intuitive for users and reduces the need to understand the acronym and the words in the English language.

**Comment by yurigangkor** [comment]
![SignalStationWarning](https://user-images.githubusercontent.com/92765146/167807051-bc72080a-73ea-42a4-910a-53168f8eb847.JPG)
[#49_SignalStationWarning.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668184/49_SignalStationWarning.zip)

**Comment by SylviaSpohn-BSH** [comment]
I'm not sure if the traffic sign symbol is common for SSW, too. SSW and SST should be differentiated or is SS more common and sufficient? SS(W) and SS(T) perhaps makes it clearer.

**Comment by alvarosanuy** [comment]
I prefer the first symbol with the abbreviation SST. Agree on considering traffic light for SST but if both SS  (Warning and Traffic) look alike it becomes confusing .......

**Comment by TomRichardson6** [comment]
Given the comments propose that we retain the existing symbol for warning but use the more intuitive traffic light symbol for SST. Through testing user feedback can be sought on what is preferred. Another option could be to combine the traffic light symbol with red and green for traffic but use two red for warning but add (W) and (T) as a suffix to avoid potential confusion. I am not proposing this art this stage but it could be used as part of user engagement.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Implement portrayal using symbol 'Symbol Signal Station Warning' developed by KHOA (first one from the top) in PC 1.0.2. Copy any other required display values from S-52 SISTAT.
2. NIWC to use the 'traffic light' option to create screenshots in Day, Dusk & Night modes and upload to this Github alongside the same views but with the "SSW' symbology. The aim is to asses display clarity and readability before making any final decisions for PC 1.1.0.

**Comment by yurigangkor** [comment]
![SSW](https://user-images.githubusercontent.com/92765146/180144449-d06f20bb-d0ae-4575-9d7e-ffb3c0cc5769.PNG)
[SignalStationWarning.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9156725/SignalStationWarning.zip)

**Comment by alvarosanuy** [comment]
By definition, this feature identifies '...  _a place onshore from which signals are made_ ...'.

Consequently, the geometric primitive Surface option would be to cater for buildings that, a very large scale, may have been captured as areas. Keeping this in mind **I recommend we depict Surfaces with their boundaries unsymbolized and the Point symbol as centered in the middle of the area**. Refer to Github Issue # https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/48

**Comment by mikan66** [comment]
Pics for point 2 at: https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/49#issuecomment-1184007836

Scale 1:12K.

Day: 
![image](https://user-images.githubusercontent.com/4913543/182602424-81c22122-e96d-4394-b75f-54f8ee9540cc.png)

Dusk:
![image](https://user-images.githubusercontent.com/4913543/182602452-d953c908-b307-46ce-a566-052ce9ce5762.png)

Night:
![image](https://user-images.githubusercontent.com/4913543/182602481-d7db3b5f-5de5-41af-9caf-79b6806a1886.png)

**Comment by alvarosanuy** [comment]
Recommend we move forward and implement SSW symbol for PC 1.1.0

**Comment by mikan66** [comment]
Faked with Building, point and area. 
![image](https://user-images.githubusercontent.com/4913543/187419442-bd5f3cc4-cafd-41fe-9ad8-b93f16061d1b.png)

No area highlight, centered symbol
![image](https://user-images.githubusercontent.com/4913543/187419548-cc7add4a-b668-445b-b239-653eb8437c60.png)

See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/112#issuecomment-1231517001

**Comment by alvarosanuy** [comment]
@mikan66 - Please implement in PC 1.02 using 2022_SISTAW03.svg (to be renamed SISTAW03.svg in the PC). This new symbol added by KHOA after my post meeting comments, has addressed some concerns around the line width used in their first version. Sorry for the confusion.
I will close this issue when implemented by NIWC.

**Comment by mikan66** [comment]
See corrected symbol name in rule at commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/112#issuecomment-1241170735

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2
