### ISSUE TITLE
Grouping of Soundings in ENC Updates

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#5]
**S-101PT5 Action 20** - Discuss paper S-101PT5-17

[S-101PT5_2020_17_EN_Grouping of Soundings in ENC Updates_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290016/S-101PT5_2020_17_EN_Grouping.of.Soundings.in.ENC.Updates_V1.pdf)

**Comment by DavidGrant-NIWC** [comment]
Sounding feature has the attributes shown below. It has an association to a pointSet, where each Z coordinate encodes the depth. Changes to a soundings attribute values affect all the associated points. Changes to the spatial associated with a sounding may affect individual points.

Need to clarify what should happen in the following cases:
- Feature
    - Add
    - Change an attribute value
    - Delete
- Spatial
    - Add one or more points
    - Move one or more points (x, y)
    - Modify depth (z)
    - Delete one or more points

**Sounding Attributes**:
![image](https://user-images.githubusercontent.com/62906211/95374112-ed623c00-08ab-11eb-92ef-aecc6f7cf261.png)

**Comment by alvarosanuy** [comment]
Refer to Draft document S-98 Annex C '**Harmonised Portrayal for ECDIS and INS**' section C-14.11' (a copy is available from the home page of this Github repository).
The practical implementation of the **UpdateInformation** feature may make this proposal irrelevant although we think is still recommendable not to group soundings published as part of an ENC update  (with other groups or as a new group). If supported, this recommendation should be passed to the DCEG subWG for consideration and action.
Additionally, we recommend that special attention is payed to these scenarios when developing and testing S101 ENC Updates in S100 ECDIS.

**Comment by DavidGrant-NIWC** [comment]
S-52 (and S-98 C-14.11.1) also requires marking of manual updates, so **UpdateInformation** does not completely resolve this issue.

Recommend addressing issue via update to S-98 C-14.11. The GFM allows a feature to have multiple spatials; this should be addressed in the guidance.

![image](https://user-images.githubusercontent.com/62906211/95592041-1a326280-0a16-11eb-9efe-f5017d03c65b.png)

**Comment by SylviaSpohn-BSH** [comment]
From the view as ENC producer we would be happy to keep the funcionality of grouping soundings in ENC updates. But I can't estimate the technical effects or problems.

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144327452-df2c7c6f-6067-492e-bbe0-1b6c8922cb5d.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Close this issue and open a new one to focus the discussions on **UpdateInformation** - expected behavior in ECDIS and portrayal options.
2. Await for the development of test data as requested by S-101PT Action PortSG-73.
3. Request S101PT Chair to submit a proposal to the Singapore's Lab to engage mariners to discuss and recommend their preferred implementation of the ECDIS' '_Review Update_' function.
