### ISSUE TITLE
Area of Piles

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#51]
[6. Area of Piles.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204313/6.Area.of.Piles.zip)
![Area of Piles](https://user-images.githubusercontent.com/92765146/157201812-7221e405-740d-4f5a-b9b1-095aba044853.JPG)

**Comment by SylviaSpohn-BSH** [comment]
The symbol is self-explanatory, but see comment to #53. Could it be possible to add a centred pile symbol in a circle in the centre of the polygon (also useful for small scales)?

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**
This **categoryOfPile** should only be used for geometric primitive Surface and Point (as per DCEG extract below)

![image](https://user-images.githubusercontent.com/70189016/180100471-89743ece-f95a-45f9-85ad-498c87df09bb.png)

Despite this, portrayal implementation below recommends (just in case) linking Curve as well (which will effectively display as 'Piling' - **categoryOfPile**=5).

1. Approve implementation of complex line style as uploaded by KHOA to this Github space.
2. Use new complex line for Curves and Surfaces (_Plain_ and _Symbolised_ boundaries).
3. For Point geometry use existing S-52 symbol (PILPNT02).
4. Update rules accordingly [**Piles**; **categoryOfPile**=6 (area of piles)].

**Comment by yurigangkor** [comment]
![Areas of Piles](https://user-images.githubusercontent.com/92765146/180146459-ea813228-c45b-46c8-b03a-b2a1c7c9ac20.PNG)
[Area of Piles.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9156805/Area.of.Piles.zip)

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by DavidGrant-NIWC** [comment]
Implemented, but please verify:
* [x] "OverRADAR" is the correct display plane
* [x] DrawingPriority = 15
* [x] ViewingGroup = 12410 (Base Display)
* [x] Name = Piles
* [x] Description = Area or row of piles
* [x] There is no centered point symbol associated with the area. Areas typically have centered symbols to account for the case where the edges of the area are not visible on the display.

Note that the category of pile doesn't matter within portrayal - if it's encoded as a curve or surface it will be symbolized using the linestyle without regard for _categoryOfPile_.

No real test data, but simulated using an island:
![image](https://user-images.githubusercontent.com/62906211/189213909-e1ce685a-a7b7-48d3-b07c-103065295d15.png)

**Comment by alvarosanuy** [comment]
> * There is no centered point symbol associated with the area. Areas typically have centered symbols to account for the case where the edges of the area are not visible on the display.

This has been consciously decided in our last PsWG meeting and the reasoning recorded in the minutes.
