### ISSUE TITLE
Moire Effect

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#52]
[8. Moire Effect.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204322/8.Moire.Effect.zip)
![Moire Effect](https://user-images.githubusercontent.com/92765146/157201963-3bdfd972-ff9d-4be4-854b-516cea0a7478.JPG)

**Comment by TomRichardson6** [comment]
Support this symbol which is consistent with the paper chart symbology in S-4.

**Comment by yurigangkor** [comment]
![MoireEffect](https://user-images.githubusercontent.com/92765146/167807182-827bdeab-a953-4cd2-90d8-260500ae66a8.JPG)
[#52_MoireEffect.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8668195/52_MoireEffect.zip)

**Comment by SylviaSpohn-BSH** [comment]
The second symbol is closer to INT1 P31. I agree to reduce the distance between triangle and circle. Could the line weight of the outer circle perhaps a bit reduced (semi-bold)?

**Comment by IngaFjellanger** [comment]
Is there a particular cause for using colour MARMG instead of CHMGD?

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. **KHOA** to produce a new version of the symbol as follows:
- Rename symbol as MOIRE01
- change colour to CHMGD
- reduce the thickness of the circle to 0.32.

**KHOA** to upload latest SVG, CSS and Engineering Drawing files to this Github issue.

**Comment by yurigangkor** [comment]
![Moire Effect](https://user-images.githubusercontent.com/92765146/180144835-390b12c7-947b-4f39-8d60-f313579423b6.PNG)
[MoireEffect.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9156746/MoireEffect.zip)

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/f4124912688383e05c8552f38f8685bd5fe5e820
