### ISSUE TITLE
Tank Farm

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#54]
[10. Tank Farm.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204332/10.Tank.Farm.zip)
![Tank Farms](https://user-images.githubusercontent.com/92765146/157202266-9d2666ad-1853-4f72-9b71-8f6ce880741c.JPG)

**Comment by SylviaSpohn-BSH** [comment]
Could agree partly: the bottom right circle seems to small compared to the other 3 circles and the line weight of the outer circle is not big enough, see RENERG01 at #67

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. KHOA to create a new version of the proposed symbol as follows:
- use a larger circle diameter [as per SY(ENTRES51) - 9.94mm].
- fix the size of the bottom right circle to match the rest.
Upload new files (SVG, CSS and Engineering Drawing) to this Github space.

2. Use LC(NAVARE51) for _Symbolised_ boundaries and S-52 instruction LS(DASH,2,CHGRD) for _Plain_ boundaries.

**Comment by yurigangkor** [comment]
![Tank Farm](https://user-images.githubusercontent.com/92765146/180145061-cc912737-4324-434e-a6cf-5c6eeffa3a96.PNG)
[Tank.Farm.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9156757/Tank.Farm.zip)

**Comment by mikan66** [comment]
Tank Farm only, (needs test data) commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/7a9626591a0df09a47a25cb6550c16d4df10e149

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1238024384
