### ISSUE TITLE
Wave Farm

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#55]
[12. Wave Farm.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204345/12.Wave.Farm.zip)
![Wave Farm](https://user-images.githubusercontent.com/92765146/157202510-0822b62e-5a1d-48b6-bae4-ade3005f905e.JPG)

**Comment by KlasOstergren-SMA** [comment]
Not sure if this symbol is needed. The symbol created in #67 is similar to the L6 symbol in S-4, which is used for both wave and solar farms. I prefer to use that one instead of this.

**Comment by SylviaSpohn-BSH** [comment]
There is an risk of confusion with symbol H 44 overfalls. Suggest to take a symbol close to L5/L6.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Use the final version of the _renewable energy_ symbol created in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/67 as a center symbol for the Surface. Wait for latest files (SVG, CSS and Engineering Drawing) to be upload by Mikus (he was tasked to create a larger version of the symbol initially posted in that space).
2. Use LC(NAVARE51) for _Symbolised_ boundaries and S-52 instruction _LS(DASH,2,CHGRD)_ for _Plain_ boundaries.

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1238024384

**Comment by alvarosanuy** [comment]
Rule updated by NIWC - Close this issue.
