### ISSUE TITLE
Pilotage district

### ISSUE THREAD

**Issue by yurigangkor** [S-101-Portrayal-subWG/Working-Documents#57]
[14. Pilotage district.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8204355/14.Pilotage.district.zip)
![Pilotage district](https://user-images.githubusercontent.com/92765146/157202710-cfc6fd70-26eb-4fc5-9c87-c87d83a98472.JPG)

**Comment by TomRichardson6** [comment]
Given that the point symbol used here is identical to the Pilot Boarding Place symbol suggest that some sort of modification to the symbol should be used to distinguish the district from specific pilot boarding locations. Enclosing the symbol within a box or reducing the size of the symbol could be means to achieve this.

**Comment by IngaFjellanger** [comment]
XML file 2021_PilotageDistrict as included in this issue, will only create 2 dashes between the PILBOP02 symbols. Picture shows 4 dashes which we think is better. 
Following Tom Richardson’s comment we suggest the related symbol PILBOP02 should be scaled at least 0.8. 
![image](https://user-images.githubusercontent.com/70318960/170027231-48c7db2c-9983-462b-a801-d18eda99ae78.png)

**Comment by IngaFjellanger** [comment]
We suggest to add a line pattern PILDSTR1 as:
```
<?xml version="1.0" encoding="ISO-8859-1"?>

<?S100lineage source="S52Preslib4.0" format="S100Ed2" version="0.1" creationDate="2022-04-07"?>
<?S100Meta name="PILDSTR1" exposition="boundary of an Pilotage District area"?>
<lineStyle>
   <intervalLength>38</intervalLength>
   <pen width="0.32">
      <color>TRFCF</color>
   </pen>
   <dash>
      <start>2</start>
      <length>6</length>
   </dash>
   <dash>
      <start>16</start>
      <length>6</length>
   </dash>
   <dash>
      <start>24</start>
      <length>6</length>
   </dash>
   <dash>
      <start>32</start>
      <length>6</length>
   </dash>
   <symbol reference="PILBOP02">
      <position>12</position>
      <scaleFactor>0.8</scaleFactor>
   </symbol>
</lineStyle>

```

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. Approve the complex line style as proposed by dKart (Inga) - 4 dashes and smaller (80%) PILBOP02 symbol version.
2. **Inga** - Upload new SVG, CSS and Engineering Drawing files to this Github space.

**Comment by IngaFjellanger** [comment]
Hi, 
We have created 2 options.
1.  The PILBOP02 symbol is used with scale 0.8 in the line style PILDSTR1.xml file. 
2. A new symbol EMPILDST which is created from PILBOP02 and scaled on 0.8. This symbol is used directly in the line style PILDSTR1.xml

Which option do you want us to upoad?

**Comment by alvarosanuy** [comment]
> Hi, We have created 2 options.
> 
> 1. The PILBOP02 symbol is used with scale 0.8 in the line style PILDSTR1.xml file.
> 2. A new symbol EMPILDST which is created from PILBOP02 and scaled on 0.8. This symbol is used directly in the line style PILDSTR1.xml
> 
> Which option do you want us to upoad?

@DavidGrant-NIWC  - Any preference?? Option 1 would mean we do not need to register a new point symbol (EMPILDST) ....

**Comment by IngaFjellanger** [comment]
[Pilotage.district.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9444449/Pilotage.district.zip)
Uploaded option 1

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/94#issuecomment-1233211020
