### ISSUE TITLE
Virtual AIS Aids to Navigation

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#59]
Symbols created by 7Cs. Thanks Holger.

https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON01.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON02.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON03.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON04.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON05.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON06.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON07.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON08.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON09.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON10.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/VATON11.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/daySvgStyle.css

**Comment by alvarosanuy** [comment]
From Holger regarding 'Preferred Channel' marks:

I have checked how lateral marks with CATLAM 3 and 4 (preferred channel to port – starboard) are portrayed in S-52.
The use one of the symbols: BOYLAT13, BOYLAT14, BOYLAT23, and BOYLAT24. (simplified Lookup table)
These are exactly the symbols on which the new symbols VATON05, VATON06, VATON07, and VATON08 are based on.
So, there is no need to have different symbols for Preferred Channel marks since if there is no difference for the real navaids. Why there should be a difference for the virtual ones?

**Comment by HolgerBothien** [comment]
[VirtualAtoN.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8371186/VirtualAtoN.zip)
Please find the symbols and a word document with details and engineering drawings in the attached zip archive.
Note that the symbols are also in the code section of this GitHub repository.

**Comment by alvarosanuy** [comment]
A new buoy symbol is now proposed for Buoy New Danger Marking (refer to Github #   https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/46).

I propose we consider developing a V-AIS version for this mark, different to the one used in S-52 (which is identical to Special Purpose mark). Something like:

![image](https://user-images.githubusercontent.com/70189016/161165438-a616f2a6-597e-424a-a7d6-1cd3b7d2dc1c.png)

**Comment by DavidGrant-NIWC** [comment]
Adding this symbol here (currently it's only in #46). This issue (#59) is for feature VirtualAISAidToNavigation, whereas #46 is for feature BuoyNewDangerMarking.

[Virtual AtoN - New Danger Marking symbol](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8395819/New.danger.zip)

![image](https://user-images.githubusercontent.com/62906211/165325609-f96b9e80-04a5-4001-ab8b-14fd0d42df4b.png)

**Comment by IngaFjellanger** [comment]
1. We suggest to decrease magenta circle to a diameter of 8mm. This will improve readability of both this symbol and ECDIS rhombus. Suggestion: Set radius of magenta circle equal to 4 mm for all symbols of Virtual AIS Aid to Navigation features.
2. We suggest renaming symbols for Virtual AIS AtoN according to type of AtoN instead of their values. It simplifies the handling of the symbols files and analyze drawing instruction during implementation of PC.
Suggestion:
Rename symbols according to virtualAISAidToNavigationType
VATON01 -> VAISCAR01
VATON02 -> VAISCAR02
VATON03 -> VAISCAR03
VATON04 -> VAISCAR04
VATON05 -> VAISLAT05
VATON06 -> VAISLAT06
VATON07 -> VAISLAT07
VATON08 -> VAISLAT08
VATON09 -> VAISISD09
VATON10 -> VAISSAW10
VATON11 -> VAISSPP11
VATON12 -> VAISNDM12 where
![image](https://user-images.githubusercontent.com/70318960/169977587-1dd0cad4-620f-4288-abe3-8a293926034d.png) or ![image](https://user-images.githubusercontent.com/70318960/169977615-6de19ccf-a137-4019-beb9-9dd8f517a12c.png)

**Comment by GuttormTomren** [comment]
Various marks/symbols are presented, based on existing marks.  A new proposal is made for the EWMB. Preferred channels marks are identical to the regular port/starboard mark, we asume that a pick report will separate these marks (when the symbols are identical). Size and font issues to be decided by IHO. 
![image](https://user-images.githubusercontent.com/93490864/172781696-37d5aeb3-25f3-4e62-ae8b-4cd573f78d8c.png)


 
If possible, dedicated symbols should be consideres developed. Image from IALA MBS.

**Comment by DavidGrant-NIWC** [comment]
In S-52 these are symbolized using NEWOBJ, which means that the following attributes are associated with the symbol:

viewing group: 21020 - Generic object (NEWOBJ1)
display priority: 18 (6 in S-52)
display plane: under radar

For S-101, at a minimum a new viewing group should be agreed upon and registered. For now we will implement using 21020.

**Comment by HolgerBothien** [comment]
[VATON00.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9095154/VATON00.zip)
The symbol for a general / unknown type virtual AIS

**Comment by alvarosanuy** [comment]
Refer to https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/37 

> **Decision made at Portrayal subWG meeting on 12/7/22**
> 
> 1. Implement using Virtual AIS symbols generated by Holger and included in [Virtual AIS Aids to Navigation #59](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59)
> 2. Holger to develop an additional V-AIS symbol (circle with grey infill) that will display with a small magenta question mark (bottom right) to link possible instances of **VirtualAidsToNavigation** having **virtualAidsToNavigationType**=Unknown.
>    SVG, CSS and Engineering Drawing files to be uploaded to [Virtual AIS Aids to Navigation #59](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59)

**Unrelated Decision regarding the comment below:**

1. Create new Github issue to discuss possible changes to the existing symbology for **categoryOfLateralMark** 3 (preferred channel to starboard lateral mark) and 4 (preferred channel to port lateral mark) so they depict more like INLAND ENC symbols. If implemented, changes should flow to **virtualAISAidToNavigationType** values 7 & 8 (?). 

> Various marks/symbols are presented, based on existing marks. A new proposal is made for the EWMB. Preferred channels marks are identical to the regular port/starboard mark, we assume that a pick report will separate these marks (when the symbols are identical). Size and font issues to be decided by IHO. ![image](https://user-images.githubusercontent.com/93490864/172781696-37d5aeb3-25f3-4e62-ae8b-4cd573f78d8c.png)
> 
> If possible, dedicated symbols should be considered developed. Image from IALA MBS.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/51#issuecomment-1234167581
