### ISSUE TITLE
Category of Landmark=25 - Torii

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#60]
Symbols created by 7Cs. Thanks Holger.

https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/TORII01.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/TORII11.svg
https://github.com/S-101-Portrayal-subWG/Working-Documents/blob/master/daySvgStyle.css

**Comment by HolgerBothien** [comment]
[TORII.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8371496/TORII.zip)
Please find attached an archive with two symbols and a word document with details and engineering drawings.
Note that two symbols have been developed to disinguish between non-conspicuous and visual conspicuous objects.
This is done for all other landmark symbols.
Note that the symbols are also in the code section of this GitHub repository.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Accept the symbols TORII01 and TORII11 as uploaded by Holger to this Github space and link them to **categoryOfLandamrk**=25 (torii). TORII11 is for when **visualProminence**=1 (visually conspicuous)

**Comment by mikan66** [comment]
Simulation of "towers" as "torii", but what is the rule for **categoryOfLandmark**=25 (torii) and  **visualProminence** is Unknown?  This question also applies to all Landmark categories that map back to S-52 with visualProminence unknown and any other attribute combination for this feature with categoryOfLandmark defined.  

Example: From S-52:  LNDMRK    CATLMK13CONVIS1    SY(MONUMT12)
What about this situation?  LNDMRK    CATLMK13CONVIS_UNKNOWN    SY(MONUMT12)

Is below the general assumption for any additional attribute combination of "unknown" that didn't have a defined value in S-52?
LNDMRK    CATLMK13    SY(MONUMT02)

If above is the general case for unknown attributes with a defined **categoryOfLandmark** then I just need the definition for:
LNDMRK    CATLMK25    ????????


![image](https://user-images.githubusercontent.com/4913543/182680939-b70bd05d-e00d-4e77-a83c-dc313c52840e.png)
![image](https://user-images.githubusercontent.com/4913543/182680992-c3725f45-1316-4605-adde-e0a03a40be93.png)

**Comment by alvarosanuy** [comment]
> Simulation of "towers" as "torii", but what is the rule for **categoryOfLandmark**=25 (torii) and **visualProminence** is Unknown? This question also applies to all Landmark categories that map back to S-52 with visualProminence unknown and any other attribute combination for this feature with categoryOfLandmark defined.
> 
> Example: From S-52: LNDMRK CATLMK13CONVIS1 SY(MONUMT12) What about this situation? LNDMRK CATLMK13CONVIS_UNKNOWN SY(MONUMT12)
> 

**In general terms**:

**_Example_:**

CATLMK13CONVIS1 displays SY(MONUMT12)
CATLMK13                displays SY(MONUMT02) - This entry caters for CONVIS=2 or Unknown (anything but CONVIS1) and, of course, for any other possible attribute value encoded in any other attribute for the feature.

For Torii and any other **categoryOfLandmark**, the above principle must apply.
When **visualProminence** =2, 3 or Unknown the 'Buff colour' symbol version (not visually conspicuous) must display.

Symbol TORII01 is the one to link to LNDMRK CALMK25 (refer to my post meeting comment 14/7 above).

**Comment by mikan66** [comment]
See commit [7209222](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/7209222a97105e1aaf3387b4cac1da3045ab3462)
