### ISSUE TITLE
Observation Wheel

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#62]
Observation wheel, conspicuous and non conspicuous. Entry P_15 from  S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx.

**2022-06-02**: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix) plus two new symbols as per the second image:
[P_15_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8826739/P_15_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/171706071-73ecd7a5-f66f-475c-937b-42a54afe32ae.png)
![image](https://user-images.githubusercontent.com/72803214/171706561-b5374f18-ed17-4522-be12-b4d466ba5b18.png)

**2022-06-02** Update. Additional symbol for discussion created based on the idea in the comments. Symbol .svg files added to the above .zip file.
![image](https://user-images.githubusercontent.com/72803214/171703413-57d9c6ea-85d1-4d68-a946-46bb0be0bcd1.png)

**Comment by SylviaSpohn-BSH** [comment]
If the symbol is really necessary suggest to simplify it to a circle on the triangle without gondolas.

**Comment by MikusRL** [comment]
I have updated .svg files in the .zip file in initial comment for NIWIC comment fix.

And thank you Sylvia, was not too satisfied with my initial symbol, too much going on. Have created a simplified versions too. For discussion to the group.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Accept the symbols FERWHL03 and FERWHL04 as uploaded by Mikus to this Github space and link them to **categoryOfLandmark**=24 (observation wheel). FERWHL03 is for when **visualProminence**=1 (visually conspicuous).

**Comment by mikan66** [comment]
Tower as wheel and visually conspicuous
![image](https://user-images.githubusercontent.com/4913543/184357560-82c89d38-daa2-448e-9e41-953e04a8cec3.png)

Tower as wheel and NOT visually conspicuous
![image](https://user-images.githubusercontent.com/4913543/184357655-2cf14f18-1608-4d16-8573-7ab05bd3c29a.png)

See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/0eb269795300dae9e7f2754e21a3afc8959f9cbc

**Comment by TomRichardson6** [comment]
An update has been applied to TDS0007 so that Edition 6 now includes an Observation wheel (visually Conspicuous). The datasets do not cover visually conspicuous and not visually conspicuous for all combinations. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0007/6
