### ISSUE TITLE
Current Farm

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#63]
P_10 point symbol generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx.

2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_10_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8826254/P_10_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160711570-68b03ce3-f9cc-48a9-be69-bf7857ecdf16.png)

**Comment by SylviaSpohn-BSH** [comment]
Agree to the symbol, but wonder if the energy symbol is not in black comparable to the dangerous wreck symbol?

**Comment by MikusRL** [comment]
This was the task from the spreadsheet document: "_Develop New 'underwater current turbine' symbol (as per INT1 L6) in CHGRD colour but depicting circle using danger line instead of continuous line._" If needed, I am happy to create all black symbol version too. At the moment colour is black for the dots, and grey for the center symbol.

**Comment by MikusRL** [comment]
I have updated .svg file in the .zip file in initial comment for NIWIC comment fix.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Use the final version of the _renewable energy_ symbol created in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/67 as a center symbol for the Surface. Wait for latest files (SVG, CSS and Engineering Drawing) to be upload by Mikus (he was tasked to create a larger version of the symbol initially posted in that space).
2. Use LC(NAVARE51) for _Symbolised_ boundaries and S-52 instruction _LS(DASH,2,CHGRD)_ for _Plain_ boundaries.

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1238024384

**Comment by alvarosanuy** [comment]
Rule updated by NIWC - Close this issue.
