### ISSUE TITLE
Local Direction of Buoyage CEVNI

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#64]
P_9 point symbol generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx

2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_9_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8826211/P_9_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160715593-fd8a7506-6b67-4857-9b97-a23b37a55564.png)

**Comment by SylviaSpohn-BSH** [comment]
agree to symbol

**Comment by IngaFjellanger** [comment]
Based on what I read on https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/42 , I would prefer red and green dots

**Comment by MikusRL** [comment]
I have updated .svg file in the .zip file in initial comment for NIWIC comment fix. 

Discussion: would there be a need then for two more options - red and green and green and red? Or is CEVNI alwaus only one for the two?

**Comment by alvarosanuy** [comment]
1. When **marksNavigationalSystemOf**=1 and **orientationValue** has a value, display SY(DIRBOYA1). As per S-52.
2. When **marksNavigationalSystemOf**=2 and **orientationValue** has a value, display SY(DIRBOYB1). As per S-52.
3. When **marksNavigationalSystemOf**=11 (CEVNI) and **orientationValue** has a value use SY(DIRBOYA1).
4. When **NavigationalSystemOfMarks**=9 or is not populated & **orientationValue** has a value, display SY(DIRBOY01). As per S-52.
5. _**If possible to encode**_ and both **NavigationalSystemOfMarks** and **orientationValue** are not populated (Unknown) then NO symbolisation is to be portrayed. As per S-52.

**Comment by mikan66** [comment]
Point 5 (above): "If possible to encode and both NavigationalSystemOfMarks and orientationValue are not populated (Unknown) then NO symbolisation is to be portrayed. As per S-52." 

Current Lua rule for point 5 above agrees with S-52 and displays line instruction "MARSYS51".  I assume this is to be maintained "as-is" or removed so there is absolutely nothing displayed (this would not agree with S-52)?

See PC commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/100538c1437f974f1980dea04380b3b7a62e2b40

**Comment by alvarosanuy** [comment]
> Point 5 (above): "If possible to encode and both NavigationalSystemOfMarks and orientationValue are not populated (Unknown) then NO symbolisation is to be portrayed. As per S-52."
> 
> Current Lua rule for point 5 above agrees with S-52 and displays line instruction "MARSYS51". I assume this is to be maintained "as-is" or removed so there is absolutely nothing displayed (this would not agree with S-52)?
> 
> See PC commit [iho-ohi/S-101_Portrayal-Catalogue@100538c](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/100538c1437f974f1980dea04380b3b7a62e2b40)

The decision at the meeting was to discontinue the use of LC(MARSYS51) to symbolise Surface boundaries. Consequently, scenarios where **NavigationalSystemOfMarks** and **orientationValue** are not populated, must not portray at all.
A Validation test to identify these (bad) encoding practices would be helpful ....

**Comment by mikan66** [comment]
LC(MARSYS51)  will be replaced with 'NullInstruction' to support Pick Report. remove LC(MARSYS51): https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/0dbf824bae83ee65b825e49937ceac979675abd3

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/f395ee191a798aef3bcc10d4943a405c524922ce
