### ISSUE TITLE
Foul ground boundary and line element

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#65]
P_8 point symbol generated from the spreadsheet:  S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx
[P_8.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8375371/P_8.zip)
![image](https://user-images.githubusercontent.com/72803214/160717390-30377796-5139-4688-a388-dc7b02a2cb18.png)

2022-06-01. Updated. Fixed y coordinate for symbolBox in .svg file and updated Symbol Explanation in the Word table, which also goes in the .svg file as 
"...desc>Area of foul ground (safe for navigation but not for anchoring) boundary</desc..." 
[P_8_20220601.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8817802/P_8_20220601.zip)
![image](https://user-images.githubusercontent.com/72803214/171470087-a47e560f-7170-4bec-a292-371f8aca200a.png)

**Comment by IngaFjellanger** [comment]
This central symbol above we agree with. The line style of the borders are not mentioned here.

**Comment by DavidGrant-NIWC** [comment]
Note: the symbolBox for this symbol is incorrect - it disagrees with the svgBox/viewBox. See related PC issue: [#84](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/84)

**Comment by SylviaSpohn-BSH** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bn22/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bn22/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Agree to symbol, explanation was already changed from foul area (unsafe for navigation) to area of foul ground (safe for navigation).
--




</body>

</html>

**Comment by MikusRL** [comment]
I will update this symbol for David comment. @alvarosanuy please do not yet upload this exact one to the registry. I will also then check others. Hope this is the only one where this minus sign has gone missing. Please give me a day at least for that to check. Thanks.

@SylviaSpohn-BSH Not sure if I understand correctly your comment - do you want me to update the Symbol Explanation entry in the table above to "Area of foul ground (safe for navigation)"? Thanks.

**Comment by SylviaSpohn-BSH** [comment]
@Mikus: Yes, you're right. Foul **area** is the wrong term. Foul area is very dangerous for navigation. It should read "foul ground area" or better to what you proposed.

**Comment by MikusRL** [comment]
@SylviaSpohn-BSH thank you! 

@alvarosanuy I am happy to update that to "Area of foul ground (safe for navigation but not for anchoring) boundary", Do you agree? Thanks.

**Comment by alvarosanuy** [comment]
@MikusRL  - Hi Mikus, I think that the definition of 'foul ground' already exists in the DCEG and the FC. The "symbol explanation' field should be used to describe the 'symbol name' (usually encoded as an acronym), in plain words. For example 'symbol explanation' could be populated as: _Central symbol used within Foul Ground area features to facilitate their identification, particularly when some or all their boundaries do not sit within the ECDIS display ._

Maybe  a bit too long but I hope you get what I'm trying to point out here.

**Comment by DavidGrant-NIWC** [comment]
Agree with Alvaro wrt the explanation.

For the name, the use of tokens is a carryover from S-52. In S-101 the xmlID is more analogous to the S-52 token. It would be better to use names which could be used by the ECDIS to convey meaning to the mariner, although note that currently it is not required to show the names in the pick report (likely because in S-52 they were not meaningful):

![image](https://user-images.githubusercontent.com/62906211/171672860-cd7e968b-8143-45db-90c2-c68bed6b1776.png)

Currently in the testbed it shows the symbol description along with any aliases, but it would be nice to display a shorter string (the name) and only show the description/explanation as a tooltip:
![image](https://user-images.githubusercontent.com/62906211/171674265-ac5cfae5-b6ae-43e1-9e6a-603013eec63e.png)

**Comment by MikusRL** [comment]
The above said gives meaning, and I am happy to update the files accordingly, but please for the firs ones still bit help needed - identify/mapp for me, where in the .svg file I need to add or change:
- name = token, and goes in between - title?
- explanations = description = aliases, and goes in between desc?
- any other more? 
(I have not yet managed to review your long list of what needs to go with the symbol metadata. Please map those also to the above required here. Thanks)

And then I believe group needs to discuss/agree, what exacly to put in the file - please use the first comments table entries and suggest changes, and also for the other symbols then please the same. Thanks.

**Comment by DavidGrant-NIWC** [comment]
### Symbol Information

I don't think any of the information is stored in the SVG file, it is stored in the portrayal registry, and exposed to the ECDIS via the portrayal catalog (portrayal_catalog.xml).

![image](https://user-images.githubusercontent.com/62906211/171700061-f44d2a48-1bf2-4a55-80a8-cb88bcbbc772.png)

I mistakenly said we showed an alias for the symbol; unlike the feature catalog, there is no alias for the symbols within the PC. We show the name, which is effectively equivalent to an alias for the symbols brought forward from S-52.

These are the attributes of a symbol and the corresponding definition/location within the portrayal catalog and the portrayal registry. Until the symbol is registered, the information should be tracked along with the symbol.

|PC|Registry Item|Notes|
|:---|:---|:---|
|symbol.id|S100_PR_RegistrItem.xmlID|
|symbol.description.name|S100_RE_RegisterItem.name|
|-|S100_RE_RegisterItem.definition|Not in PC
|symbol.description.description|S100_PR_RegisterItem.description|
|The symbol file|S100_PR_Symbol
|Symbol file and CSS files|S100_PR_ColourToken|The colour tokens referenced by the symbol - must be registered if new
|-|S100_PR_ItemSchema|Not in PC

### Display Parameters
Feature / attribute combinations are evaluated by the portrayal catalog rule files and these combinations drive the selection of symbols and their associated display parameters. In other words, the display parameters are independent of the symbol, but when a symbol is developed it is presumably to symbolize a given feature (possibly with specific attribute values). This feature/attribute symbolization should be described not just with a symbol, but also with the necessary display parameters.

I expect the sub-WG will need to provide these display parameters.

The minimum set of display parameters which must be defined are:
* Display Plane
* Display Priority
* Viewing Group
* Text Group (whenever text is output)

These display parameters must be associated with a feature type, any required attribution, and the geometry type (point, curve, or surface). If portrayal context parameters such as Radar Overlay, Plain Boundaries, etc., affect the symbol selection or display parameters then these must also be noted.

The above information is equivalent to the information provided in the S-52 DAI files and in the S-52 appendices to Part 1:
![image](https://user-images.githubusercontent.com/62906211/171725908-c4e0fdec-3f26-490d-95e0-61af96ac2096.png)

Here's the description of the content of the look up tables for areas when context parameter "Plain Boundaries" is enabled:
![image](https://user-images.githubusercontent.com/62906211/171726084-cdcbb480-ff4f-4e98-97e2-a561c0e95595.png)

and entries for "CONVYR":
![image](https://user-images.githubusercontent.com/62906211/171726202-c61f6f08-1844-4eb4-a368-572c1d7f281a.png)

Finally, note that symbolization of a particular feature type may require many different symbols, each with its own display parameters. For instance, an area may require:
* A symbol shown at the centroid of the visible portion of the area
* One or more symbols referenced from a fill pattern which fills the area
* One or more symbols referenced from a line style which outlines the area
* A date dependent symbol (Display Plane=overRadar, Display Priority=24, Viewing Group = 31032)
* An INFORM symbol (Display Plane=overRadar, Display Priority=24, Viewing Group = 31030)

**Comment by DavidGrant-NIWC** [comment]
We have replaced the point symbol used to symbolize points and areas with the symbol provided, but what is the desired portrayal for curves? In S-57 it was not possible to have a curve of type OBSTRN with CATOBS=7, so there is no symbolization defined in S-52.

viewing group=? (recommend 34050/34051 based on presence of VALSOU)
display priority=? (recommend 12)
display plane=? (recommend under radar)
linestyle=? (recommend 0.32 mm dashed line with colour=CHGRD)

**Comment by TomRichardson6** [comment]
I note that S-4 B-422.8 only describes point and area symbology. Although I expect curves to be rare we should cater for this and I would support a dashed grey line but propose that the point symbol FOULGD02 should be shown also (Complex linestyle). 

Not related but I find it odd that the pick report details the symbols in the way shown above is this a new requirement from S-98? I am unclear on the user benefit of this information in the pick report.

**Comment by DavidGrant-NIWC** [comment]
> Not related but I find it odd that the pick report details the symbols in the way shown above is this a new requirement from S-98? I am unclear on the user benefit of this information in the pick report.

The requirement is from S-52 10.8.1:
![image](https://user-images.githubusercontent.com/62906211/177631727-1b6f7a57-7943-4dc6-8054-0170a396e0e6.png)

The information is also useful to us when debugging the portrayal. At some point we may additionally show the symbol associated with the description in the pick report - that would be more user-friendly, but it's a little difficult to implement.

**Comment by TomRichardson6** [comment]
@DavidGrant-NIWC thanks David I stand corrected, I can certainly see the value in testbeds but I don't recall ever seen this presented in an ECDIS system in the pick report only via the chart 1 function. I will gauge some mariner views on this and raise a further Github item on this point. Certainly not for action for the PC at this stage.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Approve symbol FOULGD02 but it size has to be amended. Two new vesrions are required; one to support Curves (7.1mm diameter) and another one to support Surfaces (9.94mm diameter). **Mikus** to create and upload new SVG, CSS & Engineering Drawing files **for both sizes** to this Github issue.
2. _Point geometry_ to use existing (S-52 SY(FOULGND01) when VALSOU is not populated.
3. _Curve Geometry_ - Develop complex line style using new symbol FOULGD02 (7.1mm) evenly spaced on a 0.32 mm dashed line with colour=CHGRD. **Inga** to develop and upload Complex line style to this Github issue.
4. _Surface Geometry_ - Symbolised & Plain - Use  0.32 mm. dashed line with colour=CHGRD and center symbol FOULGD02 (9.94mm)
5. DCEG subWG to discuss the need (use case) for geometric primitive Curve for this feature type (currently not allowed in S-57). 
6. If DCEG SubGroup returns that Curve should be discontinued, then an update to the FC and PC will follow as per current practices.

- IMO display category 'OTHER' or 'BASE' depending on VALSOU and 'safety contour' input.
- viewing group= 34050 or 34051 based on presence of VALSOU.
- display priority=12
- display plane=under radar or over radar depending on VALSOU and 'safety contour' input.

**Alvaro** -  I decided to leave this issue open to discuss statement in DCEG section 13.6.1. It seems to be an intention to separate **Obstruction**, **categoryOfObstruction**=6(foul area) from **FoulGround** in a way that makes one feature unsafe for navigation and the other safe **but** we kept **valueOfSounding** as a valid attribute for **FoulGround** and therefore we are effectively  allowing for 'Safety Contour' calculations that may return that a **FoulGround** **is not** safe to navigate over (!?)

**Comment by MikusRL** [comment]
For the fourth bullet point above:

_"4\. _Surface Geometry_ - Symbolised & Plain - Use  0.32 mm. dashed line with colour=CHGRD and center symbol FOULGD02 (9.94mm)"_

I will create a new symbol for the center symbol, so the center symbol and edge symbol do not get mixed up. Center symbol will be called FOULGD03.

**Comment by LeoKuzmin** [comment]
In according with:
_"3. Curve Geometry - Develop complex line style using new symbol FOULGD02 (7.1mm) evenly spaced on a 0.32 mm dashed line with colour=CHGRD. Inga to develop and upload Complex line style to this Github issue."_
Please, find the attached file with the SVG, xml, CSS & Engineering Drawing files of Foul Ground feature with curve type.
@MikusRL: I suppose we don't need to rename center symbol  'FOULGD02' since the embedded symbol must be called with prefix 'EM'. I have called it EMFOULGD.
[FoulGround_Curve.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9351240/FoulGround_Curve.zip)

**Comment by LeoKuzmin** [comment]
BTW, the 2nd bullet, see Alvaro's message above:
"_Point geometry to use existing (S-52 SY(FOULGND01) when VALSOU is not populated._"
It is not quite correct, since FoulGround.lua script provides the drawing of the symbol FOULGND01 independently on VALSOU value according to S-52 Look-up Table.. Otherwise the script must be changed.

**Comment by alvarosanuy** [comment]
@mikan66 - Final instructions for implementation:

- Point feature  - Use FOULGND01 as per S-52
- Curve - Use new complex line style FOULGRD1.xml
- Surface symbolised & Plain boundaries - Use 0.32 mm. dashed line with colour=CHGRD and new central symbol **to be supplied by Mikus (see below).**

@MikusRL - We need a new central symbol (as per your FOULGD02 but with a diameter = 9.94mm).

Other parameters as follows:

- IMO display category 'OTHER' or 'BASE' depending on VALSOU and 'safety contour' input.
- viewing group= 34050 or 34051 based on presence of VALSOU.
- display priority=12
- display plane=under radar or over radar depending on VALSOU and 'safety contour' input.

**This issue will continue open until changes are implemented in PC 1.0.2 by NIWC.**

**Comment by MikusRL** [comment]
@alvarosanuy 
Sorry for a small confusion here I made. I understood from comment and saw in files from Leo, that he has created the center symbol already, but did not checked the svg file specifically in detail, as assumed it was created as per the description allocated to me. But You are correct Alvaro, Leo created a symbol for a line, and I still need to create a centered symbol. I am on it right away.

**Comment by MikusRL** [comment]
I have created the symbol and drawing.
[FOULGD51 centre symbol.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9470511/FOULGD51.centre.symbol.zip)
I aplied a fainf colour, as per the sentred symbols - CHGRF. 

![image](https://user-images.githubusercontent.com/72803214/187933750-15c9a606-65ad-4b03-9a20-4f9f8a0e12e2.png)

**Comment by mikan66** [comment]
> @mikan66 - Final instructions for implementation:
> * Surface symbolised & Plain boundaries - Use 0.32 mm. dashed line with colour=CHGRD and new central symbol **to be supplied by Mikus (see below).**

Dashed line color CHGRD disagrees with new symbol CHGRF.

**Comment by mikan66** [comment]
Are we adding this to alerts for SafetyContour?  Currently it is not.

**Comment by MikusRL** [comment]
> Dashed line color CHGRD disagrees with new symbol CHGRF.

Yes, I made it faint, as that I see as general approach for center symbols. Please correct me if I am wrong, but isn't that also the case with the magenta simplified symbolization of areas, that the line is Dominant color, but the central symbol is larger and Faint color usually. It makes sense, as is easier to distinguish on screen then a point symbol vs and centred symbol not only by size but also by lighter color. 

@alvarosanuy If you also do not agree to this my initiative, then I am happy to change the color for the center symbol file to Dominant color - CHGRD.

**Comment by mikan66** [comment]
@LeoKuzmin , Please note SVG FILE BUG:  in new file, EMFOULGD.svg, line 16, 's1' should be 'sl'.  I will correct locally on PC check-in.
circle class="sl f0 sCHGRD" style="stroke-width: 0.32" cx="0.2" cy="0.2" r="3.55"

NOTE: used features AnchorageArea and LandElevation to simulate.  Still testing but here are some samples.

> Surface symbolised & Plain boundaries - Use 0.32 mm. dashed line with colour=CHGRD and new central symbol to be supplied by Mikus (see below).
![image](https://user-images.githubusercontent.com/4913543/190230828-30d9627c-c0e8-48a9-933b-80cbb83f6154.png)

Point: 
![image](https://user-images.githubusercontent.com/4913543/190231160-09fc9e4b-3bc6-48fd-88e5-cf0a39d53ac9.png)

curve: 
![image](https://user-images.githubusercontent.com/4913543/190240742-db30e759-db19-4af2-9e72-95a04348ef15.png)

**Comment by alvarosanuy** [comment]
> Are we adding this to alerts for SafetyContour? Currently it is not.

**Not for now** - Awaiting possible remodelling from DCEG. Having VALSOU as an attribute in FoulGround makes you think that this value should be compared against SC and trigger an Indication accordingly but ...... this is not the case in S-52 where OBSTRN, CATOBS=7 is excluded from CS(OBSTRN07). Foul ground by definition is an area safe to navigate but not for other activities like trawling, anchoring, etc). If producers think the area may be unsfae to navigate over by certain ships in the area the feature should be encoded as OBTRN/Foul Area ......

**Comment by alvarosanuy** [comment]
> > Dashed line color CHGRD disagrees with new symbol CHGRF.
> 
> Yes, I made it faint, as that I see as general approach for center symbols. Please correct me if I am wrong, but isn't that also the case with the magenta simplified symbolization of areas, that the line is Dominant color, but the central symbol is larger and Faint color usually. It makes sense, as is easier to distinguish on screen then a point symbol vs and centred symbol not only by size but also by lighter color.
> 
> @alvarosanuy If you also do not agree to this my initiative, then I am happy to change the color for the center symbol file to Dominant color - CHGRD.

I couldn't find any guidance on this topic and although some magenta symbols follow the principle mentioned by mikus (line is Dominant, central symbol is Faint), this is not always the case. There are multiple examples of small central symbols and area patterns in Grey that have both, line and symbol in Dominant colour .......
I think we have the opportunity to create some rules here and potentially allocate any central large (around 9mm diameter) central symbol that is enclosed in a circle a Faint colour & central symbols not having a surrounding circle and being small (generally less than 6mm D) in size a Dominant colour.

If we go ahead with this, **FoulGround** and **DiscolouredWater** https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/61 will have to follow this guidance (I think they currently do as the central symbols for both were supplied in Faint grey colour).

**Does anyone have something against this general ruling??**

**Comment by mikan66** [comment]
> > Are we adding this to alerts for SafetyContour? Currently it is not.
> 
> **Not for now** - Awaiting possible remodelling from DCEG. Having VALSOU as an attribute in FoulGround makes you think that this value should be compared against SC and trigger an Indication accordingly but ...... this is not the case in S-52 where OBSTRN, CATOBS=7 is excluded from CS(OBSTRN07). Foul ground by definition is an area safe to navigate but not for other activities like trawling, anchoring, etc). If producers think the area may be unsfae to navigate over by certain ships in the area the feature should be encoded as OBTRN/Foul Area ......

The rule will have simple VALSOU logic only controlling viewing group and radar.  I plan to close this issue in the PC today as I don't see any other tweaks needed at this time (regarding visualization).

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/39#issuecomment-1247940868

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2
