### ISSUE TITLE
Triangulation Mark, non conspicuous

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#66]
P_7 point symbol generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx
[P_7.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8375409/P_7.zip)
![image](https://user-images.githubusercontent.com/72803214/160718510-ac6dd30a-9630-4c5a-a30d-1d1806342063.png)

**Comment by KlasOstergren-SMA** [comment]
I'm not sure why we need a symbol for a not conspicious control point. I cannot see any need for the mariner.

In the S-57 to S-101 conversion guidance 4.3 Control Points, the following is stated:
"For S-101, it is considered that control point information is not required for ENC. In general, therefore, encoded CTRPNT will not be converted. However, in certain circumstances where a control point may be visible from seaward and therefore used as a navigational fixing mark, this information may be encoded in S-101 using a Landmark feature."

In S-4 (B-304.1) it is stated:
"A triangulation point must be represented (if shown) by the symbol B20. This symbol should be used to indicate the existence of a pillar or other mark that may be visible from sea."

**Comment by MikusRL** [comment]
Would agree with Klas. In DCEG 1.0.2 Clean_V2 in paragraph 5.6 is similar note at the end, and not defined Feature Control point as such.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Approve symbol POSGEN05 as uploaded by Mikus to this Github space. Update rules accordingly (**categoryOfLandmark**=22 (triangulation mark); **visualProminence**<>1 (visually conspicuous).

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/108#issuecomment-1230455827
