### ISSUE TITLE
Renewable Energy Farm

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#67]
P_6 point symbol generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx.
General idea is for the Solar farm.

2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_6_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8826034/P_6_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160720971-be8f08df-e0fe-4245-ba6f-cb347b8152d0.png)

**Comment by SylviaSpohn-BSH** [comment]
Agree to the symbol in the area according to INT 1 L6.

**Comment by MikusRL** [comment]
I have updated .svg files in the .zip file in initial comment for NIWIC comment fix.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Mikus to create a new version of the proposed symbol using a larger circle diameter [as per SY(ENTRES51) - 9.94mm]. New files (SVG, CSS and Engineering Drawing) to uploaded to this Github space.
2. Use LC(NAVARE51) for Symbolised boundaries and S-52 instruction LS(DASH,2,CHGRD) for Plain boundaries.

**Comment by mikan66** [comment]
Mikus: any updates on a few of these "Offshore Production Area" related symbols?

**Comment by MikusRL** [comment]
Hi Mikan, yes, sorry, symbol coming shortly. I have not forgotten, just a bit out of time :). The same with the others which on me.

**Comment by MikusRL** [comment]
I have created three symbols based on that symbol ENTRES itself is in three versions - 51, 61 and 71. The ! and i versions are conditional, when restriction or information is encoded. There is no dedicated symbol if both are encoded, but I think then the strongest (RENERG61) should be shown, correct? 
And as last, as opposed to CHGRD color mentioned in the minutes, I chose the CHGRF (faint version), to be consistent with the larger centred symbols, which are faint normal. The previous prototype was designed for the line symbol, which normally are CHGRD. The Symbolized and plain lines with this symbol, still are to be drawn as per Alvaro's comment above.
[RENERG_Centred.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9442457/RENERG_Centred.zip)

I have not updated any of the .svg "metadata" entries, as comented in #28 earlier.

No embedded shift in SVG, but could be same approach as commented in #68, if group agrees. 

![image](https://user-images.githubusercontent.com/72803214/187148350-2a0061e2-b212-495c-91af-9b6d378ed8a9.png)

![image](https://user-images.githubusercontent.com/72803214/187148414-604c1ae1-ad1c-41bb-a42f-f67a6ec0ff85.png)

![image](https://user-images.githubusercontent.com/72803214/187148505-c3160e05-3525-4615-b58b-abd1d77bdb8b.png)

**Comment by alvarosanuy** [comment]
@MikusRL 

- RENERG51 is fine. It will be added to the **OffshoreProductionArea** rule when **categoryOfOffshoreProductionArea** = 2 or 3 or 6 (Wave, Current and Solar Farms). This rule will include (as per S-52) a call to CSP RESTRN01 (and from that to RESCSP02).

- I believe RENERG61 and RENERG71 are not required. CSP RESTRN01 + RESCSP02 will 'add' new symbols (to be off set by the OEM) to an angle and distance from RENERG51 based on the values of the attribute **restriction** (if populated).

                     Does anyone have a different view on this???

**Comment by alvarosanuy** [comment]
This issue has been re opened until changes are implemented in PC 1.0.2 by NIWC.

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1238024384
