### ISSUE TITLE
Distance Mark's Unit of Measurement

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#69]
P_4 point symbols generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx

2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_4_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8825858/P_4_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160735517-77e4ff19-957d-4485-8157-83d9ef350824.png)
![image](https://user-images.githubusercontent.com/72803214/160735587-ac23eced-1033-490e-8e09-5095d49601a1.png)
![image](https://user-images.githubusercontent.com/72803214/160735627-84f5a525-863f-4185-a0f3-e367f429880c.png)
![image](https://user-images.githubusercontent.com/72803214/160735670-daaa55d1-5685-42ad-9140-7f01353384e3.png)

**Comment by IngaFjellanger** [comment]
1. Do we need to add new symbols for each Unit of Measurement. Would it not be more logical to use TextInstruction to draw abbreviation according to the unit value near the magenta circle symbol (m, km, yd, StM and M). E.g. 
![image](https://user-images.githubusercontent.com/70318960/169839661-b59f8f31-7839-4e2c-86f7-497a0d58d9f1.png)
Suggestion: Change DistanceMark. lua script to draw combination of  distance value and units by means of a TextInstruction.
If value of the .waterwayDistance or .distanceUnitOfMeasurement attributes is unknown, the standard symbols DISMAR03 or DISMAR04 should be used.

2. The pivot point of DISMAR03 (05/07/09/11) doesn’t coincide with the magenta circle which is interpreted as position of the real mark. Could we change this?
Suggestion: Add a new symbol DISMAR02.svg as a small magenta symbol in the pivot point

**Comment by SylviaSpohn-BSH** [comment]
Agree to add the unit of measurement. If there is a circle why could the symbol not be centred in the middle of the circle? Is the number kept in black? Could the symbol perhaps be closer to INT1 B25 (with differentiation between visible and unvisible marks?  Italic and magenta in the water, if unvisible, at the land upright in black?)

**Comment by MikusRL** [comment]
I have updated .svg files in the .zip file in initial comment for NIWIC comment fix. 

Agree to Sylvia and Inga. But first I was tasked to re-create the new ones as the reference symbol, as I have mentioned that for each symbol in the comments line. And if group agrees, I am happy to either make the pivot point to the centre of the circle, or as Inga suggests in nr2 - just circle plus TextInstruction, or as Sylvia suggests. But would be happy to hear the discussion of the group on that too.

**Comment by alvarosanuy** [comment]
**Refer to decision made at Portrayal subWG meeting on 14/7/22** - https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/39
