### ISSUE TITLE
NIWC Testbed Update - Slide # 12 - Quality of Bathymetric Data

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#7]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf) 

![image](https://user-images.githubusercontent.com/70189016/94630723-ecf4fe80-0309-11eb-9655-ebb302d073af.png)

**Comment by DavidGrant-NIWC** [comment]
Current portrayal (unhappy faces):
![image](https://user-images.githubusercontent.com/62906211/95349179-ccd6b980-088c-11eb-943d-a9cb17e1f563.png)

**Comment by alvarosanuy** [comment]
We could start by consolidating in one place all the proposals (that we know of) that have been submitted by different organizations to different IHO WGs in the last 10 years or so. Any other new fresh alternatives would be also very well welcomed .......
We should continue working after session and aim to present no more than 2 concrete alternatives to the next S101PT VTC meeting in early December.

Below is a link to the documents I am aware of:
https://1drv.ms/u/s!AmIbzaNwjeNwgQ7B8c5ZvvjM4ZNj

Below are the AHO's comments to the proposal submitted by Germany as NCWG3-08.4A. Comments were based on S-57 & S-52:

**NCWG3-08.4A** - The AHO thanks Germany for their research project and would like to contribute with the following comments:

·         The AHO agrees with the idea of being able to set up a “corridor” for the display of the DQI pattern during route planning (for the display of ZOCs within see next bullet point regarding the use of ‘indhlt’ and ‘dnghlt’). The ‘check route’ functionality should be extended to report breaches to a pre-set ZOC category (a lower CATZOC intersects the safety corridor).

·         The AHO agrees with the possibility of displaying the DQI pattern in a circle which moves with the ship during route monitoring but:

o   Instead of showing all the different patterns (ZOC categories) inside the “guard zone” we’d prefer the mariner being able to set up a CATZOC value (e.g. B) and let the software highlight any overlap with a lower ZOC area on the fly. This could be done using a modified version (dashed) of the new Mariner Object ‘indhlt’(one ZOC category off) or ‘dnghlt’ (more than one ZOC category off). This approach reduces clutter, as the guard zone around the ship will not show any pattern unless it gets in contact with an M_QUAL that breaches the settings (e.g C, D or U). If the mariner wants to know more about the M_QUAL it can do pick report and, for example, clarify if it’s a ZOC C or ZOC D area.

o   Instead of the “mouse hover” option, we’d prefer a “full screen” option which would only display M_QUALs breaching the CATZOC settings previously set up by the mariner. A full screen option provides a better picture of the surroundings and would help mariners come up with a new course faster in case of an emergency.
Mariners would switch to ‘full screen’ mode only when they want to ‘look ahead’ or if an unplanned change of course needs to be made.

o   We think there should be only 3 display options:

- ZOC = Unassessed  - A pattern made of U letters in grey colour (displays always irrespective of the settings)

- ZOC worse than settings  - Circle with exclamation mark within (grey colour)

- ZOC equal or better than settings  - No pattern at all 

In the future development of S-100 compatible ECDIS, it would be useful to include an “ON/OFF” setting called “DQI”. When selected mariners would be able to set up the radius and the ZOC value of a “Data quality guard zone”. This would affect the DQI pattern display. Mariners should then have the option to select a "Full screen" or "Radius” display.

**Comment by AntonioDiLieto** [comment]
During DQWG15 (Feb 2020), there was a discussion on the name of the feature Quality of Bathymetric Data. For the end user (at least those represented by Carnival and Intertanko) this is quite confusing. The current S-57 uses the attribute Category of Zones of Confidence in data which seems to be well understood by the mariner community for now at least as a concept. In the end, it was decided that a proposal should be made to S-100WG/S-101PT to rename the feature Quality of Bathymetric Data into Zones of Confidence.

It took years of training and practice for the mariners to understand the CATZOC concept and visualization. In name of a large group of mariners, I would not change the portrayal of CATZOCs.

On the other hand, in the future development of S-100 compatible ECDIS, I would welcome an enhanced route checking functionality that could detect the intersection between the planned route corridor and the uncertainties associated to bathymetric features. This was also discussed during DQWG15, starting from a paper submitted by Australia  (“Uncertainty of measurements and ECDIS performance”). This paper was thoroughly discussed as it suggests HOs to start populating HORACC, VERACC, SOUACC and POSACC in S-57 datasets. The DQWG recognised that in theory this is a good idea, however the internal resources required for HOs is a limiting factor.

**Comment by DavidGrant-NIWC** [comment]
> In name of a large group of mariners, I would not change the portrayal of CATZOCs.
This recommendation requires the development / approval of rules for mapping from S-101 QoBD to CATZOC.

**Comment by NLHO-Rogier** [comment]
Please note that their are two approaches discussed here: 1) screen wide symbology 2) ship centered symbology. 
SINTEF in Norway is working on a ship based Uncertainty Zone (between ships but can be extended to static dangerous objects), see paper S-100WG5-04.3
University of New Hamshire has demonstrated various portrayal options for screen wide symbolsbology (see paper DQWG15-05.4A.

**Comment by SylviaSpohn-BSH** [comment]
So far as I know BSH was not content with the outcome from the Frauenhofer study but it can seen as a base for the further work which has been done by the University of New Hamshire and others.
I agree to hear what the users say and not to confuse them more. The DQI switch could be an option. It needs further investigation. It is not easy for the cartographic data collectors to get the data to let e.g. the ship centered symbol or the obstruction symbol etc. change.

**Comment by DavidGrant-NIWC** [comment]
> > In name of a large group of mariners, I would not change the portrayal of CATZOCs.
> 
> This recommendation requires the development / approval of rules for mapping from S-101 QoBD to CATZOC.

We see two options for implementing S-52 equivalent portrayal of CATZOC in S-101. **We recommend option 1.**

## Option 1
Add CATZOC as an attribute of the QoBD feature. The S-101 portrayal catalogue rule can then use the attribute directly to produce a portrayal which matches S-52.

## Option 2
Using the existing attributes of QoBD, update the S-101 portrayal catalogue rule to implement a portrayal which matches S-52. This requires determining CATZOC from the S-101 attributes. CATZOC can be computed using S-57 Appendix A, Chapter 2, ZOC Table and Remarks (pg 2.107-2.108), **assuming this guidance is valid**.
* If the guidance in S-57 is not valid, the information below will need to be updated to implement option 2.

### Items supporting option 2
#### Mapping of S-57 to S-101 attributes
![image](https://user-images.githubusercontent.com/62906211/97058524-121d0b80-155c-11eb-84a6-0d0e7892d457.png)

#### Truth table for portrayal of QoBD as CATZOC
![image](https://user-images.githubusercontent.com/62906211/97058605-47295e00-155c-11eb-817d-ba0f4636fcf7.png)

#### S-57 Appendix A, Chapter 2, ZOC Table and Remarks:
![image](https://user-images.githubusercontent.com/62906211/97058657-6627f000-155c-11eb-8058-e328228b54df.png)

**Comment by alvarosanuy** [comment]
**We prefer Option 1.**
The new attribute ''zocCategory' or 'qobdCategory' should be considered by the DCEG subWG (Jeff has been tasked to review and remodel QoBD based on proposals from the DQWG and the AHO). No formal decision has been made by HSSC12 on the renaming of QoBD but the the DQWG has been tasked to transfer their recommendations on the 'Conditional visualization of QoBD' to the S101PT.
A good thing about Option 1 (apart from simplifying portrayal rules) is that allows retaining the existing validation checks that  confirm compliance between CATZOC and POSACC/SOUACC values. This way encoders have the chance to fix typos (i.e. POSACC=30 instead of 3m for a ZOC B area).
In the example above, Option 2 wouldn't trigger any warnings and a ZOC A1 area would be depicted as A2 purely based on the 'erroneous' horizontal uncertainty value.

**Comment by NLHO-Rogier** [comment]
The IHO recently published IHO Standard S-67 providing guidance to the Mariner how to interpret the symbology of CATZOC. Changing this in the near future should only be done if the benefits clearly outweigh the fact that Mariners are now getting used to this terminology and symbology.

**Comment by alvarosanuy** [comment]
A decision has been made to:

- retain existing S-52 symbology (aligned with CATZOC values)
- include the term **categoryOfZoneOfConfidence** into the modelling of **QoBD** (In coordination with the DCEG subWG)
- Add entry to the 'Portrayal and ECDIS Performance' log regarding the development and testing of new **QoBD** symbology and ECDIS performance (including A&I) for post DF-ECDIS implementation.
