### ISSUE TITLE
Physical AIS Aid to Navigation

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#70]
P_2 point symbols generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx
2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_2_20220602_fix.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8825758/P_2_20220602_fix.zip)

![image](https://user-images.githubusercontent.com/72803214/160739435-77e35772-03f3-4999-b208-7a55575fdd53.png)
![image](https://user-images.githubusercontent.com/72803214/160739492-37a912c5-b467-49fc-839c-11480be2c7d0.png)
![image](https://user-images.githubusercontent.com/72803214/161448228-8d8ba0f3-bb56-4bf9-9ba7-adbf11bccf4c.png)
![image](https://user-images.githubusercontent.com/72803214/161448257-4eca6285-05df-4433-9f8a-9b48db55e122.png)
![image](https://user-images.githubusercontent.com/72803214/161448318-638466fd-37f7-490b-9d44-1a57e4304557.png)
![image](https://user-images.githubusercontent.com/72803214/161448373-6ffeb5f9-71b8-44c8-8a27-03be48833435.png)

**Comment by alvarosanuy** [comment]
Please refer to my comment made on 21/3/22 in Github isue # https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/37.

It proposes a way to differentiate "real' from 'Synthetic' AIS signals on physical structures.

**Comment by MikusRL** [comment]
I am updating the first comment and the zip file with three more symbols to reflect the Synthetic AIS as discussed in issue https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/37

**Comment by IngaFjellanger** [comment]
We think the symbols AISPHY02 (version 2 ) and AISSYN02 (version 2) are better than version 3 symbols. If we use AIS symbols version #3 they will clutter up lights label which is drawn in the same place.
However, the AISPHY02 should be changed to avoid overlapping the “AIS” label and light flare.
Sample of AISPHY02 symbol (9mm diameter magenta circle): 
![image](https://user-images.githubusercontent.com/70318960/169972516-046037f8-224f-4242-abf4-9cd880967b59.png)
![image](https://user-images.githubusercontent.com/70318960/169972549-73f4084d-2e8e-4006-8f19-55d51d6270a7.png)
Sample of AISPHY03 symbol (9mm diameter magenta circle): 
![image](https://user-images.githubusercontent.com/70318960/169972697-c99eb611-eba8-48b4-a9c4-4787f31f4d2c.png)
![image](https://user-images.githubusercontent.com/70318960/169972719-95e47f4d-0d8f-4456-894c-c93c0016d4db.png)
Suggestion: Use the modified AISPHY02 (version 2 ) symbol to depict PhysicalAISAidToNavigation feature type. But decrease the diameter of the magenta circle equal to 8 mm.
Use AISSYN02 (version 2) for Synthetic AIS when encoding rules will be defined for the feature.

Regarding version #1 symbols: We think the circle is not large enough to surround a structure symbol. Probably, magenta circle with diameter equal to 8 mm will be a more optimal size. See example of using 8 mm magenta circle for virtual AIS features:
![image](https://user-images.githubusercontent.com/70318960/169973161-cbc545f9-08a5-4722-9555-752fbb881831.png)

**Comment by SylviaSpohn-BSH** [comment]
If necessary to distinguish I would agree to the symbol version 3. Synthetic and virtual come from land and should get an upright label. My opinion is that the addition (S) is not necessary, but if decided for it should be included in the paper chart, too. Needs to be discussed in NCWG than.

**Comment by MikusRL** [comment]
Based on the examples above I am happy to create New Version of Version 2/3, with 8mm, but where text is placed in upper part, so it would not obstruct default light characteristics. I will try to do it as soon as I can.

**Comment by MikusRL** [comment]
Based on the above discussion have created Version 4 of Physical and Synthetic AIS Symbol:
[P_2_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8825731/P_2_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/171127973-f5c8dd51-3206-404c-86d2-24a35e07d342.png)
![image](https://user-images.githubusercontent.com/72803214/171128130-97fef4b4-7bd1-4ac2-8a45-efcce68ad886.png)

**Comment by MikusRL** [comment]
I have updated .svg files in the .zip files, initial ones and version 4 ones, in initial comment and just above, for NIWIC comment fix.

**Comment by GuttormTomren** [comment]
This proposes to add a letter after AIS, to distinguish between physical and synthetic 
Physical (no letter)
Synthetic (letter S) 
![image](https://user-images.githubusercontent.com/93490864/172781885-44379121-f249-4172-bb07-f8576da1677e.png)
![image](https://user-images.githubusercontent.com/93490864/172781909-4fc2ffd9-8f6c-423e-9ee8-6fa034d00497.png)







There is made three options, with various fonts and size. IALA support comments made by IngaFjellanger regarding readability. 

Proposal to use letter S to indicate synthetic AIS is supported by IALA, but in front of the letters, 
As shown;
S-AIS
Reason for this is explained in Github #37.

**Comment by MikusRL** [comment]
I will make new version (AISSYN05) shortly for the S-AIS symbol, taking as a base the AISPHY04 (Version 4). Hope I have understood the discussions here and in #37 .

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 12/7/22**

1. **PhysicalAISAidToNavigation** should be discontinued and a new complex attribute added to all possible supporting navaid structures to:

- identify those associated to AIS and,
- from those, separate the ones linked to _Real_ or _Synthetic_ signals.

DCEG subWG lead (JW) will continue the conversation with the IALA representative and target any amendments to the FC for version 1.1.0.

2. The symbology to be used (once re-modelling is finalised) will look as per the image below but:

- Magenta circle must be 9mm in diameter
- For _Synthetic_ - the text needs to be amended from AIS(S) to **S-AIS**. 
- For _Real_ - the text will read **AIS**

3. Mikus to upload new SVG, CSS and Engineering Drawing files to this Github Issue.
4. Leave issue open until re-modelling is finalised. At that point PC Rules will need updating.

![image](https://user-images.githubusercontent.com/70189016/178660860-2898fb37-6e37-4c60-b885-510167b1063f.png)

**Comment by MikusRL** [comment]
As per the above task uploading the Symbol files.

[Physical and Synthetic AIS_20220713.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9099682/Physical.and.Synthetic.AIS_20220713.zip)

![image](https://user-images.githubusercontent.com/72803214/178669597-38cf1632-f5dc-4bdc-83b2-fe96a69ca0be.png)
![image](https://user-images.githubusercontent.com/72803214/178669753-71bcb638-a79f-48ec-88a7-91cb311aba88.png)

**Comment by alvarosanuy** [comment]
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/23

**Comment by alvarosanuy** [comment]
At NCWG8 and S101PT9 meetings it was agreed  not to proceed with a unique portrayal for Synthetic AIS signals until the IMO leads the way (triggered by a proposal from IALA??) and recognizes, in its instruments, the need to sub-divide AIS signals on physical aids to navigation.

Consequently, the decisions made at the last PsWG meeting are amended as follows: 

- **PhysicalAISAidToNavigation** features are not to be discontinued or remodeled as originally proposed.
- **PhysicalAISAidToNavigation** are to be mapped to AISPHY05
![image](https://user-images.githubusercontent.com/70189016/204445863-414b2607-8245-4607-b945-198331644f07.png)

@DavidGrant-NIWC - Can you please update the **PhysicalAISAidToNavigation** portrayal rule accordingly? This issue will be closed when done.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. The subWG decided to proceed with the instructions provided in the previous comment.

2. For PC 1.1.0.

**Comment by mikan66** [comment]
@alvarosanuy I'll need the full details here for viewing group, display priority, and radar Over or Suppressed?  Will the viewing group be in the range of 17000-17999 or someplace else?  I can stub in 17000 but will need to allocate this range in the PC.

**Comment by alvarosanuy** [comment]
> @alvarosanuy I'll need the full details here for viewing group, display priority, and radar Over or Suppressed? Will the viewing group be in the range of 17000-17999 or someplace else? I can stub in 17000 but will need to allocate this range in the PC.

VG = 27240 (as per S-98)
Over-Radar
Display priority = (8 in S-52 range - I think is 24 in S-101 range)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
