### ISSUE TITLE
Submarine volcano

### ISSUE THREAD

**Issue by HolgerBothien** [S-101-Portrayal-subWG/Working-Documents#71]
I developed a symbol how it was proposed for marking a submarine volcano.
It is for point symbolisation.
The proposed shape has to many details, it just looks ugly at 6 x 6 mm.
So, I generalized it.
Worth to be mentioned: The picture does show a vulcano above the water and should be used for a submarine volcano.
I am not in favour of it and would prefer text instruction for this rather rare type of obstruction.
Nevertheless, here is the symbol to be discussed.
[SubmarineVolcano.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8397475/SubmarineVolcano.zip)

**Comment by SylviaSpohn-BSH** [comment]
Perhaps we should take an more common and simpler symbol for volcanos - a triangle is used in the majority of atlases - or we could only provide textual information accompanying point and depth including depth contours. If there is danger to navigation, it could be depicted with a smoke column.

**Comment by HolgerBothien** [comment]
[SubmarineVolcano (2).zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9112182/SubmarineVolcano.2.zip)
Here is a version with the water line above.

**Comment by HolgerBothien** [comment]
![image](https://user-images.githubusercontent.com/88826517/178994686-ffef5f75-c733-40c4-ba54-b873047aff5b.png)

**Comment by HolgerBothien** [comment]
![image](https://user-images.githubusercontent.com/88826517/179000731-c84e4814-9bf7-4169-9edf-d948f7029e54.png)

**Comment by HolgerBothien** [comment]
![image](https://user-images.githubusercontent.com/88826517/179000909-9f118542-9b00-4902-ab94-31c8ea15d2d1.png)

**Comment by HolgerBothien** [comment]
[SubmarineVolcano (3).zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9112475/SubmarineVolcano.3.zip)
And here is the symbol.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

- Approve latest version (3) of the VOLCANO01 symbol uploaded by Holger to this Github space.
- Map this symbol to Point **Obstructions** features with **categoryOfObstruction**=21 (active submarine volcano)
- DCEG subWG lead to initiate discussions to restrict the use of geometric primitive Surface & Curve when encoding this **categoryOfObstruction** (DCEG + Validation checks).
- In the meantime, map Surface & Curve **Obstructions** features with **categoryOfObstruction**=21 (active submarine volcano) using CS(OBSTRN07).

**Comment by mikan66** [comment]
Example of version (3)
![image](https://user-images.githubusercontent.com/4913543/184141016-35e19efb-66ba-47e9-92d6-d6165e05c590.png)

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/19ac47d2aaadabccedc1fde4950cb425cd071196.

**Comment by HolgerBothien** [comment]
looks good. But the pivot point of the symbol should be in the middle of the base line.
Remembering the discussion with Hugh the pivot point is implicit always 0, 0. That is here not the case.
The symbol must be changed. 
I still think that it is not a good idea to have the pivot point always at 0, 0. 
That was OK as long the symbols has been converted from S-52.
But now it means, to change the pivot point ALL coordinates must be changed.
May be we need an optional mechanism to define the pivot point if it is not 0,0.
But this would require a change in S-100.

**Comment by mikan66** [comment]
That's right about the pivot point.  I will re-open the PC side issue.

**Comment by TDYCARHugh** [comment]
I think all that is needed to adjust the pivot point is to shift all the absolute coordinates in the symbol using the X,Y values of the non-zero pivot point so the pivot point becomes 0,0.  The viewbox min-x, min-y and all the X,Y values in the SVG drawing instructions would need to be shifted.  If there are several symbols that need to be adjusted it should be quite simple to script such a shift operation.

**Comment by mikan66** [comment]
I have not been tracking pivot point for the new symbols, but a quick look in my temporary folders for the new symbols I'm incorporating, only volcano is non-zero so far.

**Comment by LeoKuzmin** [comment]
Please, take a look at the modified symbol with pivot point 0,0
[SubmarineVolcano_4.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9359550/SubmarineVolcano_4.zip)
.

**Comment by mikan66** [comment]
New point symbol ver 4 update only, see commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/b2f914a16436d46b74d4481f6bb489b393bb88af

**Comment by mikan66** [comment]
Test data V5:  101AA00DS0013.000.  Clearing TEST in https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/103
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/4913543/9d602adf-b1c6-4919-8af9-a96f04167b4e)
