### ISSUE TITLE
Reported Anchorage

### ISSUE THREAD

**Issue by HolgerBothien** [S-101-Portrayal-subWG/Working-Documents#72]
A symbol similar to ACHARE02 but slightly smaller and using CHBLK instead of magenta has been developed for depicting reported anchorages.
[ReportedAnchorage.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8397767/ReportedAnchorage.zip)

**Comment by DavidGrant-NIWC** [comment]
![image](https://user-images.githubusercontent.com/62906211/161293334-69a0ba1e-8da6-4b61-b204-b34b56fc645e.png)

**Comment by TomRichardson6** [comment]
Support this new symbol and suggest that it will be easily understood for users as it reflects the equivalent paper chart symbol that is in use (N10). 

Suggest that the corresponding INT 1 reference N10 should be included in the document for traceability. Although the symbol is different it is a simplified derivative of the INT 1 symbology.

**Comment by IngaFjellanger** [comment]
To be sure that we do understand: Should ACHARE03 in black be used with point symbols when there is no limit around it while ACHARE51 in magenta should be used when there is a magenta limit around the area? No use of ACHARE02?

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Implement the symbol ACHARE03 as proposed.
2. NIWC to link symbol to **AnchorageArea** Point feature with **categoryOfAnchorage**=15 (reported anchorage).
3. Jeff - DCEG SubWG to discuss modelling or new guidance to prevent the use of **categoryOfAnchorage**=15 (reported anchorage) in **AnchorageArea** features of geometric primitive Surface.

**Comment by mikan66** [comment]
See comment and commit at https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/121#issuecomment-1222366965

**Comment by TomRichardson6** [comment]
Point and Surface features have been added to TDS00016 Edition 8 to reflect this new Portrayal. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0016/8

**Comment by DavidGrant-NIWC** [comment]
Reported anchorage with point geometry in center, reported anchorage with surface geometry on right ("?" because the geometry is not permitted for reported anchorage)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a532b0dd-c42c-4cad-8e9f-0b014a3e20d4)
