### ISSUE TITLE
Marine Pollution Regulations Area (MARPOL)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#74]
**Comment originally added in** https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/30*
**Transferred to this Github space for discussion.**

![image](https://user-images.githubusercontent.com/70189016/177886427-b814201b-af16-47fc-9520-9b12a937019e.png)
This is the dKart suggestion for how it could be implemented.

**Comment by alvarosanuy** [comment]
This would be the first time we use Green colour (beyond intertidal features and navaids) in ENC. S-52 uses Magenta for PSSA and ESSA. I believe we have replicated this in S-101. 
My opinion is that there are more merits to amend PSSA, ESSA, MR, etc to green than an administrative/regulated area that looks after the prevention of pollution, such as MARPOL.
At the moment, and based on the assessment report from Jeff's spreadsheet,  NIWC has been tasked to portray **MarinePollutionRegulationsArea** as Administrative areas (in Magenta as per - NP5012 3.5).

Also note that S-4  (B-437.5) states that (for a number of very good reasons), MARPOL Special Area limits should not normally be inserted on navigation charts. Also to consider is that, many times, Special Areas live within PSSAs ..

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Symbolise **MarinePollutionRegulationsArea** as per S-52 ADMARE features (Symbolised and Plain Boundaries).
2. Allocate **MarinePollutionRegulationsArea** a new viewing group (36060)
3. Allocate existing _Environmentally Sensitive Sea Areas_ (DCEG 17.7) the same viewing group than MARPOL (36060). In practice we are visually grouping **MarinePollutionRegulationsArea** + **RestrictedAreaRegulatory/Navigational** with **categoryOfRestrictedArea**= 27 (ESSA) or **categoryOfRestrictedArea**= 28 (PSSA).

**Comment by mikan66** [comment]
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/ae45e2ab510b28a57291c5da1123c483b938dee4

**Comment by TomRichardson6** [comment]
TDS00016 includes this feature. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0016/8

**Comment by DavidGrant-NIWC** [comment]
|Plain Boundaries|Symbolized Boundaries|
|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/09d321c2-7e56-4d90-9250-7e70cf653761)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/9db39370-af3b-458b-b7d9-8d23c8ecd2d3)
