### ISSUE TITLE
Crane - Curve & Point_Conspicuous

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#75]
**Content as per Inga's email (16 June 2022)**

Hello,
In connection with implementing portrayal some issues have been raised internally in dKart:

**Crane curve**

In S-57 CRANES could only be point or area. On the other hand, in S-101 Crane can be point, curve or surface. We have not found any portrayal of Crane curve in the portrayal catalog.
Our suggestion is to display Crane feature with curve geometry type like described below: 
•	Line is displayed as a solid line LANDF colour with the width 0.64 like a Runway feature is depicted.
•	The symbol CRANES01 must be drawn in center of the line. 
•	Viewing Group and Display Priority should be the same as for a Crane feature with surface geometry type.
 
![image](https://user-images.githubusercontent.com/70189016/177896175-86f3fa0d-438d-458e-b434-29e3c78c18d2.png)

Personally I am not sure I can find a situation where it is logical to use curve. In DCEG 8.12.1 there is a remark which tells to use Railway in the situations I would think curve could be an option: 
The position of a sheerleg or a travelling crane is defined as its resting position. If it is required to encode the track, it must be done using the feature Railway (see clause 6.13). 

**Visual conspicuous crane**

There is no special portrayal for feature Crane with visual prominence attribute equal to "1". Probably we need a new symbol CRANES03 with colour CHBLK to depict visual prominence of the Crane feature, the same way TOWERS03 symbol is used in a pair with the symbol TOWERS01.

![image](https://user-images.githubusercontent.com/70189016/177896038-8b2414eb-1819-4544-8f7a-757bede60c15.png)

**Comment by IngaFjellanger** [comment]
[Cranes.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9150412/Cranes.zip)
Here is a zip file with our symbols and other necessary files.

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Accept a new symbol (CRANES03) for visually conspicuous **Crane** features of geometric primitive Point.
2. Non visually conspicuous **Crane** Point features to use existing S-52 symbol CRANES01.
3. Implement 2 new complex lines for **Crane** features of geometric primitive Curve as detailed in Cranes.zip file uploaded by Inga on 21/7. Option with black symbol (CRANES13) must be linked to Cranes that are visually conspicuous and the one with the brown symbol (CRANES11) to those that are not.

**Note that** DCEG subWG lead will investigate the existence of a use case for the encoding of Crane features using Curves. DCEG 8.12 instructs to use a **Railway** feature to depict a Crane's track (!?). See DCEG extract below:

![image](https://user-images.githubusercontent.com/70189016/180110278-84150986-677a-4888-b72e-8769884baafe.png)

**Comment by LeoKuzmin** [comment]
I'm concerned the 3rd point of Alvaro's comment from the 21st July: "_Implement 2 new complex lines for Crane features of geometric primitive Curve..._". Probably, I didn’t fully understand when he talks about complex lines.
As far as I remember we discussed and decided that there must be only one central Crane symbol on the line. In fact, xml file of a complex line cannot define a line style where just one central symbol is used.
Such a portrayal of a line feature can only be given by the drawing instructions in a lua script. 
In the case of a linear Crane, we should curry sequentially out drawing instructions of the solid line and the central symbol, either CRANES11 or CRANES13. Therefore  we cannot "implement 2 new complex lines" as new line styles.

**Comment by alvarosanuy** [comment]
> I'm concerned the 3rd point of Alvaro's comment from the 21st July: "_Implement 2 new complex lines for Crane features of geometric primitive Curve..._". Probably, I didn’t fully understand when he talks about complex lines. As far as I remember we discussed and decided that there must be only one central Crane symbol on the line. In fact, xml file of a complex line cannot define a line style where just one central symbol is used. Such a portrayal of a line feature can only be given by the drawing instructions in a lua script. In the case of a linear Crane, we should curry sequentially out drawing instructions of the solid line and the central symbol, either CRANES11 or CRANES13. Therefore we cannot "implement 2 new complex lines" as new line styles.

@LeoKuzmin - Sorry for the confusion. You are right.

**NIWC** - Please implement symbolisation of Curves as per Leo's comment above.

**Comment by mikan66** [comment]
Alvaro: This issue looks like a 100% drop-in of the provided package (symbols and rule) within the Cranes.zip file from Inga.  Correct?

**Comment by alvarosanuy** [comment]
> 

@mikan66 - I'm not sure the Crane.lua file in Inga's Cranes.zip covers all the required instances [Point (visually conspicuous and not) + Curve (visually conspicuous and not) + Surface (Plain and symbolized boundaries)]. I leave the assessment up to you guys.

**The portrayal instructions (after Leo's input above) are:**

1. Point geometry (Non visually conspicuous) - Use existing S-52 symbol CRANES01.svg
2. Point geometry (Visually conspicuous) - Use new symbol CRANES03.svg
3. Curve geometry (Non visually conspicuous):
• Line is displayed as a solid line LANDF colour with the width 0.64 like a Runway feature is depicted.
• The new symbol CRANES11.svg must be drawn in center of the line.
• Viewing Group and Display Priority should be the same as for a Crane feature with surface geometry type.
4. Curve geometry (Visually conspicuous):
• Line is displayed as a solid line LANDF colour with the width 0.64 like a Runway feature is depicted.
• The new symbol CRANES13.svg must be drawn in center of the line.
• Viewing Group and Display Priority should be the same as for a Crane feature with surface geometry type.
5. Surface geometry (Plain and Symbolized) - As per current S-52 instructions

**Comment by mikan66** [comment]
> > 
> 
> @mikan66 - I'm not sure the Crane.lua file in Inga's Cranes.zip covers all the required instances [Point (visually conspicuous and not) + Curve (visually conspicuous and not) + Surface (Plain and symbolized boundaries)]. I leave the assessment up to you guys.
> 
> **The portrayal instructions (after Leo's input above) are:**
> 
> 1. Point geometry (Non visually conspicuous) - Use existing S-52 symbol CRANES01.svg
> 2. Point geometry (Visually conspicuous) - Use new symbol CRANES03.svg
> 3. Curve geometry (Non visually conspicuous):
>    • Line is displayed as a solid line LANDF colour with the width 0.64 like a Runway feature is depicted.
>    • The new symbol CRANES11.svg must be drawn in center of the line.
>    • Viewing Group and Display Priority should be the same as for a Crane feature with surface geometry type.
> 4. Curve geometry (Visually conspicuous):
>    • Line is displayed as a solid line LANDF colour with the width 0.64 like a Runway feature is depicted.
>    • The new symbol CRANES13.svg must be drawn in center of the line.
>    • Viewing Group and Display Priority should be the same as for a Crane feature with surface geometry type.
> 5. Surface geometry (Plain and Symbolized) - As per current S-52 instructions

@alvarosanuy - I agree this rule needs work, I'll see if I can figure it all out.  It's on my short list.

**Comment by LeoKuzmin** [comment]
Unfortunately, a mistake has been omitted. Line width of the curve feature must be 0,64 instead of 0.32.  It should be changed. For other cases of Cranes' portrayal corresponds to described above.
![image](https://user-images.githubusercontent.com/106175259/192571013-cd51e7f5-2b30-4079-96cc-519fe280b7e8.png)

As regards  Viewing Group and Display Priority, they where left from initial Crane.lua script.
viewingGroup = 22220 for visual conspicuous Cranes and
viewingGroup = 32440 for other Cranes.
 Display Priority is equal to 12. I kept it as it is in the initial Crane.lua script. Although S-52 look-up table files for any primitives type of CRANES object have Display Priority is equal to "4". Probably it was changed consciously.

**Comment by mikan66** [comment]
OK, here are some samples as I understand the requirements.  Slightly modified Cranes.lua previously provided here in this issue. I will check in on SEPT 28 if there is agreement. 
![image](https://user-images.githubusercontent.com/4913543/192597725-3b3b2144-3cad-4c07-ad75-6bf7c488197e.png)
![image](https://user-images.githubusercontent.com/4913543/192597965-85bc9bd3-626e-4663-86df-a3827df13133.png)

**Comment by alvarosanuy** [comment]
Looks good to me.

**Comment by mikan66** [comment]
See commit https://github.com/iho-ohi/S-101_Portrayal-Catalogue/commit/e64dd2e19a6450ae569da6a97ae6a4f59b0e7de7

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2
