### ISSUE TITLE
Information Area

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#76]
**Extract from recommendation made in 'Jeff's spreadsheet':**

**First** - DCEG subWG to discuss/confirm Curve and Surface geometric primitives are valid for this feature (Information **Area**).

**Proposed symbology** (All in CHMGF colour)

- **Point** - INFARE51 symbol but with the size of CHINFO07.
- **Curve** - Dashed  with evenly spaced point symbols (smaller INFARE51).
- **Surface** -  Boundary as per curve geometry, supported by centered point symbol INFARE51 (original size).

![image](https://user-images.githubusercontent.com/70189016/177909809-0605434f-de54-48f5-9765-19dfdcf713cf.png)

![image](https://user-images.githubusercontent.com/70189016/177909860-af92a7aa-7807-45b1-815d-b2fc887f8072.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 14/7/22**

1.  Implement the following symbology:
- **Point** - INFARE51 symbol but with the size of CHINFO07 and in CHMGF colour. - **Mikus** to create and upload SVG, CSS and Engineering Drawing files to this Github space.
- **Curve** - Dashed line with evenly spaced point symbols (use symbol created above). - **Inga** to create complex line style and upload SVG, CSS and Engineering Drawing files to this Github space.
- **Surface** - Use simple dashed line in CHMGF colour (same as Curve), supported by area centered S-52 point symbol INFARE51.

2. **NIWC** - To update **InformationArea** rule accordingly.
Viewing Group: 31032
IMO display Category: Other
Radar: O
Display priority: 4

3. **Jeff** and DCEG subWG to review and update/fix the inconsistency (conflict) of guidance of curve encoding in the DCEG, as it allows the curve as a primitive, but recommends to create a thin area instead further in the last bullet point.

**Comment by LeoKuzmin** [comment]
I would like to make more accurate the description of the Surface portrayal. 
Shall we draw border of the surface feature as a simple dashed line, i.e. without embedded symbols? Does the phrase "(same a Curve)" refer to just colour CHMGF?
As regards viewing group 31032, currently this VG name is "Date dependent" with the description: The object is present only during the indicated period. 
Are you sure we should combine 'date dependent' symbol and Information area symbology in the same Viewing Group?

**Comment by alvarosanuy** [comment]
> Shall we draw border of the surface feature as a simple dashed line, i.e. without embedded symbols? Does the phrase "(same a Curve)" refer to just colour CHMGF? 

**No embedded symbols. Just simple dashed line (same line thickness and dash length and spacing).**

> As regards viewing group 31032, currently this VG name is "Date dependent" with the description: The object is present only during the indicated period.
> Are you sure we should combine 'date dependent' symbol and Information area symbology in the same Viewing Group?

**I selected VG 31032 because in S-52 4.0.2 Annex A, Part I, section 14.2, this VG is free and sits under IMO Display 'OTHER' and for the general group called "INFORMATION ABOUT THE CHART DISPLAY'. 
I can't find any relationship with 'Date Dependent'. My understanding is that OEMs must implement a dedicated 'selector' in their ECDIS interface to allow mariners switch ON/OFF the magenta 'd' symbol (CHDATD01) that indicates a feature is encoded with a date dependant attribute (i.e. DATESTA, DATEND). I can't find anything saying that this has to be done using VG 31032. 
Am I missing something here??**

**Comment by LeoKuzmin** [comment]
Please see the file "portrayal_catalogue.xml" of PC.
`      <viewingGroup id="31032">
         <description>
            <name>Date dependent</name>
            <description>The object is present only during the indicated period</description>
            <language>eng</language>
         </description>
      </viewingGroup>
`
There is function ProcessTimes() in the S100Scripting.lua file where VG = 31032 is assigned for the CHDATD01 symbol. 
There is a standard mechanism of management of Viewing groups and Viewing layers (switch ON/OFF). I suppose it is not quite good to combine "date dependence" symbol and Information area symbology in one VG. It will be strange if mariners switch off Date dependence symbols and in the same time all Information Area portrayal is disappeared.
Perhaps, it is more suitable to use VG = 31020 - "nautical publication" for Information Area.
First, it makes more sense. And secondly, this VG is not used anywhere in the PC.

**Comment by alvarosanuy** [comment]
@david - Can you please clarify the use of VG 31032 for 'date dependent' features in the current version of the S101 PC?

It seems that in S-52 PL 4.0.2 (Fig 1 ÉCDIS Display Concept) the allocation of attributes such as priority, VG, etc to objects encoded with  'date dependent' attributes was performed by ECDIS.
Did NIWC allocate a specific VG (31032) to these features in S101 to enforce 'machine readability' principles??

In this case, we will need to allocate **InformationArea** features a different VG under the same group layer. I recommend using VG 31033 instead.

**Comment by DavidGrant-NIWC** [comment]
> @david - Can you please clarify the use of VG 31032 for 'date dependent' features in the current version of the S101 PC?

Short answer: VG 31032 is used for the 'd' symbol in the current S-101 PC
Long answer: See #13

**Comment by DavidGrant-NIWC** [comment]
> In this case, we will need to allocate **InformationArea** features a different VG under the same group layer. I recommend using VG 31033 instead.

Recommend this issue is re-opened until finalized.

I think you mean you want to allocate INFARE51 symbols to a new VG (**InformationArea** portrayal uses VG 26200). The INFARE51 symbol would only be visible when the display category is set to All Others, VG 26200 is enabled, and VG 31033 (proposed) is enabled.

* [ ] Define new ViewingGroup
  * [x] ID  - 31033 (proposed)
  * [ ] Name - "HO note"?
  * [ ] Description - "Minor restrictions or information notices apply"?
  * [x] Add to viewing group layer - 18: Miscellaneous (Other) (proposed)
  * [ ] Register these changes

**Comment by alvarosanuy** [comment]
I did not notice that VG 26200 was already allocated to **InformationArea**. My only intention was to give this feature a dedicated VG so the new symbology could be turned ON/OFF independently. 
I believe there's no need to add another layer of complexity.
Disregard the request for a new VG for **InformationArea**.

**Comment by MikusRL** [comment]
I have created symbol INFARES01.
[INFARE01.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9443518/INFARE01.zip)

I have a concerns of how CHMGF linework would go together with INFARE51 CHMGF color. It might be needed to consider to harmonize the colors of either linework or INFARE51 for areas and centred symbols readability as one object.

![image](https://user-images.githubusercontent.com/72803214/187173641-29b2c83f-15d9-47ff-b772-082650e7e4a8.png)

Same as with previous - no metadata attributes updated - see #28 .

**Comment by MikusRL** [comment]
Leo kindly did the point symbols as well. Thank you.

Leo comments:
Please, find attached zip file with prepared symbols and doc with description.
[InformationArea.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9445986/InformationArea.zip)

I have prepared the symbol (INFARE01.svg) for point Information Area feature as Alvaro wrote, i.e. the drawing as INFARE51,  the size, colour and pivot point as CHINFO07. As regards a position of pivot point, since Alvaro did not mention it, it definitely must be allocated in the symbol center

Since the embedded symbol must be identical to a point symbol, I have duplicated INFARE01 with new name  (EMINFARE.svg) and description.

The INFARE51.xml file defines the line pattern. As there are nothing requirements for spacing, size and number of dashes, I used as the line style CTNARE51 (border of Caution Area) as initial.

**Comment by alvarosanuy** [comment]
@LeoKuzmin 

- Do we need 2 identical symbols (INFARE01 & EMINFARE) or can we use EMINFARE for Point features and disregard INFARE 51??

**Comment by LeoKuzmin** [comment]
@alvarosanuy 
Of course we can use one of the symbol for both geometry types of the feature. However, usually, a point symbol is usually different from the embedded symbol of corresponding line style, e.g. Pilotage District, Foul Ground. I've assumed that an embedded symbol could be changed, for example it can be decreased to be different from point symbol. If you consider that we should use one symbol file, I would prefer to keep the INFARE01 symbol as a general case.

**Comment by alvarosanuy** [comment]
> 

We will then use INFARE01.svg for the Point symbol and I'll ask you to amend and re-supply INFARE51.xml so it pints to the same SVG symbol.

**Comment by LeoKuzmin** [comment]
Please, find the attached zip file with amended files xml and doc.
[InformationArea.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9468015/InformationArea.zip)

**Comment by DavidGrant-NIWC** [comment]
Implemented by https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/110, but please verify:
* [ ] ViewingGroup = 26200 (Standard Display)
    * This seems wrong - standard display should be the minimum information for safe navigation
    * InformationArea has an alias to M_NPUB, which uses 31020 in S-52
* [x] DrawingPriority = 12 for points, curves, and surfaces
    * Seems wrong - points are usually higher priority than lines, which are higher priority than areas
* [x] DisplayPlane = UnderRADAR
* [ ] Plain and symbolized boundaries use same portrayal
* [x] Simplified and paper chart points use same portrayal

Note that using "INFARE01" as the centered area symbol makes it impossible to distinguish a large area from a single point. The "i" near the "LocalDirectionOfBuoyage" symbol is actually associated with the entire area - the edges are masked by the chart boundary.
![image](https://user-images.githubusercontent.com/62906211/189227306-2979a6cb-4db5-432a-9ca4-ae93ee356da8.png)

**Comment by alvarosanuy** [comment]
> ViewingGroup = 26200 (Standard Display)
> * This seems wrong - standard display should be the minimum information for safe navigation
> * InformationArea has an alias to M_NPUB, which uses 31020 in S-52

**Agree** - by definition **InformationArea** is _'an area for which general information regarding navigation, **but not 
directly related to safety of navigation**, is available_'

**Please amend VG to 31020**

> DrawingPriority = 12 for points, curves, and surfaces
> * Seems wrong - points are usually higher priority than lines, which are higher priority than areas

This is not always the case in S-52 (there are numerous examples where the same object has the same DP irrespective of the geometric primitive. In fact this is the case for M_NPUB). My understanding is that ECDIS must, when DP are the same between **different** features (not sure there's a use case when the same feature overlaps itself using different geo. primitives, but the same principle applies), give priority in the following order: Text-Point-Line-Area. The tricky part is when different features, of the same geo. primitive and DP, share location - who wins? Some recommendation exist in S-98 Annex C (C-7.2.9).
In short, I do not see why the same feature has to have different DP based on the type of geometric primitive ..... I would leave DP=12 for all **InformationArea** features, irrespective of their geometric primitive.
**Anyone else has an strong opinion on this??**

> * Plain and symbolized boundaries use same portrayal

This is true but please note that the complex line used for Curves is different than the boundary used for Surfaces (refer to my comment from 21/7/22 regarding the Decision made at Portrayal subWG meeting on 14/7/22 + response to Leo's question on 22/7).


> Note that using "INFARE01" as the centered area symbol makes it impossible to distinguish a large area from a single point. The "i" near the "LocalDirectionOfBuoyage" symbol is actually associated with the entire area - the edges are masked by the chart boundary.

INFARE01 is not the symbol to be used as the centered area symbol. The symbol to use is INFARE51 (refer to my comment from 21/7/22 regarding the Decision made at Portrayal subWG meeting on 14/7/22).

**Comment by TDYCARHugh** [comment]
Regarding the choice to prioritize points above lines and lines above areas. This is to prevent features from being hidden or overwritten by other features. An area with a solid fill will paint over lower priority symbology. A fat line could cover a symbol.  If an area only has a line style or a centered symbol then the priority could be higher if desired.  Also keep in mind that in S-52 there was only one priority per feature thus all the symbology of the feature (with the exception of Text) was drawn at the same priority. In S-100 priority can be assigned to each drawing instruction so Text or a centered symbol can be given a higher priority than the linestyle or fill instructions.

**Comment by DavidGrant-NIWC** [comment]
* Changed viewing group to 31020
* Updated name of viewing group 31020
    * old: "nautical publication (M_NPUB)"
    * new: "information area or nautical publication (M_NPUB)"
* DrawingPriority of 12 matches S-52 M_NPUB for points and areas
    * I agree that it's ok to have all match.
* Symbology
    * Points: INFARE01.svg
    * Curves: INFARE51.xml
    * Surfaces: INFARE51.svg + CHMGF dashed line
* Points now draw over RADAR to match S-52 M_NPUB
    * lines and areas are below RADAR

![image](https://user-images.githubusercontent.com/62906211/189422019-cfecfb35-2ad3-41f3-9d54-08cc289a0792.png)

**Comment by alvarosanuy** [comment]
Implemented in PC 1.0.2
