### ISSUE TITLE
Update Information

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#78]
This issue has been created as an Action item from [https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/5](url)

The objective is to discuss how **UpdateInformation** would be implemented in ECDIS and what symbology (if any) it would require.

The goal is to implement some default symbology for all geometric primitives (P, C, S) in PC 1.1.0 to support testing before a final decision is made for S-101 2.0.0. Note that, in parallel, we plan to seek Singapore's Lab support to engage mariners and recommend their the preferred implementation of the 'Review Update' function in ECDIS (to be implemented in S-101 2.0.0 or later ...).

**Comment by mikan66** [comment]
I offer the below to assist in further discussions. This is an example of what we have seen in a sample update dataset that contains feature: 'UpdateInformation'.  We indicated that it was "added" and then you can review the text in the Pick Report.  This is strictly prototype visualization for our own use and is not indicative of any presentation requirements. 

![image](https://user-images.githubusercontent.com/4913543/178803222-7179a2a7-f4a8-4233-a96d-4b258b9ef47e.png)

**Comment by alvarosanuy** [comment]
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/99

**Comment by alvarosanuy** [comment]
An option could be amending the modelling of **UpdateInformation** to include a new mandatory attribute called 'Update type'. The attribute would be an Enumerated List (EN) with the following options: New; Modified; Deleted.

The intention with introducing a new attribute is to help with portrayal as it would trigger existing S-52 symbology currently in use by the 'Review Update' function in ECDIS. 

- SY(CHRVDEL1)    Point feature has been deleted by an automatic update
- SY(CHRVID01)     Point feature has been inserted or modified by an automatic update
- LC(CHRVDEL2)     Line feature or area boundary has been deleted by an automatic update
- LC(CHRVID02)      Line feature or area boundary has been inserted or modified by an automatic update

The issue with this proposal is that the **UpdateInformation** symbology would clash with the symbols depicted by ECDIS if the mariner decides to use the 'Review Update' functionality in ECDIS. I believe that the existing functionality should be amended to only depict **UpdateInformation** features within the ENC update and, based on the value of the new attribute, portray them accordingly alongside the change explanation and encoded in the **updateDescription** attribute.

With this approach, **UpdateInformation** would be only portrayed and referred to by the 'Update Review' functionality and not automatically symbolised by Portrayal Catalogue Rules. Producers (HOs) will become responsible for systematically encoding this feature when delivering safety critical info to mariners via ENC Updates. S-100 ECDIS (or the S-100 side in a DF-ECDIS) wouldn't any longer highlight changes if not accompanied by an **UpdateInformation** feature.

**Comment by alvarosanuy** [comment]
I just noticed the following guidance in Edition 1.0.0 of S-98 Annex C (Table C-16 and section 12.11.2). See images below.

Although the text in Table C-16 could be interpreted as 'aligned' with the proposal I presented in the previous Github comment, the 'Update Review' mechanism is still confusing and needs to specify how ECDIS will 'identify the chart corrections in a dataset'. 

- [ ] Based on **UpdateInformation** features only
- [ ] Identifying modifications to objects without considering **UpdateInformation** (as currently done in S-57 ECDIS)
- [ ] A combination of the above???

It looks like the symbolization bit does not need to change (retain as per S-52).
The task for us now is to decide and document how we want ECDIS to identify the features that changed and the 'type of change' so they can be symbolised accordingly.
**More food for thought !**

![image](https://user-images.githubusercontent.com/70189016/183796407-8987493e-7d46-4d57-9d76-f731ebd3bbdb.png)


![image](https://user-images.githubusercontent.com/70189016/183796169-15d113e7-d046-48f4-9a1c-fa2e5066b8ca.png)

**Comment by mikan66** [comment]
So, we have currently prototyped a combination approach for internal testing.  In the earlier screen-shot for the **UpdateInformation**, the indication is that it was an "Added Feature" (via the update dataset) and the key point is that this "feature" provided information via the text Attribute about a specific surface.   

The main take away is to note that most of the information in the update dataset was analogous of the S-57 approach. Only very specific **UpdateInformation** records were provided and not for every updated record in the update dataset.

**Comment by TomRichardson6** [comment]
Casting my mind back on this to the development of the DCEG my recollection is that this Update Information as a feature was intended to allow a producer to clearly indicate a specific change or highlight a set of changes that are temporary and preliminary in nature. ~But in all of those discussions we considered the review update functionality to be separate and that is driven by the S-57 update instructions themselves. The assumption was that some producers may not use these at all due to the additional encoding effort but we wanted to support those that wished to. So I would not support creating Update Information features to duplicate those instructions. So I think there has been some misunderstanding introduced here via S-98.

**Comment by alvarosanuy** [comment]
More confusion ..... I came across this section in S98 Annex C where it looks somebody has already decided on how **UpdateInformation** features should portray in S-101. I personally think all this needs more discussion particularly around the way **UpdateInformation** and ECDIS' ''Update review' function would work/complement each other.

![image](https://user-images.githubusercontent.com/70189016/190324102-59c38435-663d-4513-aff7-0f879f467490.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. There was consensus within the subWG that **UpdateInformation** should:

- Replace the current (S-57/S-52) 'Review Update' ECDIS functionality
- The feature should be remodeled to include a new mandatory attribute called 'Update type' (or similar). This attribute would be an Enumerated List (EN) with the following options: New; Modified; Deleted.
- Symbology should match S-52 symbology based on the geometry type and the value of the **updateType** attribute.
- The symbology, etc would only be presented to mariners when they run the 'Review update' process (as per current practice)
- The best practice for the management and presentation to the mariner of cumulative ENC Update changes needs more discussion.

2. **It is paramount that the S101PT makes a decision (support) the proposed way forward ASAP** so all related documentation (S-98, DCEG, FC, etc) can be updated and provide a clear and authoritative way forward.. **Alvaro** to present a paper at the next S101PT meeting if necessary.

3. The subWG recognises that mariners' input would be extremely advantageous to support any decision. Consequently it is recommended presenting a proposal to the Singapore lab (or other testbeds) to specifically focus on the 'ENC update review' topic from the user perspective.

4. It was also recognised that, in order for the proposed way forward to succeed, ENC production softwares will have to play an important part in assisting encoders with the semi-automated generation of **UpdateInformation** features (minimal user intervention) when compiling ENC Updates.

**Comment by TomRichardson6** [comment]
@alvarosanuy thanks for flagging this as a priority, I think we should commence work on a paper which PT10 can hopefully endorse for inclusion in edition 1.2.0 an interim FC could potentially be created to support testing. 

For me this approach needs input from the production software providers to ensure that production systems can populate this new information without burdening producers. Your 4. I think we should aim to circulate the paper to this group well ahead of PT10.  

A potential benefit of this approach is that the ECDIS route check function could be used to highlight items since a previous route check. 

I would be happy to work with you on the paper.

**Comment by alvarosanuy** [comment]
> @alvarosanuy thanks for flagging this as a priority, I think we should commence work on a paper which PT10 can hopefully endorse for inclusion in edition 1.2.0 an interim FC could potentially be created to support testing.

@TomRichardson6  - Agreed. I'll prepare a draft and share with you for comments before we socialise it with ENC production software companies for their input.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- [x] **Alvaro** to submit a paper to S-101PT10 to present this topic and seek endorsement on the preferred way forward.

**Comment by alvarosanuy** [comment]
Issue also exists in DCEGsWG
https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/41

**Comment by alvarosanuy** [comment]
This issue can be closed as the DCEGsWG has decided to implement proposed changes for testing in Edition 1.2.0 (https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/41).
Also, note the creation of 'follow up' portrayal issues such as:
 https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/151 and
https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/152
