### ISSUE TITLE
Review symbology for categoryOfLateralMark 3 & 4 (Preferred Channel marks)

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#79]
This issue has been created as a result of a decision made in https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/59

The objective is to discuss possible changes to the existing symbology for **categoryOfLateralMark** 3 (preferred channel to starboard lateral mark) and 4 (preferred channel to port lateral mark) so they depict more like INLAND ENC symbols. If implemented, changes should flow to **virtualAISAidToNavigationType** values 7 & 8 (?).

**Comment by HolgerBothien** [comment]
For simplified symbols it should be easy since they have a color fill.
Paper chart symbols do only show the shape.
We (SevenCs) using color filled paper chart symbols for a very long time, it is accepted by the IHO and appreciated by our customers. We happy to share the knowledge and discusses ways forward. This will be of course a work package with significant efforts.

**Comment by LeoKuzmin** [comment]
I am concerned the using of lateral marks symbols for different IALA zones. The feature type Virtual AIS Aid To Navigation does not have the attribute "marks navigational – system of" to define a suitable symbol for port or starboard lateral mark. In this case the lua script has to search an overlapping feature "Navigational System of Marks"  to define IALA zone. 
This task can be resolved by lua scripts. However, as far as I understand we would like to avoid the decision of topological tasks during the portrayal building.
Probably, this question has been arisen in other issue. If so, please, give a reference.

**Comment by TomRichardson6** [comment]
I support adopting the colored fills as used by SevenCs. I would propose that this change could follow edition 1.1.0 and be included in 1.2.X or 2.0.0. 

I also agree with @LeoKuzmin that it is undesirable to have to query another object and therefore propose a modelling change within the DCEG to add the marks navigational system of simple attribute to the Virtual AIS Aid to Navigation feature type DCEG (1.0.2) ref 21.3.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. The subWG decided to approve the use of INLAND-type symbols for 'preferred channel' marks (affects Lateral Buoys, Lateral Beacons and Virtual AIS features). Below is a screenshot from the GI Registry showing ALL the available INLAND symbols.
![image](https://user-images.githubusercontent.com/70189016/212196673-fcfb2dec-6a52-4853-91ec-5c3726190a11.png)

2. After more investigation it seems we will need to develop all the symbols ourselves as the INLAND ones are not enough and there are no symbols for beacons. IALA system allows for 3 different buoy shapes as per the screenshot below. We should develop 9 new symbols to cater for the 3 different buoy shapes (can, conical, pillar & spar) - (@HolgerBothien - would you mind assisting with this task ??)
![image](https://user-images.githubusercontent.com/70189016/212196234-6b356ee4-9df5-4697-92b8-fbe736b8e945.png)

3. For Beacons, 'paper chart' symbols could be left unchanged but we should develop 2 new 'simplified' symbols using BCNLA15 and BCNLAT16 as an starting point and making the new symbol taller to allow for a horizontal band of the opposite colour in the middle (@HolgerBothien - would you mind assisting with this task ??)

4. Preferred channel (Starboard and Port) symbols must be developed for Virtual AIS features. (@HolgerBothien - would you mind assisting with this task ??)

5. In order to implement portrayal, the modelling of **VirtualAisAiddToNavigation** must be amended to include the attribute **marks navigational – system of** as a conditional-mandatory to be populated only when **virtualAisAidToNavigationType**=7 or 8. 

6. Mapping instructions will need to be discussed in more detail once we have the prototyped symbols ready.

**Comment by HolgerBothien** [comment]
Yes, I can assist with the above mentioned task. But why we should limit the use of color fill symbols to the bifurcation buoys. At least the most common lateral, cardinal, safe water and special prurpose buoys should be taken into acount.

**Comment by alvarosanuy** [comment]
> Yes, I can assist with the above mentioned task. But why we should limit the use of color fill symbols to the bifurcation buoys. At least the most common lateral, cardinal, safe water and special prurpose buoys should be taken into acount.

This issue is specifically about 'Preferred channel' marks so, although we could look at extrapolating to other types of marks the complexity of the job changes and the intention needs to be endorsed by the subWG (and even maybe the PT).
I would prefer to start slow and see how everything looks on the screen......
The 'preferred channel' marks were picked up from the crowd because 'paper chart/Traditional' symbols do not have colour and they mainly rely on a topmark to convey the purpose of  a mark (the problem here is that preferred channel does not have a unique topmark shape). In a similar way, 'Traditional symbols' rely on their colour to convey their purpose but, 'preferred channel' currently depicts just like any other lateral mark.
In fact, checking my previous comment regarding 'Paper chart/Traditional' symbols for **Beacons** (bullet point # 3), I now think that we may also need to introduce colour to their symbols. This would require 6 (?) additional new symbols as we should create versions for all 3 possible shapes (Pile, Tower & Lattice).

- Can the rest of the subWG please comment on their understanding of the scope of this Github issue? Should we introduce colour to 'Paper chart/Traditional' symbols? I personally think that, for preferred channels, there's a good reason to 'break the norm' but I think is worth asking as some of you may not have yet grasped what we are trying to do here ....

**Comment by HolgerBothien** [comment]
For buoys we would need 8 new symbols. They would look like:
![image](https://user-images.githubusercontent.com/88826517/213137841-63271cab-25e9-46fe-b1ae-251f9c386a6a.png)
This are variants of the existing symbols for paper chart depiction.
For beacon only the shape : pile and tower could have a colour fill. The lattice symbol cannot easily be filled.
I wonder how important beacons are in this scope.

**Comment by HolgerBothien** [comment]
Colour filled beacon symbols could look like:
![image](https://user-images.githubusercontent.com/88826517/213217745-d07a6512-83b2-4e30-a27c-72ff5d1d2675.png)

**Comment by HolgerBothien** [comment]
The BCNGEN* symbols can be used for beacons with shape = pile or buoyant beacons, and BCNTOW* symbols for beacon shape = tower. All other shapes will be presented as before.
And again when changing this type of buoys why not the other lateral buoys, cardinal buyos, isolated danger, safe water and special purpose buoys as well. The symbols are all existing (Ok, the needs to be converted to SVG)

**Comment by TomRichardson6** [comment]
@alvarosanuy responding to your question on scope, I support the proposal from Holger to expand to all buoys and beacons. I agree that the PT would need to endorse this so we can aim to do this there and include it in 1.2.0, having prepared the symbols and rules ahead of that meeting. From my experience of ECS systems and other applications there is strong user preference for the colored symbols and these are more intuitive. This would be an improvement over S-57 ENCs although I guess not for Holger's customers! I'd suggest that a new issue is raised if the consensus is in support of that approach to make that scope clear.

**Comment by alvarosanuy** [comment]
Thanks Holger!. They look great and will facilitate the discussion within the subWG. Look forward to the prototypes for the **Simplified** versions of buoys and beacons and V-AIS.

As suggested by Tom, I think the best way forward to focus the discussion on new **Paper Chart** symbols for the other types of buoys/beacons is to create a dedicated Github issue. I'll do that.

**Comment by HolgerBothien** [comment]
Simplified Buoy symbol prototypes based on existing BOYLATxx symbols.
![image](https://user-images.githubusercontent.com/88826517/213397569-ac454e4d-c360-4581-b60a-c1eba542ddfb.png)
Simplified beacons:
![image](https://user-images.githubusercontent.com/88826517/213397848-6866271c-f460-4473-9a3f-b0d9c94800ef.png)
Note that here we have two shapes (major and minor lateral beacons)
In S-52 there are already entries in the simplified lookup tables for color 3.4.3 and color 4,3,4. 
That makes the changes in the rules relatively simple.

**Comment by HolgerBothien** [comment]
And here are the prototypes for the virtual Aids to Navigation symbols:
![image](https://user-images.githubusercontent.com/88826517/213440852-42ee1438-91c2-4edb-af52-890f667a770e.png)
For this I have already made the SVGs and the engineering drawings. The are together with the existing symbols in the following archive:
[VirtualAtoN.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10456639/VirtualAtoN.zip)

**Comment by HolgerBothien** [comment]
All the other symbols above and more if we going to color fills for paper chart symbols in general, I have in S-52 format. They need to converted to SVG. I will ask Hugh if he can do that.

**Comment by HolgerBothien** [comment]
[Simplified.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10511291/Simplified.zip)

**Comment by HolgerBothien** [comment]
Here are the symbols for the simplified mode. The symbols for the paper chart mode are part of the package posted in issue 117.

**Comment by HolgerBothien** [comment]
```
"BCNLAT","","SY(BCNDEF13);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP1|","SY(BCNLAT23);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP2|","SY(BCNLAT23);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP7|","SY(BCNLAT23);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP1|","SY(BCNLAT24);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP2|","SY(BCNLAT24);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP7|","SY(BCNLAT24);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP3|","SY(BCNLAT17);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP4|","SY(BCNLAT17);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|BCNSHP5|","SY(BCNLAT17);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP3|","SY(BCNLAT18);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP4|","SY(BCNLAT18);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|BCNSHP5|","SY(BCNLAT18);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3,4,3|","SY(BCNLAT17);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4,3,4|","SY(BCNLAT18);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP1|","SY(BCNLAT21);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP2|","SY(BCNLAT21);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP7|","SY(BCNLAT21);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP1|","SY(BCNLAT22);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP2|","SY(BCNLAT22);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP7|","SY(BCNLAT22);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP3|","SY(BCNLAT15);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP4|","SY(BCNLAT15);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|BCNSHP5|","SY(BCNLAT15);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP3|","SY(BCNLAT16);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP4|","SY(BCNLAT16);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|BCNSHP5|","SY(BCNLAT16);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","BCNSHP6|CONVIS1|","SY(CAIRNS11);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","BCNSHP6|","SY(CAIRNS01);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR3|","SY(BCNLAT15);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"
"BCNLAT","COLOUR4|","SY(BCNLAT16);TE('bn %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27020"

```

**Comment by HolgerBothien** [comment]
The logic can be generated from the S-52 lookuptable above. Note, that there are no new entries, only some SY() instructions have been changed, This is the simplified mode,

**Comment by HolgerBothien** [comment]
And here for BOYLAT:
```
"BOYLAT","","SY(BOYDEF03);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP1|COLOUR3,4,3|","SY(BOYLAT16);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP1|COLOUR4,3,4|","SY(BOYLAT15);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP2|COLOUR3,4,3|","SY(BOYLAT26);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP2|COLOUR4,3,4|","SY(BOYLAT25);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM3|COLOUR3,4,3|","SY(BOYLAT26);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM3|COLOUR4,3,4|","SY(BOYLAT25);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM4|COLOUR3,4,3|","SY(BOYLAT16);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM4|COLOUR4,3,4|","SY(BOYLAT15);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP1|COLOUR3|","SY(BOYLAT14);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP1|COLOUR4|","SY(BOYLAT13);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP2|COLOUR3|","SY(BOYLAT24);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","BOYSHP2|COLOUR4|","SY(BOYLAT23);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM1|COLOUR3|","SY(BOYLAT24);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM1|COLOUR4|","SY(BOYLAT23);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM2|COLOUR3|","SY(BOYLAT14);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"
"BOYLAT","CATLAM2|COLOUR4|","SY(BOYLAT13);TE('by %s','OBJNAM',2,1,2,'15110',-1,-1,CHBLK,21)","8","O","STANDARD","27010"

```

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 11/5/23**

- Decision to move ahead with implementation in PC 1.2.0.

- [x] Alvaro to register symbols in the GI Registry.
- [x] Alvaro to create DCEGsWG issue to request:

- Inclusion of the attribute "marks navigational – system of" in **VirtualAISAidToNavigation** in order to assist with the mapping of the correct 'preferred channel mark' symbol. Although  this task can be resolved by LUA scripts, the preferred option is to avoid performing topological tasks during the portrayal building.
- Making the encoding of the attribute "marks navigational – system of" mandatory when 'category of lateral mark' = 3 or 4 **OR** 'virtual AIS aid to navigation type' = 7 or 8.

**Comment by alvarosanuy** [comment]
> And here are the prototypes for the virtual Aids to Navigation symbols: ![image](https://user-images.githubusercontent.com/88826517/213440852-42ee1438-91c2-4edb-af52-890f667a770e.png) For this I have already made the SVGs and the engineering drawings. The are together with the existing symbols in the following archive: [VirtualAtoN.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10456639/VirtualAtoN.zip)

@HolgerBothien - Engineering Drawings are missing for the following 4 V-AIS symbols: VATON12, VATON13, VATON14 & VATON15 (VATON1 to 11 have been already registered).
Can you please generate & upload their ED so I can finalise their registration? Thanks!

@HolgerBothien - **I just noticed that the V-AIS symbol for Emergency Wreck Marking was created and registered using the name VATON12.
The 4 symbols above will need to be re-created to change their names to: VATON13, VATON14, VATON15 & VATON16.
Engineering Drawings will have to match their new names.**

**Comment by HolgerBothien** [comment]
[VATON13-16.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11609420/VATON13-16.zip)
Please find here the renamed symbols (title changed inside as well) and the EDs for them.

**Comment by alvarosanuy** [comment]
**Completed registration of 8 Physical marks and 4 V-AIS on 02/06/23**

@mikan66 - Please note that I had to change the name of the following SVG files (name already existed in the Registry - used by Inland ENC Domain):

BCNLAT23 changed to BCNLAT27
BOYLAT25 changed to BOYLAT28
BOYLAT26 changed to BOYLAT29

I changed the name of the file; the symbol name within the XML file & the name in the Engineering Drawings.

**Final list of files to use in PC 1.2.0 is below:**
[Preferred Channel Marks_FINAL.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/11631147/Preferred.Channel.Marks_FINAL.zip)

**Comment by TomRichardson6** [comment]
All

Test Dataset 21 has been updated so that Virtual AIS AtoNs exist for both types of preferred channel mark. Please advise if further test datasets are needed consider that existing buoys/beacons in TDS 20 cover the physical aids. 

https://github.com/iho-ohi/S-101-Test-Datasets/tree/main/dev/cells/101AA00DS0021/5

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/d3911c5c-fe7d-4386-883c-2e339a1e3da7)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 17/10/23**

- Close this issue and open a new one focused on confirming mapping rules can identify the system of lateral marks in place at the location of the navaid and select the right 'preferred channel mark' symbol accordingly.
