### ISSUE TITLE
No Geometry Feature: Island Group (IslandGroup)

### ISSUE THREAD

**Issue by mikan66** [S-101-Portrayal-subWG/Working-Documents#83]
A rule is needed to define portrayal for this feature which has permittedPrimitives defined as "noGeometry".
Alias: C_AGGR

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. **Jeff** to take the discussion to the DCEG subWG to ensure there's a way to enable the portrayal of **featureName** when encoded in features with 'no geometry' (change in modelling or encoding guidance). The decisions would impact on all features listed in Github issues 80 - 87.
2. S-98 probably requires some additional instructions on how to expose this information by 'pick report', but to be discussed once DCEG discussions are finalized.
3. Leave issue open until outcome from DCEG subWG discussions.
4. Not for 1.0.2.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. Implement text instruction for when **featureName** is set to 'display'

**Comment by mikan66** [comment]
@alvarosanuy, please provide viewing group and radar info for "Island Group" to complete portrayal for S-101.

**Comment by alvarosanuy** [comment]
> @alvarosanuy, please provide viewing group and radar info for "Island Group' to complete portrayal for S-101.

- [ ] **Standard display - VG=21060 (as per S-57 LNDRGN).

- [ ] **Over-radar**

**Other views???**

**Comment by alvarosanuy** [comment]
Implemented in PC 1.1.0
