### ISSUE TITLE
NIWC Testbed Update - Slide # 17 - Id values in portrayal catalogues

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#9]
**S-101PT5 Action 24** - Discuss paper S-101PT5-21

[S-101PT5_21_EN_NIWC Test Bed Report_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5290033/S-101PT5_21_EN_NIWC.Test.Bed.Report_S101PT5_V1.pdf)

![image](https://user-images.githubusercontent.com/70189016/94633025-8377ee80-030f-11eb-8d3c-0b4ca27e2924.png)

**Comment by DavidGrant-NIWC** [comment]
Additionally, _id_ should match portrayal register _xmlID_ attribute:

![image](https://user-images.githubusercontent.com/62906211/95348804-6487d800-088c-11eb-8e67-0e783cf21606.png)

**Comment by alvarosanuy** [comment]
Shouldn't the 'id' follow the numbers listed in the IHO Registry? (i.e. id=1 Standard display).
![image](https://user-images.githubusercontent.com/70189016/95670887-c02fc980-0bdc-11eb-8bc9-fa5f85645304.png)

**Comment by DavidGrant-NIWC** [comment]
My assumption is that the "No" column in the registry corresponds to 'itemIdentifier' in S100_RE_RegisterItem.

Although 'xmlID' could be set to match the number, for readability of the portrayal catalog I recommend something more meaningful such as "Base", "Standard", etc. as noted in the issue. Whatever is chosen for xmlID, each value must be unique within the registry to support synchronizing display modes across portrayal catalogues and product types.

> ![image](https://user-images.githubusercontent.com/62906211/95885888-d740f980-0d4b-11eb-83ab-41116feee6ce.png)

**Comment by TDYCARHugh** [comment]
We could change the type of these id to be an XML ID type which is not allowed to start with a number and a camel code from the register to have the same id across portrayal catalogues.

**Comment by DavidGrant-NIWC** [comment]
We would like to update the S-101 PC to use the xmlID, however we don't know what the values should be.
* The registry does not currently show a value for xmlID. The column should be added. Action for KHOA?
![image](https://user-images.githubusercontent.com/62906211/104240342-e9edcc00-5429-11eb-9fea-a1e8c95a01c0.png)

**Comment by rmalyankar** [comment]
The No. column is automatically generated when the table is displayed in the registry user interface, the numbers are not unique identifiers.

**Comment by TDYCARHugh** [comment]
The itemIdentifier is a primary key in the register so is unique.
CREATE TABLE IF NOT EXISTS `S100PR`.`PR_RegisterItem` (
  `itemIdentifier` INT NOT NULL AUTO_INCREMENT,
  `itemType` TINYINT(4) NOT NULL,
  `name` VARCHAR(100) NULL,
  `definition` VARCHAR(1000) NULL,
  `remarks` VARCHAR(1000) NULL,
  `itemStatus` TINYINT(4) NULL DEFAULT 1,
  `dateAmended` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `dateAccepted` DATETIME NULL,
  `register` INT NULL,
  `referenceSource` SMALLINT(6) NULL,
  PRIMARY KEY (`itemIdentifier`), ...

The xml id needs to comply with NCName and cannot start with a number.  So perhaps we can generate the xmlId in the register using the itemIdentifier number prefixed with 'PR_'.

**Comment by rmalyankar** [comment]
Alvaro's formulation of this item in the slide is right; adding the xmlID field to the registry (with a unique constraint) would provide the necessary information.

Either that, or the PR_<identifier> idea, or a concatenation+compression of the item class, name field and itemIdentifier, for example "displayMode.base.<itemIdentifier>". Or if a new constraint is added requiring the name to be unique in the table (e.g., "baseECDIS"?), itemIdentifier can be left out and it would still be meaningful and synchronizable ("displayMode.baseECDIS").

In any of the alternatives, the FCB will also need to be updated.

**Comment by TDYCARHugh** [comment]
I don't understand the reason to concanate a bunch of fields together.  The itemIdentifier is unique across all types in the portrayal registry.  So the only thing needed is to add something to the beginning to make it a valid xml id. I suggested PR_ because the id is unique to the Portrayal Register space.  It looks like the GUI for the Portrayal register should show the itemIdentifier or xml id built from the itemIdentifier. in the GUI and in exports.

**Comment by rmalyankar** [comment]
The top note in this discussion says "meaningful value". If documents need to identify a specific display mode something like displayMode.baseECDIS is more useful than PR_12345. Otherwise not a significant issue.

**Comment by TDYCARHugh** [comment]
Aha, I don't think this id was ever intended as something a human would be dealing with, it is just meant to be a unique identifier used for reference links etc. The name, definition and remarks would be more human meaningful content.

**Comment by DavidGrant-NIWC** [comment]
Recommended actions:
* [ ] Choose a format for xmlID (auto generated from the itemIdentifier, or "meaningful value")
* [ ] Ensure IHO portrayal registry web page is updated to show xmlID to users

**Comment by alvarosanuy** [comment]
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144341941-7305f62f-2619-450b-bc1f-6aa0b80f1318.png)

**Comment by alvarosanuy** [comment]
**Decision made at Portrayal subWG meeting on 26/7/22**

1. Leave this issue open as no progress has been made.
2. **Jeff** to organise and chair a focus group meeting as directed by S-101PT decision **PortSG-47**.
3. No impact on publication of PC 1.0.2 or 1.1.0.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. Still work in progress
2. @JeffWootton - Can you please provide an update on the progress of this task?

**Comment by alvarosanuy** [comment]
@JeffWootton - Can you please provide an update on the progress of this task?

**Comment by DavidGrant-NIWC** [comment]
When we do get around to defining values for these entries, note that we are inconsistent in allowing underscores. It would be nice if there was a single type defined in one place that is used consistently in all of the schemas.

|Schema|Constraint|Used by|
|:---|:---|:---
|S100BaseModel.xsd `IDString`|[0-9a-zA-Z_]*|Portrayal input XML|
|S100SymbolDefinition.xsd `IDString`|[0-9a-zA-Z]*|PC and alert catalog entries (no underscores)|
|S100Presentation.xsd `Reference`|[0-9a-zA-Z_]*|Drawing instructions (supports various references, including to features)
|S100FC.xsd `StringCode`|[A-Za-z][A-Za-z0-9_]*|FC entries
|S100Pixmap.xsd `ColorId`|[a-zA-Z0-9_]+|Pixmap color entries (3 chars max)

**Comment by JeffWootton** [comment]
@alvarosanuy : I spoke to Yong yesterday and this issue needs to be included in the KHOA program of work for the GI Registry before any work can be done.  A GI Registry GitLab repository Issue has been created for GI Registry action that points to this #9.  This GitLab Issue has been labelled as Critical.

**Comment by TDYCARHugh** [comment]
If there is a desire to keep the portrayal Id values consistent and unique across portrayals then we could consider prefixing the id number with something like an agency code.  This would allow for the case where an unofficial or local portrayal catalogue is developed.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

- [x] **Alvaro** to follow up with @JeffWootton to find out key information on the GitLab issue such as: written requirements, KHOA's implementation plans and 'planned resolution date'. Direct access to the issue in the GI Registry GitLab repository would be beneficial for this and for other future Registry related tasks. 
- [x] Alvaro to include this issue in his PsWG report to S101PT10

**NIWC requested that the update to the GI Registry is completed well before the target day for the release of PC 2.0.0.**

**Comment by alvarosanuy** [comment]
@JeffWootton  - Can you please talk to Yong/KHOA and provide an update on this topic?

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- [x] Alvaro to seek status update with @JeffWootton.

**Comment by alvarosanuy** [comment]
> [ ] Alvaro to seek status update with @JeffWootton.

Email sent on 20/10/23

**Comment by alvarosanuy** [comment]
**Email from Yong below (received 06NOV2023):**

Dear Alvaro and Jeff,

The xmlID for the Portrayal register has been added on the interface as requested. Please let me know it if you have further clarification or asks.

https://registry.iho.int/portrayal/list.do

- [x] **NIWC** (and others) please provide feedback before we Close this issue

**Comment by alvarosanuy** [comment]
**Concerns on current xmlID implementation in the GI Registry raised by @DavidGrant-NIWC below:**

@JeffWootton & @ **Yong Baek** - Your views on Dave's comments ?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/asanchez/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU link="#0563C1" vlink="#954F72" style='tab-interval:36.0pt'>


<p class=MsoNormal style='mso-outline-level:1'><b><span lang=EN-US
style='mso-ligatures:none;mso-ansi-language:EN-US'>From:</span></b><span
lang=EN-US style='mso-ligatures:none;mso-ansi-language:EN-US'> Grant, David M
(52400) CIV USN NIWC ATLANTIC VA (USA) &lt;<a
href="mailto:david.m.grant22.civ@us.navy.mil">david.m.grant22.civ@us.navy.mil</a>&gt;
<br>
<b>Sent:</b> Saturday, 27 January 2024 5:39 AM<br>
<b>To:</b> Sanchez, Alvaro MR &lt;<a href="mailto:alvaro.sanchez@defence.gov.au">alvaro.sanchez@defence.gov.au</a>&gt;;
Jeff Wootton (IHO) &lt;<a href="mailto:jeff.wootton@iho.int">jeff.wootton@iho.int</a>&gt;<br>
<b>Cc:</b> <a href="mailto:Hugh.Astle@Teledyne.com">Hugh.Astle@Teledyne.com</a>;
Stamenkovich, Miroslav (52400) CIV USN NIWC ATLANTIC SC (USA) &lt;<a
href="mailto:miroslav.stamenkovich.civ@us.navy.mil">miroslav.stamenkovich.civ@us.navy.mil</a>&gt;<br>
<b>Subject:</b> xmlID values<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>We have an
action to update the S-101 PC to use the xmlID values from the registry to
ensure portrayal catalogs can work with one another (the same concept uses the
same lookup in different PC’s).<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>Before I do
this, should I use the currently registered xmlID’s which appear to be random
numbers? For instance, the xmlID for viewing group 11050 is “915”. The xmlID
for the over radar display plane is “1503”. My preference would be to have
meaningful identifiers to make the PC easier to read and maintain.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>


Item | Current xmlID | Suggested xmlID
-- | -- | --
Viewing Group 11050 | “915” | “11050”
Display Plane over radar | “1503” | “OverRADAR”
Display mode “Display Base” | “927” | “DisplayBase”
Context parameter “Safety Depth” | “1459” | “SafetyDepth”



<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-US style='mso-ansi-language:EN-US'>These xmlID
values correspond to the “id” values embedded in PC’s. They are used to
identify catalog entries:<o:p></o:p></span></p>

</body>

</html>

![xczx](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/26dc40bb-ab7d-405d-a23b-56fa57a18ef6)

**Comment by JeffWootton** [comment]
Considering that there were no implementation guidelines provided when the GI Registry Development Team at KHOA implemented the unique xmlID for the Portrayal Register (and there was no discussion on possible format or alignment with registered items in the S-100WG), the xmlID was implemented as a simple incrementing numeric value (as has been done for the identifier in the Data Dictionary Register).

I have initiated an Issue in the GI Registry Development GitLab for discussion within the KHOA Development Team and possibly in the S-100WG.

**Comment by DavidGrant-NIWC** [comment]
I think what was done in the registry was necessary and is a step forward. I'm just requesting the ability to change (some of) the _xmlID_ values. In my mind, I always assumed the _xmlID_ would be provided along with the other values as part of the registration request - it's an attribute just like all the rest. I get that this was not done for those items which are already registered, so the incrementing numeric was used as a default.

The main issue which KHOA resolved is that the value was not exposed in the registry user interface; now it is.

Note that the portrayal registry contents and interface will need to be updated anyway. The current contents are:
* Incomplete
  * classes were added, for instance to hold the alert catalog contents
  * most of the viewing groups are missing definitions
  * etc.
* Incorrect
  * some of the contents shown in the registry interface are no longer valid (e.g., Cascading style sheets, Colour profile, etc.)
  * many of the PC contents have changed but the registry is yet to be updated (I'll take the blame for this...)
  * items were registered long ago that were never used (e.g., the fonts)
  * schemas have not been updated
  * etc.

This hasn't been an issue to this point because the products are doing their testing in isolation and haven't needed to synchronize their presentations. OEM's have not gotten to the point where they are merging the contents of PC's (different versions, and/or different products) for presentation to the user.

Here is the request at the top of this issue, but I agree I was probably not clear enough that the _id_ in the PC is the same as the _xmlID_ in the registry.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/0dd4b405-30eb-4384-8e06-165391f9c4c7)

**Comment by alvarosanuy** [comment]
Now tracked in https://github.com/iho-ohi/S100Infrastructure/issues/2
