### ISSUE TITLE
Incorrect drawing of some Complex line styles - Part 3

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#91]
**Dedicated Github issue to discuss topic presented by dKart (@IngaFjellanger) in the paper below (bullet point 9):**

[Comments to Portrayal Catalogue_last version.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9193818/Comments.to.Portrayal.Catalogue_last.version.docx)

Extract from paper:

9.	Symbols EMLOWAC(01/31).svg use stroke-width equal to 0.64. Symbols view unreadable since their height is equal to 0.79 and width = 1.3. Their borders join together. Besides it does not comply with S-52. Suggest stroke-width equal to 0.3

![image](https://user-images.githubusercontent.com/70189016/181129175-a578ccc7-d955-4d7a-80f9-d56be08fe8c6.png)

**Comment by IngaFjellanger** [comment]
[ThickLOWACC_comment#9.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9196659/ThickLOWACC_comment.9.zip)
Here is a document and some svg files

**Comment by TDYCARHugh** [comment]
I can see in the original conversion that the linewidth was 1 pixel (0.3) and afterwards those symbols were modified manually to have a 2 pixel (0.64) width. 

I vaguely recall that there was a change being made around that time to make all conspicuous symbols use a 0.6 line width instead of 0.3.  

Perhaps it was something done as an intended improvement in S-101 portrayal that was not included in S-52?  I have not found documentation about it.

**Comment by DavidGrant-NIWC** [comment]
Will revert to S-52 presentation in PC 1.1.0

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 11th January 2023**

1. Decided to revert line thickness to 0.3mm to match S-52. @DavidGrant-NIWC to update EMLOWAC01; 11; 21; 31; 41 and upload new versions to this space so **Alvaro** can commence registration in the IHO GI Registry.

2. For PC 1.1.0.

**Comment by DavidGrant-NIWC** [comment]
[EMLOWACnn.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/10709340/EMLOWACnn.zip)

**Comment by DavidGrant-NIWC** [comment]
Incorporated in PC 1.1.0: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/139

**Comment by alvarosanuy** [comment]
New symbols have been updated to the GI Registry (new versions of existing symbols).
