### ISSUE TITLE
Proposal to amend the orientation of the existing symbol for Spotlights

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#93]
**Dedicated Github issue to discuss topic presented by dKart (@IngaFjellanger) in the paper below (bullet point 1):**

[Comments to Portrayal Catalogue_last version.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9193818/Comments.to.Portrayal.Catalogue_last.version.docx)

Extract from paper:

1.	Drawing symbol LIGHTS82 is used to depict both light category values 8 (flood light) and 11(spotlight). However, lights with those values light in different directions. Usually a flood light illuminates a structure and/or surrounded area. In this case the symbol LIGHTS82 logically directs bearing towards the structure symbol. For the spotlight it would be more correct to use a similar symbol directed away from the structure symbol since the spotlight is used to illuminate area aside the structure.

![image](https://user-images.githubusercontent.com/70189016/181129979-44200a98-e495-48a7-a98d-30cd062c2e17.png)

**Comment by IngaFjellanger** [comment]
[SpotLight_comment#1.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9196483/SpotLight_comment.1.zip)
Here is a svg file with suggested symbol

**Comment by alvarosanuy** [comment]
Spotlight is not referenced by S-4. 
Agree with the logic behind Inga's proposal but I believe it would be better to discuss this topic (_floodlight & spotlight real world purposes and the need for dedicated symbology_) at the NCWG level first.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. The subWG decided to refer proposals to update existing symbology or develop new one to the NCWG. This is to provide an opportunity to harmonise presentation among different charting products and ensure concepts and definitions between S-4 and DCEG stay aligned.

2. **Alvaro** to submit this issue for discussion at the next NCWG meeting in November 2023. Issue will remain open until feedback is received by the NCWG.

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.

**_Spotlights/Floodlight does the symbol define where the spotlight feature is charted i.e., the light source, 
and not the area which is illuminated, or does the symbol indicate what is being lit?_**

There is an option in S-101 where the angle of the light flare can be amended, i.e., the flare bearing. 
The difference in the descriptions is that a floodlight is used to highlight a feature whereas a spotlight is a 
focussed beam. 

Australia asked about what people’s solution would be to issue 7 which is Spotlights/Floodlight does the 
symbol define where the spotlight feature is charted i.e., the light source, and not the area which is 
illuminated, or does the symbol indicate what is being lit?

The Chair suggested doing the rays towards the feature, The Chair said if you turn it around then it changes 
the direction.

UK said that they use a different name, as floodlight and spotlight have different meanings.
ESRI asked if the floodlight is orientated one way, then it means a spotlight and the other means floodlight.
UK said that the light all around could be an option.

Sweden suggested that they need to define the definitions of the flood light and spotlight.
UK 82S said that they felt this was a light pointing as something, whereas a floodlight is pointing down.
Shared TheLightFlareAndDescription – Australia said they want a solution to which way the light should go.

USA suggested that there is a bigger problem than just symbology – said they need the encoding to support 
that.
There is an option in S-101 where the angle of the light flare can be amended, i.e., the flare bearing.
The difference in the descriptions is that a floodlight is used to highlight a feature and or an area whereas a 
spotlight is a focussed beam. 

UK shared an example of what they have done with floodlights. However, the S-101 implementation is 
different.

The Chair asked if everyone agreed the symbol shouldn’t point towards the feature.
The Chair said he can bring this discussion to a WG? and bring the opinions in the group to this.

**_Outcome:_** NCWG Chair will take this topic to the S-101 portrayal sub-working group to clarify the question 
and the use-case.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

- [ ] NCWG consider introducing the 'Spotlight' concept in S-4/INT-1 and assess the need to harmonize INT1 display with S-101.

**S-52 & S-101** - CATLIT=8(flood light) **or 11(spotlight)**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/87479364-abcd-44dc-a97d-f0306b11653b)

**INT1**

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/4859a562-e471-4d8f-93b0-6536530579c5)

**Close this Issue** - No further action at this stage.
