### ISSUE TITLE
Ice area

### ISSUE THREAD

**Issue by Christian-Shom** [S-101-Portrayal-subWG/Working-Documents#94]
From ENCWG "Display Sub WG" (Norway)
The portrayal of an **Ice area** encoded on **Land area** is very similar to **Unsurveyed area**. It is then very difficult to distinguish 
between **Ice area** and **Unsurveyed area**. 
A new S-101 symbology for **Ice area** would be desirable.
![image](https://user-images.githubusercontent.com/71139640/181213102-ae580127-a8fb-4bf9-aade-d23a1a9ba222.png)

**Comment by alvarosanuy** [comment]
What about something like this?

Pattern and line thickness as per ICEARE04. Background colour could be a bit more greyish if wanted ......
![image](https://user-images.githubusercontent.com/70189016/190561222-4c7dd696-35df-43cd-9bf7-230b18f2ec09.png)

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. The subWG decided to refer proposals to update existing symbology or develop new one to the NCWG. This is to provide an opportunity to harmonise presentation among different charting products and ensure concepts and definitions between S-4 and DCEG stay aligned.

2. **Alvaro** to submit this issue for discussion at the next NCWG meeting in November 2023. Issue will remain open until feedback is received by the NCWG.

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.

Ice Areas and Un-surveyed areas are very similar from a clarity POV, blue could be mistaken for a depth
area plus we need to remain mindful of the different colour modes on an ECDIS. 
UK shared images of examples for issue 6 on paper 5.14.
UK shared an image an image of what they do for an unsurveyed area.

The Chair suggested there should be a colour difference as it makes it unclear, The Chair asked the group 
what would be the preferred area, he said that the ice area may need to change.

Denmark suggested a darker grey as it creates a differentiation.
ESRI suggested using C25.
It has also been noted that the different display modes, night, and dusk for example, could affect the tone 
of the grey.

India - in my opinion unsurveyed areas and the areas coved with ice both are obstruction to safe 
navigation. However, we have symbol for ice covered on land. The floating ice is subject to drift. The area 
can be demarcated with danger line with a caution note. Too much symbology may create data clutter and 
confusion.

The Chair suggested changing the background grey to a different grey in an ice area.

**_Outcome:_** NCWG agrees that different colours are required for clarity.

**Comment by forodd** [comment]
Please find attached the S-57 dataset (NO2A4852) covering the area of the example in the first post above.
Please note that this is a remote area (Svalbard 80° N) with limited surveys and very bad data quality and coverage, so the encoding might not be optimal. 

The dataset has not been prepared for S-101 conversion, please let me know if there are any issues converting it and I will correct the S-57 file if needed. 


[NO2A4852_testdata.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14929702/NO2A4852_testdata.zip)

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 09/04/24**

- [x] **Norway** to upload S-57 cell used to create the screenshot at the top of this Issue. 
- [x] **Australia** to convert to S-101 and make sure it loads in OnShore ECDIS. Upload S-101 file to this Issue.
- [x] **NIWC** to experiment altering ICEARE04 using different tones of grey (pattern and background colours) and upload screenshots for sWG review.

**Comment by benhazelgrove** [comment]
S-57 file has been converted to S-101 using Australian Conversion mapping and has been trial loaded in ShoreECDIS to ensure it loads.

[101AU002A4852.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14973549/101AU002A4852.zip)

**Comment by DavidGrant-NIWC** [comment]
### Current Portrayal
|Day|Dusk|Night|
|:---:|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/f3f7e962-9483-4457-86ee-a7b87da31235)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/002fd2f1-4d0a-4ae9-8357-568dca4f1337)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a2de2112-4a43-40c4-8038-4dc4481074f4)

**Comment by DavidGrant-NIWC** [comment]
Could you add an `IceArea` in the unsurveyed area and also one over part of the depth area?

It might be useful to add an attribute to indicate whether the `IceArea` is over land or water. If over land just the pattern could be drawn; when over water the fill and pattern could be drawn.

Here's an alternate portrayal where the fill is not drawn:
|Day|Dusk|Night|
|:---:|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/f356e012-491c-44e0-8361-41b059f1c438)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/5cbd6909-cde9-4561-a4b7-aaf7efd50869)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a6e5c437-65fe-4d8d-ac79-17f31728f898)

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/88c55cf6-d00d-4fdf-9512-003f6fea9808)

**Comment by forodd** [comment]
I have now updated the S-57 file and added 2 ICEAREs in the lower left part of the dataset. File is attached below.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/32159177/acccca39-1be0-44b2-8851-3334a2e4c2b6)

[NO2A4852_testdata_ed2.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/14995065/NO2A4852_testdata_ed2.zip)

**Comment by benhazelgrove** [comment]
In the S-101 dataset, I have added 2 ICEARE features as well.
[101AU002A4852.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/15002409/101AU002A4852.zip)

**Comment by DavidGrant-NIWC** [comment]
Here's another portrayal using the new data and a translucent fill:

|Day|Dusk|Night|
|:---:|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/c71bc1d6-bd2c-4997-b87d-9cefba3ddb10)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/3d4ea33f-e231-42cd-99bb-23061bcf860a)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/dbcffdcc-5757-4f21-bb93-4bc10137b290)

**Comment by alvarosanuy** [comment]
I'm happy with how **IceArea** looks on land when removing the background color as suggested by Dave.

I'm not sure about the real use cases for having **IceArea** features over Bathy (contours and sounding **+Depth Area**) though .....
In S-57 ICEARE does not trigger A&I so I imagine that a safer option for alerting Mariners of Ice coverage would be CTNAREs released by ENC updates that are released, as needed, when conditions change. Maybe other producers would create ENC updates having the dangerous area covered by ICEARE and UNSARE and keep the bathy where is possible no navigate (e.g. 'thin' or no ice coverage).

Maybe we are overthinking possible real-world scenarios and, by just removing the background color from ICEARE over land, we are covering and improving the portrayal for the most common scenarios.

I would like to hear what those producers like @forodd (Norway) have to say about their encoding practices and what else we can do to improve portrayal in those scenarios.

**Comment by forodd** [comment]
I am also happy about the proposal to just remove the background color for ICEARE covering land.

We only encode the glaciers on land (ICEARE w CATICE=5 on top of LNDARE) but the seaward edge might end up in an UNSARE, so ICEARE might be encoded also on top of UNSARE close to land, but never on top of DEPARE. 

We do not encode any floating ICEAREs so it is not so important for us how it looks with ICEARE on top of DEPARE.

**Comment by alvarosanuy** [comment]
**Decision:**

- [ ] NIWC to update **IceArea** Rule and remove the use of Color Fill (NODTA) when **IceArea** overlaps **LandArea**. Retain Color Fill for when it overlaps **UnsurveyedArea** features (as per current practices, **IceArea** portrayal will continue having priority (masking) **Unsurveyed** symbology).

**Comment by DavidGrant-NIWC** [comment]
> * [ ]  NIWC to update **IceArea** Rule and remove the use of Color Fill (NODTA) when **IceArea** overlaps **LandArea**. Retain Color Fill for when it overlaps **UnsurveyedArea** features (as per current practices, **IceArea** portrayal will continue having priority (masking) **Unsurveyed** symbology).

Currently, the portrayal would have to do spatial evaluation to determine if an `IceArea` overlaps a `LandArea`. It's not clear what should happen when an `IceArea` overlaps both a `LandArea` and an `UnsurveyedArea` (or more consequently, a `DepthArea`). 

I'd recommend either:
1. Always use a translucent fill
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/751d3366-9d81-442c-a753-e10de1be3380)

1. Add an ECDIS system (portrayal) attribute to control the opacity of the color fill associated with a feature.
    * The production system could auto-populate this value by doing the spatial evaluation.
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/a447caf0-9a8b-4399-aba7-2984deca5c6e)

**Comment by alvarosanuy** [comment]
**Decision:**

- [ ] NIWC to update **IceArea** Rule and apply Transparency (percentage as per samples provided above) to the existing symbology; this is irrespective of the overlapping Skin of the Earth feature.

**Comment by DavidGrant-NIWC** [comment]
Implemented in PC 1.3:

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/c78b1f41-07f9-4498-9cd7-3c51072b5f53)

**Comment by alvarosanuy** [comment]
**Implemented in PC 1.3.0**
