### ISSUE TITLE
Restricted area on Dock area

### ISSUE THREAD

**Issue by Christian-Shom** [S-101-Portrayal-subWG/Working-Documents#98]
From ENCWG "Display Sub WG"
There is no need to encode a **Coastline** feature at the limit of a **Dock area**. The consequence (because of the display priority) 
is that an unnecessary line symbol on the coastline.
![image](https://user-images.githubusercontent.com/71139640/181252751-e6552d75-3ab2-4af9-9e0a-472a2ee62923.png)
Needs to be checked if this is still valid in S-101. If yes, the display priorities should be reviewed.

**Comment by alvarosanuy** [comment]
**Portrayal subWG meeting - 12th January 2023**

1. Portrayal needs to be re-assessed once **DockArea** is removed from the Group1. The **DockArea** will need to be covered by either DepthArea or UnsurveyedArea or LandArea and this will have an impact on the need for the encoding of COALNE/SLCONS features, etc.

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 10/5/23**

1. Request Test Data. Two different datasets (old and new SOE) are required to compare portrayal behavior.

**Comment by mikan66** [comment]
> **Decisions made at Portrayal subWG meeting on 10/5/23**
> 
> 1. Request Test Data. Two different datasets (old and new SOE) are required to compare portrayal behavior.

I don't believe there is test data covering this scenario as of this comment date.

**Comment by alvarosanuy** [comment]
[@tomrichardson](https://github.com/TomRichardson6) - Can you please prepare a TDS case as requested above?

**Comment by alvarosanuy** [comment]
Below are screenshots from an S-101 ENC where **DockArea** is no longer a Group1 feature (it sits on top of DEPARE and COALNE is a must along the boundary between Land and Water.
Based on the current look, I recommend we close this issue.
![ECDIS1](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/72e22d90-46a0-4374-a834-ec8ba651c341)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/87ac0a12-98f6-4339-a9a7-012cbe34fccf)
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/70189016/1e916154-52cb-4124-a264-db3a54ce937e)

**Comment by DavidGrant-NIWC** [comment]
The dock area should not be below the depth area. Can you send us this dataset (or drop it in here) so we can investigate?
![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/88430a84-80c1-438f-b4fc-8f8d5050a17f)

**Comment by MatthewCraggs** [comment]
[101AU005SYD01.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/12910901/101AU005SYD01.zip)

**Comment by DavidGrant-NIWC** [comment]
Edited 10/16 - Fixed the labels so they match the pictures.
|Dock Area On|Dock Area Off|
|:---:|:---:|
|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/4ee6b848-b6c6-46c6-be93-e4833a1d6e8f)|![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/d35f78c1-1f7a-4fb5-9c6d-ce5d317dfbf4)|

* Dock area fill has the same priority (9) as the shallow water pattern, so the order is arbitrary, and the shallow pattern may be obscured.
* Dock area is covering a land area near "Sailing Club" (encoding error?)
* Foreshore is obscured by the dock area
* Depth areas are obscured by the dock area

**Comment by MatthewCraggs** [comment]
> * Dock area is covering a land area near "Sailing Club" (encoding error?)

Agreed, That is an encoding error!

**Comment by alvarosanuy** [comment]
**Decisions made at Portrayal subWG meeting on 18/10/23**

- [ ] **NIWC** - Amend **DockArea** Surface symbology to remove infill blue colour.
- [x] **Alvaro**  - Refer issue to NCWG to look at potential new central symbol for **DockArea** Surface.

**Comment by alvarosanuy** [comment]
Paper submitted to NCWG9 (Nov 2023).
Will leave this issue open until we get feedback from NCWG Chair.

**Comment by DavidGrant-NIWC** [comment]
- [x] NIWC - Amend `DockArea` surface symbology to remove infill blue colour.

![image](https://github.com/S-101-Portrayal-subWG/Working-Documents/assets/62906211/82903907-59ff-41a6-8e4e-c0c254dd6447)

**Comment by MikkoHovi-FI** [comment]
According to DCEG (editions 1.1.0 and 1.2.0) Dock Area **must not** be encoded on top of Depth Area. It is only encoded when the dock is not navigable optimum display scale and must be encoded on Land Area or Unsurveyed Area only.

The blue infill and the "integrated" coastline makes sense when this guidance is followed. As well as drawing the feature on top of Land Area.

The definition of a Dock Area is "An artificially enclosed area within which ships may moor and which may have gates to regulate water level." I would be tempted to claim that the feature in the above example is not a Dock Area.

Also, I would like to remind that even if Dock Area was Group 1 in the earlier versions of S-101, the S-57 DOCARE is not Group 1.

**Comment by alvarosanuy** [comment]
Area fill has been retained - Refer to PC 1.2.0.

**Comment by MatthewCraggs** [comment]
### Below are the comments from NCWG9.
Restricted area on Dock area: Stakeholders are invited to discuss and debate a new portrayal for DockArea 
including. The simplest solution could be the addition of a new central symbol to the area to reinforce its 
purpose. 

The Chair noted that according to S-101 DCEG one must not encode dock area on top of depth area, and
suggested that the sub-group WG looking into this.

The Chair said NCWG could to return to this topic when we hear back from the sub-group WG.

**_Outcome:_** NCWG noted that according to S-101 DCEG a Dock Area feature must be covered by a Land Area 
or Unsurveyed Area. Therefore the original blue infill is the sensible option.
